### ISSUE TITLE
Received response status [FAILED] from custom resource - when adding Apple OAuth through amplify update auth

### ISSUE THREAD

**Issue by LucasKnudsen** [aws-amplify/amplify-js#10081]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication, Analytics, GraphQL API, Storage

### Amplify Categories

auth, storage, function, api, analytics

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.37 GB / 15.88 GB
  Binaries:
    Node: 16.0.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.24.0 - ~\node_modules\.bin\npm.CMD
  Browsers:
    Chrome: 103.0.5060.114
    Edge: Spartan (44.22000.120.0), Chromium (103.0.1264.37)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @babel/core: ^7.12.9 => 7.18.5 (7.18.6)
    @babel/runtime: ^7.12.5 => 7.18.3 (7.18.6)
    @hookstate/core: ^4.0.0-rc5 => 4.0.0-rc5
    @react-native-async-storage/async-storage: ^1.17.6 => 1.17.6
    @react-native-community/blur: ^3.6.0 => 3.6.0
    @react-native-community/datetimepicker: ^6.1.3 => 6.1.3
    @react-native-community/eslint-config: ^2.0.0 => 2.0.0
    @react-native-community/masked-view: ^0.1.11 => 0.1.11
    @react-native-community/netinfo: ^9.0.0 => 9.0.0
    @react-native-picker/picker: ^2.4.1 => 2.4.1
    @react-navigation/bottom-tabs: ^6.3.1 => 6.3.1
    @react-navigation/native: ^6.0.10 => 6.0.10
    @react-navigation/native-stack: ^6.6.2 => 6.6.2
    HelloWorld:  0.0.1
    amazon-cognito-identity-js: ^5.2.9 => 5.2.9
    aws-amplify: ^4.3.24 => 4.3.24
    aws-amplify-react-native: ^6.0.4 => 6.0.4
    babel-jest: ^26.6.3 => 26.6.3
    docuilib:  0.0.0
    eslint: ^7.32.0 => 7.32.0
    eslint-config-prettier: ^8.5.0 => 8.5.0 (6.15.0)
    eslint-plugin-react: ^7.30.0 => 7.30.0
    eslint-plugin-uilib:  2.1.7
    formik: ^2.2.9 => 2.2.9
    hermes-inspector-msggen:  1.0.0
    jest: ^26.6.3 => 26.6.3
    link: ^1.5.0 => 1.5.0
    metro-react-native-babel-preset: ^0.67.0 => 0.67.0
    moti: ^0.18.0 => 0.18.0
    papaparse: ^5.3.2 => 5.3.2
    prettier: ^2.6.2 => 2.6.2
    prop-types: ^15.8.1 => 15.8.1
    react: 17.0.2 => 17.0.2
    react-native: ^0.68.2 => 0.68.2
    react-native-bootsplash: ^4.2.3 => 4.2.3
    react-native-clean-project: ^4.0.1 => 4.0.1
    react-native-cli: ^2.0.1 => 2.0.1
    react-native-gesture-handler: ^2.5.0 => 2.5.0
    react-native-haptic-feedback: ^1.13.1 => 1.13.1
    react-native-inappbrowser-reborn: ^3.6.3 => 3.6.3
    react-native-linear-gradient: ^2.5.6 => 2.5.6
    react-native-modal: ^13.0.1 => 13.0.1
    react-native-reanimated: ^2.8.0 => 2.8.0
    react-native-safe-area-context: ^4.3.1 => 4.3.1
    react-native-screens: ^3.13.1 => 3.13.1
    react-native-svg: ^12.3.0 => 12.3.0
    react-native-svg-charts: ^5.4.0 => 5.4.0
    react-native-svg-transformer: ^1.0.0 => 1.0.0
    react-native-toast-message: ^2.1.5 => 2.1.5
    react-native-ui-lib: ^6.17.1 => 6.17.1
    react-native-vector-icons: ^9.1.0 => 9.1.0
    react-native-wagmi-charts: ^2.1.0 => 2.1.0
    react-native-wagmi-charts-example:  0.0.1
    react-test-renderer: 17.0.2 => 17.0.2
    src:  undefined ()
    uilib-native:  3.0.8
    yup: ^0.32.11 => 0.32.11
    zustand: ^4.0.0-rc.1 => 4.0.0-rc.1
  npmGlobalPackages:
    @aws-amplify/cli: 8.4.0
    node-gyp: 8.2.0
    npm: 7.24.0

```

</details>

### Describe the bug

I'm attempting to add Apple Sign In to my OAuth social providers. Currently, Facebook and Google is running fine. 

```
Using service: Cognito, provided by: awscloudformation
 What do you want to do? Update OAuth social providers
 Select the identity providers you want to configure for your user pool:
 (*) Facebook
 (*) Google
 ( ) Login With Amazon
>(*) Sign in with Apple
```

However, it won't let me push the updates to the cloud. I'm getting following errors in the CLI:

```
UPDATE_IN_PROGRESS          HostedUIProvidersCustomResourceInputs                   Custom::LambdaCallout      Wed Jul 13 2022 21:15:28 GMT+0200 (Central European Summer Time) Requested update required the provider to create a new physical resource
UPDATE_FAILED               HostedUIProvidersCustomResourceInputs                   Custom::LambdaCallout      Wed Jul 13 2022 21:15:29 GMT+0200 (Central European Summer Time) Received response status [FAILED] from custom resource. Message returned: See the details in CloudWatch Log Stream: 2022/07/13/[$LATEST]8097aca9bb0d4cea85ed306e591e4be7 (RequestId: cc22aec8-1665-4b23-b8c8-5f2cd681e3ca)
UPDATE_ROLLBACK_IN_PROGRESS amplify-aegis-dev-131808-authaegisa3662214-PI0CA78IETBW AWS::CloudFormation::Stack Wed Jul 13 2022 21:15:30 GMT+0200 (Central European Summer Time) The following resource(s) failed to update: [HostedUIProvidersCustomResourceInputs].
- Updating resources in the cloud. This may take a few minutes...

UPDATE_FAILED authaegisa3662214 AWS::CloudFormation::Stack Wed Jul 13 2022 21:15:34 GMT+0200 (Central European Summer Time) Embedded stack arn:aws:cloudformation:us-east-1:186873840600:stack/amplify-aegis-dev-131808-authaegisa3662214-PI0CA78IETBW/82023380-eb0c-11ec-8c4d-0eb6f010f3bd was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to update: [HostedUIProvidersCustomResourceInputs].
```

```
Following resources failed

Resource Name: 2022/07/13/[$LATEST]8097aca9bb0d4cea85ed306e591e4be7 (Custom::LambdaCallout)
Event Type: update
Reason: Received response status [FAILED] from custom resource. Message returned: See the details in CloudWatch Log Stream: 2022/07/13/[$LATEST]8097aca9bb0d4cea85ed306e591e4be7 (RequestId: cc22aec8-1665-4b23-b8c8-5f2cd681e3ca)
URL: https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/arn%3Aaws%3Acloudformation%3Aus-east-1%3A186873840600%3Astack%2Famplify-aegis-dev-131808-authaegisa3662214-PI0CA78IETBW%2F82023380-eb0c-11ec-8c4d-0eb6f010f3bd/events


× An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: /
Resource is not in the state stackUpdateComplete
```

What's more, the CloudWatch Log Stream URL given above just takes me to an empty screen.
After locating the correct Log Group, I'm able to retrieve these errors: 

```
2022-07-13T19:15:26.741Z	bbfa48e3-a48d-4562-8b34-c1ee0645b000	INFO	{
  Providers: [
    {
      ProviderName: 'Facebook',
      ProviderType: 'Facebook',
      LastModifiedDate: 2022-07-12T17:44:20.739Z,
      CreationDate: 2022-06-13T11:34:04.928Z
    },
    {
      ProviderName: 'Google',
      ProviderType: 'Google',
      LastModifiedDate: 2022-07-12T17:44:20.675Z,
      CreationDate: 2022-06-21T14:56:48.278Z
    }
  ]
}
```

```
2022-07-13T19:15:27.938Z	bbfa48e3-a48d-4562-8b34-c1ee0645b000	INFO	InternalErrorException: Internal server error.
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)

```

```
2022-07-13T19:15:27.941Z	bbfa48e3-a48d-4562-8b34-c1ee0645b000	INFO	Response body:
 {
    "Status": "FAILED",
    "Reason": "See the details in CloudWatch Log Stream: 2022/07/13/[$LATEST]8097aca9bb0d4cea85ed306e591e4be7",
    "PhysicalResourceId": "2022/07/13/[$LATEST]8097aca9bb0d4cea85ed306e591e4be7",
    "StackId": "arn:aws:cloudformation:us-east-1:186873840600:stack/amplify-aegis-dev-131808-authaegisa3662214-PI0CA78IETBW/82023380-eb0c-11ec-8c4d-0eb6f010f3bd",
    "RequestId": "cc22aec8-1665-4b23-b8c8-5f2cd681e3ca",
    "LogicalResourceId": "HostedUIProvidersCustomResourceInputs",
    "NoEcho": false,
    "Data": {
        "err": {
            "message": "Internal server error.",
            "code": "InternalErrorException",
            "time": "2022-07-13T19:15:27.938Z",
            "requestId": "e70464b9-b361-4d9d-b669-2bb29735d112",
            "statusCode": 500,
            "retryable": true
        }
    }
}

```

Finally, if I add the social provider manually through the console, it's working - however I'm not able to pull that down with Amplify, and the setting gets overruled on following code pushes.

### Expected behavior

I expect Apple to be included in my list of OAuth social providers.

### Reproduction steps

1. Run `amplify update auth` and setup Apple Sign In
2. Run `amplify push`

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by justinjaeger** [comment]
What was the solution?? I'm experiencing the same issue

**Comment by justinjaeger** [comment]
Oh - my issue, for reference, was that my private key (extracted from the .p8 file) was just `<key>` and not `-----BEGIN PRIVATE KEY-----<key>-----END PRIVATE KEY-----`

**Comment by tannerabread** [comment]
hi @justinjaeger this looks more like a CLI issue and I believe the OP closed this from the wrong repo. 
I followed the trail and it looks like [this issue](https://github.com/aws-amplify/amplify-cli/issues/10752) was opened which was closed as a duplicate of [this issue](https://github.com/aws-amplify/amplify-cli/issues/9893). The 2nd issue has a bit of context you might be able to follow and might help you. It ultimately leads to [this comment](https://github.com/aws-amplify/amplify-cli/issues/9893#issuecomment-1204469744) explaining there is a feature-request open for generic OIDC providers and instructions to please open a [new issue in the cli repo](https://github.com/aws-amplify/amplify-cli/issues/new/choose) if you are still having problems
