### ISSUE TITLE
Unable to update Cognito User Attributes

### ISSUE THREAD

**Issue by BrianHHough** [aws-amplify/amplify-js#10108]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line

  System:
    OS: macOS 12.3
    CPU: (10) arm64 Apple M1 Max
    Memory: 439.77 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 103.1.40.113
    Chrome: 103.0.5060.134
    Safari: 15.4
  npmPackages:
    @aws-amplify/ui-react: ^3.1.0 => 3.1.0 
    @aws-amplify/ui-react-internal:  undefined ()
    @aws-amplify/ui-react-legacy:  undefined ()
    @emotion/react: ^11.9.3 => 11.9.3 
    @emotion/styled: ^11.9.3 => 11.9.3 
    @mui/icons-material: ^5.8.4 => 5.8.4 
    @mui/material: ^5.9.1 => 5.9.1 
    @testing-library/jest-dom: ^5.16.4 => 5.16.4 
    @testing-library/react: ^13.3.0 => 13.3.0 
    @testing-library/user-event: ^13.5.0 => 13.5.0 
    aws-amplify: ^4.3.27 => 4.3.27 
    moment: ^2.29.4 => 2.29.4 
    react: ^18.2.0 => 18.2.0 (18.0.0)
    react-dom: ^18.2.0 => 18.2.0 
    react-router: ^6.3.0 => 6.3.0 
    react-router-dom: ^6.3.0 => 6.3.0 
    react-scripts: 5.0.1 => 5.0.1 
    web-vitals: ^2.1.4 => 2.1.4 
  npmGlobalPackages:
    @aws-amplify/cli: 9.1.0
    corepack: 0.10.0
    nodemon: 2.0.19
    npm: 8.11.0

```

</details>

### Describe the bug

I am running a function that is supposed to allow the user to update a user attribute of the Cognito account. Specifically, here, their `preferred_username` using the Auth.updateUserAttributes method.

I have the following function connected to a form, but the response does not issue a change in the `preferred_username` but instead I get an error saying: `Uncaught (in promise) TypeError: user.getSession is not a function`

### Expected behavior

I would expect the Cognito property for the current authenticated user to be updated from the current value to `username` as defined by the user's input.

### Reproduction steps

1. Input text into the form
2. Run the function `handleSubmit`
3. The Cognito User's `preferred_username` should be updated, however it errors

### Code Snippet

```javascript
// Put your code below this line.

>> Here is the function I am trying to run:

function handleSubmit(event, username) {
      event.preventDefault();
      try {
        const user = Auth.currentAuthenticatedUser();
        const response = Auth.updateUserAttributes(user, {
          "preferred_username": username
        })
        console.log(response)
      ;
      } catch (error) {
        console.log('error updating profile')
      }
    }

function handleChange(event) {
      const {value} = event.target;
      setUsername(value.toLowerCase());
    }



>> Here is the page in more context:


const [ username, setUsername] = useState();

<form 
  style={theme.form}
  onSubmit={handleSubmit}
>

    <div style={theme.usernamecon}>
    <h3>Username</h3>
    {console.log(username)}
    <input
      type="text"
      id="username" 
      name="username" 
      onChange={handleChange}
      value={username}
      placeholder={user.attributes.preferred_username}
      style={theme.inputField}
    >
    </input>
    </div>
    <button type="submit">Save Changes</button>
  </form>

```

### Log output

<details>

```
// Put your logs below this line
Auth.ts:1680 Uncaught (in promise) TypeError: user.getSession is not a function
    at Auth.ts:1680:1
    at new Promise (<anonymous>)
    at AuthClass.userSession (Auth.ts:1678:1)
    at Auth.ts:1270:1
    at new Promise (<anonymous>)
    at AuthClass.updateUserAttributes (Auth.ts:1269:1)
    at handleSubmit (index.js:20:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)

```

</details>

**Comment by BrianHHough** [comment]
Just figured out the solve — my function needed to be async await! 🙃

```javascript
async function handleSubmit(event, user) {
      event.preventDefault();
      try {
        const user = await Auth.currentAuthenticatedUser();
        const response = await Auth.updateUserAttributes(user, {
          "preferred_username": username
        })
        console.log(response)
      ;
      } catch (error) {
        console.log('error updating profile')
      }
    }
```

**Comment by nadetastic** [comment]
Hi @BrianHHough! Glad you were able to resolve your issue! 

I'll go ahead and mark this issue as closed.
