### ISSUE TITLE
Storage.put Error: Region is missing in production env, but localhost works well

### ISSUE THREAD

**Issue by ShenShu2016** [aws-amplify/amplify-js#10149]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Storage

### Amplify Categories

storage

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
    Memory: 12.62 GB / 31.92 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.77)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @aws-amplify/api: ^4.0.46 => 4.0.46
    @aws-amplify/api-graphql: ^2.3.10 => 2.3.10
    @aws-amplify/auth: ^4.5.10 => 4.5.10
    @aws-amplify/storage: ^4.4.29 => 4.4.29
    @ckeditor/ckeditor5-alignment: ^18.0.0 => 18.0.0 (34.0.0)
    @ckeditor/ckeditor5-build-classic: ^34.0.0 => 34.2.0
    @ckeditor/ckeditor5-react: ^5.0.1 => 5.0.2
    @date-io/date-fns: ^2.14.0 => 2.14.0
    @date-io/dayjs: ^2.14.0 => 2.14.0
    @date-io/luxon: ^2.14.0 => 2.14.0
    @date-io/moment: ^2.14.0 => 2.14.0
    @emotion/react: ^11.7.1 => 11.9.3
    @emotion/styled: ^11.6.0 => 11.9.3
    @mui/icons-material: ^5.2.4 => 5.8.4
    @mui/lab: ^5.0.0-alpha.82 => 5.0.0-alpha.92
    @mui/material: ^5.2.4 => 5.9.2
    @mui/styles: ^5.8.0 => 5.9.2
    @mui/system: ^5.9.1 => 5.9.2
    @mui/x-data-grid: ^5.11.1 => 5.14.0
    @mui/x-date-pickers: ^5.0.0-alpha.4 => 5.0.0-beta.2 (5.0.0-alpha.0)
    @react-google-maps/api: ^2.10.2 => 2.12.1
    @reduxjs/toolkit: ^1.8.1 => 1.8.3
    @reduxjs/toolkit-query:  1.0.0
    @reduxjs/toolkit-query-react:  1.0.0
    @types/aos: ^3.0.4 => 3.0.4
    @types/jest: ^27.5.1 => 27.5.2
    @types/node: ^17.0.0 => 17.0.45 (18.6.1)
    @types/react: ^17.0.37 => 17.0.47 (17.0.37)
    @types/react-dom: ^17.0.11 => 17.0.17
    @types/react-html-parser: ^2.0.2 => 2.0.2
    @types/react-lazy-load-image-component: ^1.5.2 => 1.5.2
    @types/react-router-dom: ^5.3.2 => 5.3.3
    @types/react-slick: ^0.23.10 => 0.23.10
    @types/uuid: ^8.3.4 => 8.3.4
    @typescript-eslint/eslint-plugin: ^5.30.7 => 5.31.0
    @typescript-eslint/parser: ^5.30.7 => 5.31.0 (1.13.0, 3.10.1)
    aos: ^2.3.4 => 2.3.4
    aws-amplify: ^4.3.22 => 4.3.28
    babel-eslint: ^10.1.0 => 10.1.0
    babel-plugin-styled-components: ^2.0.2 => 2.0.7
    card-validator: ^8.1.1 => 8.1.1
    ckeditor5-custom-build: file:ckeditor5 => 0.0.1
    cross-env: ^7.0.2 => 7.0.3
    date-fns: ^2.28.0 => 2.29.1
    eslint: ^8.20.0 => 8.20.0 (5.16.0, 7.32.0)
    eslint-config-airbnb: ^19.0.4 => 19.0.4
    eslint-config-airbnb-typescript: ^17.0.0 => 17.0.0
    eslint-config-prettier: ^8.5.0 => 8.5.0
    eslint-config-react-app: ^7.0.0 => 7.0.1
    eslint-plugin-flowtype: ^8.0.3 => 8.0.3
    eslint-plugin-import: ^2.26.0 => 2.26.0
    eslint-plugin-jsx-a11y: ^6.6.1 => 6.6.1
    eslint-plugin-prettier: ^4.2.1 => 4.2.1
    eslint-plugin-react: ^7.30.1 => 7.30.1
    eslint-plugin-react-hooks: ^4.6.0 => 4.6.0
    formik: ^2.2.9 => 2.2.9
    htmlparser2: ^8.0.1 => 8.0.1 (3.10.1, 6.1.0)
    jarallax: ^1.12.8 => 1.12.8
    lodash: ^4.17.21 => 4.17.21
    material-ui-confirm: ^3.0.4 => 3.0.4
    moment: ^2.29.3 => 2.29.4
    notistack: ^2.0.5 => 2.0.5
    prettier: ^2.7.1 => 2.7.1 (1.19.1)
    prettier-eslint: ^13.0.0 => 13.0.0 (9.0.2)
    prettier-eslint-cli: ^5.0.0 => 5.0.1
    prop-types: ^15.8.1 => 15.8.1
    react: ^17.0.1 => 17.0.2
    react-countup: ^6.1.0 => 6.3.0
    react-dom: ^17.0.1 => 17.0.2
    react-draggable: ^4.4.5 => 4.4.5
    react-easy-crop: ^4.2.0 => 4.4.0
    react-github-btn: ^1.3.0 => 1.3.0
    react-html-parser: ^2.0.2 => 2.0.2
    react-html-parser-demo:  0.0.0
    react-image-lightbox: ^5.1.4 => 5.1.4
    react-lazy-load-image-component: ^1.5.1 => 1.5.5
    react-player: ^2.10.1 => 2.10.1
    react-redux: ^8.0.1 => 8.0.2
    react-router: ^6.3.0 => 6.3.0
    react-router-dom: ^6.1.1 => 6.3.0
    react-scripts: 5.0.0 => 5.0.0
    react-slick: ^0.28.1 => 0.28.1
    react-sortable-hoc: ^2.0.0 => 2.0.0
    react-syntax-highlighter: ^15.4.5 => 15.5.0
    react-typed: ^1.2.0 => 1.2.0
    react-visibility-sensor: ^5.1.1 => 5.1.1
    rimraf: ^3.0.2 => 3.0.2 (2.6.3)
    slick-carousel: ^1.8.1 => 1.8.1
    swiper: ^8.2.2 => 8.3.1
    swiper_angular:  0.0.1
    typescript: ^4.5.4 => 4.7.4 (3.9.10)
    uuid: ^8.3.2 => 8.3.2 (3.4.0, 3.3.2)
    web-vitals: ^2.1.2 => 2.1.4
    yup: ^0.32.11 => 0.32.11
  npmGlobalPackages:
    @aws-amplify/cli: 8.2.0
    typescript: 4.7.2
    yarn: 1.22.18

```

</details>

### Describe the bug

One month ago its working well both in local and production
but now has the error below
Use the same backend and same React frontend. It works in local, but once deployed on amplify this error happen.

Error: Region is missing
>     at yl (RegionConfig.ts:34:11)
>     at new t (S3Client.ts:654:21)
>     at xB (S3ClientUtils.ts:156:19)
>     at e._createNewS3Client (AWSS3ProviderManagedUpload.ts:321:20)
>     at new e (AWSS3ProviderManagedUpload.ts:73:24)
>     at e.put (AWSS3Provider.ts:563:20)
>     at e.put (Storage.ts:343:25)
>     at userImageSlice.tsx:159:13
>     at createAsyncThunk.ts:605:15
>     at index.js:32:1

await Storage.put(`${targetTable}/${id}.${fileEXT}`, file, {
        level: "protected",
        contentType: "image/*",
      });

### Expected behavior

it should be same as local

### Reproduction steps

1. update amplify frontend
2. upload image using storage.put
3. error triggered

### Code Snippet

```javascript
// Put your code below this line.
      await Storage.put(`${targetTable}/${id}.${fileEXT}`, file, {
        level: "protected",
        contentType: "image/*",
      });
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

![image](https://user-images.githubusercontent.com/21266146/182661883-ccd66c5e-d270-409b-8ce6-66d042247f07.png)

**Comment by ShenShu2016** [comment]
I found the error:

because of these in package.json

    @aws-amplify/api: ^4.0.46 => 4.0.46
    @aws-amplify/api-graphql: ^2.3.10 => 2.3.10
    @aws-amplify/auth: ^4.5.10 => 4.5.10
    @aws-amplify/storage: ^4.4.29 => 4.4.29

after I remove then in package.json it works fine. but will give me these kind of lint error:
`                                 Line 25:1:    '@aws-amplify/api' should be listed in the project's dependencies. Run 'npm i -S @aws-amplify/api' to add it                  import/no-extraneous-dependencies
                                 Line 27:1:    '@aws-amplify/api-graphql' should be listed in the project's dependencies. Run 'npm i -S @aws-amplify/api-graphql' to add it  import/no-extraneous-dependencies`

**Comment by charlieforward9** [comment]
This happened to me because my `aws-exports` file was not up to date.
