### ISSUE TITLE
DataStore - subscriptionError Connection failed: NetInfo must be passed to networkMonitor to enable reachability in React Native

### ISSUE THREAD

**Issue by jgo80** [aws-amplify/amplify-js#10148]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

DataStore

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.25 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - /opt/homebrew/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 103.0.5060.134
    Safari: 15.6
  npmGlobalPackages:
    npm: 8.15.0
    yarn: 1.22.17

```

</details>

### Describe the bug

Since `aws-amplify@4.3.30` DataStore Subscriptions are not working anymore. 

`DataStore - subscriptionError Connection failed: NetInfo must be passed to networkMonitor to enable reachability in React Native` please see Reproduction steps and Log output below.

Even downgrading (strictly) to `aws-amplify@4.3.27` won't help as npm/yarn will start installing false dependencies.

### Expected behavior

DataStore Subscriptions should work as documented.

### Reproduction steps

1. Follow Amplify[ Getting Started with React Native Guide]( https://docs.amplify.aws/start/q/integration/react-native/)
2. Start the React Native app and see the errors popping up in the terminal

### Code Snippet

```javascript
  useEffect(() => {

    //query the initial todolist and subscribe to data updates
    const subscription = DataStore.observeQuery(Todo).subscribe((snapshot) => {
      //isSynced can be used to show a loading spinner when the list is being loaded. 
      const { items, isSynced } = snapshot;
      setTodos(items);
    });

    //unsubscribe to data updates when component is destroyed so that we don’t introduce a memory leak.
    return function cleanup() {
      subscription.unsubscribe();
    }

  }, []);

```

### Log output

<details>

```
 WARN  [WARN] 18:14.460 DataStore - subscriptionError Connection failed: NetInfo must be passed to networkMonitor to enable reachability in React Native
 WARN  [WARN] 18:14.461 DataStore {"cause": {"error": {"errors": [Array]}, "provider": {"_config": [Object], "connectionStateMonitor": [ConnectionStateMonitor], "keepAliveTimeout": 300000, "promiseArray": [Array], "socketStatus": 0, "subscriptionObserverMap": [Map]}}, "errorType": "Unknown", "localModel": null, "message": "Connection failed: NetInfo must be passed to networkMonitor to enable reachability in React Native", "model": "Todo", "operation": "Create", "process": "subscribe", "recoverySuggestion": "Ensure app code is up to date, auth directives exist and are correct on each model, and that server-side data has not been invalidated by a schema change. If the problem persists, search for or create an issue: https://github.com/aws-amplify/amplify-js/issues", "remoteModel": null}

[WARN] 18:14.462 DataStore - subscriptionError Connection failed: NetInfo must be passed to networkMonitor to enable reachability in React Native
 WARN  [WARN] 18:14.462 DataStore {"cause": {"error": {"errors": [Array]}, "provider": {"_config": [Object], "connectionStateMonitor": [ConnectionStateMonitor], "keepAliveTimeout": 300000, "promiseArray": [Array], "socketStatus": 0, "subscriptionObserverMap": [Map]}}, "errorType": "Unknown", "localModel": null, "message": "Connection failed: NetInfo must be passed to networkMonitor to enable reachability in React Native", "model": "Todo", "operation": "Update", "process": "subscribe", "recoverySuggestion": "Ensure app code is up to date, auth directives exist and are correct on each model, and that server-side data has not been invalidated by a schema change. If the problem persists, search for or create an issue: https://github.com/aws-amplify/amplify-js/issues", "remoteModel": null}

 WARN  [WARN] 18:14.462 DataStore - subscriptionError Connection failed: NetInfo must be passed to networkMonitor to enable reachability in React Native
 WARN  [WARN] 18:14.462 DataStore {"cause": {"error": {"errors": [Array]}, "provider": {"_config": [Object], "connectionStateMonitor": [ConnectionStateMonitor], "keepAliveTimeout": 300000, "promiseArray": [Array], "socketStatus": 0, "subscriptionObserverMap": [Map]}}, "errorType": "Unknown", "localModel": null, "message": "Connection failed: NetInfo must be passed to networkMonitor to enable reachability in React Native", "model": "Todo", "operation": "Delete", "process": "subscribe", "recoverySuggestion": "Ensure app code is up to date, auth directives exist and are correct on each model, and that server-side data has not been invalidated by a schema change. If the problem persists, search for or create an issue: https://github.com/aws-amplify/amplify-js/issues", "remoteModel": null}


```

</details>

### Additional information and screenshots

**Additional Note:**
The error occurs **both** with React Native (with the exact error as described above) **and** with React on the Web, where the error states:

```console
GraphQLAPI.ts:423 Uncaught (in promise) Error: No pubsub module applied for subscription
    at GraphQLAPIClass2._graphqlSubscribe (GraphQLAPI.ts:423:10)
    at GraphQLAPIClass2.graphql (GraphQLAPI.ts:272:17)
    at APIClass2.graphql (API.ts:239:27)
    at SubscriptionProcessor2.<anonymous> (subscription.ts:397:44)
    at step (mutation.ts:584:1)
    at Object.next (mutation.ts:584:1)
    at fulfilled (mutation.ts:584:1)
```

**Comment by liebharc** [comment]
We're facing the same issue. Thanks for opening this issue, it would have taken us at least some more hours to realize that this is an issue with the amplify version. Downgrading aws-amplify with a pnpm override to 4.3.27 is a workaround for us at the moment and perhaps it helps other pnpm users who stumble over this.

```

"dependencies": {
...
    "aws-amplify": "4.3.27",
    "@react-native-community/netinfo": "8.3.1",
    "aws-amplify-react-native": "^6.0.5",
...
},
"pnpm": {
  "overrides": {
    "aws-amplify": "4.3.27",
    "@react-native-community/netinfo": "8.3.1"
  }
}
```

**Comment by rohankurane45** [comment]
> We're facing the same issue. Thanks for opening this issue, it would have taken us at least some more hours to realize that this is an issue with the amplify version. Downgrading aws-amplify with a pnpm override to 4.3.27 is a workaround for us at the moment and perhaps it helps other pnpm users who stumble over this.
> 
> ```
> 
> "dependencies": {
> ...
>     "aws-amplify": "4.3.27",
>     "@react-native-community/netinfo": "8.3.1",
>     "aws-amplify-react-native": "^6.0.5",
> ...
> },
> "pnpm": {
>   "overrides": {
>     "aws-amplify": "4.3.27",
>     "@react-native-community/netinfo": "8.3.1"
>   }
> }
> ```

Is it the only way to solve this warnings?

**Comment by hellojustxn** [comment]
I have the same issue when invoking  `observe` and `observeQuery`

**Comment by conor909** [comment]
Same issue here although @liebharc workaround seems to get past the error, but it seems Amplify is very unstable with a lot of live bugs

**Comment by AlexChaseJones** [comment]
is there a different solution to this using npm? I'm unable to get my project running using pnpm due to a series of issues outlined here https://github.com/pnpm/pnpm/issues/2622#issuecomment-641591451

Manually downgroading aws-amplify to `4.3.27` causes a host of other issues that I didn't attempt to work through, but I'm curious if that's the only solution

**Comment by jgo80** [comment]
I manually downgraded to `4.3.24` (using the exact version without `~` or `^`) using yarn for the time being.
Hoping for a reaction by an AWS official developer.

**Comment by AlexChaseJones** [comment]
> I manually downgraded to `4.3.24` (using the exact version without `~` or `^`) using yarn for the time being. Hoping for a reaction by an AWS official developer.

Unfortunately I'm getting a new error after doing that 

```
Unable to resolve module ../../utils/ConnectionStateMonitor from /
ode_modules/@aws-amplify/pubsub/lib-esm/Providers/AWSAppSyncRealTimeProvider/index.js:
```

Might just have to wait on the patch for this one

**Comment by bobthebuilder1997** [comment]
@AlexChaseJones ,
                                     You can delete `node_modules` directory and then update the package.json dependency to `"aws-amplify":"4.3.24" `. After that run `yarn install` and it should work fine after that. It worked for me.

**Comment by AlexChaseJones** [comment]
@bobthebuilder1997 That worked, I originally tried the same steps but with `npm install` and was getting the previous error. I'm curious what exactly would cause that, I'm not well versed on the differences between yarn and npm.. Does npm build dependencies differently than yarn?

**Comment by BarkinBln** [comment]
I'm having the same issue and none of the above solutions worked for me. Is there any other different solution to this issue ?

**Comment by Rushabhsinora** [comment]
I am also facing the same warning to we have any solution for temporary like import {LogBox} from 'react-native'  &   LogBox.ignoreLogs(["DataStore - subscriptionError"])  or any permanent solution. Do let me know

**Comment by stocaaro** [comment]
Closing for now. Please reopen if you are able to reproduce the issue on `aws-amplify` >= 4.3.31.

**Comment by chai86** [comment]
I return to my perfectly functioning app today (which was working last week) only to find the the Amplify side of it doesn't work anymore!!

I'm simply reading and writing messages to Datastore and having them displayed in an app screen.

Im using  "aws-amplify": "**4.3.31**" & "aws-amplify-react-native": "^6.0.5",

I get repeated errors of the same kind: 

1) DataStore - subscriptionError Connection failed: com.amazonaws.depdish.graphql.auth 
2) DataStore - User is unauthorized to query syncUsers with auth mode API_KEY. No data could be returned
3) DataStore {"cause": [GraphQLError: Request failed with status code 401], "errorInfo": undefined, "errorType": "Unauthorized", "localModel": {"_version": undefined, "chatroomID": "3a89040d-8225-44c9-9323-125d71f28759", "content": "testmessage", "createdAt": undefined, "id": "e215e02a-3492-4697-b692-6294799e39fb", "updatedAt": undefined, "userID": "18bbb78b-5496-4772-8960-067e9fc3a282"}, "message": "Request failed with status code 401", "operation": "Create", "process": "mutate", "recoverySuggestion": "**Ensure app code is up to date, auth directives exist and are correct on each model, and that server-side data has not been invalidated by a schema change.**


I haven't touched my code or anything server side at all, just ran my project. What has Amplify changed?
The suggestion to downgrade version to 4.3.27 didn't work either. There is no issue with users being logged in. On production code, this is incredibly alarming. 

Please help!

**Comment by undefobj** [comment]
> I return to my perfectly functioning app today (which was working last week) only to find the the Amplify side of it doesn't work anymore!!
> 
> I'm simply reading and writing messages to Datastore and having them displayed in an app screen.
> 
> Im using  "aws-amplify": "**4.3.31**" & "aws-amplify-react-native": "^6.0.5",
> 
> I get repeated errors of the same kind: 
> 
> 1) DataStore - subscriptionError Connection failed: com.amazonaws.deepdish.graphql.auth 
> 2) DataStore - User is unauthorized to query syncUsers with auth mode API_KEY. No data could be returned
> 3) DataStore {"cause": [GraphQLError: Request failed with status code 401], "errorInfo": undefined, "errorType": "Unauthorized", "localModel": {"_version": undefined, "chatroomID": "3a89040d-8225-44c9-9323-125d71f28759", "content": "testmessage", "createdAt": undefined, "id": "e215e02a-3492-4697-b692-6294799e39fb", "updatedAt": undefined, "userID": "18bbb78b-5496-4772-8960-067e9fc3a282"}, "message": "Request failed with status code 401", "operation": "Create", "process": "mutate", "recoverySuggestion": "**Ensure app code is up to date, auth directives exist and are correct on each model, and that server-side data has not been invalidated by a schema change.**
> 
> 
> I haven't touched my code or anything server side at all, just ran my project. What has Amplify changed?
> The suggestion to downgrade version to 4.3.27 didn't work either. There is no issue with users being logged in. On production code, this is incredibly alarming. 
> 
> Please help! 
> 

Looks like an authorization error. Are you sure your API Key hasn't expired? If that's not the issue I suggest opening a new GitHub issue.

**Comment by chai86** [comment]
@undefobj  Looks like thats what it was!! I'm sure i set the token duration for 10years (3649 days), but it looks like it needs refreshing often. Is there any way i can set this **for sure** for a multiple year duration?

**Comment by Abdullah47744** [comment]
WARN  [WARN] 23:05.947 DataStore - subscriptionError Connection failed: {"errors":[{"message":"Validation error of type FieldUndefined: Field '_version' in type 'Dish' is undefined @ 'onUpdateDish/_version'"},{"message":"Validation error of type FieldUndefined: Field '_lastChangedAt' in type 'Dish' is undefined @ 'onUpdateDish/_lastChangedAt'"},{"message":"Validation error of type FieldUndefined: Field '_deleted' in type 'Dish' is undefined @ 'onUpdateDish/_deleted'"}]}
 WARN  [WARN] 23:05.964 DataStore {"cause": {"error": {"errors": [Array]}, "provider": {"_config": [Object], "awsRealTimeSocket": [WebSocket], "connectionState": "Connecting", "connectionStateMonitor": [ConnectionStateMonitor], "connectionStateMonitorSubscription": [Subscription], "keepAliveAlertTimeoutId": 513, "keepAliveTimeout": 300000, "keepAliveTimeoutId": 512, "promiseArray": [Array], "reconnectionMonitor": [ReconnectionMonitor], "socketStatus": 1, "subscriptionObserverMap": [Map]}}, "errorType": "Unknown", "localModel": null, "message": "Connection failed: {\"errors\":[{\"message\":\"Validation error of type FieldUndefined: Field '_version' in type 'Dish' is undefined @ 'onUpdateDish/_version'\"},{\"message\":\"Validation error of type FieldUndefined: Field '_lastChangedAt' in type 'Dish' is undefined @ 'onUpdateDish/_lastChangedAt'\"},{\"message\":\"Validation error of type FieldUndefined: Field '_deleted' in type 'Dish' is undefined @ 'onUpdateDish/_deleted'\"}]}", "model": "Dish", "operation": "Update", "process": "subscribe", "recoverySuggestion": "Ensure app code is up to date, auth directives exist and are correct on each model, and that server-side data has not been invalidated by a schema change. If the problem persists, search for or create an issue: https://github.com/aws-amplify/amplify-js/issues", "remoteModel": null}

i can read data from aws amplify any one help please

**Comment by stocaaro** [comment]
Hello @Abdullah47744 ,

I think the issue you encountered is better covered in the discussion on [this issue](https://github.com/aws-amplify/amplify-js/issues/4853).

In brief, DataStore's offline sync behavior needs a suite of features that come with enabling conflict resolution. The `Dish` model in you app doesn't appear to have these fields and you may need to go back and set that up as described in the issue I've linked to get DataStore working.

Hope this helps!
