### ISSUE TITLE
Long monitor contention with owner pool-4-thread-87 (4997) at void com.amplifyframework.api.aws.SubscriptionEndpoint.releaseSubscription(java.lang.String)(SubscriptionEndpoint.java:-1) waiters=24 in void com.amplifyframework.api.aws.SubscriptionEndpoint.releaseSubscription(java.lang.String) repeated 85 times

### ISSUE THREAD

**Issue by kingmarleycoffee** [aws-amplify/amplify-js#10400]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

GraphQL API, DataStore

### Amplify Categories

api

### Environment information

I got Long monitor contention with owner pool-4-thread-87 (4997) at void com.amplifyframework.api.aws.SubscriptionEndpoint.releaseSubscription(java.lang.String)(SubscriptionEndpoint.java:-1) waiters=24 in void com.amplifyframework.api.aws.SubscriptionEndpoint.releaseSubscription(java.lang.String) repeated 85 times when i am trying to get data from amplify using GraphQL 

### Describe the bug

Long monitor contention with owner pool-4-thread-2 (4869) at java.lang.Object java.lang.Object.internalClone()(Object.java:-2) waiters=0 in void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 2.732s

### Expected behavior

get a data without taking all this time, it takes more than 1 minute to get the data.

### Reproduction steps

-

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

W/le.we_guarante( 4656): Long monitor contention with owner pool-4-thread-2 (4869) at java.lang.Object java.lang.Object.internalClone()(Object.java:-2) waiters=76 in void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 28.951s
W/le.we_guarante( 4656): Long monitor contention with owner pool-4-thread-2 (4869) at java.lang.Object java.lang.Object.internalClone()(Object.java:-2) waiters=77 in void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 29.275s
W/le.we_guarante( 4656): Long monitor contention with owner pool-4-thread-2 (4869) at java.lang.Object java.lang.Object.internalClone()(Object.java:-2) waiters=78 in void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 29.659s
W/le.we_guarante( 4656): Long monitor contention with owner pool-4-thread-2 (4869) at java.lang.Object java.lang.Object.internalClone()(Object.java:-2) waiters=79 in void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 30.069s
W/le.we_guarante( 4656): Long monitor contention with owner pool-4-thread-2 (4869) at java.lang.Object java.lang.Object.internalClone()(Object.java:-2) waiters=80 in void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 30.396s
W/le.we_guarante( 4656): Long monitor contention with owner pool-4-thread-2 (4869) at java.lang.Object java.lang.Object.internalClone()(Object.java:-2) waiters=81 in void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 30.680s
W/le.we_guarante( 4656): Long monitor contention with owner pool-4-thread-2 (4869) at java.lang.Object java.lang.Object.internalClone()(Object.java:-2) waiters=82 in void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 31.096s
W/le.we_guarante( 4656): Long monitor contention with owner pool-4-thread-2 (4869) at java.lang.Object java.lang.Object.internalClone()(Object.java:-2) waiters=83 in void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 31.501s
W/le.we_guarante( 4656): Long monitor contention with owner pool-4-thread-2 (4869) at java.lang.Object java.lang.Object.internalClone()(Object.java:-2) waiters=84 in void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 31.910s
W/le.we_guarante( 4656): Long monitor contention with owner pool-4-thread-2 (4869) at java.lang.Object java.lang.Object.internalClone()(Object.java:-2) waiters=85 in void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 32.320s
I/amplify:aws-datastore( 4656): Started subscription processor for models: [29 models] of types [ON_CREATE, ON_UPDATE, ON_DELETE].
I/System.out( 4656): [socket]:check permission begin!
2
I/amplify:aws-datastore( 4656): Successfully sync'd down model state from cloud.
Successfully sync'd down model state from cloud.
I/le.we_guarante( 4656): Background young concurrent copying GC freed 66102(4853KB) AllocSpace objects, 20(412KB) LOS objects, 53% free, 4724KB/10146KB, paused 1.226ms total 107.410ms
3
I/amplify:aws-datastore( 4656): Successfully sync'd down model state from cloud.
I/le.we_guarante( 4656): Background concurrent copying GC freed 53277(4787KB) AllocSpace objects, 26(696KB) LOS objects, 49% free, 4515KB/9030KB, paused 568us total 142.228ms
2
I/amplify:aws-datastore( 4656): Successfully sync'd down model state from cloud.
I/le.we_guarante( 4656): Background concurrent copying GC freed 38826(3958KB) AllocSpace objects, 2(32KB) LOS objects, 49% free, 4816KB/9633KB, paused 693us total 166.281ms
5
I/amplify:aws-datastore( 4656): Successfully sync'd down model state from cloud.
I/le.we_guarante( 4656): Background young concurrent copying GC freed 51056(4199KB) AllocSpace objects, 5(108KB) LOS objects, 43% free, 5432KB/9633KB, paused 1.515ms total 121.137ms
W/amplify:aws-datastore( 4656): Initial cloud sync failed for Users.
W/amplify:aws-datastore( 4656): DataStoreException{message=Failure performing sync query to AppSync: [GraphQLResponse.Error{message='Cannot return null for non-nullable type: 'EmployersAds' within parent 'Users' (/syncUsers/items[27]/employersAds)', locations='null', path='[GraphQLPathSegment{value='syncUsers'}, GraphQLPathSegment{value='items'}, GraphQLPathSegment{value='27'}, GraphQLPathSegment{value='employersAds'}]', extensions='null'}], cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
W/amplify:aws-datastore( 4656): 	at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$sync$0(AppSyncClient.java:116)
W/amplify:aws-datastore( 4656): 	at com.amplifyframework.datastore.appsync.AppSyncClient$$ExternalSyntheticLambda4.accept(Unknown Source:6)
W/amplify:aws-datastore( 4656): 	at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:151)
W/amplify:aws-datastore( 4656): 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
W/amplify:aws-datastore( 4656): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/amplify:aws-datastore( 4656): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/amplify:aws-datastore( 4656): 	at java.lang.Thread.run(Thread.java:919)
E/amplify:flutter:datastore( 4656): DataStoreException{message=Initial cloud sync failed for Users., cause=DataStoreException{message=Failure performing sync query to AppSync: [GraphQLResponse.Error{message='Cannot return null for non-nullable type: 'EmployersAds' within parent 'Users' (/syncUsers/items[27]/employersAds)', locations='null', path='[GraphQLPathSegment{value='syncUsers'}, GraphQLPathSegment{value='items'}, GraphQLPathSegment{value='27'}, GraphQLPathSegment{value='employersAds'}]', extensions='null'}], cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Check your internet connection.}

**Comment by kingmarleycoffee** [comment]
any help, please
