### ISSUE TITLE
AWSPinpointProvider - updateEndpoint failed [ReferenceError: Property 'err' doesn't exist]

### ISSUE THREAD

**Issue by markl-vesper** [aws-amplify/amplify-js#10494]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Push Notifications

### Amplify Categories

notifications

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 5.31 GB / 31.39 GB
  Binaries:
    Node: 14.20.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 106.0.5249.119
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.47)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @aws-amplify/pushnotification: 4.3.36 => 4.3.36
    @babel/core: ^7.12.9 => 7.19.3
    @babel/plugin-proposal-decorators: 7.14.5 => 7.14.5 (7.19.3)
    @babel/plugin-syntax-decorators: 7.19.0 => 7.19.0
    @babel/runtime: ^7.12.5 => 7.19.0
    @invertase/react-native-apple-authentication: 1.1.2 => 1.1.2
    @react-native-async-storage/async-storage: 1.15.7 => 1.15.7 (1.17.10)
    @react-native-community/art: 1.2.0 => 1.2.0
    @react-native-community/eslint-config: ^2.0.0 => 2.0.0
    @react-native-community/masked-view: 0.1.11 => 0.1.11
    @react-native-community/netinfo: 6.0.0 => 6.0.0
    @react-native-community/push-notification-ios: 1.10.1 => 1.10.1 (1.0.3)
    @react-native-material/core: 1.3.7 => 1.3.7
    @react-navigation/drawer: 6.1.4 => 6.1.4
    @react-navigation/native: 6.0.2 => 6.0.2
    @react-navigation/native-stack: 6.1.0 => 6.1.0
    @rneui/base: 4.0.0-rc.6 => 4.0.0-rc.6
    @rneui/themed: 4.0.0-rc.6 => 4.0.0-rc.6
    @stripe/stripe-react-native: 0.19.0 => 0.19.0
    HelloWorld:  0.0.1
    amazon-cognito-identity-js: 5.2.10 => 5.2.10
    appcenter-cli: 2.6.1 => 2.6.1
    aws-amplify: 4.3.37 => 4.3.37
    babel-jest: ^26.6.3 => 26.6.3
    babel-plugin-transform-remove-console: 6.9.4 => 6.9.4
    babel-preset-mobx: ^2.0.0 => 2.0.0
    cardinal-direction: 1.1.1 => 1.1.1
    convert-radix64: ^0.2.0 => 0.2.0
    convert-units: 2.3.4 => 2.3.4
    core-js: 3 => 3.25.5
    deprecated-react-native-prop-types: ^2.3.0 => 2.3.0
    es6-symbol: ^3.1.3 => 3.1.3
    eslint: ^7.32.0 => 7.32.0
    eslint-plugin-react-hooks: ^2.0.0 => 2.5.1 (4.6.0)
    fast-text-encoding: 1.0.3 => 1.0.3
    geodesy: ^2.2.0 => 2.4.0
    graphql: 14.5.8 => 14.5.8 (15.8.0)
    graphql-tag: 2.10.1 => 2.10.1
    haversine: ^1.1.1 => 1.1.1
    hermes-engine:  %VERSION%
    hermes-engine-cli:  %VERSION%
    hermes-eslint:  0.9.0
    hermes-estree:  0.9.0
    hermes-inspector-msggen:  1.0.0
    hermes-parser:  0.9.0
    hermes-parser-packages:  undefined ()
    hermes-transform:  0.9.0
    hermes-website:  0.0.0
    jest: ^26.6.3 => 26.6.3
    jetifier: ^2.0.0 => 2.0.0
    joi: 17.3.0 => 17.3.0 (17.6.2)
    jsc-android: 241213.1.0 => 241213.1.0 (250230.2.1)
    lodash: ^4.17.15 => 4.17.21 (4.17.15)
    metro-react-native-babel-preset: 0.72.3 => 0.72.3
    mobx: 6.3.2 => 6.3.2
    mobx-react: 7.2.0 => 7.2.0
    moment: 2.29.1 => 2.29.1 (2.29.4)
    numeral: ^2.0.6 => 2.0.6
    patch-package: 6.4.7 => 6.4.7
    react: 18.1.0 => 18.1.0
    react-native: 0.70.2 => 0.70.2
    react-native-app-intro-slider: 4.0.4 => 4.0.4
    react-native-camera: 4.0.3 => 4.0.3
    react-native-code-push: 7.0.1 => 7.0.1
    react-native-codegen: ^0.0.7 => 0.0.7 (0.70.5)
    react-native-config: 1.4.8 => 1.4.8
    react-native-dash: 0.0.11 => 0.0.11
    react-native-device-info: 10.2.1 => 10.2.1
    react-native-dropdown-picker: 5.3.0 => 5.3.0
    react-native-gesture-handler: 1.10.3 => 1.10.3
    react-native-inappbrowser-reborn: 3.6.3 => 3.6.3
    react-native-json-tree: 1.3.0 => 1.3.0
    react-native-maps: 0.30.2 => 0.30.2
    react-native-modal: 13.0.0 => 13.0.0
    react-native-modal-selector: 2.0.8 => 2.0.8
    react-native-permissions: ^3.0.5 => 3.6.1 (2.2.2)
    react-native-phone-input: 1.1.0 => 1.1.0
    react-native-picker-select: 8.0.4 => 8.0.4
    react-native-progress: 5.0.0 => 5.0.0
    react-native-qrcode-scanner: 1.5.4 => 1.5.4
    react-native-reanimated: 2.10.0 => 2.10.0
    react-native-restart: 0.0.22 => 0.0.22
    react-native-safe-area-context: 3.3.0 => 3.3.0
    react-native-screens: 3.18.1 => 3.18.1
    react-native-splash-screen: 3.2.0 => 3.2.0
    react-native-svg: 12.1.1 => 12.1.1
    react-native-swipe-item: ^0.4.0 => 0.4.0
    react-native-timeago: ^0.5.0 => 0.5.0
    react-native-unordered-list: 1.0.4 => 1.0.4
    react-native-user-inactivity: 1.2.0 => 1.2.0
    react-native-vector-icons: 6.6.0 => 6.6.0
    react-native-walkthrough-tooltip: 1.4.0 => 1.4.0
    react-native-webview: 11.23.0 => 11.23.0
    react-test-renderer: 18.1.0 => 18.1.0
    text-encoding-polyfill: 0.6.7 => 0.6.7
    typescript: 3.8.2 => 3.8.2
    uuid: 8.3.2 => 8.3.2 (3.4.0, 3.3.2, 7.0.3)
    victory-native: 35.5.4 => 35.5.4
    webpack: ^4.42.0 => 4.46.0
  npmGlobalPackages:
    merge-yaml-cli: 1.1.2
    merge-yaml: 1.1.0
    npm: 6.14.17
    serverless: 3.22.0
    yarn: 1.22.19

```

</details>

### Describe the bug

When calling 

```
        Analytics.updateEndpoint({
          address: AuthStore.deviceId,
          optOut: 'NONE',
          userId: this.username,
        });
```

we are seeing below error

 ERROR  [ERROR] 46:10.579 AWSPinpointProvider - updateEndpoint failed [ReferenceError: Property 'err' doesn't exist]

### Expected behavior

No error should be generated

### Reproduction steps

npx react-native run-android

application builds and installs onto emulator then runs and error is generated as user is logging into app

### Code Snippet

```javascript
        Analytics.updateEndpoint({
          address: AuthStore.deviceId,
          optOut: 'NONE',
          userId: this.username,
        });

```

### Log output

<details>

```
 LOG  [DEBUG] 36:43.531 AWSPinpointProvider - _public record {"event": {"address": "Tty7G", "name": "_update_endpoint", "optOut": "NONE", "userId": undefined}, "provider": undefined}
 LOG  [DEBUG] 36:43.532 Credentials - getting credentials
 LOG  [DEBUG] 36:43.532 Credentials - picking up credentials
 LOG  [DEBUG] 36:43.533 Credentials - getting new cred promise
 LOG  [DEBUG] 36:43.533 Credentials - checking if credentials exists and not expired
 LOG  [DEBUG] 36:43.534 Credentials - are these credentials expired? {"accessKeyId": "***", "authenticated": true, "expiration": 2022-10-18T04:18:53.000Z, "identityId": "us-east-1:6f8d486a-b351-447a-977e-8bebee5d36e1", "secretAccessKey": "***", "sessionToken": "***"}
 LOG  [DEBUG] 36:43.540 Credentials - credentials not changed and not expired, directly return
 LOG  [DEBUG] 36:43.545 AWSPinpointProvider - set credentials for analytics {"accessKeyId": "***", "authenticated": true, "expiration": 2022-10-18T04:18:53.000Z, "identityId": "us-east-1:6f8d486a-b351-447a-977e-8bebee5d36e1", "secretAccessKey": "***", "sessionToken": "***"}
 LOG  [DEBUG] 36:43.547 AWSPinpointProvider - init clients
 LOG  [DEBUG] 36:43.548 AWSPinpointProvider - no change for aws credentials, directly return from init
 LOG  [DEBUG] 36:44.545 AWSPinpointProvider - updateEndpoint error [ReferenceError: Property 'err' doesn't exist]
 ERROR  [ERROR] 36:44.546 AWSPinpointProvider - updateEndpoint failed [ReferenceError: Property 'err' doesn't exist]
 WARN  Possible Unhandled Promise Rejection (id: 0):
ReferenceError: Property 'err' doesn't exist
ReferenceError: Property 'err' doesn't exist
 LOG  [DEBUG] 36:51.503 AWSPinpointProvider - init clients
 LOG  [DEBUG] 36:51.503 AWSPinpointProvider - no change for aws credentials, directly return from init
 LOG  [DEBUG] 36:51.555 EventsBuffer - _putEvents Failed:  [ReferenceError: Property 'err' doesn't exist]


```

</details>

### aws-exports.js

```
AWS_REGION=ap-southeast-2
AWS_URL=https://wv7enahj5jgh3lheid4wh2qaji.appsync-api.ap-southeast-2.amazonaws.com/graphql
AWS_IDENTITY_POOL_ID=ap-southeast-2:e6e50429-4768-4cec-84a0-ada2a4ec7232
AWS_USER_POOL_ID=ap-southeast-2_NK49se16K
AWS_USER_POOL_WEB_CLIENT_ID=64bl2d2njurm2u63pohrhbn7d3
AWS_OAUTH_DOMAIN=auth-test.dev.vespercortex.com
AWS_PINPOINT_APP_ID=aa66bff4fad34fd0a92a37f01c81a7e6
AWS_PINPOINT_REGION=ap-southeast-2
```

### Mobile Device

Android Pixel 4XL

### Mobile Operating System

Android 12

### Additional information and screenshots

Pinpoint Analytics is working fine so its not a credentials issue. For some reason it would appear the updateEndpoint is throwing the error

**Comment by markl-vesper** [comment]
Hi @abdallahshaban557 

Thanks for reaching out. Well today the error is no longer apparent when logging in with any user. What I do notice though is that PushNotification.onRegister is never called so we never get to save the token locally or update our backend and associate with the user on our side.

After reading a few forums I attempted to debug this a bit further using 

```
import { NativeModules } from 'react-native';
NativeModules.RNPushNotification.getToken(
  token => console.log('RNPushNotification.getToken: ', token),
  err => console.log('RNPushNotification.getToken err: ', err),
);
```

and

```
const result = PushNotification.initializeAndroid()
console.log('initializeAndroid result: ', result)
```

Both fail with

 ERROR  [ERROR] 49:58.851 Notification - Error getting the token from Firebase Service java.util.concurrent.ExecutionException: java.io.IOException: FIS_AUTH_ERROR
 
 It might be that the dpenedencies need updating perhaps? Some forums suggest this
 
 ```
implementation "com.google.firebase:firebase-core:15.0.2"
implementation "com.google.firebase:firebase-messaging:15.0.2"
```

**Comment by tannerabread** [comment]
Hi :wave: @markl-vesper 

Trying to get some clarity on where the current issue is. Originally you were talking about Pinpoint endpoint errors when logging in and now you are having a PushNotification error. 
I see that you are no longer having the Analytics error itself, did the Push Notification error only show up after the other error went away? And is it now safe to assume there is no problems with Analytics and this is now a Push Notifications issue?

One last thing, I see you are experiencing this on Android, have you tried on iOS?

**Comment by markl-vesper** [comment]
Hi @tannerabread 

Yes - Yesterday the errors were occuring during the Analytics.updateEndpoint. Today that error is no longer occuring. The only changes were to restart the environment in terms of node server and device emulator.

Actually the push notification error showed up as part of attempting to triage the original issue prior to opening this case. I was attempting to determine the value of the token and if it was making it as far as being saved on our side and thats when I noticed the token on our side was null and that both geToken and initialiseAndroid are throwing the FIS_AUTH_ERROR

**Comment by markl-vesper** [comment]
One further update re original issue. Its just come back after restarting the app. No other changes were made. Had been in a meeting and came back to desk and sent the above reply and then started app and the original error

[ERROR] 50:36.296 AWSPinpointProvider - updateEndpoint failed [ReferenceError: Property 'err' doesn't exist]

has returned.

Would seem that this is an intermittent issue now

**Comment by markl-vesper** [comment]
running adb logcat has helped further. Looks like a config file is not being included somehow. I'll dig down deeper into this

10-19 09:35:59.528  1328  1560 E GCM     : Missing checkin config file
10-19 09:35:59.528  1328  1560 W GCM     : GCM FAILED TO INITIALIZE - missing checkin
10-19 09:35:59.531  3567  4056 E FirebaseInstanceId: Topic sync or token retrieval failed on hard failure exceptions: AUTHENTICATION_FAILED. Won't retry the operation.
10-19 09:35:59.533  1328  3685 E GCM     : Missing checkin config file
10-19 09:35:59.534  1328  3685 W GCM     : GCM FAILED TO INITIALIZE - missing checkin
10-19 09:35:59.539  1328  3790 I Fitness : FitCleanupIntentOperation received Intent android.intent.action.PACKAGE_CHANGED [CONTEXT service_id=17 ]
10-19 09:35:59.556  3567  3594 W Bugle   : BugleFirebaseInstanceIDManagerImpl: Failed to refresh firebase instance ID
10-19 09:35:59.556  3567  3594 W Bugle   : java.io.IOException: AUTHENTICATION_FAILED

**Comment by markl-vesper** [comment]
upgrade of aws-amplify did not help but I believe I have found the issue

The logcat is reporting the apikey is invalid. When you download the google-services.com it contains TWO current_key entries in api_key section. These do not match the WebAPI Key in the top section on the console screen

As test I replaced the api key in google-services.json with the key from the screen instead of using the api keys that were downloaded and errors have gone!!

This makes me wonder how on earth our app in the store is working (yet it is) when it is using an old apikey. This app has not needed a rebuild for a long time since we update via codepush so perhaps it might start to fail if we had to rebuild the native side.

For now it looks better. I have not tested an actual PN yet as I need to go to a meeting now

**Comment by tannerabread** [comment]
Thanks for the updates. That's really interesting that your app is working with an old apiKey!

I'll leave this open until you have time to test the PN but I do have one more question, are you only running this on an emulated device? If so, was the triaging of the first error the first time you tried to use the PushNotification category at all?

**Comment by markl-vesper** [comment]
Hi @tannerabread 

Have tried PN on both physical device and emulator

I have completed some further debugging since yesterday

Currently the app will only build when compileSdkVersion = 33. Anything below that then the build will fail due to some android libraries complaining about requiring 33 (I can provide that output if required)

However when building app against 33 and running a test PN I can see the PN arrive via adb logcat output but we get the the below error

```
10-20 10:40:24.831 13969 14153 I RNPushNotificationMessagingService: Message From: 123917093506
10-20 10:40:24.836 13969 13969 I emit    : notification emit
10-20 10:40:24.837 13969 13969 I RNPushNotificationMessagingService: sendNotification: Bundle[{pinpoint.openApp=true, userInteraction=false, pinpoint.notification.sound=default, pinpoint.notification.title=Cortex Alarm, pinpoint.notification.body=Vessel position is outside of its alarm zone, id=-939047208, pinpoint.campaign.campaign_id=_DIRECT, pinpoint.notification.silentPush=0}]
10-20 10:40:24.839 13969 13969 D skia    : --- Failed to create image decoder with message 'unimplemented'
10-20 10:40:24.839 13969 13969 I RNPushNotificationHelper: sendNotification: Intent { cmp=com.cortexmonitoring/com.amazonaws.amplify.pushnotification.modules.RNPushNotificationBroadcastReceiver (has extras) }
10-20 10:40:24.841 13969 13969 E RNPushNotificationHelper: failed to send push notification
10-20 10:40:24.841 13969 13969 E RNPushNotificationHelper: java.lang.IllegalArgumentException: com.cortexmonitoring: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
10-20 10:40:24.841 13969 13969 E RNPushNotificationHelper: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
10-20 10:40:24.841 13969 13969 E RNPushNotificationHelper:      at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
10-20 10:40:24.841 13969 13969 E RNPushNotificationHelper:      at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
10-20 10:40:24.841 13969 13969 E RNPushNotificationHelper:      at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
10-20 10:40:24.841 13969 13969 E RNPushNotificationHelper:      at com.amazonaws.amplify.pushnotification.modules.RNPushNotificationHelper.sendToNotificationCentre(RNPushNotificationHelper.java:318)
10-20 10:40:24.841 13969 13969 E RNPushNotificationHelper:      at com.amazonaws.amplify.pushnotification.RNPushNotificationMessagingService.sendNotification(RNPushNotificationMessagingService.java:110)
10-20 10:40:24.841 13969 13969 E RNPushNotificationHelper:      at com.amazonaws.amplify.pushnotification.RNPushNotificationMessagingService.handleFCMMessagePush(RNPushNotificationMessagingService.java:90)
10-20 10:40:24.841 13969 13969 E RNPushNotificationHelper:      at com.amazonaws.amplify.pushnotification.RNPushNotificationMessagingService.access$000(RNPushNotificationMessagingService.java:39)
10-20 10:40:24.841 13969 13969 E RNPushNotificationHelper:      at com.amazonaws.amplify.pushnotification.RNPushNotificationMessagingService$1.run(RNPushNotificationMessagingService.java:65)
10-20 10:40:24.841 13969 13969 E RNPushNotificationHelper:      at android.os.Handler.handleCallback(Handler.java:938)
10-20 10:40:24.841 13969 13969 E RNPushNotificationHelper:      at android.os.Handler.dispatchMessage(Handler.java:99)
10-20 10:40:24.841 13969 13969 E RNPushNotificationHelper:      at android.os.Looper.loopOnce(Looper.java:201)
10-20 10:40:24.841 13969 13969 E RNPushNotificationHelper:      at android.os.Looper.loop(Looper.java:288)
10-20 10:40:24.841 13969 13969 E RNPushNotificationHelper:      at android.app.ActivityThread.main(ActivityThread.java:7842)
10-20 10:40:24.841 13969 13969 E RNPushNotificationHelper:      at java.lang.reflect.Method.invoke(Native Method)
10-20 10:40:24.841 13969 13969 E RNPushNotificationHelper:      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
10-20 10:40:24.841 13969 13969 E RNPushNotificationHelper:      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

Am now trying to understand this error and looking for possible fixes

**Comment by tannerabread** [comment]
Hi 👋 @markl-vesper thank you for leaving your debug trail here in case anyone else encounters this same issue.

Closing this as resolved. If anyone else experiences this issue and is in need of assistance, please feel free to comment and provide us with additional information so we can re-open this issue and be better able to assist you.

Thank you!
