### ISSUE TITLE
Error: Cannot find module '@aws-sdk/util-credentials' on Amplify Hosting next.js 

### ISSUE THREAD

**Issue by oste** [aws-amplify/amplify-js#10738]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Not applicable

### Amplify Categories

hosting

### Environment information

<details>

```
OS: Linux 4.14 Debian GNU/Linux 10 (buster) 10 (buster)
CPU: (4) x64 Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz
Memory: 1.91 GB / 7.50 GB
Container: Yes
Shell: 5.0.3 - /bin/bash
Binaries:
Node: 14.21.1 - /usr/local/bin/node
Yarn: 1.22.19 - /usr/local/bin/yarn
npm: 6.14.17 - /usr/local/bin/npm
npmGlobalPackages:
@aws-amplify/cli: 10.5.1
corepack: 0.14.2
npm: 6.14.17


```

</details>

### Describe the bug

While deploying my app to amplify hosting using the new next.js compute feature I am getting the below stack trace.

I am using the following packages.
"@aws-amplify/ui-react": "^4.1.0",
"next": "^12.2.5",
"aws-amplify": "^5.0.4",

```
2022-12-05T05:25:49.397Z [INFO]: info  - Compiled successfully
2022-12-05T05:25:49.399Z [INFO]: info  - Collecting page data...
**2022-12-05T05:25:52.033Z [WARNING]: Error: Cannot find module '@aws-sdk/util-credentials'
                                    Require stack:**
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/index.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveSsoCredentials.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveProfileData.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/fromIni.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/index.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-node/dist-cjs/index.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/runtimeConfig.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/STSClient.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/STS.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/index.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/runtimeConfig.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/LocationClient.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/Location.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/index.js
                                    - /src/monorepo/node_modules/@aws-amplify/geo/lib/Providers/AmazonLocationServiceProvider.js
                                    - /src/monorepo/node_modules/@aws-amplify/geo/lib/Geo.js
                                    - /src/monorepo/node_modules/@aws-amplify/geo/lib/index.js
                                    - /src/monorepo/node_modules/aws-amplify/lib/index.js
                                    - /src/monorepo/node_modules/@aws-amplify/ui/dist/index.js
                                    - /src/monorepo/node_modules/@aws-amplify/ui-react-core/dist/index.js
                                    - /src/monorepo/node_modules/@aws-amplify/ui-react/dist/index.js
                                    - /src/monorepo/apps/admin/.next/server/pages/_app.js
                                    - /src/monorepo/node_modules/next/dist/server/require.js
                                    - /src/monorepo/node_modules/next/dist/server/load-components.js
                                    - /src/monorepo/node_modules/next/dist/export/worker.js
                                    - /src/monorepo/node_modules/next/dist/build/worker.js
                                    - /src/monorepo/node_modules/next/dist/compiled/jest-worker/processChild.js
                                    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
                                    at Function.mod._resolveFilename (/src/monorepo/node_modules/next/dist/build/webpack/require-hook.js:27:32)
                                    at Function.mod._resolveFilename (/src/monorepo/node_modules/next/dist/build/webpack/require-hook.js:27:32)
                                    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
                                    at Module.require (internal/modules/cjs/loader.js:974:19)
                                    at require (internal/modules/cjs/helpers.js:101:18)
                                    at Object.<anonymous> (/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/index.js:7:28)
                                    at Module._compile (internal/modules/cjs/loader.js:1085:14)
                                    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
                                    at Module.load (internal/modules/cjs/loader.js:950:32) {
                                    code: 'MODULE_NOT_FOUND',
                                    requireStack: [
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/index.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveSsoCredentials.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveProfileData.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/fromIni.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/index.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-node/dist-cjs/index.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/runtimeConfig.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/STSClient.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/STS.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/index.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/runtimeConfig.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/LocationClient.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/Location.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/index.js',
                                    '/src/monorepo/node_modules/@aws-amplify/geo/lib/Providers/AmazonLocationServiceProvider.js',
                                    '/src/monorepo/node_modules/@aws-amplify/geo/lib/Geo.js',
                                    '/src/monorepo/node_modules/@aws-amplify/geo/lib/index.js',
                                    '/src/monorepo/node_modules/aws-amplify/lib/index.js',
                                    '/src/monorepo/node_modules/@aws-amplify/ui/dist/index.js',
                                    '/src/monorepo/node_modules/@aws-amplify/ui-react-core/dist/index.js',
                                    '/src/monorepo/node_modules/@aws-amplify/ui-react/dist/index.js',
                                    '/src/monorepo/apps/admin/.next/server/pages/_app.js',
                                    '/src/monorepo/node_modules/next/dist/server/require.js',
                                    '/src/monorepo/node_modules/next/dist/server/load-components.js',
                                    '/src/monorepo/node_modules/next/dist/export/worker.js',
                                    '/src/monorepo/node_modules/next/dist/build/worker.js',
                                    '/src/monorepo/node_modules/next/dist/compiled/jest-worker/processChild.js'
                                    ]
                                    }
2022-12-05T05:25:52.035Z [WARNING]: Error: Cannot find module '@aws-sdk/util-credentials'
                                    Require stack:
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/index.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveSsoCredentials.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveProfileData.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/fromIni.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/index.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-node/dist-cjs/index.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/runtimeConfig.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/STSClient.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/STS.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/index.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/runtimeConfig.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/LocationClient.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/Location.js
                                    - /src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/index.js
                                    - /src/monorepo/node_modules/@aws-amplify/geo/lib/Providers/AmazonLocationServiceProvider.js
                                    - /src/monorepo/node_modules/@aws-amplify/geo/lib/Geo.js
                                    - /src/monorepo/node_modules/@aws-amplify/geo/lib/index.js
                                    - /src/monorepo/node_modules/aws-amplify/lib/index.js
                                    - /src/monorepo/node_modules/@aws-amplify/ui/dist/index.js
                                    - /src/monorepo/node_modules/@aws-amplify/ui-react-core/dist/index.js
                                    - /src/monorepo/node_modules/@aws-amplify/ui-react/dist/index.js
                                    - /src/monorepo/apps/admin/.next/server/pages/_app.js
                                    - /src/monorepo/node_modules/next/dist/server/require.js
                                    - /src/monorepo/node_modules/next/dist/server/load-components.js
                                    - /src/monorepo/node_modules/next/dist/export/worker.js
                                    - /src/monorepo/node_modules/next/dist/build/worker.js
                                    - /src/monorepo/node_modules/next/dist/compiled/jest-worker/processChild.js
                                    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
                                    at Function.mod._resolveFilename (/src/monorepo/node_modules/next/dist/build/webpack/require-hook.js:27:32)
                                    at Function.mod._resolveFilename (/src/monorepo/node_modules/next/dist/build/webpack/require-hook.js:27:32)
                                    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
                                    at Module.require (internal/modules/cjs/loader.js:974:19)
                                    at require (internal/modules/cjs/helpers.js:101:18)
                                    at Object.<anonymous> (/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/index.js:7:28)
                                    at Module._compile (internal/modules/cjs/loader.js:1085:14)
                                    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
                                    at Module.load (internal/modules/cjs/loader.js:950:32) {
                                    code: 'MODULE_NOT_FOUND',
                                    requireStack: [
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-sso/dist-cjs/index.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveSsoCredentials.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/resolveProfileData.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/fromIni.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-ini/dist-cjs/index.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/credential-provider-node/dist-cjs/index.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/runtimeConfig.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/STSClient.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/STS.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/node_modules/@aws-sdk/client-sts/dist-cjs/index.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/runtimeConfig.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/LocationClient.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/Location.js',
                                    '/src/monorepo/node_modules/@aws-sdk/client-location/dist-cjs/index.js',
                                    '/src/monorepo/node_modules/@aws-amplify/geo/lib/Providers/AmazonLocationServiceProvider.js',
                                    '/src/monorepo/node_modules/@aws-amplify/geo/lib/Geo.js',
                                    '/src/monorepo/node_modules/@aws-amplify/geo/lib/index.js',
                                    '/src/monorepo/node_modules/aws-amplify/lib/index.js',
                                    '/src/monorepo/node_modules/@aws-amplify/ui/dist/index.js',
                                    '/src/monorepo/node_modules/@aws-amplify/ui-react-core/dist/index.js',
                                    '/src/monorepo/node_modules/@aws-amplify/ui-react/dist/index.js',
                                    '/src/monorepo/apps/admin/.next/server/pages/_app.js',
                                    '/src/monorepo/node_modules/next/dist/server/require.js',
                                    '/src/monorepo/node_modules/next/dist/server/load-components.js',
                                    '/src/monorepo/node_modules/next/dist/export/worker.js',
                                    '/src/monorepo/node_modules/next/dist/build/worker.js',
                                    '/src/monorepo/node_modules/next/dist/compiled/jest-worker/processChild.js'
                                    ]
                                    }
2022-12-05T05:25:52.036Z [WARNING]: 
2022-12-05T05:25:52.036Z [WARNING]: > Build error occurred
2022-12-05T05:25:52.038Z [WARNING]: Error: Failed to collect page data for /auth
                                    at /src/monorepo/node_modules/next/dist/build/utils.js:916:15
                                    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
                                    type: 'Error'
                                    }
2022-12-05T05:25:52.149Z [WARNING]: error Command failed with exit code 1.
2022-12-05T05:25:52.149Z [INFO]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2022-12-05T05:25:52.156Z [ERROR]: !!! Build failed
2022-12-05T05:25:52.156Z [ERROR]: !!! Non-Zero Exit Code detected
2022-12-05T05:25:52.157Z [INFO]: # Starting environment caching...
2022-12-05T05:25:52.157Z [INFO]: # Uploading environment cache artifact...
2022-12-05T05:25:52.237Z [INFO]: # Uploaded environment cache artifact
2022-12-05T05:25:52.237Z [INFO]: # Environment caching completed
Terminating logging...
```

### Expected behavior

either @aws-sdk/credential-provider-sso is not used or if it should be used it would be able to find all of it's dependencies.

### Reproduction steps

- Create next app with the following dependencies
```
"@aws-amplify/ui-react": "^4.1.0",
"next": "^12.2.5",
"aws-amplify": "^5.0.4",
```

- Deploy to amplify hosting using the new next.js

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

It's worth noting that on my local machine the @aws-sdk/client-location package does not even use/have `@aws-sdk/credential-provider-sso` it only seems to install `credential-provider-ini/node/process`

**Comment by tannerabread** [comment]
Transferring to hosting for better coverage
