### ISSUE TITLE
Next.js 13 'app' directory Auth error: 'Cannot find module './withSSRContext''

### ISSUE THREAD

**Issue by ben-sommer** [aws-amplify/amplify-js#11059]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line

System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 16.78 GB / 31.93 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @aws-amplify/auth: ^5.1.10 => 5.1.10
    @aws-amplify/ui-react: ^4.3.9 => 4.3.9
    @aws-cdk/aws-cognito-identitypool-alpha: 2.66.1-alpha.0 => 2.66.1-alpha.0
    @next/font: 13.1.6 => 13.1.6
    @svgr/webpack: ^6.5.1 => 6.5.1
    @tailwindcss/forms: ^0.5.3 => 0.5.3
    @types/node: 18.13.0 => 18.13.0
    @types/react: 18.0.28 => 18.0.28
    @types/react-dom: 18.0.11 => 18.0.11
    autoprefixer: ^10.4.13 => 10.4.13
    aws-amplify: ^5.0.16 => 5.0.16
    aws-crt: ^1.15.9 => 1.15.9
    brfs: ^2.0.2 => 2.0.2
    eslint: 8.34.0 => 8.34.0
    eslint-config-next: 13.1.6 => 13.1.6
    json-loader: ^0.5.7 => 0.5.7
    next: 13.2.1 => 13.2.1
    plaiceholder: ^2.5.0 => 2.5.0
    postcss: ^8.4.21 => 8.4.21
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    react-hook-form: ^7.43.5 => 7.43.5
    react-icons: ^4.7.1 => 4.7.1
    server-only: ^0.0.1 => 0.0.1
    sharp: ^0.31.3 => 0.31.3
    tailwindcss: ^3.2.6 => 3.2.6
    transform-loader: ^0.2.4 => 0.2.4
    typescript: 4.9.5 => 4.9.5
  npmGlobalPackages:
    @aws-amplify/cli: 5.1.2
    amplify-cli: 1.0.0
    cdk: 2.66.1
    cross-env: 7.0.3
    eslint: 7.31.0
    firebase-tools: 9.16.0
    heml: 1.1.3
    lint-staged: 12.2.2
    nexe: 4.0.0-beta.19
    next: 12.0.7
    pnpm: 7.27.0
    prettier: 2.3.2
    react-scripts: 4.0.3
    serverless: 2.55.0
    svelte-kit: 1.0.0
    typescript: 4.4.3
    windows-build-tools: 5.2.2
```

</details>

### Describe the bug

When importing the `Auth` module from `aws-ampify` in a [Next.js 13 client component](https://beta.nextjs.org/docs/rendering/server-and-client-components#client-components) and running `next dev`, I get the error ` Cannot find module './withSSRContext'` in the terminal. 

### Expected behavior

I expected the `Auth` module to load from `aws-amplify` successfully so I can use the `Auth.signIn()` method in my application.

### Reproduction steps

1. Create a new Next.js 13 project with `npx create-next-app@latest --experimental-app`
2. Install `aws-amplify` with `npm i --save aws-amplify`
3. Create a new route by creating a folder in the `src/app` directory called `test`
4. Create the `src/app/test/page.tsx` file with the following contents (this is a server component)
```
import { Client } from "./client";

export default function Page() {
  return <Client />;
}
```
5. Create the `src/app/test/client.tsx` file with the following contents (this is a client component)
Note: you will need to add your own cognito environment variables to `.env`
```
"use client";

import { Amplify } from "aws-amplify";

export const Client = () => {
  const config = {
    Auth: {
      identityPoolId: process.env.NEXT_PUBLIC_COGNITO_IDENTITY_POOL_ID,
      region: process.env.NEXT_PUBLIC_COGNITO_REGION,
      userPoolId: process.env.NEXT_PUBLIC_COGNITO_USERPOOL_ID,
      userPoolWebClientId: process.env.NEXT_PUBLIC_COGNITO_CLIENT_ID,
    },
    ssr: true,
  };

  Amplify.configure(config);

  return null;
};
```
6. Run `npm run dev` to start the development server
7. Navigate to [localhost:3000/test](http://localhost:3000/test) and observe the error

### Log output

<details>

```
error - Error: Cannot find module './withSSRContext'
Require stack:
- C:\Users\USERNAME\Documents\Projects\PROJECT\.next\server\app\test\page.js
- C:\Users\USERNAME\Documents\Projects\PROJECT\node_modules\.pnpm\next@13.2.1_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\server\require.js
- C:\Users\USERNAME\Documents\Projects\PROJECT\node_modules\.pnpm\next@13.2.1_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\server\load-components.js
- C:\Users\USERNAME\Documents\Projects\PROJECT\node_modules\.pnpm\next@13.2.1_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\build\utils.js
- C:\Users\USERNAME\Documents\Projects\PROJECT\node_modules\.pnpm\next@13.2.1_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\server\dev\static-paths-worker.js
- C:\Users\USERNAME\Documents\Projects\PROJECT\node_modules\.pnpm\next@13.2.1_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\compiled\jest-worker\processChild.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.mod._resolveFilename (C:\Users\USERNAME\Documents\Projects\PROJECT\node_modules\.pnpm\next@13.2.1_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\build\webpack\require-hook.js:23:32)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at eval (webpack-internal:///(sc_server)/./node_modules/.pnpm/aws-amplify@5.0.16_aws-crt@1.15.9/node_modules/aws-amplify/lib/index.js:50:24)
    at Object.(sc_server)/./node_modules/.pnpm/aws-amplify@5.0.16_aws-crt@1.15.9/node_modules/aws-amplify/lib/index.js (C:\Users\USERNAME\Documents\Projects\PROJECT\.next\server\app\test\page.js:337:1)
    at __webpack_require__ (C:\Users\USERNAME\Documents\Projects\PROJECT\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(sc_server)/./app/test/client.tsx:5:69)
    at Module.(sc_server)/./app/test/client.tsx (C:\Users\USERNAME\Documents\Projects\PROJECT\.next\server\app\test\page.js:316:1) {
  type: 'Error',
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\USERNAME\\Documents\\Projects\\PROJECT\\.next\\server\\app\\test\\page.js',
    'C:\\Users\\USERNAME\\Documents\\Projects\\PROJECT\\node_modules\\.pnpm\\next@13.2.1_biqbaboplfbrettd7655fr4n2y\\node_modules\\next\\dist\\server\\require.js',
    'C:\\Users\\USERNAME\\Documents\\Projects\\PROJECT\\node_modules\\.pnpm\\next@13.2.1_biqbaboplfbrettd7655fr4n2y\\node_modules\\next\\dist\\server\\load-components.js',
    'C:\\Users\\USERNAME\\Documents\\Projects\\PROJECT\\node_modules\\.pnpm\\next@13.2.1_biqbaboplfbrettd7655fr4n2y\\node_modules\\next\\dist\\build\\utils.js',
    'C:\\Users\\USERNAME\\Documents\\Projects\\PROJECT\\node_modules\\.pnpm\\next@13.2.1_biqbaboplfbrettd7655fr4n2y\\node_modules\\next\\dist\\server\\dev\\static-paths-worker.js',
    'C:\\Users\\USERNAME\\Documents\\Projects\\PROJECT\\node_modules\\.pnpm\\next@13.2.1_biqbaboplfbrettd7655fr4n2y\\node_modules\\next\\dist\\compiled\\jest-worker\\processChild.js'
  ],
  page: '/test'
}

```

</details>

### Manual configuration

```js
{
    Auth: {
      identityPoolId: process.env.NEXT_PUBLIC_COGNITO_IDENTITY_POOL_ID,
      region: process.env.NEXT_PUBLIC_COGNITO_REGION,
      userPoolId: process.env.NEXT_PUBLIC_COGNITO_USERPOOL_ID,
      userPoolWebClientId: process.env.NEXT_PUBLIC_COGNITO_CLIENT_ID,
    },
    ssr: true,
  }
```

**Comment by ben-sommer** [comment]
Just tried replicating this issue with my steps above. The error is gone and the `Auth` module works as expected. Closing until I figure out how my implementation differs to this.

**Comment by nadetastic** [comment]
@ben-sommer I see you were able to get it working, let me know if you are able to determine what cause this issue. Thanks!

**Comment by ben-sommer** [comment]
In my `next.config.js` file I was telling webpack not to parse the `aws-crt` module due to some earlier issues I was having. It didn't change anything but forgot to remove it. My old `next.config.js` is below:
```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    appDir: true,
  },
  webpack: (config) => {
    config.module.noParse = [/aws-crt/];

    return config;
  },
}

module.exports = nextConfig;
```

**Comment by nadetastic** [comment]
Thank you for providing the context! @ben-sommer
