### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by ReneDiazDiversity** [aws-amplify/amplify-js#11078]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Not applicable

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line
Binaries:
    Node: 17.0.1 - /usr/local/bin/node
    npm: 8.1.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 110.1.48.171
    Chrome: 110.0.5481.177
    Firefox: 110.0.1
    Safari: 16.2
  npmPackages:
    phaser: ^3.55.2 => 3.55.2 
    postcss-preset-env: ^6.7.0 => 6.7.0 
  npmGlobalPackages:
    corepack: 0.10.0
    npm: 8.1.0
    parcel-bundler: 1.12.5

rdmacbook2021@RD-MacBook-2021 ~ % 


```

</details>

### Describe the bug

AIP call working on local host but not on live site. [Deployed amplify app
 aiGptPopup.884dea51.js:5          Uncaught (in promise) TypeError: Failed to fetch
    at Object.v (aiGptPopup.884dea51.js:5:2243)
    at HTMLButtonElement.G (jsxRuntime.module.c94421eb.js:1:4917)

### Expected behavior

should return api call

should return api call

### Reproduction steps

Chrome extension is installed and then a query is made which calls the OpenAI API

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @ReneDiazDiversity 👋 thanks for raising this issue. Is there anymore error info from the OpenAI response? Hard to tell what the cause of the issue is based on the current error message. 

Is there an API Key being used in an environment variable? Might be that hosting is missing that environment variable and just needs to be configured in the settings and then redeployed. Can you confirm if this is the case?

**Comment by ReneDiazDiversity** [comment]
It is an extension we are building. Yes, it must be installed, but it is not launched yet on the chrome store.  
I'm not sure what is environment variable

However, I am having the same issue with our other project which is a web app https://www.grantaide.com/aiapp

**Comment by david-mcafee** [comment]
@ReneDiazDiversity - the environment variable @chrisbonifacio was referring to is the API key to call the Open AI API. On the web app that you linked, I'm seeing [a 404](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404) - are you seeing this on your extension, as well? 

Also, can you let us know where you are encountering the `[Deployed amplify app aiGptPopup.884dea51.js:5 Uncaught (in promise) TypeError: Failed to fetch at Object.v (aiGptPopup.884dea51.js:5:2243) at HTMLButtonElement.G (jsxRuntime.module.c94421eb.js:1:4917)` error? Are you seeing coming from the CLI after `amplify push`? Or are you seeing this when you open the extension / app?

Without much other detail, my best guess is that there is an error with your calls to OpenAI (thus the 404).

Can you please add further repro steps to this ticket, and potentially the snippet of code that's failing? Can you also tell us how you are using Amplify for this project? Thank you!

**Comment by ReneDiazDiversity** [comment]
can you send me the link of where you are getting the 404 please

**Comment by ReneDiazDiversity** [comment]
?

**Comment by david-mcafee** [comment]
Hey @ReneDiazDiversity - the 404 was from the website you linked (https://www.grantaide.com/aiapp) - noticed that in the console when I asked a test question. 

Can you please add further reproduction steps for the error you are seeing? Thank you!!

**Comment by ReneDiazDiversity** [comment]
I'm not getting a 404 
as for the extenstion we are not getting an error it is just not getting a reply from the open ai api

**Comment by chrisbonifacio** [comment]
@ReneDiazDiversity it sounds like you might be using the `API` methods such as `API.get`, `API.post`, etc. Is that correct? Can you share a code snippet of how you're trying to make the request to OpenAI?
