### ISSUE TITLE
TypeError: Converting circular structure to JSON in aws-amplify Auth

### ISSUE THREAD

**Issue by umuthopeyildirim** [aws-amplify/amplify-js#11145]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
 System:
    OS: macOS 13.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 23.57 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.2 - /usr/local/bin/npm
    Watchman: 2023.03.13.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 111.0.5563.146
    Safari: 16.3
  npmPackages:
    @aws-amplify/ui-react: ^4.4.0 => 4.4.1 
    @aws-amplify/ui-react-internal:  undefined ()
    @types/react: ^18.0.28 => 18.0.29 
    @types/react-dom: ^18.0.11 => 18.0.11 
    @vitejs/plugin-react: ^3.1.0 => 3.1.0 
    autoprefixer: ^10.4.14 => 10.4.14 
    aws-amplify: ^5.0.20 => 5.0.22 
    daisyui: ^2.51.4 => 2.51.5 
    postcss: ^8.4.21 => 8.4.21 
    react: ^18.2.0 => 18.2.0 
    react-daisyui: ^3.0.3 => 3.0.3 
    react-dom: ^18.2.0 => 18.2.0 
    react-icons: ^4.8.0 => 4.8.0 
    react-lazy-load-image-component: ^1.5.6 => 1.5.6 
    react-router-dom: ^6.9.0 => 6.9.0 
    sweetalert2: ^11.7.3 => 11.7.3 
    sweetalert2-react-content: ^5.0.7 => 5.0.7 
    tailwindcss: ^3.2.7 => 3.2.7 
    vite: ^4.2.0 => 4.2.1 
  npmGlobalPackages:
    corepack: 0.17.0
    live-server: 1.2.2
    npm: 9.6.2
```

</details>

### Describe the bug

Please check output part.
Unable to change or update user attributes.
Bug seems to be in this repo but i also included my codebase.

### Expected behavior

updateUserAttributes should update users name, email etc.

### Reproduction steps

1. Try to use userAttributes in react javascript base

### Code Snippet

```javascript
// Put your code below this line.
import { useState, useEffect } from "react";
import { Auth } from "aws-amplify";
import { Navigate } from "react-router-dom";
import { Modal, Input } from 'react-daisyui';
import Swal from 'sweetalert2'
import withReactContent from 'sweetalert2-react-content'

// TODO: Add change name and email functionality
function ProfileDetail(){
    const MySwal = withReactContent(Swal)
    const [user, setUser] = useState(null);
    const [visible, setVisible] = useState(false)
    const [nameVisible, setNameVisible] = useState(false)
    const [emailVisible, setEmailVisible] = useState(false)
    const [oldPassword, setOldPassword] = useState('');
    const [newPassword, setNewPassword] = useState('');
    const [newName, setNewName] = useState('');
    const [newEmail, setNewEmail] = useState('');
    const [tenant, setTenant] = useState('');

    useEffect(() => {
      fetchUserInfo(setTenant);
    }, []);

    useEffect(() => {
        async function getUser() {
            try {
                const user = await Auth.currentAuthenticatedUser();
                setUser(user);
            } catch (error) {
                console.log('error getting user', error);
                return <Navigate to="/" />
            }
        }
        getUser();
    }, [])

    // after confirmation, the user was added to the
// cognito group associated with the tenant
    async function fetchUserInfo(setTenant) {
        // get the access token of the signed in user
        const {accessToken} = await Auth.currentSession();
        // get the tenant from the top of the cognito groups list
        const cognitogroups = accessToken.payload['cognito:groups'];
        const tenant = cognitogroups[0];
        setTenant(tenant);
    }

    async function changePassword(oldPassword, newPassword) {
        try {
            const user = await Auth.currentAuthenticatedUser();
            await Auth.changePassword(user, oldPassword, newPassword);
            MySwal.fire({
                title: 'Success!',
                text: 'Your password has been changed.',
                icon: 'success',
                confirmButtonText: 'OK'
            })
        } catch (error) {
            console.log('error changing password', error);
            // Add sweetalert also contain error message
            MySwal.fire({
                title: 'Error! Unable to change password.',
                text: error.message,
                icon: 'error',
                confirmButtonText: 'OK'
            })
            
        }
    }

    async function changeName(newName) {
        try {
          const user = await Auth.currentAuthenticatedUser();
          const attributes = {
            name: newName
          };
          await Auth.updateUserAttributes(user, attributes);
          MySwal.fire({
            title: 'Success!',
            text: 'Your name has been changed.',
            icon: 'success',
            confirmButtonText: 'OK'
          })
        } catch (error) {
          console.log('error changing name', error);
          // Add sweetalert also contain error message
          MySwal.fire({
            title: 'Error! Unable to change name.',
            text: error.message,
            icon: 'error',
            confirmButtonText: 'OK'
          })
        }
    }
      
    async function changeEmail(newEmail) {
        try {
          const user = await Auth.currentAuthenticatedUser();
          const attributes = {
            email: newEmail
          };
          await Auth.updateUserAttributes(user, attributes);
          MySwal.fire({
            title: 'Success!',
            text: 'Your email has been changed.',
            icon: 'success',
            confirmButtonText: 'OK'
          })
        } catch (error) {
          console.log('error changing email', error);
          // Add sweetalert also contain error message
          MySwal.fire({
            title: 'Error! Unable to change email.',
            text: error.message,
            icon: 'error',
            confirmButtonText: 'OK'
          })
        }
    }
          

    const handleChangePassword = () => {
        changePassword(oldPassword, newPassword);
        toggleVisible();
    }

    const handleNameVisible = () => {
        setNameVisible(!nameVisible)
    }

    const handleEmailVisible = () => {
        setEmailVisible(!emailVisible)
    }
    
    const toggleVisible = () => {
        setVisible(!visible)
    }

    const handleOldPassword = (e) => {
        setOldPassword(e.target.value);
    }

    const handleNewPassword = (e) => {
        setNewPassword(e.target.value);
    }

    const handleNewName = (e) => {
        setNewName(e.target.value);
    }

    const handleNewEmail = (e) => {
        setNewEmail(e.target.value);
    }

    return (
        <>
            {user ? (
                <div className="space-y-4 space-x-4">
                    <h1 className="text-2xl text-gray-200">Welcome, {user.attributes.name}</h1>
                    <p className="text-gray-200">Email: {user.attributes.email}</p>
                    <button className="btn btn-primary" onClick={handleNameVisible}>Change Name</button>
                    <button className="btn btn-secondary" onClick={handleEmailVisible}>Change E-Mail</button>
                    <button className="btn btn-info" onClick={toggleVisible}>Change Password</button>
                    <p className="text-xl">Your tenant is {tenant}</p>
                </div>
            ) : (
                <div className="space-y-4">
                    <h1 className="text-2xl text-gray-200">Welcome, Loading...</h1>
                </div>
            )}
            {visible ? (
                <>
                    <Modal open={visible} onClickBackdrop={toggleVisible}>
                        <Modal.Header className="font-bold">
                            Change Your Password
                        </Modal.Header>

                        <Modal.Body className="flex flex-col space-y-2">
                            {/* Add input boxes for old and new password */}
                            <Input type="password" placeholder="Old Password" onChange={handleOldPassword} />
                            <Input type="password" placeholder="New Password" onChange={handleNewPassword} />
                        </Modal.Body>

                        <Modal.Actions>
                            <button className="btn btn-error" onClick={handleChangePassword}>Change Password</button>
                            <button className="btn btn-second" onClick={toggleVisible}>Cancel</button>
                        </Modal.Actions>
                    </Modal>
                </>
            ): null}
            {nameVisible ? (
                <>
                    <Modal open={nameVisible} onClickBackdrop={handleNameVisible}>
                        <Modal.Header className="font-bold">
                            Change Your Name
                        </Modal.Header>
                        
                        <Modal.Body className="flex flex-col space-y-2">
                            {/* Add input boxes for old and new password */}
                            <Input type="text" placeholder="New Name" onChange={handleNewName} />
                        </Modal.Body>

                        <Modal.Actions>
                            <button className="btn btn-primary" onClick={changeName}>Change Name</button>
                            <button className="btn btn-second" onClick={handleNameVisible}>Cancel</button>
                        </Modal.Actions>
                    </Modal>
                </>
            ): null}
            {emailVisible ? (
                <>
                    <Modal open={emailVisible} onClickBackdrop={handleEmailVisible}>
                        <Modal.Header className="font-bold">
                            Change Your E-Mail
                        </Modal.Header>

                        <Modal.Body className="flex flex-col space-y-2">
                            {/* Add input boxes for old and new password */}
                            <Input type="text" placeholder="New E-Mail" onChange={handleNewName} />
                        </Modal.Body>

                        <Modal.Actions>
                            <button className="btn btn-primary" onClick={changeEmail}>Change E-Mail</button>
                            <button className="btn btn-second" onClick={handleEmailVisible}>Cancel</button>
                        </Modal.Actions>
                    </Modal>
                </>
            ): null}
        </>
    )
}

export default ProfileDetail;
```

### Log output

<details>

```
[DEBUG] 45:38.510 AuthClass - getting current authenticated user
ConsoleLogger.ts:105 [DEBUG] 45:38.511 AuthClass - get current authenticated userpool user
ConsoleLogger.ts:115 [DEBUG] 45:38.511 AuthClass - Succeed to get the user session CognitoUserSession2 {idToken: CognitoIdToken2, refreshToken: CognitoRefreshToken2, accessToken: CognitoAccessToken2, clockDrift: 0}
ConsoleLogger.ts:115 [DEBUG] 45:38.512 AuthClass - Succeed to get the user session CognitoUserSession2 {idToken: CognitoIdToken2, refreshToken: CognitoRefreshToken2, accessToken: CognitoAccessToken2, clockDrift: 0}
Client.js:98 Uncaught (in promise) TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'HTMLButtonElement'
    |     property '__reactFiber$udd1hg7uu2q' -> object with constructor 'FiberNode'
    --- property 'stateNode' closes the circle
    at JSON.stringify (<anonymous>)
    at Client4.request (Client.js:98:18)
    at CognitoUser2.updateAttributes (CognitoUser.js:864:17)
    at Auth.ts:1447:10
```

</details>

### aws-exports.js

```javascript
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_mobile_analytics_app_id": "ab84989c86784d0cb70f4211d30fdc5f",
    "aws_mobile_analytics_app_region": "eu-west-2",
    "Analytics": {
        "AWSPinpoint": {
            "appId": "ab84989c86784d0cb70f4211d30fdc5f",
            "region": "eu-west-2"
        }
    },
    "aws_appsync_graphqlEndpoint": "https://*****************.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "*******************",
    "aws_cloud_logic_custom": [
        {
            "name": "rendererAPI",
            "endpoint": "https://********.execute-api.eu-west-2.amazonaws.com/dev",
            "region": "eu-west-2"
        }
    ],
    "aws_cognito_identity_pool_id": "eu-west-2:eb45a53d-fc9a-46c7-a136-a6e699693762",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_Y615ia10c",
    "aws_user_pools_web_client_id": "kov9qn17g55gm68avtjc391qj",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME",
        "NICKNAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "rendererbucket152352-dev",
    "aws_user_files_s3_bucket_region": "eu-west-2"
};


export default awsmobile;
```

### Mobile Device

None

### Mobile Operating System

Nonr

### Mobile Browser

Arc Browser, Chrome

### Mobile Browser Version

None

### Additional information and screenshots

```
{
  "name": "mirage-renderer",
  "description": "Precisely annotated synthetic image data solves cold start problems, increases existing training data's efficiency, covers edge cases and reduces development time and cost. You don't have to be a data rich company to benefit from synthetic data.",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@aws-amplify/ui-react": "^4.4.0",
    "autoprefixer": "^10.4.14",
    "aws-amplify": "^5.0.20",
    "daisyui": "^2.51.4",
    "postcss": "^8.4.21",
    "react": "^18.2.0",
    "react-daisyui": "^3.0.3",
    "react-dom": "^18.2.0",
    "react-icons": "^4.8.0",
    "react-lazy-load-image-component": "^1.5.6",
    "react-router-dom": "^6.9.0",
    "sweetalert2": "^11.7.3",
    "sweetalert2-react-content": "^5.0.7",
    "tailwindcss": "^3.2.7"
  },
  "devDependencies": {
    "@types/react": "^18.0.28",
    "@types/react-dom": "^18.0.11",
    "@vitejs/plugin-react": "^3.1.0",
    "vite": "^4.2.0"
  }
}
```

**Comment by tannerabread** [comment]
Hi @umuthopeyildirim I think I may have found your issue.

It looks like `newName` and `newEmail` from your state are declared but never read
![image](https://user-images.githubusercontent.com/30082936/228580775-f83f5ae6-c301-4727-81ab-119ef2e7f898.png)
![image](https://user-images.githubusercontent.com/30082936/228580846-1fbf39e2-4fef-4968-abd1-a2c3f9805f70.png)

Instead of pulling from the state your functions are expecting those parameters to be passed in, so the `name: newName` in your `changeName` function is scoped to the parameter being passed in, but you aren't passing in a parameter when binding the function to the button.
![image](https://user-images.githubusercontent.com/30082936/228581333-b7c7d823-621b-4553-a865-892e28c69a41.png)
![image](https://user-images.githubusercontent.com/30082936/228585371-55540fbc-d3e0-43dc-a3a8-d24c5728f10c.png)

I tried this flow in my own app and didn't get the same error as you, but it did cause issues. Can you try removing the parameter from the function so that your app will use the state instead? 

Another note is the code you supplied never updates the `newEmail` field by never calling `handleNewEmail` but you may not have been there yet after seeing the error with changing the name

**Comment by tannerabread** [comment]
So I'm not actually sure why the name one started working as it is still scoped to the parameter which isn't being passed.

Since you are storing your input in state and want those values in your functions, it might be better to just remove the parameters from the function definition so that it accesses the state variables instead.
A mixture of the 2 codes you posted and following that advice would lead to code like:
```js
import { useState, useEffect } from "react";
import { Auth } from "aws-amplify";
import { Navigate } from "react-router-dom";
import { Modal, Input } from 'react-daisyui';
import Swal from 'sweetalert2'
import withReactContent from 'sweetalert2-react-content'

// TODO: Add change name and email functionality
function ProfileDetail(){
    const MySwal = withReactContent(Swal)
    const [user, setUser] = useState(null);
    const [visible, setVisible] = useState(false)
    const [oldPassword, setOldPassword] = useState('');
    const [newPassword, setNewPassword] = useState('');
    const [tenant, setTenant] = useState('');
    const [name, setName] = useState('');
    const [email, setEmail] = useState('');

    useEffect(() => {
      fetchUserInfo(setTenant);
    }, []);

    const toggleVisible = () => {
        setVisible(!visible)
    }


    useEffect(() => {
        async function getUser() {
            try {
                const user = await Auth.currentAuthenticatedUser();
                setUser(user);
            } catch (error) {
                console.log('error getting user', error);
                return <Navigate to="/" />
            }
        }
        getUser();
    }, [])

    // after confirmation, the user was added to the
// cognito group associated with the tenant
    async function fetchUserInfo(setTenant) {
        // get the access token of the signed in user
        const {accessToken} = await Auth.currentSession();
        // get the tenant from the top of the cognito groups list
        const cognitogroups = accessToken.payload['cognito:groups'];
        const tenant = cognitogroups[0];
        setTenant(tenant);
    }

    async function changePassword(oldPassword, newPassword) {
        try {
            const user = await Auth.currentAuthenticatedUser();
            await Auth.changePassword(user, oldPassword, newPassword);
            MySwal.fire({
                title: 'Success!',
                text: 'Your password has been changed.',
                icon: 'success',
                confirmButtonText: 'OK'
            })
        } catch (error) {
            console.log('error changing password', error);
            // Add sweetalert also contain error message
            MySwal.fire({
                title: 'Error! Unable to change password.',
                text: error.message,
                icon: 'error',
                confirmButtonText: 'OK'
            })
            
        }
    }

    async function changeName() {
        try {
          const user = await Auth.currentAuthenticatedUser();
          await Auth.updateUserAttributes(user, { name: name });
          MySwal.fire({
            title: 'Success!',
            text: 'Your name has been changed.',
            icon: 'success',
            confirmButtonText: 'OK'
          })
        } catch (error) {
          console.log('error changing name', error);
          MySwal.fire({
            title: 'Error! Unable to change name.',
            text: error.message,
            icon: 'error',
            confirmButtonText: 'OK'
          })
        }
    }
      
    async function changeEmail() {
        try {
          const user = await Auth.currentAuthenticatedUser();
          console.log(email)
          await Auth.updateUserAttributes(user, { email: email });
          MySwal.fire({
            title: 'Success!',
            text: 'Your email has been changed.',
            icon: 'success',
            confirmButtonText: 'OK'
          })
          console.log('email changed successfully', user)
        } catch (error) {
          console.log('error changing email', error);
          MySwal.fire({
            title: 'Error! Unable to change email.',
            text: error.message,
            icon: 'error',
            confirmButtonText: 'OK'
          })
        }
    }

    const handleChangePassword = () => {
        changePassword(oldPassword, newPassword);
        toggleVisible();
    }

    const handleOldPassword = (e) => {
        setOldPassword(e.target.value);
    }

    const handleNewPassword = (e) => {
        setNewPassword(e.target.value);
    }

    const handleNameChange = (e) => {
        setName(e.target.value);
    }

    const handleEmailChange = (e) => {
        setEmail(e.target.value);
    }

    return (
        <>
          {user ? (
            <div className="space-y-4">
              <h1 className="text-2xl text-gray-200">Welcome, {user.attributes.name}</h1>
              <p className="text-gray-200">Email: {user.attributes.email}</p>
              <div className="space-y-4">
                <div className="flex items-center">
                  <Input placeholder="Name" value={name} onChange={handleNameChange} />
                  <button className="btn btn-second ml-2" onClick={changeName}>Change Name</button>
                </div>
                <div className="flex items-center">
                  <Input placeholder="Email" value={email} onChange={handleEmailChange} />
                  <button className="btn btn-second ml-2" onClick={changeEmail}>Change Email</button>
                </div>
                <button className="btn btn-second" onClick={toggleVisible}>Change Password</button>
                <p className="text-xl">Your tenant is {tenant}</p>
              </div>
            </div>
          ) : (
            <div className="space-y-4">
              <h1 className="text-2xl text-gray-200">Welcome, Loading...</h1>
            </div>
          )}
          {visible ? (
            <>
              <Modal open={visible} onClickBackdrop={toggleVisible}>
                <Modal.Header className="font-bold">
                  Change Your Password
                </Modal.Header>
      
                <Modal.Body>
                  <Input type="password" placeholder="Old Password" onChange={handleOldPassword} />
                  <Input type="password" placeholder="New Password" onChange={handleNewPassword} />
                </Modal.Body>
      
                <Modal.Actions>
                  <button className="btn btn-error" onClick={handleChangePassword}>Change Password</button>
                  <button className="btn btn-second" onClick={toggleVisible}>Cancel</button>
                </Modal.Actions>
              </Modal>
            </>
          ): null}
        </>
    );
}

export default ProfileDetail;
```

Note the lines `async function changeName() {` and `async function changeEmail() {`
You will probably also want to do the same with your password function

**Comment by umuthopeyildirim** [comment]
Still not working, even with your codes. It gets the email param correctly as you can see in the console.  Is this related to a setting in AWS Cognito or Amplify? 

Console output:

```
Email address to change: hope@gmail.com
ProfileDetail.jsx:107 email changed successfully 
CognitoUser2 {username: '4b64b6cf-6b5f-4dc5-83e9-6375d1155a57', pool: CognitoUserPool2, Session: null, client: Client4, signInUserSession: CognitoUserSession2, …}
Session
: 
null
attributes
: 
{sub: '4b64b6cf-6b5f-4dc5-83e9-6375d1155a57', email_verified: true, name: 'hope', nickname: 'hope', email: 'umut475@gmail.com'}
authenticationFlowType
: 
"USER_SRP_AUTH"
client
: 
Client4 {endpoint: 'https://cognito-idp.eu-west-2.amazonaws.com/', fetchOptions: {…}}
deviceKey
: 
null
keyPrefix
: 
"CognitoIdentityServiceProvider.kov9qn17g55gm68avtjc391qj"
pool
: 
CognitoUserPool2 {userPoolId: 'eu-west-2_Y615ia10c', clientId: 'kov9qn17g55gm68avtjc391qj', client: Client4, advancedSecurityDataCollectionFlag: true, storage: Storage, …}
preferredMFA
: 
"NOMFA"
signInUserSession
: 
CognitoUserSession2 {idToken: CognitoIdToken2, refreshToken: CognitoRefreshToken2, accessToken: CognitoAccessToken2, clockDrift: 0}
storage
: 
Storage {aws-amplify-cacheInAppMessaging:AWSPinpoint:undefined: '{"key":"aws-amplify-cacheInAppMessaging:AWSPinpoin…es":4833029259732,"type":"string","byteSize":231}', CognitoIdentityServiceProvider.63pqk0vvjidfu9ghs42q7iuu9h.03eb6973-173b-4e45-a00a-4664226ba464.accessToken: 'eyJraWQiOiJ3V0lUWXNtS0NjV25vd3Q3bW51Wmk5ZlNiTXF5Nk…A4BGVzyTrHIrMZYmkXkODZzpQzgtiPOEPEw4y-u4RyrWWLtGw', CognitoIdentityServiceProvider.63pqk0vvjidfu9ghs42q7iuu9h.03eb6973-173b-4e45-a00a-4664226ba464.idToken: 'eyJraWQiOiJPWkxrXC9GSDVObmNlak94QTFKek5JNUppdVpXRz…oTyr7589UL74cINSpYfcnyKpK-hI66K69d2s1LY9Svdg5hDsQ', aws-amplify-cacheInAppMessaging:AWSPinpoint:ab84989c86784d0cb70f4211d30fdc5f: '{"key":"aws-amplify-cacheInAppMessaging:AWSPinpoin…es":4833533746216,"type":"string","byteSize":254}', CognitoIdentityServiceProvider.5komfqm9i9n1iph2bq8iebr8i2.fd920998-ae51-43fb-9840-230a4cc3a680.refreshToken: 'eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiUl…qpP41Y85irjm23UZP055D3dTbU.4q7yKnd8LfbI3TJclpSWag', …}
userDataKey
: 
"CognitoIdentityServiceProvider.kov9qn17g55gm68avtjc391qj.4b64b6cf-6b5f-4dc5-83e9-6375d1155a57.userData"
username
: 
"4b64b6cf-6b5f-4dc5-83e9-6375d1155a57"
[[Prototype]]
: 
Object
```

**Comment by tannerabread** [comment]
Hi @umuthopeyildirim I'm sorry I missed your response for so long, can you confirm if you were receiving the verification code on the email you were trying to switch to? When you change the email or phone number, the library requires you to confirm the code sent to the new entity with the `[verifyCurrentUserAttributeSubmit` method](https://docs.amplify.aws/lib/auth/manageusers/q/platform/js/#confirm-attribute)

Here is a [longer working sample](https://docs.amplify.aws/lib/auth/manageusers/q/platform/js/#updating-and-verifying-a-cognito-user-email-address) on how to do that
