### ISSUE TITLE
AmazomMQ and Pub/Sub, MqttOverWSProvider - Error forming connection Error: AMQJS0013E

### ISSUE THREAD

**Issue by Nikola-Milovic** [aws-amplify/amplify-js#11322]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

PubSub

### Amplify Categories

auth

### Describe the bug

When trying to connect with AmazonMQ using the `MqttOverWSProvider` and Pub/Sub I keep experiencing the same error 

```js
[DEBUG] 57:11.670 MqttOverWSProvider - Error forming connection Error: AMQJS0013E Invalid argument wss://b-dxxxxx-70d9-406b-axxc-xxxxxdfa15-1.mq.eu-central-1.amazonaws.com:61619 for host.
    at new Client4 (paho-mqtt.js:2007:12)
    at MqttOverWSProvider2.<anonymous> (MqttOverWSProvider.ts:188:18)
    at step (tslib.es6.js:100:23)
    at Object.next (tslib.es6.js:81:53)
    at tslib.es6.js:74:71
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:70:12)
    at MqttOverWSProvider2.newClient (MqttOverWSProvider.ts:182:3)
    at MqttOverWSProvider2.<anonymous> (MqttOverWSProvider.ts:236:30)
    at step (tslib.es6.js:100:23)
```

### Expected behavior

I would connect and use Pub/Sub as expected

### Reproduction steps

Create an ActiveMQ broker on AmazonMQ and try to connect to it 

```javascript
import { CfnOutput, Fn } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { aws_iam as iam, aws_secretsmanager as secman, aws_amazonmq as amazonmq } from 'aws-cdk-lib';
import { isDev } from './utils';

type ActiveMQConstructProps = {
  authenticatedRole: iam.IRole;
};

export class ActiveMQConstruct extends Construct {
  constructor(scope: Construct, id: string, props: ActiveMQConstructProps) {
    super(scope, id);

    const { authenticatedRole } = props;

    const password = new secman.Secret(this, 'BrokerAdminPassword', {
      generateSecretString: { excludePunctuation: true },
      description: 'Password for the Message Broker User',
    });

    const user: amazonmq.CfnBroker.UserProperty = {
      consoleAccess: true,
      username: 'admin',
      password: password.toString(),
    };

    const mqBroker = new amazonmq.CfnBroker(this, 'ActiveMQ', {
      autoMinorVersionUpgrade: true,
      brokerName: 'MyActiveMQ',
      storageType: 'in-memory', // havent tested this option, you can maybe remove it
      maintenanceWindowStartTime: {
        dayOfWeek: 'WEDNESDAY',
        timeOfDay: '14:00',
        timeZone: 'Europe/London',
      },
      deploymentMode: 'SINGLE_INSTANCE',
      engineType: 'ActiveMQ', // Change engine type to ActiveMQ
      engineVersion: '5.15.10', // Use a compatible ActiveMQ version
      hostInstanceType: 'mq.t3.micro',
      publiclyAccessible: true,
      users: [user],
    });
  }
}
```

### Code Snippet

```javascript
import { MqttOverWSProvider } from "@aws-amplify/pubsub";
import { Amplify, Analytics, Hub, Logger, PubSub } from "aws-amplify";

Logger.LOG_LEVEL ="DEBUG" 

export const configureAmplify = async () => {
	try {
		Amplify.configure({
			Auth: {
				region: env.AWS_REGION,
				userPoolId: env.AWS_COGNITO_USER_POOL_ID,
				userPoolWebClientId: env.AWS_COGNITO_ADMIN_USER_POOL_CLIENT_ID,
				identityPoolId: env.AWS_COGNITO_IDENTITY_POOL_ID,
				identityPoolRegion: env.AWS_REGION,
				mandatorySignIn: true,
			},
		});

		// https://github.com/aws-amplify/amplify-js/issues/11255#issuecomment-1510430059
		Amplify.register(PubSub);
		Amplify.addPluggable(
			new MqttOverWSProvider({
				aws_pubsub_endpoint: env.AWS_MQTT_ENDPOINT,
				aws_region: env.AWS_REGION,
			}),
		);

	} catch (error) {
		console.error("error occured during amplify setup", error);
	}
}
```

And in my `main.tsx` for my Vite website 

```
import {configureAmplify} from "@admin/lib/amplify";

configureAmplify()

ReactDOM.createRoot(document.getElementById("root")!).render(
	<React.StrictMode>
		<BrowserRouter>
			<Main />
		</BrowserRouter>
	</React.StrictMode>,
);
```
### Additional information and screenshots

Not sure which one of these should I use, I tried them all

![image](https://user-images.githubusercontent.com/50072027/235347448-6876b34e-a65d-40d6-8b0a-aff4a6fc4d08.png)

The broker is publicly available

**Comment by cwomack** [comment]
@Nikola-Milovic, appreciate your patience on this issue for how it took us to get back.  Is this still occurring and do you have a minimal sample repo you can share to reproduce this?

**Comment by Nikola-Milovic** [comment]
@cwomack i can try recreating it when I get the time, its been a while since I tried using it

**Comment by ashika112** [comment]
@Nikola-Milovic were you able to re-create this issue in another minimal sample app you could share?

**Comment by Nikola-Milovic** [comment]
@ashika112 sorry, I havent, I moved away from it after having these issues. You can close this if nobody else is experiencing the same issues.

**Comment by ashika112** [comment]
@Nikola-Milovic Thanks for quick reponse and sorry we hadnt gotten back earlier. I will close this issue for now since we hadnt seen anyone facing similar issue
