### ISSUE TITLE
AWSPinpointProvider - updateEndpoint failed TypeError: Cannot read properties of undefined (reading 'byteLength')

### ISSUE THREAD

**Issue by afern247** [aws-amplify/amplify-js#11418]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-adminui/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-adminui/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2tehu1nszw8pw

### Region

us-east-1

### Environment name

dev

### Amplify CLI Version

12.0.1

### If applicable, what version of Node.js are you using?

v18.14.0

### What operating system are you using?

Mac

### Browser type?

Firefox

### Describe the bug

I'm seeing a lot of errors on the front end when I pull the project and try to log in:

![image](https://github.com/aws-amplify/amplify-studio/assets/34192856/8d9b4c69-ee08-44db-b199-542c8b112323)

and on the terminal I see:

```
[ERROR] 57:12.933 AWSPinpointProvider - updateEndpoint failed TypeError: Cannot read properties of undefined (reading 'byteLength')
    at Object.fromArrayBuffer (/Users/arturo/Development/Github/web-app/node_modules/@aws-sdk/util-buffer-from/dist/cjs/index.js:6:60)
    at castSourceData (/Users/arturo/Development/Github/web-app/node_modules/@aws-sdk/hash-node/dist/cjs/index.js:29:31)
    at Hash.update (/Users/arturo/Development/Github/web-app/node_modules/@aws-sdk/hash-node/dist/cjs/index.js:12:26)
    at hmac (/Users/arturo/Development/Github/web-app/node_modules/@aws-sdk/signature-v4/dist/cjs/credentialDerivation.js:60:10)
    at Object.getSigningKey (/Users/arturo/Development/Github/web-app/node_modules/@aws-sdk/signature-v4/dist/cjs/credentialDerivation.js:32:29)
    at SignatureV4.getSigningKey (/Users/arturo/Development/Github/web-app/node_modules/@aws-sdk/signature-v4/dist/cjs/SignatureV4.js:139:39)
    at SignatureV4.signRequest (/Users/arturo/Development/Github/web-app/node_modules/@aws-sdk/signature-v4/dist/cjs/SignatureV4.js:98:73)
    at async /Users/arturo/Development/Github/web-app/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:14:22
    at async StandardRetryStrategy.retry (/Users/arturo/Development/Github/web-app/node_modules/@aws-sdk/middleware-retry/dist/cjs/defaultStrategy.js:56:46)
    at async /Users/arturo/Development/Github/web-app/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22 {
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
```

### Expected behavior

Not seeing the error..

### Reproduction steps

For some context:
- I'm using Typescript/React. 
- I want to note that the same thing is happening for the prod environment.
- I'm using an admin user to authenticate

1. I deleted my amplify folder locally and the src folder too
2. then I try to pull the environment with `amplify pull --appId d2tehu1nszw8pw --envName dev`
3. A new tap on my browser opens up to authenticate and I see this:
![image](https://github.com/aws-amplify/amplify-studio/assets/34192856/ff9581e2-3b30-47e7-8d61-df6b58eb66d4)

Before this issue I would see a notification there like to allow or not, but now it's not showing...
4. I paste the key on the terminal and it lets me pull the environment fine all good.
5. I run the app with `npm run dev` and I see the error on the picture above...

What's going on?

**Comment by nadetastic** [comment]
Hi @afern247 following up on this issue. The error message `Cannot read properties of undefined / byteLength` is usually tied to missing permissions on the current user. For example, if the current user is not signed in to your application, but needs to be signedIn to your app to interact with Analytics, this error may occur. Can you confirm if this is the case for you, or if you were able to get this resolved?

**Comment by afern247** [comment]
This can be closed, I'm not using Amplify anymore, thanks
