### ISSUE TITLE
Amplify Storage Issue

### ISSUE THREAD

**Issue by vgthoppae** [aws-amplify/amplify-js#11492]
### Amplify CLI Version

11.1.1

### Question

This may be something simple, the `Storage.put` command works fine from localhost, but breaks when the app is accessed from the custom domain set up on hosting, with the below error. Simply puzzling. Appreciate any pointers.

```
TypeError: (0 , sx.resolveHostHeaderConfig) is not a function
    at new t (_app-355c5eb0eb8aef58.js:13:240132)
    at sL (_app-355c5eb0eb8aef58.js:13:242758)
    at e._createNewS3Client (_app-355c5eb0eb8aef58.js:13:256028)
    at new e (_app-355c5eb0eb8aef58.js:13:251009)
    at e.put (_app-355c5eb0eb8aef58.js:13:272345)
    at e.put (_app-355c5eb0eb8aef58.js:13:280266)
    at O (_app-355c5eb0eb8aef58.js:35:387332)
```

This is an amplify provisioned storage with CORS policies.

**Comment by nadetastic** [comment]
Hi @vgthoppae thank you for opening this issue, im working to reproduce this issue - can you confirm which versions of aws-amplify you are using?

**Comment by vgthoppae** [comment]
@nadetastic  Thanks for the response. The client library of` aws-amplify `is `5.0.9`.

**Comment by nadetastic** [comment]
@vgthoppae and what type of app is this? a react app/vue etc?

**Comment by vgthoppae** [comment]
@nadetastic it's a react/next js app.

**Comment by nadetastic** [comment]
@vgthoppae I haven't been able to reproduce this issue with so far - and since you mentioned that its only a problem on hosting, im going to transfer this issue to the Hosting Repo for better investigation. Please share any other relevant information such as:
- the AppID
- context around how you are calling the `Storage.put` command
- whether you are using the App Router or not
- version of Next/etc
