### ISSUE TITLE
pnpm in monorepo fails

### ISSUE THREAD

**Issue by trixobird** [aws-amplify/amplify-js#11574]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

Not applicable

### Amplify Categories

Not applicable

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 13.4.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 5.03 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
    pnpm: 8.6.5 - ~/Library/pnpm/pnpm
    Watchman: 2023.04.03.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1
  npmPackages:
    @types/node: 20.3.3 => 20.3.3 
    @types/react: 18.2.14 => 18.2.14 
    @types/react-dom: 18.2.6 => 18.2.6 
    autoprefixer: 10.4.14 => 10.4.14 
    eslint: 8.44.0 => 8.44.0 
    eslint-config-next: 13.4.7 => 13.4.7 
    next: 13.4.7 => 13.4.7 
    postcss: 8.4.24 => 8.4.24 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    tailwindcss: 3.3.2 => 3.3.2 
    typescript: 5.1.6 => 5.1.6 
  npmGlobalPackages:
    @vatom/cli: 2.2.19
    corepack: 0.17.0
    npm: 9.5.1


```

</details>

### Describe the bug

I am trying to use pnpm in a monorepo. Here is the monorepo that I used: https://github.com/teacherfox/amplify-monorepo

I am only using console, since I want evaluate amplify.

If I use this script:
```
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - curl -fsSL https://get.pnpm.io/install.sh | sh -
            - source /root/.bashrc
            - npm install
        build:
          commands:
            - npm run build
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
    #   cache:
    #     paths:
    #       - node_modules/**/*
    appRoot: fe
```
Everything works. But if I use pnpm:
```
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - curl -fsSL https://get.pnpm.io/install.sh | sh -
            - source /root/.bashrc
            - pnpm install
        build:
          commands:
            - pnpm run build
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
    #   cache:
    #     paths:
    #       - node_modules/**/*
    appRoot: fe
```
I am getting a 500 errors in the /ssr and the follwing log error in cloudwatch:
```


2023-07-02T14:36:44.855+03:00 | LOGS Name: bootstrap State: Already subscribed Types: [Platform, Function]
-- | --
  | 2023-07-02T14:36:44.891+03:00 | ln: failed to create symbolic link ‘/tmp/app/node_modules/node_modules’: Read-only file system
  | 2023-07-02T14:36:44.893+03:00 | ln: failed to create symbolic link ‘/tmp/app/pages/pages’: Read-only file system
  | 2023-07-02T14:36:44.894+03:00 | ln: failed to create symbolic link ‘/tmp/app/public/public’: Read-only file system
  | 2023-07-02T14:36:44.911+03:00 | ln: failed to create symbolic link ‘/tmp/app/.next/static/static’: Read-only file system
  | 2023-07-02T14:36:44.912+03:00 | ln: failed to create symbolic link ‘/tmp/app/.next/server/chunks/chunks’: Read-only file system
  | 2023-07-02T14:36:45.100+03:00 | node:internal/modules/cjs/loader:1029
  | 2023-07-02T14:36:45.100+03:00 | throw err;
  | 2023-07-02T14:36:45.100+03:00 | ^
  | 2023-07-02T14:36:45.100+03:00 | Error: Cannot find module 'styled-jsx/package.json'
  | 2023-07-02T14:36:45.100+03:00 | Require stack:
  | 2023-07-02T14:36:45.100+03:00 | - /var/task/node_modules/next/dist/server/require-hook.js
  | 2023-07-02T14:36:45.100+03:00 | - /var/task/node_modules/next/dist/server/next-server.js
  | 2023-07-02T14:36:45.100+03:00 | - /tmp/app/server.js
  | 2023-07-02T14:36:45.100+03:00 | at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
  | 2023-07-02T14:36:45.100+03:00 | at Function.resolve (node:internal/modules/cjs/helpers:114:19)
  | 2023-07-02T14:36:45.100+03:00 | at Object.<anonymous> (/var/task/node_modules/next/dist/server/require-hook.js:31:25)
  | 2023-07-02T14:36:45.100+03:00 | at Module._compile (node:internal/modules/cjs/loader:1196:14)
  | 2023-07-02T14:36:45.100+03:00 | at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
  | 2023-07-02T14:36:45.100+03:00 | at Module.load (node:internal/modules/cjs/loader:1074:32)
  | 2023-07-02T14:36:45.100+03:00 | at Function.Module._load (node:internal/modules/cjs/loader:909:12)
  | 2023-07-02T14:36:45.100+03:00 | at Module.require (node:internal/modules/cjs/loader:1098:19)
  | 2023-07-02T14:36:45.100+03:00 | at require (node:internal/modules/cjs/helpers:108:18)
  | 2023-07-02T14:36:45.100+03:00 | at Object.<anonymous> (/var/task/node_modules/next/dist/server/next-server.js:13:1) {
  | 2023-07-02T14:36:45.100+03:00 | code: 'MODULE_NOT_FOUND',
  | 2023-07-02T14:36:45.100+03:00 | requireStack: [
  | 2023-07-02T14:36:45.100+03:00 | '/var/task/node_modules/next/dist/server/require-hook.js',
  | 2023-07-02T14:36:45.100+03:00 | '/var/task/node_modules/next/dist/server/next-server.js',
  | 2023-07-02T14:36:45.100+03:00 | '/tmp/app/server.js'
  | 2023-07-02T14:36:45.100+03:00 | ]
  | 2023-07-02T14:36:45.100+03:00 | }
  | 2023-07-02T14:36:45.111+03:00 | START RequestId: a505fc24-48ff-42e2-b5f3-c586a806dbbd Version: $LATEST
  | 2023-07-02T14:36:45.113+03:00 | RequestId: a505fc24-48ff-42e2-b5f3-c586a806dbbd Error: Runtime exited with error: exit status 1 Runtime.ExitError
  | 2023-07-02T14:36:45.113+03:00 | REPORT RequestId: a505fc24-48ff-42e2-b5f3-c586a806dbbd Duration: 324.17 ms Billed Duration: 325 ms Memory Size: 1024 MB Max Memory Used: 26 MB
  | 2023-07-02T14:36:45.518+03:00 | LOGS Name: bootstrap State: Already subscribed Types: [Platform, Function]
  | 2023-07-02T14:36:45.554+03:00 | ln: failed to create symbolic link ‘/tmp/app/node_modules/node_modules’: Read-only file system
  | 2023-07-02T14:36:45.556+03:00 | ln: failed to create symbolic link ‘/tmp/app/pages/pages’: Read-only file system
  | 2023-07-02T14:36:45.556+03:00 | ln: failed to create symbolic link ‘/tmp/app/public/public’: Read-only file system
  | 2023-07-02T14:36:45.575+03:00 | ln: failed to create symbolic link ‘/tmp/app/.next/static/static’: Read-only file system
  | 2023-07-02T14:36:45.576+03:00 | ln: failed to create symbolic link ‘/tmp/app/.next/server/chunks/chunks’: Read-only file system
  | 2023-07-02T14:36:45.774+03:00 | node:internal/modules/cjs/loader:1029
  | 2023-07-02T14:36:45.774+03:00 | throw err;
  | 2023-07-02T14:36:45.774+03:00 | ^
  | 2023-07-02T14:36:45.774+03:00 | Error: Cannot find module 'styled-jsx/package.json'
  | 2023-07-02T14:36:45.774+03:00 | Require stack:
  | 2023-07-02T14:36:45.774+03:00 | - /var/task/node_modules/next/dist/server/require-hook.js
  | 2023-07-02T14:36:45.774+03:00 | - /var/task/node_modules/next/dist/server/next-server.js
  | 2023-07-02T14:36:45.774+03:00 | - /tmp/app/server.js
  | 2023-07-02T14:36:45.774+03:00 | at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
  | 2023-07-02T14:36:45.774+03:00 | at Function.resolve (node:internal/modules/cjs/helpers:114:19)
  | 2023-07-02T14:36:45.774+03:00 | at Object.<anonymous> (/var/task/node_modules/next/dist/server/require-hook.js:31:25)
  | 2023-07-02T14:36:45.774+03:00 | at Module._compile (node:internal/modules/cjs/loader:1196:14)
  | 2023-07-02T14:36:45.774+03:00 | at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
  | 2023-07-02T14:36:45.774+03:00 | at Module.load (node:internal/modules/cjs/loader:1074:32)
  | 2023-07-02T14:36:45.774+03:00 | at Function.Module._load (node:internal/modules/cjs/loader:909:12)
  | 2023-07-02T14:36:45.774+03:00 | at Module.require (node:internal/modules/cjs/loader:1098:19)
  | 2023-07-02T14:36:45.774+03:00 | at require (node:internal/modules/cjs/helpers:108:18)
  | 2023-07-02T14:36:45.774+03:00 | at Object.<anonymous> (/var/task/node_modules/next/dist/server/next-server.js:13:1) {
  | 2023-07-02T14:36:45.774+03:00 | code: 'MODULE_NOT_FOUND',
  | 2023-07-02T14:36:45.774+03:00 | requireStack: [
  | 2023-07-02T14:36:45.774+03:00 | '/var/task/node_modules/next/dist/server/require-hook.js',
  | 2023-07-02T14:36:45.774+03:00 | '/var/task/node_modules/next/dist/server/next-server.js',
  | 2023-07-02T14:36:45.774+03:00 | '/tmp/app/server.js'
  | 2023-07-02T14:36:45.774+03:00 | ]
  | 2023-07-02T14:36:45.774+03:00 | }
  | 2023-07-02T14:36:45.779+03:00 | START RequestId: 2501435f-bc46-4dbd-87e9-edccdb43579a Version: $LATEST
  | 2023-07-02T14:36:45.790+03:00 | RequestId: 2501435f-bc46-4dbd-87e9-edccdb43579a Error: Runtime exited with error: exit status 1 Runtime.ExitError
  | 2023-07-02T14:36:45.790+03:00 | REPORT RequestId: 2501435f-bc46-4dbd-87e9-edccdb43579a Duration: 336.05 ms Billed Duration: 337 ms Memory Size: 1024 MB Max Memory Use
```

### Expected behavior

I should not get any error

### Reproduction steps

1. Create an amplify app, chosing this repo https://github.com/teacherfox/amplify-monorepo and adding `fe` as the directory mono repo
2. Use the attached script
3. Deploy

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by nadetastic** [comment]
Hi @trixobird thank you for opening this issue. Since it appears that this issue is related to Amplify Hosting, I'll transfer it over to the Hosting repo for better assistance. Thanks!
