### ISSUE TITLE
Errors after signin

### ISSUE THREAD

**Issue by joshuaMarple** [aws-amplify/amplify-js#11586]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```

  System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 4.33 GB / 7.67 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.3.1 - /usr/bin/node
    npm: 9.6.7 - /usr/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
  npmPackages:
    @angular-devkit/build-angular: ^16.0.4 => 16.1.3
    @angular/animations: ^16.1.3 => 16.1.3
    @angular/cdk: ^16.1.3 => 16.1.3
    @angular/cli: ~16.0.4 => 16.0.6
    @angular/common: ^16.0.0 => 16.1.3
    @angular/compiler: ^16.0.0 => 16.1.3
    @angular/compiler-cli: ^16.0.0 => 16.1.3
    @angular/core: ^16.0.0 => 16.1.3
    @angular/forms: ^16.0.0 => 16.1.3
    @angular/material: ^16.1.3 => 16.1.3
    @angular/platform-browser: ^16.0.0 => 16.1.3
    @angular/platform-browser-dynamic: ^16.0.0 => 16.1.3
    @angular/router: ^16.0.0 => 16.1.3
    @aws-amplify/ui-angular: ^3.2.18 => 3.2.19
    @ngrx/effects: ^16.0.1 => 16.0.1
    @ngrx/entity: ^16.0.1 => 16.0.1
    @ngrx/router-store: ^16.0.1 => 16.0.1
    @ngrx/store: ^16.0.1 => 16.0.1
    @ngrx/store-devtools: ^16.0.1 => 16.0.1
    @types/jasmine: ~4.3.0 => 4.3.5
    aws-amplify: ^5.2.5 => 5.3.3
    graphql-scalars: ^1.22.2 => 1.22.2
    jasmine-core: ~4.6.0 => 4.6.0
    karma: ~6.4.0 => 6.4.2
    karma-chrome-launcher: ~3.2.0 => 3.2.0
    karma-coverage: ~2.2.0 => 2.2.1
    karma-coverage-coffee-example:  1.0.0
    karma-jasmine: ~5.1.0 => 5.1.0
    karma-jasmine-html-reporter: ~2.0.0 => 2.0.0
    karma-phantomjs-launcher: ^1.0.4 => 1.0.4
    material-design-icons: ^3.0.1 => 3.0.1
    prettier: 2.8.8 => 2.8.8
    rxjs: ~7.8.0 => 7.8.1
    rxjs/ajax:  undefined ()
    rxjs/fetch:  undefined ()
    rxjs/operators:  undefined ()
    rxjs/testing:  undefined ()
    rxjs/webSocket:  undefined ()
    tslib: ^2.3.0 => 2.6.0 (2.5.3, 1.14.1, 2.3.1, 2.4.1)
    typescript: ~5.0.2 => 5.0.4
    zone-mix:  undefined ()
    zone-node:  undefined ()
    zone-testing:  undefined ()
    zone.js: ~0.13.0 => 0.13.1
    zone.js/async-test:  undefined ()
    zone.js/async-test.min:  undefined ()
    zone.js/fake-async-test:  undefined ()
    zone.js/fake-async-test.min:  undefined ()
    zone.js/jasmine-patch:  undefined ()
    zone.js/jasmine-patch.min:  undefined ()
    zone.js/long-stack-trace-zone:  undefined ()
    zone.js/long-stack-trace-zone.min:  undefined ()
    zone.js/mocha-patch:  undefined ()
    zone.js/mocha-patch.min:  undefined ()
    zone.js/proxy:  undefined ()
    zone.js/proxy.min:  undefined ()
    zone.js/sync-test:  undefined ()
    zone.js/sync-test.min:  undefined ()
    zone.js/task-tracking:  undefined ()
    zone.js/task-tracking.min:  undefined ()
    zone.js/webapis-media-query:  undefined ()
    zone.js/webapis-media-query.min:  undefined ()
    zone.js/webapis-notification:  undefined ()
    zone.js/webapis-notification.min:  undefined ()
    zone.js/webapis-rtc-peer-connection:  undefined ()
    zone.js/webapis-rtc-peer-connection.min:  undefined ()
    zone.js/webapis-shadydom:  undefined ()
    zone.js/webapis-shadydom.min:  undefined ()
    zone.js/wtf:  undefined ()
    zone.js/wtf.min:  undefined ()
    zone.js/zone-bluebird:  undefined ()
    zone.js/zone-bluebird.min:  undefined ()
    zone.js/zone-error:  undefined ()
    zone.js/zone-error.min:  undefined ()
    zone.js/zone-legacy:  undefined ()
    zone.js/zone-legacy.min:  undefined ()
    zone.js/zone-patch-canvas:  undefined ()
    zone.js/zone-patch-canvas.min:  undefined ()
    zone.js/zone-patch-cordova:  undefined ()
    zone.js/zone-patch-cordova.min:  undefined ()
    zone.js/zone-patch-electron:  undefined ()
    zone.js/zone-patch-electron.min:  undefined ()
    zone.js/zone-patch-fetch:  undefined ()
    zone.js/zone-patch-fetch.min:  undefined ()
    zone.js/zone-patch-jsonp:  undefined ()
    zone.js/zone-patch-jsonp.min:  undefined ()
    zone.js/zone-patch-message-port:  undefined ()
    zone.js/zone-patch-message-port.min:  undefined ()
    zone.js/zone-patch-promise-test:  undefined ()
    zone.js/zone-patch-promise-test.min:  undefined ()
    zone.js/zone-patch-resize-observer:  undefined ()
    zone.js/zone-patch-resize-observer.min:  undefined ()
    zone.js/zone-patch-rxjs:  undefined ()
    zone.js/zone-patch-rxjs-fake-async:  undefined ()
    zone.js/zone-patch-rxjs-fake-async.min:  undefined ()
    zone.js/zone-patch-rxjs.min:  undefined ()
    zone.js/zone-patch-socket-io:  undefined ()
    zone.js/zone-patch-socket-io.min:  undefined ()
    zone.js/zone-patch-user-media:  undefined ()
    zone.js/zone-patch-user-media.min:  undefined ()
  npmGlobalPackages:
    corepack: 0.18.0
    npm: 9.6.7

```

</details>

### Describe the bug

After a user logs in, I am consistently getting the error:

```Error: Uncaught (in promise): TypeError: Cannot assign to read only property 'signInUserSession' of object '[object Object]'
TypeError: Cannot assign to read only property 'signInUserSession' of object '[object Object]'
    at AuthClass.<anonymous> (Auth.js:1703:47)
    at step (tslib.es6.js:100:1)
    at Object.next (tslib.es6.js:81:46)
    at fulfilled (tslib.es6.js:71:43)
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (core.mjs:26259:33)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at Zone.run (zone.js:129:43)
    at zone.js:1257:36
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at resolvePromise (zone.js:1193:31)
    at resolvePromise (zone.js:1147:17)
    at zone.js:1260:17
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:25945:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:25945:36)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Object.onInvokeTask (core.mjs:26246:33)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Zone.runTask (zone.js:173:47)```

From inspecting the code, it looks like this is an error in the Auth codebase- 

https://github.com/aws-amplify/amplify-js/blob/main/packages/auth/src/Auth.ts#L1916 assigns a value to user.signInUserSession, which is presumably readonly at this point.

### Expected behavior

I do not expect to see this error.

### Reproduction steps

Created a basic app, following tutorial. 

I have one service that listens to signin events, copied below.

### Code Snippet

```javascript
import { CognitoUser } from "@aws-amplify/auth";
import { Injectable, inject } from "@angular/core";
import { Store } from "@ngrx/store";
import { Auth, Hub } from "aws-amplify";
import {
  userAlreadyLoggedIn,
  userAlreadyLoggedOut,
  userLoggedIn,
  userLoggedOut,
} from "./auth.actions";

@Injectable({
  providedIn: "root",
})
export class AuthService {
  private readonly store = inject(Store);

  public initializeAuthListener(): void {
    Hub.listen("auth", ({ payload: { event, data } }) => {
      if (event === "signIn") {
        debugger;
        this.store.dispatch(
          userLoggedIn({ user: Object.freeze(data as CognitoUser) })
        );
      } else if (event === "signOut") {
        this.store.dispatch(userLoggedOut());
      }
    });
  }

  public async checkCurrentUser() {
    try {
      const user = await Auth.currentAuthenticatedUser();
      this.store.dispatch(userAlreadyLoggedIn({ user: Object.freeze(user) })); // freezing following directions at https://stackoverflow.com/questions/52477374/angular-typeerror-cannot-freeze-when-dispatching-an-action
    } catch (error) {
      this.store.dispatch(userAlreadyLoggedOut()); // freezing following directions at https://stackoverflow.com/questions/52477374/angular-typeerror-cannot-freeze-when-dispatching-an-action
    }
  }
}
```

checkCurrentUser and initializeAuthListener are called at the top level application level on start, and no other time.

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
Hello, @joshuaMarple 👋.  The error that you're referencing might be coming from the use of the `Object.freeze()` since you're calling it on the `CognitoUser` object it seems. This will make it read-only and [prevent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze) the `signInUserSession` property from being modified.  

Can you see if removing the use of `Object.freeze()` resolves the issue?

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
