### ISSUE TITLE
AWS Amplify-js PubSub works on local dev build but fails on production build

### ISSUE THREAD

**Issue by wdawson61** [aws-amplify/amplify-js#11681]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication, PubSub

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
wdawson$ npx envinfo --system --binaries --browsers --npmPackages --duplicates --npmGlobalPackages
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Memory: 3.10 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.20.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 114.0.5735.248
    Safari: 13.1.1
  npmPackages:
    @types/react: ^18.0.15 => 18.2.16 
    @types/react-dom: ^18.0.6 => 18.2.7 
    @vitejs/plugin-react: ^2.0.0 => 2.2.0 
    aws-amplify: ^5.3.2 => 5.3.5 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    react-loading: ^2.0.3 => 2.0.3 
    vite: ^3.0.0 => 3.2.7 
  npmGlobalPackages:
    @aws-amplify/cli: 12.2.1
    aws-amplify: 5.3.5
    corepack: 0.17.0
    n: 9.1.0
    npm: 8.19.4
    yarn: 1.22.19

```

</details>

### Describe the bug

I am using Amplify-js in a static webApp.  The app renders a satellite raster-map, retrieves a tracker history (geo) and subscribes to a topic on AWS IOT Core  using using a pre-configured and working backend on AWS.  It places a "live" tracker icon on a layer on the map updating the tracker position via a subscribes to an AWS IOT core topic. 
`Amplify.addPluggable(new AWSIoTProvider)`
  This all works correctly when run locally (npm start) but a production build (npm run build) results in: 
`TypeError: Cannot read properties of null (reading 'subscribe')
    at index.971eb3bc.js:870:34691
    at tg (index.971eb3bc.js:32:24462)
    at dc (index.971eb3bc.js:32:42826)
    at index.971eb3bc.js:32:41074
    at ze (index.971eb3bc.js:17:1673)
    at MessagePort.O (index.971eb3bc.js:17:2059)`

Upon inspection of the Amplify object in the debugger, I see that the **many fields are null in the production case** and are non-null in the working case.

I've turned on verbose Amplify logger output and see a rather different log output when in the working vs non-working cases, but don't understand (and can't seem to find answers to) how the individual members of the Amplify object are actually populated and it seems there is a fair amount of magic happening even before the main.jsx ->amplify.configure() call as the PubSub field is already populated at that point (in the working case).  The issue can be reproduced with just the PubSub portion of the app, which I've pasted below.  I am happy to submit the simplified app if need be.

### Expected behavior

I expect the same behavior from a production build and dev build or a clear indication of what to expect and ways to mitigate any issues  that might ensue.

### Reproduction steps

1. npm start
2. browse to localhost:8080
3. Observe working test app and normal log with no errors.
4. npm run build
5. npm run preview
6. browse to localhost:4173
7. observe white screen
8. open java console, observe:
```
TypeError: Cannot read properties of null (reading 'subscribe')
    at index.f06f2e03.js:755:1349
    at gl (index.f06f2e03.js:32:24445)
    at Uo (index.f06f2e03.js:32:42757)
    at index.f06f2e03.js:32:41021
    at D (index.f06f2e03.js:17:1543)
    at MessagePort.m (index.f06f2e03.js:17:1902)
```

### Code Snippet

```javascript
// Put your code below this line.

-------------- App.jsx ----------------
import React from 'react';
import './App.css';
import { useState, useEffect } from "react";
import { Amplify } from 'aws-amplify';
import { AWSIoTProvider } from '@aws-amplify/pubsub/lib/Providers';
import ReactLoading from 'react-loading';
import config from "../pubsub.json"
export default function App() {
  const [gps1Data, setGps1Data] = useState({});

  function ListGPSPos({posData}) {
    if (Object.keys(posData).length === 0) {
      return (
        <ReactLoading type = "spinningBubbles" color ="#0"/>)
    }

     return (Object.keys(posData).map((key) => (
        <li> {key}: {posData[key]} </li>
        )
    ))    
  }
  
  function decodeGPSData(input) {
    switch (input.fPort)
    {
      case 2:
        const obj = {};
        obj.data = input.data;
        obj.fPort = input.fPort;
        setGps1Data(obj);
        break;
      default:
    }
  }

  useEffect(() => {
    Amplify.configure({
      Auth: {
        identityPoolId: config.REACT_APP_IDENTITY_POOL_ID,
        region: config.REACT_APP_REGION,
        userPoolId: config.REACT_APP_USER_POOL_ID,
        userPoolWebClientId: config.REACT_APP_USER_POOL_WEB_CLIENT_ID
      }
    });
    
    Amplify.addPluggable(new AWSIoTProvider({
      aws_pubsub_region: config.REACT_APP_REGION,
      aws_pubsub_endpoint: `wss://${config.REACT_APP_MQTT_ID}/mqtt`,
    }));
    
    Amplify.PubSub.subscribe('application/Tracking/device/313932316e30740b/rx').subscribe({
      next: data => decodeGPSData(data.value, data.fPort),
      error: error => console.error(error),
      close: () => console.log('Done'),
    });
    
  }, []);
  return (
    <>
      <h1>AWS IOT Core test</h1>
      <ListGPSPos posData = {gps1Data} />
    </>
  );
};

 
```

### Log output

<details>

```
// Put your logs below this line
*********** NON WORKING CASE ***********
[DEBUG] 45:13.198 Amplify - amplify config Object
index.3d78ba52.js:32 [DEBUG] 45:13.201 AuthClass - configure Auth
index.3d78ba52.js:32 [DEBUG] 45:13.201 Parser - parse config Array(3)
index.3d78ba52.js:32 [DEBUG] 45:13.201 Hub - Dispatching to auth with  Object
index.3d78ba52.js:32 [DEBUG] 45:13.228 AuthClass - getting current credentials
index.3d78ba52.js:32 [DEBUG] 45:13.228 Credentials - getting credentials
index.3d78ba52.js:32 [DEBUG] 45:13.228 Credentials - picking up credentials
index.3d78ba52.js:32 [DEBUG] 45:13.228 Credentials - getting new cred promise
index.3d78ba52.js:32 [DEBUG] 45:13.228 Credentials - checking if credentials exists and not expired
index.3d78ba52.js:32 [DEBUG] 45:13.228 Credentials - need to get a new credential or refresh the existing one
index.3d78ba52.js:32 [DEBUG] 45:13.228 Credentials - no credentials for expiration check
index.3d78ba52.js:32 [DEBUG] 45:13.229 AuthClass - Getting current user credentials
index.3d78ba52.js:32 [DEBUG] 45:13.231 AuthClass - Getting current session
index.3d78ba52.js:32 [DEBUG] 45:13.231 AuthClass - Failed to get user from user pool
index.3d78ba52.js:32 [DEBUG] 45:13.231 AuthClass - Failed to get the current user No current user
index.3d78ba52.js:32 [DEBUG] 45:13.231 AuthClass - getting guest credentials
index.3d78ba52.js:32 [DEBUG] 45:13.231 Credentials - setting credentials for guest
index.3d78ba52.js:32 TypeError: Cannot read properties of null (reading 'subscribe')
    at index.3d78ba52.js:870:34691
    at tg (index.3d78ba52.js:32:24462)
    at dc (index.3d78ba52.js:32:42826)
    at index.3d78ba52.js:32:41074
    at ze (index.3d78ba52.js:17:1673)
    at MessagePort.O (index.3d78ba52.js:17:2059)
k_ @ index.3d78ba52.js:32
index.3d78ba52.js:30 Uncaught TypeError: Cannot read properties of null (reading 'subscribe')
    at index.3d78ba52.js:870:34691
    at tg (index.3d78ba52.js:32:24462)
    at dc (index.3d78ba52.js:32:42826)
    at index.3d78ba52.js:32:41074
    at ze (index.3d78ba52.js:17:1673)
    at MessagePort.O (index.3d78ba52.js:17:2059)
index.3d78ba52.js:32 [DEBUG] 45:13.472 Credentials - Load credentials successfully Object

*********** WORKING CASE ***********
ConsoleLogger.js:134 [DEBUG] 48:18.10 Amplify - amplify config Object
ConsoleLogger.js:122 [DEBUG] 48:18.13 I18n - configure I18n
ConsoleLogger.js:122 [DEBUG] 48:18.13 I18n - create I18n instance
ConsoleLogger.js:134 [DEBUG] 48:18.13 Hub - Dispatching to core with  Object
ConsoleLogger.js:134 [DEBUG] 48:18.13 AnalyticsClass - on hub capsule core Object
ConsoleLogger.js:122 [DEBUG] 48:18.13 AuthClass - configure Auth
ConsoleLogger.js:134 [DEBUG] 48:18.13 Parser - parse config Array(3)
ConsoleLogger.js:134 [DEBUG] 48:18.14 Hub - Dispatching to core with  Object
ConsoleLogger.js:134 [DEBUG] 48:18.14 AnalyticsClass - on hub capsule core Object
ConsoleLogger.js:134 [DEBUG] 48:18.14 Hub - Dispatching to auth with  Object
ConsoleLogger.js:134 [DEBUG] 48:18.14 Hub - Dispatching to auth with  Object
ConsoleLogger.js:134 [DEBUG] 48:18.14 AnalyticsClass - on hub capsule auth Object
ConsoleLogger.js:134 [DEBUG] 48:18.14 Hub - Dispatching to auth with  Object
ConsoleLogger.js:134 [DEBUG] 48:18.14 Hub - Dispatching to auth with  Object
ConsoleLogger.js:134 [DEBUG] 48:18.14 PubSub - configure PubSub Object
ConsoleLogger.js:134 [DEBUG] 48:18.14 PubSub - configure PubSub Object
ConsoleLogger.js:134 [DEBUG] 48:18.14 AnalyticsClass - configure Analytics Object
ConsoleLogger.js:134 [DEBUG] 48:18.14 Parser - parse config Array(3)
ConsoleLogger.js:134 [DEBUG] 48:18.14 AWSPinpointProvider - configure Analytics Object
ConsoleLogger.js:134 [DEBUG] 48:18.15 Hub - Dispatching to analytics with  Object
ConsoleLogger.js:134 [DEBUG] 48:18.15 AnalyticsClass - on hub capsule analytics Object
ConsoleLogger.js:134 [DEBUG] 48:18.15 Hub - Dispatching to analytics with  Object
ConsoleLogger.js:134 [DEBUG] 48:18.15 AnalyticsClass - current configuration Object
ConsoleLogger.js:122 [DEBUG] 48:18.15 Storage - storage configure called
ConsoleLogger.js:122 [DEBUG] 48:18.15 StorageClass - configure Storage
ConsoleLogger.js:134 [DEBUG] 48:18.15 Parser - parse config Array(3)
ConsoleLogger.js:134 [DEBUG] 48:18.15 AWSS3Provider - configure Storage undefined
ConsoleLogger.js:122 [DEBUG] 48:18.15 Storage - storage vault configure called
ConsoleLogger.js:122 [DEBUG] 48:18.15 StorageClass - configure Storage
ConsoleLogger.js:134 [DEBUG] 48:18.16 Parser - parse config Array(3)
ConsoleLogger.js:134 [DEBUG] 48:18.16 AWSS3Provider - configure Storage undefined
ConsoleLogger.js:134 [DEBUG] 48:18.16 RestAPI - configure Rest API Object
ConsoleLogger.js:122 [DEBUG] 48:18.16 RestAPI - create Rest API instance
ConsoleLogger.js:134 [DEBUG] 48:18.16 RestClient - API Options Object
ConsoleLogger.js:134 [DEBUG] 48:18.16 GraphQLAPI - configure GraphQL API Object
ConsoleLogger.js:122 [DEBUG] 48:18.16 GraphQLAPI - create Rest instance
ConsoleLogger.js:134 [DEBUG] 48:18.16 RestClient - API Options Object
ConsoleLogger.js:134 [DEBUG] 48:18.16 RestAPI - configure Rest API Object
ConsoleLogger.js:122 [DEBUG] 48:18.16 RestAPI - create Rest API instance
ConsoleLogger.js:134 [DEBUG] 48:18.16 RestClient - API Options Object
ConsoleLogger.js:134 [DEBUG] 48:18.16 GraphQLAPI - configure GraphQL API Object
ConsoleLogger.js:122 [DEBUG] 48:18.17 GraphQLAPI - create Rest instance
ConsoleLogger.js:134 [DEBUG] 48:18.17 RestClient - API Options Object
ConsoleLogger.js:134 [DEBUG] 48:18.17 RestAPI - configure Rest API Object
ConsoleLogger.js:122 [DEBUG] 48:18.17 RestAPI - create Rest API instance
ConsoleLogger.js:134 [DEBUG] 48:18.17 RestClient - API Options Object
ConsoleLogger.js:134 [DEBUG] 48:18.17 GraphQLAPI - configure GraphQL API Object
ConsoleLogger.js:122 [DEBUG] 48:18.17 GraphQLAPI - create Rest instance
ConsoleLogger.js:134 [DEBUG] 48:18.17 RestClient - API Options Object
ConsoleLogger.js:134 [DEBUG] 48:18.17 GraphQLAPI - configure GraphQL API Object
ConsoleLogger.js:122 [DEBUG] 48:18.17 GraphQLAPI - create Rest instance
ConsoleLogger.js:134 [DEBUG] 48:18.17 RestClient - API Options Object
ConsoleLogger.js:134 [DEBUG] 48:18.17 Interactions - configure Interactions Object
ConsoleLogger.js:134 [DEBUG] 48:18.17 Notifications - configure Notifications undefined
ConsoleLogger.js:134 [DEBUG] 48:18.17 Notifications.InAppMessaging - configure InAppMessaging Object
ConsoleLogger.js:134 [DEBUG] 48:18.17 InAppMessaging.AWSPinpointProvider - configure AWSPinpointInAppMessagingProvider Object
ConsoleLogger.js:134 [DEBUG] 48:18.17 Predictions - configure Predictions Object
ConsoleLogger.js:122 [DEBUG] 48:18.17 Geo - configure Geo
ConsoleLogger.js:134 [DEBUG] 48:18.17 Parser - parse config Array(3)
ConsoleLogger.js:134 [DEBUG] 48:18.17 AmazonLocationServiceProvider - configure Amazon Location Service Provider Object
ConsoleLogger.js:134 [DEBUG] 48:18.18 AbstractPubSubProvider - configure AWSIoTProvider Object
ConsoleLogger.js:134 [DEBUG] 48:18.19 AbstractPubSubProvider - configure AWSIoTProvider Object
ConsoleLogger.js:134 [DEBUG] 48:18.19 Predictions - No plugin found with providerName=> AWSIoTProvider
ConsoleLogger.js:122 [DEBUG] 48:18.61 AuthClass - getting current credentials
ConsoleLogger.js:122 [DEBUG] 48:18.61 Credentials - getting credentials
ConsoleLogger.js:122 [DEBUG] 48:18.61 Credentials - picking up credentials
ConsoleLogger.js:122 [DEBUG] 48:18.61 Credentials - getting new cred promise
ConsoleLogger.js:122 [DEBUG] 48:18.62 Credentials - checking if credentials exists and not expired
ConsoleLogger.js:122 [DEBUG] 48:18.62 Credentials - need to get a new credential or refresh the existing one
ConsoleLogger.js:122 [DEBUG] 48:18.62 Credentials - no credentials for expiration check
ConsoleLogger.js:122 [DEBUG] 48:18.63 AuthClass - Getting current user credentials
ConsoleLogger.js:122 [DEBUG] 48:18.64 AuthClass - getting current credentials
ConsoleLogger.js:122 [DEBUG] 48:18.64 Credentials - getting credentials
ConsoleLogger.js:122 [DEBUG] 48:18.64 Credentials - picking up credentials
ConsoleLogger.js:122 [DEBUG] 48:18.64 Credentials - getting old cred promise
ConsoleLogger.js:122 [DEBUG] 48:18.67 AuthClass - Getting current session
ConsoleLogger.js:122 [DEBUG] 48:18.67 AuthClass - Failed to get user from user pool
ConsoleLogger.js:134 [DEBUG] 48:18.67 AuthClass - Failed to get the current user No current user
ConsoleLogger.js:122 [DEBUG] 48:18.67 AuthClass - getting guest credentials
ConsoleLogger.js:122 [DEBUG] 48:18.68 Credentials - setting credentials for guest
ConsoleLogger.js:134 [DEBUG] 48:18.196 Credentials - Load credentials successfully Object
ConsoleLogger.js:134 [DEBUG] 48:18.435 PubSub - subscribe options undefined
ConsoleLogger.js:134 [DEBUG] 48:18.435 MqttOverWSProvider - Subscribing to topic(s) application/Tracking/device/####/rx
ConsoleLogger.js:122 [DEBUG] 48:18.436 Credentials - getting credentials
ConsoleLogger.js:122 [DEBUG] 48:18.436 Credentials - picking up credentials
ConsoleLogger.js:122 [DEBUG] 48:18.436 Credentials - getting new cred promise
ConsoleLogger.js:122 [DEBUG] 48:18.436 Credentials - checking if credentials exists and not expired
ConsoleLogger.js:134 [DEBUG] 48:18.436 Credentials - are these credentials expired? Object
ConsoleLogger.js:122 [DEBUG] 48:18.436 Credentials - credentials not changed and not expired, directly return
ConsoleLogger.js:134 [DEBUG] 48:18.436 PubSub - subscribe options undefined
ConsoleLogger.js:134 [DEBUG] 48:18.436 MqttOverWSProvider - Subscribing to topic(s) application/Tracking/device/####/rx
ConsoleLogger.js:122 [DEBUG] 48:18.436 Credentials - getting credentials
ConsoleLogger.js:122 [DEBUG] 48:18.436 Credentials - picking up credentials
ConsoleLogger.js:122 [DEBUG] 48:18.436 Credentials - getting old cred promise
ConsoleLogger.js:134 [DEBUG] 48:18.442 MqttOverWSProvider - Creating new MQTT client f0769382-ea26-47df-a9ef-164cf892fdc7
```

</details>

### Manual configuration

{
"REACT_APP_REGION":"us-east-1",
"REACT_APP_USER_POOL_ID":"us-east-1_YZZZZ9gY3L",
"REACT_APP_USER_POOL_WEB_CLIENT_ID":"28magd5khZZZZ1lt5612ht0tchu",
"REACT_APP_MQTT_ID":"pdqpdqpdq-ats.iot.us-east-1.amazonaws.com",
"REACT_APP_IDENTITY_POOL_ID": "us-east-1:ea12d4ca-8656-4b1e-a760-#####"
}

**Comment by cwomack** [comment]
Hello @wdawson61, and thank you for opening this issue.  Could you possibly throw some `console.log()`'s within the useEffect hook to verify that the `Amplify.configure()` yields the same logged result in both the production and local environments?  

Would you also mind seeing if adding an explicit "clean up" function within your `useEffect` hook to ensure the subscription is unsubscribed when the component is unmounted helps resolve the error you're seeing?
```
  const subscription = Amplify.PubSub.subscribe('application/Tracking/device/313932316e30740b/rx').subscribe({
    next: data => decodeGPSData(data.value, data.fPort),
    error: error => console.error(error),
    close: () => console.log('Done'),
  });

  return () => {
    subscription.unsubscribe();
  };
```

**Comment by wdawson61** [comment]
Log files are below:  Modified app is pasted below.  I'm happy to populate you credentials for you to be able to run
[working.log](https://github.com/aws-amplify/amplify-js/files/12188253/working.log)
[not_working.log](https://github.com/aws-amplify/amplify-js/files/12188260/not_working.log)
[App.txt](https://github.com/aws-amplify/amplify-js/files/12188317/App.txt)

Thanks for looking into this!

**Comment by wdawson61** [comment]
is there anything else I can add?

**Comment by cwomack** [comment]
@wdawson61, greatly appreciate you sharing the logs!  It appears the issue might be tied to how you are importing `AWSIoTProvider` from the file path and not importing `PubSub` directly.  Can you update your imports to be similar to how the [docs reference](https://docs.amplify.aws/lib/pubsub/getting-started/q/platform/js/#aws-iot) the imports should look when using AWSIoTProvider:

```
import { Amplify, PubSub } from 'aws-amplify';
import { AWSIoTProvider } from '@aws-amplify/pubsub';
```  

And then change your subscription calls to be the following:
 
```
    PubSub.addPluggable(new AWSIoTProvider({
      aws_pubsub_region: config.REACT_APP_REGION,
      aws_pubsub_endpoint: `wss://${config.REACT_APP_MQTT_ID}/mqtt`,
    }));
```
And finally your subscriptions:

```
    PubSub.subscribe('application/Tracking/device/313932316e30740b/rx').subscribe({
      next: data => decodeGPSData(data.value, data.fPort),
      error: error => console.error(error),
      close: () => console.log('Done'),
    });
```
It's possible that the differences between the dev build working and production build failing are tied to some tree-shaking out of `PubSub` since it wasn't being imported directly.  Let me know if these changes help resolve your issues on production!

**Comment by wdawson61** [comment]
Brilliant!  That's done it.  I had a suspicion this was more of packaging bug than an Amplify bug, per se.   One question though; how is it that using Amplify.Pubsub.xxx works the same way in dev that PubSub.xxx does??

**Comment by cwomack** [comment]
@wdawson61, that's great to hear! As for your question on the difference of `Amplify.PubSub.x` vs. `PubSub.x` when imported directly and used... it's likely that when in dev mode, there was a full/proper tree-shaking that occurred so the `Amplify.PubSub.x` calls were still able to work.  However, some tree-shaking happens in prod builds and it's likely that the PubSub you imported from the file path was shaken out.  

I'll close this issue for now since it sounds like we've got you unlocked, but feel free to comment further if needed or open a new issue if you run into another blocker.  Thanks!
