### ISSUE TITLE
On saving to DataStore. TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by ilfoxo** [aws-amplify/amplify-js#11693]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

DataStore

### Amplify Categories

Not applicable

### Environment information

<details>

```
 System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 16.07 GB / 31.74 GB
  Binaries:
    Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 115.0.5790.110
    Edge: Spartan (44.22621.1992.0), Chromium (115.0.1901.183)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @azure/core-asynciterator-polyfill: ^1.0.2 => 1.0.2
    @babel/core: ^7.20.0 => 7.22.9
    @react-native-async-storage/async-storage: 1.18.2 => 1.18.2
    @react-native-community/netinfo: 9.3.10 => 9.3.10
    @react-native-picker/picker: ^2.4.10 => 2.4.10
    HelloWorld:  0.0.1
    amazon-cognito-identity-js: ^6.3.1 => 6.3.1
    amazon-cognito-identity-js/internals:  undefined ()
    aws-amplify: ^5.3.5 => 5.3.5
    aws-amplify-react-native: ^7.0.2 => 7.0.2
    expo: ~49.0.5 => 49.0.5
    expo-status-bar: ~1.6.0 => 1.6.0
    ini: ^1.3.5 => 1.3.8
    inquirer: ^6.5.1 => 6.5.2
    react: 18.2.0 => 18.2.0
    react-native: 0.72.3 => 0.72.3
  npmGlobalPackages:
    @aws-amplify/cli: 10.6.2
    serverless: 3.33.0
    yarn: 1.22.19


```

</details>

### Describe the bug

When I try to save DataStore I got  the mentioned error.

The first try was without implementing Auth, I was trying to save the information to the local database. After, i tried creating the Auth but the result was the same.

**App.js**
```javascript
import '@azure/core-asynciterator-polyfill'
import React, { useEffect, useState } from 'react';
import { Keyboard, ScrollView, StyleSheet, Text, View, Pressable } from 'react-native';
import TodoInput from './components/TodoInput';
import TodoItem from './components/TodoItem';
import { DataStore } from "aws-amplify";
import { Task } from "./src/models";
import { Amplify } from 'aws-amplify';
import awsconfig from './src/aws-exports';
import { withAuthenticator } from 'aws-amplify-react-native';
import { Auth } from 'aws-amplify';

Amplify.configure(awsconfig);

function App() {
  const [tasks, setTasks] = useState([]);

  useEffect(() => {
    fetchTasks();
  }, []);

  async function fetchTasks() {
    let dataStoreItems = await DataStore.query(Task);
    setTasks(dataStoreItems.map((item) => item));
    console.dir(dataStoreItems);
  }

  async function deleteTaskFromStorage(deleteItem) {
    const todoDelete = await DataStore.query(Task, deleteItem);
    DataStore.delete(todoDelete);
  }

  const addTask = async (task) => {
    console.log('addTask', task);
    if (task == null) return;
    fetchTasks();
    Keyboard.dismiss();
  }

  const deleteTask = (task, deleteIndex) => {
    deleteTaskFromStorage(task);
    setTasks(tasks.filter((value, index) => index != deleteIndex));
  }

  async function signOut() {
    try {
      await Auth.signOut();
    } catch (error) {
      console.log('error signing out: ', error);
    }
  }

  return (
    <View style={styles.container}>
      <Text style={styles.heading}>TODOs</Text>
      <ScrollView style={styles.scrollView}>
        <Pressable style={styles.button} onPress={signOut}>
          <Text style={styles.text}>Sing Out</Text>
        </Pressable>
        {
          tasks.map((todo, index) => {
            return (
              <View key={index} style={styles.taskContainer}>
                <TodoItem index={index + 1} task={todo.task} deleteTask={() => deleteTask(todo, index)} />
              </View>
            );
          })
        }
      </ScrollView>
      <TodoInput addTask={addTask} />
    </View>
  );
}
export default withAuthenticator(App);



const styles = StyleSheet.create({
  container: {
    backgroundColor: '#c0c0c0',
    flex: 1
  },
  heading: {
    color: '#000',
    fontSize: 20,
    fontWeight: '600',
    marginTop: 30,
    marginBottom: 10,
    textAlign: 'center',
  },
  scrollView: {
    marginBottom: 70,
  },
  taskContainer: {
    marginTop: 20,
  }
});

```

TodoInput.js
```javascript
import React, { useState } from 'react';
import { KeyboardAvoidingView, StyleSheet, View, TextInput, TouchableOpacity, } from "react-native";
import { AntDesign } from '@expo/vector-icons';
import { DataStore } from "aws-amplify";
import { Todo } from "../src/models";

export default TodoInput = (props) => {
    const [task, setTask] = useState();

    const handleAddTask = async (value) => {
        const newTodo = await DataStore.save(
            new Todo({
                task: value,
                id: Math.random().toString(36).substring(7)
            })
        )
        props.addTask(value);
        setTask(null);
    }
    return (
        <KeyboardAvoidingView
            behavior={Platform.OS === "ios" ? "padding" : "height"}
            style={styles.container}
        >
            <TextInput style={styles.inputField} value={task} onChangeText={text => setTask(text)} placeholder={'add a todo item'} placeholderTextColor={'#888'} />
            <TouchableOpacity onPress={() => handleAddTask(task)}>
                <View style={styles.button}>
                    <AntDesign name="pluscircle" size={24} color="orange" />
                </View>
            </TouchableOpacity>
        </KeyboardAvoidingView>
    );
}

const styles = StyleSheet.create({
    container: {
        borderColor: '#fff',
        backgroundColor: '#fff',
        borderWidth: 1,
        marginHorizontal: 20,
        borderRadius: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 10,
        position: 'absolute',
        bottom: 20,
    },
    inputField: {
        color: '#000',
        height: 50,
        flex: 1,
    },
    button: {
        height: 30,
        width: 30,
        borderRadius: 5,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center'
    },
});

```

### Expected behavior

Write information to DataStore

### Reproduction steps

1) npx create-expo-app Todo
2) npx amplify-app@latest
3) Create the model

```javascript
type Task @model {
  id: ID!
  task: String!
}
````

4) npm run amplify-modelgen
5) npm install aws-amplify @react-native-community/netinfo @react-native-async-storage/async-storage
6) npx expo start

I got the error when I tried to save to DataStore!

### Code Snippet

```javascript
const handleAddTask = async (value) => {
        const newTodo = await DataStore.save(      // When I try to save to DataStore
            new Todo({
                task: value,
                id: Math.random().toString(36).substring(7)
            })
        )
        props.addTask(value);
        setTask(null);
    }
```

### Log output

<details>

```
 WARN  Possible Unhandled Promise Rejection (id: 2):
TypeError: Cannot read property 'prototype' of undefined
TypeError: Cannot read property 'prototype' of undefined
    at ?anon_0_ (http://192.168.0.102:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:131288:72)
    at next (native)
    at asyncGeneratorStep (http://192.168.0.102:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:6090:26)
    at _next (http://192.168.0.102:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:6109:29)
    at anonymous (http://192.168.0.102:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:6114:14)
    at tryCallTwo (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/3n472i6k/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/3n472i6k/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/3n472i6k/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://192.168.0.102:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:6106:25)
    at apply (native)
    at handleAddTask (http://192.168.0.102:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:131296:26)
    at onPress (http://192.168.0.102:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:131312:31)
    at _performTransitionSideEffects (http://192.168.0.102:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:82121:22)
    at _receiveSignal (http://192.168.0.102:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:82071:45)
    at onResponderRelease (http://192.168.0.102:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:81927:34)
    at apply (native)
    at invokeGuardedCallbackProd (http://192.168.0.102:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:82643:21)
    at apply (native)
    at invokeGuardedCallback (http://192.168.0.102:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:82819:42)
    at apply (native)
    at invokeGuardedCallbackAndCatchFirstError (http://192.168.0.102:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:82833:36)
    at executeDispatch (http://192.168.0.102:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:82910:48)
    at executeDispatchesInOrder (http://192.168.0.102:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:82932:26)
    at executeDispatchesAndRelease (http://192.168.0.102:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:84705:35)
    at executeDispatchesAndReleaseTopLevel (http://192.168.0.102:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:84712:43)
    at forEach (native)
    at forEachAccumulated (http://192.168.0.102:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:83526:22)
    at runEventsInBatch (http://192.168.0.102:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:84725:27)
    at runExtractedPluginEventsInBatch (http://192.168.0.102:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:84835:25)
    at anonymous (http://192.168.0.102:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:84806:42)
    at batchedUpdates$1 (http://192.168.0.102:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:98271:20)
    at batchedUpdates (http://192.168.0.102:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:84681:36)
    at _receiveRootNodeIDEvent (http://192.168.0.102:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:84805:23)
    at receiveTouches (http://192.168.0.102:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:84894:34)
    at apply (native)
    at __callFunction (http://192.168.0.102:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:3732:36)
    at anonymous (http://192.168.0.102:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:3452:31)
    at __guard (http://192.168.0.102:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:3669:15)
    at callFunctionReturnFlushedQueue (http://192.168.0.102:8081/node_modules%5Cexpo%5CAppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:3451:21)


```

</details>

### aws-exports.js

```javascript
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://m4a2c3kfdvflllgwhyi3nk24pe.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "us-east-2:a6c827ea-bf99-4ca8-8197-c1b3a19869d6",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_qNRnzBUVM",
    "aws_user_pools_web_client_id": "h6cc342daghjd0sjt4ncp5eg",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;



```

### Mobile Operating System

Android

**Comment by chrisbonifacio** [comment]
Hi @ilfoxo thanks for reporting this issue and providing clear reproduction steps. We are looking into it!

**Comment by ilfoxo** [comment]
Please guys, ignore this issue. There was a typo error in Model....
