### ISSUE TITLE
TypeError: Cannot read property 'operation' of undefined

### ISSUE THREAD

**Issue by mhyassin** [aws-amplify/amplify-js#11722]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication, Analytics, GraphQL API, DataStore, Storage

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 99.52 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - /opt/homebrew/bin/npm
    Watchman: 2023.06.12.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 115.0.5790.170
    Firefox: 115.0.3
    Safari: 16.5.2
  npmPackages:
    @babel/core: ^7.20.0 => 7.21.3 (7.22.8, 7.18.13)
    @babel/eslint-parser: ^7.18.2 => 7.18.9 
    @babel/preset-env: ^7.20.0 => 7.20.2 (7.22.7)
    @babel/runtime: ^7.20.0 => 7.21.0 (7.18.9, 7.19.0)
    @commitlint/cli: ^17.0.3 => 17.0.3 
    @commitlint/config-conventional: ^17.0.3 => 17.0.3 
    @georstat/react-native-image-cache: 2.7.0 => 2.7.0 
    @react-native-async-storage/async-storage: 1.19.1 => 1.19.1 
    @react-native-clipboard/clipboard: 1.10.0 => 1.10.0 
    @react-native-community/datetimepicker: 6.1.3 => 6.1.3 
    @react-native-community/eslint-config: ^3.2.0 => 3.2.0 
    @react-native-community/eslint-plugin: ^1.3.0 => 1.3.0 (1.2.0)
    @react-native-community/netinfo: 9.4.1 => 9.4.1 
    @react-native-firebase/app: 15.7.0 => 15.7.0 
    @react-native-firebase/messaging: 15.7.0 => 15.7.0 
    @react-native-picker/picker: 2.4.1 => 2.4.1 (1.16.8)
    @react-navigation/bottom-tabs: 6.3.1 => 6.3.1 
    @react-navigation/elements: 1.3.17 => 1.3.17 (1.3.4, 1.3.9)
    @react-navigation/native: 6.0.16 => 6.0.16 
    @react-navigation/native-stack: 6.9.4 => 6.9.4 
    @react-navigation/stack: 6.2.2 => 6.2.2 
    @sentry/react-native: 5.1.1 => 5.1.1 
    @tsconfig/react-native: ^3.0.2 => 3.0.2 
    @types/d3-scale: 4.0.3 => 4.0.3 
    @types/jest: ^29.5.2 => 29.5.2 
    @types/lodash: 4.14.185 => 4.14.185 
    @types/react: 18.0.24 => 18.0.24 (18.0.17)
    @types/react-native-autocomplete-input: ^5.1.1 => 5.1.1 
    @types/react-native-vector-icons: 6.4.11 => 6.4.11 
    @types/react-native-version-check: 3.4.5 => 3.4.5 
    @types/react-test-renderer: 18.0.0 => 18.0.0 
    @typescript-eslint/eslint-plugin: ^5.61.0 => 5.61.0 (5.34.0)
    @typescript-eslint/parser: ^5.61.0 => 5.61.0 (5.34.0)
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: 6.3.1 => 6.3.1 
    amazon-cognito-identity-js/internals:  undefined ()
    aws-amplify: 5.3.6 => 5.3.6 
    axios: 0.27.2 => 0.27.2 (0.26.0)
    babel-jest: ^29.2.1 => 29.5.0 
    babel-plugin-module-resolver: 4.1.0 => 4.1.0 
    core-js: 3.30.2 => 3.30.2 
    crypto-js: 4.1.1 => 4.1.1 
    d3: 7.4.4 => 7.4.4 
    d3-array: 3.1.6 => 3.1.6 (3.2.0)
    d3-scale: 4.0.2 => 4.0.2 
    d3-shape: 3.1.0 => 3.1.0 
    date-fns: 2.28.0 => 2.28.0 
    eslint: ^8.21.0 => 8.22.0 
    eslint-config-prettier: 8.5.0 => 8.5.0 
    eslint-plugin-jest: ^26.8.2 => 26.8.7 
    fs-extra: ^10.1.0 => 10.1.0 (8.1.0, 11.1.1)
    graphql: 15.7.0 => 15.7.0 (15.8.0)
    husky: 8.0.1 => 8.0.1 
    i18next: 21.8.10 => 21.8.10 
    jest: ^29.2.1 => 29.5.0 
    jest-environment-jsdom: ^29.5.0 => 29.5.0 
    jest-transform-stub: 2.0.0 => 2.0.0 
    lint-staged: ^13.2.3 => 13.2.3 
    lodash-es: ^4.17.21 => 4.17.21 
    lottie-react-native: 5.1.4 => 5.1.4 
    metro-react-native-babel-preset: 0.73.9 => 0.73.9 
    moment: 2.29.4 => 2.29.4 
    polished: 4.2.2 => 4.2.2 
    prettier: 2.8.8 => 2.8.8 
    react: 18.2.0 => 18.2.0 
    react-i18next: 11.18.3 => 11.18.3 
    react-native: 0.71.7 => 0.71.7 
    react-native-appsflyer: 6.10.2 => 6.10.2 
    react-native-autocomplete-input: 5.2.0 => 5.2.0 
    react-native-bootsplash: 4.6.0 => 4.6.0 
    react-native-config: 1.4.6 => 1.4.6 
    react-native-email-link: 1.14.1 => 1.14.1 
    react-native-file-access: 3.0.4 => 3.0.4 
    react-native-gesture-handler: 2.12.0 => 2.12.0 
    react-native-image-crop-picker: 0.39.0 => 0.39.0 
    react-native-inappbrowser-reborn: 3.7.0 => 3.7.0 
    react-native-keyboard-aware-scroll-view: 0.9.5 => 0.9.5 
    react-native-linear-gradient: 2.6.2 => 2.6.2 
    react-native-localize: 2.2.4 => 2.2.4 
    react-native-picker-select: 8.0.4 => 8.0.4 
    react-native-purchases: 5.2.2 => 5.2.2 
    react-native-reanimated: 3.3.0 => 3.3.0 
    react-native-reanimated-carousel: 3.3.2 => 3.3.2 
    react-native-safe-area-context: 4.4.1 => 4.4.1 
    react-native-screens: 3.18.2 => 3.18.2 
    react-native-shared-element: 0.8.4 => 0.8.4 
    react-native-snackbar: 2.4.0 => 2.4.0 
    react-native-svg: 12.4.4 => 12.4.4 
    react-native-svg-transformer: 1.0.0 => 1.0.0 
    react-native-toast-message: 2.1.5 => 2.1.5 
    react-native-track-player: 2.1.3 => 2.1.3 
    react-native-vector-icons: 9.2.0 => 9.2.0 
    react-native-version-check: 3.4.7 => 3.4.7 
    react-native-webview: 11.22.2 => 11.22.2 
    react-navigation-shared-element: 3.1.3 => 3.1.3 
    react-test-renderer: 18.2.0 => 18.2.0 
    styled-components: 6.0.4 => 6.0.4 
    styled-components/macro:  undefined ()
    styled-components/native:  undefined ()
    terra-react: 1.4.18 => 1.4.18 
    tiny-timer: 1.6.0 => 1.6.0 
    ts-jest: ^29.1.1 => 29.1.1 
    ts-node: ^10.9.1 => 10.9.1 
    typescript: ^4.9.5 => 4.9.5 (4.7.4)
    zustand: 4.3.6 => 4.3.6 
  npmGlobalPackages:
    @sentry/wizard: 2.2.1
    create-react-native-app: 3.8.0
    ios-deploy: 1.11.4
    npm: 9.6.7
    react-devtools: 4.25.0
    ts-node: 10.9.1
    vercel: 27.2.0
    yarn: 1.22.19

```

</details>

### Describe the bug

We call DataStore.clear() while the user is signing out and some times after calling `await DataStore.clear()` I get this type error, not sure if it affects anything though

### Expected behavior

The promise rejection is handled correctly

### Reproduction steps

1. Just randomly call DataStore.clear()

### Code Snippet

```javascript
// Put your code below this line.

const signout = async () => {
  await DataStore.stop();
  await DataStore.clear();
  try {
    await Auth.signOut();
  } catch (err) {
    ...
  }
};

```

### Log output

<details>

```
// Put your logs below this line
 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'operation' of undefined
TypeError: Cannot read property 'operation' of undefined
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=health.onvy.staging:230333:23)
    at call (native)
    at step (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=health.onvy.staging:133300:27)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=health.onvy.staging:133248:22)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=health.onvy.staging:133222:75)
    at tryCallTwo (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:82:14)
    at __awaiter (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=health.onvy.staging:133204:38)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=health.onvy.staging:230327:68)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=health.onvy.staging:230256:58)
    at call (native)
    at step (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=health.onvy.staging:133300:27)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=health.onvy.staging:133248:22)
    at fulfilled (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=health.onvy.staging:133207:32)
    at tryCallOne (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=health.onvy.staging:26457:26)
    at _callTimer (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=health.onvy.staging:26376:17)
    at _callReactNativeMicrotasksPass (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=health.onvy.staging:26406:17)
    at callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=health.onvy.staging:26569:44)
    at __callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=health.onvy.staging:5177:46)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=health.onvy.staging:4989:45)
    at __guard (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=health.onvy.staging:5161:15)
    at flushedQueue (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=health.onvy.staging:4988:21)
    at invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=health.onvy.staging:4982:33)


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @mhyassin can you run this command `amplify diagnose --send-report` and share the project identifier that is output?

Since this error seems to happen intermittently, could you check to see if there are any mutations being sent or pending mutations in the outbox when signing out?

You can try enabling the Amplify logger by adding this line under the Amplify configuration

`Amplify.Logger.LOG_LEVEL="DEBUG";`

Or you should be able to use the Hub to listen to datastore events and log them to gain some more insight into what it's trying to do during sign out.

[Hub Listener](https://docs.amplify.aws/lib/utilities/hub/q/platform/js/)

[DataStore Events](https://docs.amplify.aws/lib/datastore/datastore-events/q/platform/js/)

**Comment by mhyassin** [comment]
Hi @chrisbonifacio, The project identifier is: 1f41c9d6304e82061193f8ee2e85ae0a

**Comment by david-mcafee** [comment]
Hi @mhyassin! Were you able to debug with any of [@chrisbonifacio's suggestions](https://github.com/aws-amplify/amplify-js/issues/11722#issuecomment-1668445919) (i.e. checking for the existence of pending mutations and / or debugging with additional logging)?

**Comment by david-mcafee** [comment]
@mhyassin looking at the logs you provided, it looks like a mutation occurs *after* the sync engine has stopped. Is it possible that somewhere you are attempting to perform a mutation after calling `DataStore.clear`? If so, there would be a race condition happening between the mutation and the attempt to clear DataStore.

Also, instead of listening for `cognitoHostedUI` prior to calling `DataStore.clear` (as you do in the code sample you provided), I'd recommend waiting for the `signOut` event from the Auth category before calling `DataStore.clear`. This is explained in our [documentation](https://docs.amplify.aws/lib/datastore/sync/q/platform/js/#clear-local-data), but I've also included a code snippet below:

```javascript
Hub.listen('auth', async (data) => {
    if (data.payload.event === 'signOut') {
        await DataStore.clear();
    }
});
```

**Comment by cwomack** [comment]
@mhyassin, did you get a chance to see the question and comment above?
