### ISSUE TITLE
Uncaught (in promise) CodeMismatchException: Invalid verification code provided, please try again.     at eval (webpack-internal:///../../node_modules/amazon-cognito-identity-js/es/Client.js:129:19)

### ISSUE THREAD

**Issue by Nutcracker52** [aws-amplify/amplify-js#11738]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
Client.js:124 Uncaught (in promise) CodeMismatchException: Invalid verification code provided, please try again.
    at eval (webpack-internal:///../../node_modules/amazon-cognito-identity-js/es/Client.js:129:19)
eval @ Client.js:124
Promise.then (async)
request @ Client.js:116
confirmPassword @ CognitoUser.js:1369
eval @ Auth.js:2072
AuthClass.forgotPasswordSubmit @ Auth.js:2071
forgotPasswordSubmit @ auth.ts:17
forgotPasswordSubmit @ index.ts:97
wrappedActionHandler @ vuex.esm.js:851
dispatch @ vuex.esm.js:516
boundDispatch @ vuex.esm.js:406
_callee2$ @ AccountResetCard.vue:46
tryCatch @ regeneratorRuntime.js:44
eval @ regeneratorRuntime.js:125
eval @ regeneratorRuntime.js:69
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:22
eval @ asyncToGenerator.js:27
eval @ asyncToGenerator.js:19
handleResetPassword @ AccountResetCard.vue:69
eval @ vee-validate.esm.js:1923
step @ vee-validate.esm.js:66
eval @ vee-validate.esm.js:47
fulfilled @ vee-validate.esm.js:37
Promise.then (async)
step @ vee-validate.esm.js:39
eval @ vee-validate.esm.js:40
__awaiter @ vee-validate.esm.js:36
handleSubmit @ vee-validate.esm.js:1913
submit @ AccountResetCard.vue:150
invokeWithErrorHandling @ vue.runtime.esm.js:3017
invoker @ vue.runtime.esm.js:1815
original_1._wrapper @ vue.runtime.esm.js:7473
![aws amplify auth](https://github.com/aws-amplify/amplify-js/assets/65933656/0b7a2632-3ded-4b0e-8d3d-abc951260f4f)


```

</details>

### Describe the bug

Package and version that I am using... 

"@aws-amplify/auth": "^5.6.0",

How to reproduce, 

Try to recover the password(forgot password) for non existing email address/ email address which is not registed.

First do call forgotPassword method in aws-amplify/auth library which returns below success code. 
{
    "CodeDeliveryDetails": {
        "AttributeName": "email",
        "DeliveryMedium": "EMAIL",
        "Destination": "2***@g***"
    }
}

This is working fine as per the document. 

Then user submit the form with wrong information, two matching passwords and wrong one time verification code to this method forgotPasswordSubmit in aws-amplify/auth library. 
Then is suppose to throw an error/exception but it returns the data as undefined and exception not handled properly. 

Due to that it throws a console error which is not great. 
This need to be handled properly this could cause hackers to spaming our systems. 

if user account exist 

1. user provide wrong code it throws an exceptions which is correct
2. User provide correct pin password get resetted

### Expected behavior

When user try to recover a password for non existing profile exception mush be thrown when random pin provided. 

### Reproduction steps

First do call forgotPassword method in aws-amplify/auth library which returns below success code. 
{
    "CodeDeliveryDetails": {
        "AttributeName": "email",
        "DeliveryMedium": "EMAIL",
        "Destination": "2***@g***"
    }
}

This is working fine as per the document. 

Then user submit the form with wrong information, two matching passwords and wrong one time verification code to this method forgotPasswordSubmit in aws-amplify/auth library. 
Then is suppose to throw an error/exception but it returns the data as undefined and exception not handled properly. 

Due to that it throws a console error which is not great. 
This need to be handled properly this could cause hackers to spaming our systems. 

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by Nutcracker52** [comment]
@cwomack 
PLEASE NOTE: this is happening only for where user account not exist and user enter random one time verification code to fire forgotPasswordSubmit function.  This means user try to reset the password for non-exist user account. in other words user submit wrong data. 
it suppose to throw an error but for some reason it's not sending it. 
Response comes back as undefined. 
Successful case return empty object without errors. in JS empty object take as undefined. 
So I cannot differenciate the two cases. 

please find the below package.json content
`{
  "name": "app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "test:unit": "TZ=UTC vue-cli-service test:unit --env=jsdom-sixteen",
    "test:unit:watch": "TZ=UTC vue-cli-service test:unit --watch --env=jsdom-sixteen",
    "test:unit:report": "TZ=UTC vue-cli-service test:unit --reporters default jest-html-reporter --env=jsdom-sixteen",
    "test:e2e": "vue-cli-service test:e2e --headless",
    "test:e2e:watch": "vue-cli-service test:e2e",
    "test:e2e:watch:local": "vue-cli-service test:e2e --url http://localhost:8080",
    "test:e2e:report": "run-s --continue-on-error clean:e2e test:e2e report:e2e",
    "clean:e2e": "node scripts/clean-e2e-reports.js",
    "report:e2e": "node scripts/generate-e2e-report.js",
    "lint": "vue-cli-service lint",
    "new": "HYGEN_TMPLS=templates hygen new",
    "docs": "vuepress dev docs --open",
    "storybook": "start-storybook -p 8085"
  },
  "dependencies": {
    "@aws-amplify/auth": "^5.6.0",
    "@sentry/browser": "^5.15.5",
    "@sentry/integrations": "^5.15.5",
    "@types/file-saver": "^2.0.5",
    "@types/googlemaps": "^3.43.3",
    "@types/graphql": "^14.5.0",
    "@types/mixpanel-browser": "^2.38.0",
    "@types/papaparse": "^5.3.7",
    "@types/ws": "^7.2.2",
    "@vue-stripe/vue-stripe": "^4.5.0",
    "apollo-cache-inmemory": "^1.6.5",
    "apollo-client": "^2.6.8",
    "apollo-link": "^1.2.13",
    "apollo-link-context": "^1.0.19",
    "apollo-link-error": "^1.1.12",
    "apollo-link-http": "^1.5.16",
    "apollo-link-ws": "^1.0.19",
    "buefy": "^0.9.0",
    "bulma-extensions": "^6.2.7",
    "core-js": "^3.27.1",
    "cypress": "^8.7.0",
    "date-fns": "^2.29.3",
    "file-saver": "^2.0.5",
    "graphql": "^14.5.8",
    "graphql-tag": "^2.12.6",
    "jest-environment-jsdom-sixteen": "^1.0.3",
    "lodash": "^4.17.21",
    "mixpanel-browser": "^2.45.0",
    "papaparse": "^5.3.2",
    "sass-loader": "^10.1.1",
    "subscriptions-transport-ws": "^0.9.16",
    "tiptap": "^1.32.2",
    "tiptap-extensions": "^1.35.2",
    "uuid": "^3.4.0",
    "vee-validate": "^3.2.1",
    "vue": "^2.6.10",
    "vue-apollo": "^3.1.0",
    "vue-class-component": "^7.2.6",
    "vue-currency-input": "^1.17.3",
    "vue-gtag": "^1.16.1",
    "vue-property-decorator": "^8.3.0",
    "vue-recaptcha-v3": "1.9.0",
    "vue-router": "^3.1.3",
    "vue-sanitize": "^0.2.1",
    "vuex": "^3.0.1",
    "xlsx": "^0.17.0"
  },
  "devDependencies": {
    "@storybook/addon-actions": "^5.3.3",
    "@storybook/vue": "^5.3.3",
    "@types/graphql": "^14.5.0",
    "@types/jest": "^24.0.11",
    "@types/lodash": "^4.14.191",
    "@types/uuid": "^3.4.7",
    "@types/zen-observable": "^0.8.3",
    "@vue/cli-plugin-babel": "^4.0.0",
    "@vue/cli-plugin-e2e-cypress": "^4.0.0",
    "@vue/cli-plugin-eslint": "^4.0.0",
    "@vue/cli-plugin-router": "^4.0.0",
    "@vue/cli-plugin-typescript": "^4.0.0",
    "@vue/cli-plugin-unit-jest": "^4.0.0",
    "@vue/cli-plugin-vuex": "^4.0.0",
    "@vue/cli-service": "^4.0.0",
    "@vue/eslint-config-prettier": "^5.0.0",
    "@vue/eslint-config-typescript": "^4.0.0",
    "@vue/test-utils": "1.0.0-beta.29",
    "babel-jest": "^25.3.0",
    "babel-loader": "^8.1.0",
    "babel-preset-vue": "^2.0.2",
    "cypress-file-upload": "^5.0.8",
    "eslint": "^5.16.0",
    "eslint-plugin-prettier": "^3.1.1",
    "eslint-plugin-vue": "^5.0.0",
    "hygen": "^5.0.3",
    "jest-html-reporter": "^3.1.0",
    "lint-staged": "^9.4.2",
    "mocha": "^5.2.0",
    "mochawesome": "^4.1.0",
    "mochawesome-merge": "^2.1.0",
    "mochawesome-report-generator": "^4.1.0",
    "npm-run-all": "^4.1.5",
    "prettier": "^1.18.2",
    "sass": "^1.24.3",
    "typescript": "^3.9.7",
    "vue-template-compiler": "^2.6.11"
  },
  "jest-html-reporter": {
    "pageTitle": "App - Unit Tests",
    "includeFailureMsg": true,
    "outputPath": "./reports/report-unit.html"
  },
  "gitHooks": {
    "pre-commit": "lint-staged"
  },
  "resolutions": {
    "cypress": "8.7.0"
  },
  "lint-staged": {
    "*.{js,vue,ts}": [
      "vue-cli-service lint",
      "git add"
    ]
  }
}
`

**Comment by Nutcracker52** [comment]
you are welcome to close this, this error was happening in our vue store poor handling functions. 
function wasn't async await function. 

` async forgotPasswordSubmit({ commit }, payload: { username: string; code: string; newPassword: string }) {
    const { username, code, newPassword } = payload
    return await forgotPasswordSubmit(username, code, newPassword)
  },` 
this fixed the console error. 
![image](https://github.com/aws-amplify/amplify-js/assets/65933656/7a4f0cfe-b8ee-4c10-9e51-240aaf3373ae)

**Comment by cwomack** [comment]
@Nutcracker52, appreciate the detailed reply and happy to hear you already discovered what was causing the error 🎉 .  Sounds like changing the password reset function to be async resolved the errors you're experiencing.  I'll close this issue then at this point, but feel free to comment back if you have more trouble with it.  Thanks!
