### ISSUE TITLE
Authentication/redirect loops with federatedSignIn after upgrade to 5.3.8

### ISSUE THREAD

**Issue by mat-mik** [aws-amplify/amplify-js#11846]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 39.38 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.0/bin/yarn
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
    Watchman: 2023.07.24.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 115.0.5790.170
    Edge: 115.0.1901.203
    Safari: 16.5.2
  npmPackages:
    @testing-library/jest-dom: 5.17.0 => 5.17.0 
    @testing-library/react: 13.4.0 => 13.4.0 
    @testing-library/user-event: 13.5.0 => 13.5.0 
    aws-amplify: 5.3.8 => 5.3.8 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    react-scripts: 5.0.1 => 5.0.1 
  npmGlobalPackages:
    corepack: 0.15.3
    npm: 9.3.1
    yarn: 1.22.19

```

</details>

### Describe the bug

We've been using Cognito with one Federated identity provider sign-in and Hosted UI. Our frontend apps are written in React and integrate with Cognito using `Amplify`. After `Amplify` upgrade 5.3.6 -> 5.3.8 we can't authenticate anymore, we end up in the loop. 5.3.7 isn't working as well but that's because of [multiple token endpoint calls](https://github.com/aws-amplify/amplify-js/issues/11808).

5.3.6 logs:
```
19:42:34.024 ConsoleLogger.js:134 [DEBUG] 42:34.24 Amplify - amplify config {Auth: {…}}
19:42:34.024 ConsoleLogger.js:122 [DEBUG] 42:34.24 AuthClass - configure Auth
19:42:34.025 ConsoleLogger.js:134 [DEBUG] 42:34.25 Parser - parse config (3) [{…}, 'to amplifyconfig', {…}]
19:42:34.025 ConsoleLogger.js:134 [DEBUG] 42:34.25 Hub - Dispatching to auth with  {event: 'parsingCallbackUrl', data: {…}, message: 'The callback url is being parsed'}
19:42:34.025 ConsoleLogger.js:134 [DEBUG] 42:34.25 Hub - Dispatching to auth with  {event: 'configured', data: null, message: 'The Auth category has been configured successfully'}
19:42:34.032 ConsoleLogger.js:122 [DEBUG] 42:34.32 AuthClass - Getting current session
19:42:34.033 ConsoleLogger.js:122 [DEBUG] 42:34.33 AuthClass - Getting current session
19:42:34.033 ConsoleLogger.js:122 [DEBUG] 42:34.33 AuthClass - Failed to get user from user pool
19:42:34.033 ConsoleLogger.js:122 [DEBUG] 42:34.33 AuthClass - Failed to get user from user pool
19:42:34.033 ConsoleLogger.js:134 [DEBUG] 42:34.33 AuthClass - Failed to get the current user No current user
19:42:34.033 ConsoleLogger.js:134 [DEBUG] 42:34.33 AuthClass - Failed to get the current user No current user
19:42:34.034 ConsoleLogger.js:122 [DEBUG] 42:34.34 Credentials - removing aws-amplify-federatedInfo from storage
19:42:34.034 ConsoleLogger.js:122 [DEBUG] 42:34.34 Credentials - removing aws-amplify-federatedInfo from storage
19:42:34.034 ConsoleLogger.js:122 [DEBUG] 42:34.34 AuthClass - no current Cognito user
19:42:34.034 ConsoleLogger.js:134 [DEBUG] 42:34.34 Hub - Dispatching to auth with  {event: 'signOut', data: null, message: 'A user has been signed out'}
19:42:34.034 ConsoleLogger.js:122 [DEBUG] 42:34.34 AuthClass - no current Cognito user
19:42:34.034 ConsoleLogger.js:134 [DEBUG] 42:34.34 Hub - Dispatching to auth with  {event: 'signOut', data: null, message: 'A user has been signed out'}
19:42:34.036 ConsoleLogger.js:122 [DEBUG] 42:34.36 OAuth - Redirecting to https://xxx.amazoncognito.com/oauth2/authorize?xxx
19:42:34.036 ConsoleLogger.js:122 [DEBUG] 42:34.36 OAuth - Redirecting to https://xxx.amazoncognito.com/oauth2/authorize?xxx

19:42:34.263 Navigated to http://localhost:3000/?code=xxx&state=xxx
19:42:34.315 ConsoleLogger.js:134 [DEBUG] 42:34.315 Amplify - amplify config {Auth: {…}}
19:42:34.315 ConsoleLogger.js:122 [DEBUG] 42:34.315 AuthClass - configure Auth
19:42:34.315 ConsoleLogger.js:134 [DEBUG] 42:34.315 Parser - parse config (3) [{…}, 'to amplifyconfig', {…}]
19:42:34.316 ConsoleLogger.js:134 [DEBUG] 42:34.316 Hub - Dispatching to auth with  {event: 'parsingCallbackUrl', data: {…}, message: 'The callback url is being parsed'}
19:42:34.316 ConsoleLogger.js:122 [DEBUG] 42:34.316 OAuth - Starting code flow with http://localhost:3000/?code=xxx&state=xxx
19:42:34.316 ConsoleLogger.js:134 [DEBUG] 42:34.316 Hub - Dispatching to auth with  {event: 'codeFlow', data: {…}, message: 'Retrieving tokens from https://xxx.amazoncognito.com/oauth2/token'}
19:42:34.317 ConsoleLogger.js:134 [DEBUG] 42:34.317 OAuth - Calling token endpoint: https://xxx.amazoncognito.com/oauth2/token with {grant_type: 'authorization_code', code: 'xxx', client_id: 'xxx', redirect_uri: 'http://localhost:3000/', code_verifier: 'xxx'}
19:42:34.317 ConsoleLogger.js:134 [DEBUG] 42:34.317 Hub - Dispatching to auth with  {event: 'configured', data: null, message: 'The Auth category has been configured successfully'}
19:42:34.334 ConsoleLogger.js:122 [DEBUG] 42:34.334 AuthClass - Getting current session
19:42:34.334 ConsoleLogger.js:122 [DEBUG] 42:34.334 AuthClass - Getting current session
19:42:34.334 ConsoleLogger.js:122 [DEBUG] 42:34.334 AuthClass - OAuth signIn in progress, waiting for resolution...
19:42:34.335 ConsoleLogger.js:122 [DEBUG] 42:34.335 AuthClass - OAuth signIn in progress, waiting for resolution...
19:42:34.557 OAuth.ts:178 Fetch finished loading: POST "https://xxx.amazoncognito.com/oauth2/token".
//..
19:42:34.558 ConsoleLogger.js:134 [DEBUG] 42:34.558 Hub - Dispatching to auth with  {event: 'signIn', data: CognitoUser, message: 'A user xxx.com has been signed in'}
19:42:34.558 ConsoleLogger.js:134 [DEBUG] 42:34.558 Hub - Dispatching to auth with  {event: 'signIn', data: CognitoUser, message: 'A user xxx.com has been signed in'}
19:42:34.558 ConsoleLogger.js:134 [DEBUG] 42:34.558 Hub - Dispatching to auth with  {event: 'signIn', data: CognitoUser, message: 'A user xxx.com has been signed in'}
19:42:34.558 ConsoleLogger.js:134 [DEBUG] 42:34.558 Hub - Dispatching to auth with  {event: 'cognitoHostedUI', data: CognitoUser, message: 'A user xxx.com has been signed in via Cognito Hosted UI'}
19:42:34.559 ConsoleLogger.js:134 [DEBUG] 42:34.559 Hub - Dispatching to auth with  {event: 'cognitoHostedUI', data: CognitoUser, message: 'A user xxx.com has been signed in via Cognito Hosted UI'}
19:42:34.559 ConsoleLogger.js:122 [DEBUG] 42:34.559 AuthClass - OAuth signIn resolved: cognitoHostedUI
19:42:34.559 ConsoleLogger.js:134 [DEBUG] 42:34.559 Hub - Dispatching to auth with  {event: 'cognitoHostedUI', data: CognitoUser, message: 'A user xxx.com has been signed in via Cognito Hosted UI'}
19:42:34.559 ConsoleLogger.js:122 [DEBUG] 42:34.559 AuthClass - OAuth signIn resolved: cognitoHostedUI
19:42:34.560 ConsoleLogger.js:134 [DEBUG] 42:34.560 AuthClass - Succeed to get the user session CognitoUserSession {idToken: CognitoIdToken, refreshToken: CognitoRefreshToken, accessToken: CognitoAccessToken, clockDrift: 0}
19:42:34.560 ConsoleLogger.js:122 [DEBUG] 42:34.560 AuthClass - Unable to get the user data because the aws.cognito.signin.user.admin is not in the scopes of the access token
19:42:34.560 ConsoleLogger.js:122 [DEBUG] 42:34.560 AuthClass - Unable to get the user data because the aws.cognito.signin.user.admin is not in the scopes of the access token
19:42:34.560 ConsoleLogger.js:134 [DEBUG] 42:34.560 AuthClass - Succeed to get the user session CognitoUserSession {idToken: CognitoIdToken, refreshToken: CognitoRefreshToken, accessToken: CognitoAccessToken, clockDrift: 0}

```

5.3.8 logs:
```
19:32:51.654 ConsoleLogger.js:134 [DEBUG] 32:51.654 Amplify - amplify config {Auth: {…}}
19:32:51.655 ConsoleLogger.js:122 [DEBUG] 32:51.655 AuthClass - configure Auth
19:32:51.655 ConsoleLogger.js:134 [DEBUG] 32:51.655 Parser - parse config (3) [{…}, 'to amplifyconfig', {…}]
19:32:51.655 ConsoleLogger.js:134 [DEBUG] 32:51.655 Hub - Dispatching to auth with  {event: 'parsingCallbackUrl', data: {…}, message: 'The callback url is being parsed'}
19:32:51.655 ConsoleLogger.js:134 [DEBUG] 32:51.655 Hub - Dispatching to auth with  {event: 'parsingCallbackUrl', data: {…}, message: 'The callback url is being parsed'}
19:32:51.656 ConsoleLogger.js:134 [DEBUG] 32:51.656 Hub - Dispatching to auth with  {event: 'configured', data: null, message: 'The Auth category has been configured successfully'}
19:32:51.656 ConsoleLogger.js:134 [DEBUG] 32:51.656 Hub - Dispatching to auth with  {event: 'configured', data: null, message: 'The Auth category has been configured successfully'}
19:32:51.656 ConsoleLogger.js:122 [DEBUG] 32:51.656 AuthClass - configure Auth
19:32:51.656 ConsoleLogger.js:134 [DEBUG] 32:51.656 Parser - parse config (3) [{…}, 'to amplifyconfig', {…}]
19:32:51.656 ConsoleLogger.js:134 [DEBUG] 32:51.656 Hub - Dispatching to auth with  {event: 'configured', data: null, message: 'The Auth category has been configured successfully'}
19:32:51.656 ConsoleLogger.js:134 [DEBUG] 32:51.656 Hub - Dispatching to auth with  {event: 'configured', data: null, message: 'The Auth category has been configured successfully'}
19:32:51.663 ConsoleLogger.js:122 [DEBUG] 32:51.663 AuthClass - Getting current session
19:32:51.664 ConsoleLogger.js:122 [DEBUG] 32:51.664 AuthClass - Getting current session
19:32:51.664 ConsoleLogger.js:122 [DEBUG] 32:51.664 AuthClass - Failed to get user from user pool
19:32:51.664 ConsoleLogger.js:122 [DEBUG] 32:51.664 AuthClass - Failed to get user from user pool
19:32:51.664 ConsoleLogger.js:134 [DEBUG] 32:51.664 AuthClass - Failed to get the current user No current user
19:32:51.664 ConsoleLogger.js:134 [DEBUG] 32:51.664 AuthClass - Failed to get the current user No current user
19:32:51.665 ConsoleLogger.js:122 [DEBUG] 32:51.665 Credentials - removing aws-amplify-federatedInfo from storage
19:32:51.665 ConsoleLogger.js:122 [DEBUG] 32:51.665 Credentials - removing aws-amplify-federatedInfo from storage
19:32:51.665 ConsoleLogger.js:122 [DEBUG] 32:51.665 AuthClass - no current Cognito user
19:32:51.665 ConsoleLogger.js:134 [DEBUG] 32:51.665 Hub - Dispatching to auth with  {event: 'signOut', data: null, message: 'A user has been signed out'}
19:32:51.665 ConsoleLogger.js:134 [DEBUG] 32:51.665 Hub - Dispatching to auth with  {event: 'signOut', data: null, message: 'A user has been signed out'}
19:32:51.665 ConsoleLogger.js:122 [DEBUG] 32:51.665 AuthClass - no current Cognito user
19:32:51.665 ConsoleLogger.js:134 [DEBUG] 32:51.665 Hub - Dispatching to auth with  {event: 'signOut', data: null, message: 'A user has been signed out'}
19:32:51.665 ConsoleLogger.js:134 [DEBUG] 32:51.665 Hub - Dispatching to auth with  {event: 'signOut', data: null, message: 'A user has been signed out'}
19:32:51.667 ConsoleLogger.js:122 [DEBUG] 32:51.667 OAuth - Redirecting to https:xxx.amazoncognito.com/oauth2/authorize?xxx
19:32:51.668 ConsoleLogger.js:122 [DEBUG] 32:51.668 OAuth - Redirecting to https:xxx.amazoncognito.com/oauth2/authorize?xxx

19:32:51.907 Navigated to http://localhost:3000/?code=xxx&state=xxx
19:32:51.961 ConsoleLogger.js:134 [DEBUG] 32:51.961 Amplify - amplify config {Auth: {…}}
19:32:51.962 ConsoleLogger.js:122 [DEBUG] 32:51.962 AuthClass - configure Auth
19:32:51.962 ConsoleLogger.js:134 [DEBUG] 32:51.962 Parser - parse config (3) [{…}, 'to amplifyconfig', {…}]
19:32:51.962 ConsoleLogger.js:134 [DEBUG] 32:51.962 Hub - Dispatching to auth with  {event: 'parsingCallbackUrl', data: {…}, message: 'The callback url is being parsed'}
19:32:51.962 ConsoleLogger.js:134 [DEBUG] 32:51.962 Hub - Dispatching to auth with  {event: 'parsingCallbackUrl', data: {…}, message: 'The callback url is being parsed'}
19:32:51.963 ConsoleLogger.js:122 [DEBUG] 32:51.963 OAuth - Starting code flow with http://localhost:3000/?code=xxx&state=xxx
19:32:51.963 ConsoleLogger.js:134 [DEBUG] 32:51.963 Hub - Dispatching to auth with  {event: 'codeFlow', data: {…}, message: 'Retrieving tokens from https://xxx.amazoncognito.com/oauth2/token'}
19:32:51.963 ConsoleLogger.js:134 [DEBUG] 32:51.963 Hub - Dispatching to auth with  {event: 'codeFlow', data: {…}, message: 'Retrieving tokens from https://xxx.amazoncognito.com/oauth2/token'}
19:32:51.964 ConsoleLogger.js:134 [DEBUG] 32:51.964 OAuth - Calling token endpoint: https://xxx.amazoncognito.com/oauth2/token with {grant_type: 'authorization_code', code: 'xxx', client_id: 'xxx', redirect_uri: 'http://localhost:3000/', code_verifier: 'xxx'}
19:32:51.964 ConsoleLogger.js:134 [DEBUG] 32:51.964 Hub - Dispatching to auth with  {event: 'configured', data: null, message: 'The Auth category has been configured successfully'}
19:32:51.964 ConsoleLogger.js:134 [DEBUG] 32:51.965 Hub - Dispatching to auth with  {event: 'configured', data: null, message: 'The Auth category has been configured successfully'}
19:32:51.965 ConsoleLogger.js:122 [DEBUG] 32:51.965 AuthClass - configure Auth
19:32:51.965 ConsoleLogger.js:134 [DEBUG] 32:51.965 Parser - parse config (3) [{…}, 'to amplifyconfig', {…}]
19:32:51.965 ConsoleLogger.js:134 [DEBUG] 32:51.965 Hub - Dispatching to auth with  {event: 'configured', data: null, message: 'The Auth category has been configured successfully'}
19:32:51.965 ConsoleLogger.js:134 [DEBUG] 32:51.965 Hub - Dispatching to auth with  {event: 'configured', data: null, message: 'The Auth category has been configured successfully'}
19:32:51.974 ConsoleLogger.js:122 [DEBUG] 32:51.974 AuthClass - Getting current session
19:32:51.974 ConsoleLogger.js:122 [DEBUG] 32:51.974 AuthClass - Getting current session
19:32:51.975 ConsoleLogger.js:122 [DEBUG] 32:51.975 AuthClass - Failed to get user from user pool
19:32:51.975 ConsoleLogger.js:122 [DEBUG] 32:51.975 AuthClass - Failed to get user from user pool
19:32:51.975 ConsoleLogger.js:134 [DEBUG] 32:51.975 AuthClass - Failed to get the current user No current user
19:32:51.975 ConsoleLogger.js:134 [DEBUG] 32:51.975 AuthClass - Failed to get the current user No current user
19:32:51.975 ConsoleLogger.js:122 [DEBUG] 32:51.975 Credentials - removing aws-amplify-federatedInfo from storage
19:32:51.975 ConsoleLogger.js:122 [DEBUG] 32:51.975 Credentials - removing aws-amplify-federatedInfo from storage
19:32:51.976 ConsoleLogger.js:122 [DEBUG] 32:51.976 AuthClass - no current Cognito user
19:32:51.976 ConsoleLogger.js:134 [DEBUG] 32:51.976 Hub - Dispatching to auth with  {event: 'signOut', data: null, message: 'A user has been signed out'}
19:32:51.976 ConsoleLogger.js:134 [DEBUG] 32:51.976 Hub - Dispatching to auth with  {event: 'signOut', data: null, message: 'A user has been signed out'}
19:32:51.976 ConsoleLogger.js:122 [DEBUG] 32:51.976 AuthClass - no current Cognito user
19:32:51.976 ConsoleLogger.js:134 [DEBUG] 32:51.976 Hub - Dispatching to auth with  {event: 'signOut', data: null, message: 'A user has been signed out'}
19:32:51.976 ConsoleLogger.js:134 [DEBUG] 32:51.976 Hub - Dispatching to auth with  {event: 'signOut', data: null, message: 'A user has been signed out'}
19:32:51.977 ConsoleLogger.js:122 [DEBUG] 32:51.977 OAuth - Redirecting to https://xxx.amazoncognito.com/oauth2/authorize?xxx
19:32:51.978 ConsoleLogger.js:122 [DEBUG] 32:51.978 OAuth - Redirecting to https://xxx.amazoncognito.com/oauth2/authorize?xxx
19:32:52.136 ConsoleLogger.js:134 [DEBUG] 32:52.136 OAuth - Error handling auth response. TypeError: Failed to fetch
    at OAuth.<anonymous> (OAuth.ts:173:1)
    at step (tslib.es6.js:100:1)
    at Object.next (tslib.es6.js:81:1)
    at tslib.es6.js:74:1
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:70:1)
    at OAuth._handleCodeFlow (OAuth.ts:120:1)
    at OAuth.<anonymous> (OAuth.ts:246:1)
    at step (tslib.es6.js:100:1)
    at Object.next (tslib.es6.js:81:1)
19:32:52.136 ConsoleLogger.js:134 [DEBUG] 32:52.136 AuthClass - Error in cognito hosted auth response TypeError: Failed to fetch
    at OAuth.<anonymous> (OAuth.ts:173:1)
    at step (tslib.es6.js:100:1)
    at Object.next (tslib.es6.js:81:1)
    at tslib.es6.js:74:1
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:70:1)
    at OAuth._handleCodeFlow (OAuth.ts:120:1)
    at OAuth.<anonymous> (OAuth.ts:246:1)
    at step (tslib.es6.js:100:1)
    at Object.next (tslib.es6.js:81:1)
19:32:52.137 ConsoleLogger.js:134 [DEBUG] 32:52.137 Hub - Dispatching to auth with  {event: 'signIn_failure', data: TypeError: Failed to fetch
    at OAuth.<anonymous> (http://localhost:3000/static/js/bundle.js:921:…, message: 'The OAuth response flow failed'}
19:32:52.137 ConsoleLogger.js:134 [DEBUG] 32:52.137 Hub - Dispatching to auth with  {event: 'signIn_failure', data: TypeError: Failed to fetch
    at OAuth.<anonymous> (http://localhost:3000/static/js/bundle.js:921:…, message: 'The OAuth response flow failed'}
19:32:52.137 ConsoleLogger.js:134 [DEBUG] 32:52.137 Hub - Dispatching to auth with  {event: 'cognitoHostedUI_failure', data: TypeError: Failed to fetch
    at OAuth.<anonymous> (http://localhost:3000/static/js/bundle.js:921:…, message: 'A failure occurred when returning to the Cognito Hosted UI'}
19:32:52.137 ConsoleLogger.js:134 [DEBUG] 32:52.137 Hub - Dispatching to auth with  {event: 'cognitoHostedUI_failure', data: TypeError: Failed to fetch
    at OAuth.<anonymous> (http://localhost:3000/static/js/bundle.js:921:…, message: 'A failure occurred when returning to the Cognito Hosted UI'}
19:32:52.137 ConsoleLogger.js:134 [DEBUG] 32:52.137 Hub - Dispatching to auth with  {event: 'customState_failure', data: TypeError: Failed to fetch
    at OAuth.<anonymous> (http://localhost:3000/static/js/bundle.js:921:…, message: 'A failure occurred when returning state'}
19:32:52.137 ConsoleLogger.js:134 [DEBUG] 32:52.137 Hub - Dispatching to auth with  {event: 'customState_failure', data: TypeError: Failed to fetch
    at OAuth.<anonymous> (http://localhost:3000/static/js/bundle.js:921:…, message: 'A failure occurred when returning state'}
19:32:52.144 OAuth.ts:173 Fetch failed loading: POST "https://xxx.amazoncognito.com/oauth2/token".
```

### Expected behavior

User authenticates correctly.

### Reproduction steps

5.3.6 working - https://github.com/mat-mik/amplify-twice-oauth2-authorize/commit/a9574a1af6b2f32c9aaef0f17f0571870432a9b7
5.3.8 broken - https://github.com/mat-mik/amplify-twice-oauth2-authorize/commit/df3a3d6c97c88eab08e716e21e9c669c7303e554

1. Pull project
2. Fill `.env` file with Cognito data
3. `npm run start`
4. launch localhost:3000

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
@mat-mik, we appreciate you opening this issue.  We're working on a fix and have a PR already linked above that we believe should resolve the authentication loop.  I'll comment again as soon as we have an update or when the fix is released!

**Comment by stocaaro** [comment]
The release containing this fix is out.  Please upgrade to the latest version and verify that the problem you where experiencing has been fixed.

**Comment by mat-mik** [comment]
Seems to be working guys, thanks for quick fix!
