### ISSUE TITLE
Unable to add Apple Auth to cognito both throu cli and Amplify Studio: Log shows InternalErrorException

### ISSUE THREAD

**Issue by aryan1107** [aws-amplify/amplify-js#11994]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 13.5.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 214.83 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
    pnpm: 8.6.11 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.179
    Safari: 16.6
  npmGlobalPackages:
    @aws-amplify/cli: 12.4.0
    corepack: 0.17.0
    firebase-tools: 12.4.6
    npm: 9.5.1
    pnpm: 8.6.11
    yarn: 1.22.19

```

</details>

### Describe the bug

Basically When Adding Apple Oauth the deployment fails have tried adding through Amplify Studio first and then CLI both time it gives same error to check the log. Then test it by adding Google Oauth it was successful problem lies when adding Apple auth.

Example error:
```
🛑 The following resources failed to deploy:
Resource Name: HostedUIProvidersCustomResourceInputs (Custom::LambdaCallout)
Event Type: update
Reason: Received response status [FAILED] from custom resource. Message returned: See the details in CloudWatch Log Stream: 2023/09/08/[$LATEST]09e31ca9fefe486c980a8314cf5ec338 (RequestId: df4cffd8-3754-4ff1-b5c8-c7c281961609)
URL: https://console.aws.amazon.com/cloudformation/home?region=us-east-2#/stacks/arn%3Aaws%3Acloudformation%3Aus-east-2%3A851535460239%3Astack%2Famplify-aiwriter-dev-102704-authaiwriter-1KI77SKFAG06C%2F2c56c340-4e5e-11ee-a321-0a84752997b7/events
```

Here is the log:
```
2023-09-08T16:14:35.260Z	2bd35fc1-34ce-4fb9-9e1a-a45ddf8690a4	INFO	InternalErrorException: Internal server error.
    at deserializeAws_json1_1InternalErrorExceptionResponse (/var/runtime/node_modules/@aws-sdk/client-cognito-identity-provider/dist-cjs/protocols/Aws_json1_1.js:6611:23)
    at deserializeAws_json1_1CreateIdentityProviderCommandError (/var/runtime/node_modules/@aws-sdk/client-cognito-identity-provider/dist-cjs/protocols/Aws_json1_1.js:2933:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/runtime/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /var/runtime/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:13:20
    at async StandardRetryStrategy.retry (/var/runtime/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /var/runtime/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at async createIdentityProvider (/var/task/index.js:96:3)
    at async handleEvent (/var/task/index.js:45:9)
    at async tryHandleEvent (/var/task/index.js:18:5)

```

### Expected behavior

Deployment Failure for Auth.

### Reproduction steps

When Adding apple OAuth trough amplify studio and then clicking on deploy.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

<img width="1394" alt="Screenshot 2023-09-08 at 12 39 00 PM" src="https://github.com/aws-amplify/amplify-js/assets/31214277/cda86ad9-5d1d-4d76-947c-b5e69f4081be">

**Comment by cwomack** [comment]
Hello, @aryan1107 and thanks for opening this issue.  It seems the errors you're getting are more CLI related so I'll transfer this issue to the CLI repo for better assistance.
