### ISSUE TITLE
DataStore and GraphQL API both can't be used in Service Worker

### ISSUE THREAD

**Issue by sjdeak** [aws-amplify/amplify-js#12771]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

GraphQL API, DataStore

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line

  System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 339.50 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.7.1 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 120.0.6099.129
    Chrome Canary: 122.0.6213.0
    Edge: 119.0.2151.97
    Firefox: 121.0
    Safari: 17.2.1
  npmPackages:
    @babel/core: ^7.21.0 => 7.22.5 
    @babel/plugin-proposal-private-property-in-object: ^7.21.11 => 7.21.11 (7.21.0-placeholder-for-preset-env.2)
    @cypress/angular:  0.0.0-development 
    @cypress/mount-utils:  0.0.0-development 
    @cypress/react:  0.0.0-development 
    @cypress/react18:  0.0.0-development 
    @cypress/svelte:  0.0.0-development 
    @cypress/vue:  0.0.0-development 
    @cypress/vue2:  0.0.0-development 
    @cypress/webpack-preprocessor: ^6.0.1 => 6.0.1 
    @emotion/cache: ^11.10.5 => 11.11.0 
    @emotion/react: ^11.10.6 => 11.11.1 
    @emotion/styled: ^11.10.6 => 11.11.0 
    @hookform/devtools: ^4.3.1 => 4.3.1 
    @hookform/resolvers: ^2.9.11 => 2.9.11 
    @hookform/resolvers/ajv:  1.0.0 
    @hookform/resolvers/class-validator:  1.0.0 
    @hookform/resolvers/computed-types:  1.0.0 
    @hookform/resolvers/io-ts:  1.0.0 
    @hookform/resolvers/joi:  1.0.0 
    @hookform/resolvers/nope:  1.0.0 
    @hookform/resolvers/superstruct:  1.0.0 
    @hookform/resolvers/typanion:  1.0.0 
    @hookform/resolvers/vest:  1.0.0 
    @hookform/resolvers/yup:  1.0.0 
    @hookform/resolvers/zod:  1.0.0 
    @iconify/react: ^4.1.0 => 4.1.0 
    @iconify/react/offline:  undefined ()
    @milkdown/core: 7.3.0 => 7.3.0 
    @milkdown/ctx: 7.3.0 => 7.3.0 
    @milkdown/plugin-block: 7.3.0 => 7.3.0 
    @milkdown/plugin-cursor: 7.3.0 => 7.3.0 
    @milkdown/plugin-history: 7.3.0 => 7.3.0 
    @milkdown/plugin-indent: 7.3.0 => 7.3.0 
    @milkdown/plugin-listener: 7.3.0 => 7.3.0 
    @milkdown/plugin-slash: 7.3.0 => 7.3.0 
    @milkdown/preset-commonmark: 7.3.0 => 7.3.0 
    @milkdown/preset-gfm: 7.3.0 => 7.3.0 
    @milkdown/prose: 7.3.0 => 7.3.0 
    @milkdown/react: 7.3.0 => 7.3.0 
    @milkdown/theme-nord: 7.3.0 => 7.3.0 
    @milkdown/transformer: 7.3.0 => 7.3.0 
    @milkdown/utils: 7.3.0 => 7.3.0 
    @mui/icons-material: ^5.11.16 => 5.11.16 
    @mui/lab: ^5.0.0-alpha.120 => 5.0.0-alpha.134 
    @mui/material: ^5.11.10 => 5.13.5 
    @mui/x-data-grid-pro: ^6.16.1 => 6.16.1 
    @mui/x-date-pickers-pro: ^6.16.0 => 6.16.0 
    @mui/x-license-pro: ^6.10.2 => 6.10.2 
    @prosemirror-adapter/react: ^0.2.6 => 0.2.6 
    @reduxjs/toolkit: ^1.9.5 => 1.9.5 
    @reduxjs/toolkit-query:  1.0.0 
    @reduxjs/toolkit-query-react:  1.0.0 
    @types/autosuggest-highlight: ^3.2.0 => 3.2.0 
    @types/lodash-es: ^4.17.10 => 4.17.10 
    @types/node: ^18.14.0 => 18.18.9 
    @types/nprogress: ^0.2.0 => 0.2.0 
    @types/numeral: ^2.0.2 => 2.0.2 
    @types/react: ^18.0.28 => 18.2.12 
    @types/react-dom: ^18.0.11 => 18.2.5 
    @types/react-lazy-load-image-component: ^1.5.2 => 1.5.3 
    @types/react-redux: ^7.1.25 => 7.1.25 
    @types/stylis: ^4.0.2 => 4.2.0 
    @types/uuid: ^9.0.3 => 9.0.3 
    @typescript-eslint/eslint-plugin: ^5.52.0 => 5.62.0 
    @typescript-eslint/parser: ^5.52.0 => 5.62.0 
    apexcharts: ^3.42.0 => 3.43.0 
    autosuggest-highlight: ^3.3.4 => 3.3.4 
    aws-amplify: ^6.0.6 => 6.0.6 
    aws-amplify/adapter-core:  undefined ()
    aws-amplify/analytics:  undefined ()
    aws-amplify/analytics/kinesis:  undefined ()
    aws-amplify/analytics/kinesis-firehose:  undefined ()
    aws-amplify/analytics/personalize:  undefined ()
    aws-amplify/analytics/pinpoint:  undefined ()
    aws-amplify/api:  undefined ()
    aws-amplify/api/server:  undefined ()
    aws-amplify/auth:  undefined ()
    aws-amplify/auth/cognito:  undefined ()
    aws-amplify/auth/cognito/server:  undefined ()
    aws-amplify/auth/server:  undefined ()
    aws-amplify/datastore:  undefined ()
    aws-amplify/in-app-messaging:  undefined ()
    aws-amplify/in-app-messaging/pinpoint:  undefined ()
    aws-amplify/push-notifications:  undefined ()
    aws-amplify/push-notifications/pinpoint:  undefined ()
    aws-amplify/storage:  undefined ()
    aws-amplify/storage/s3:  undefined ()
    aws-amplify/storage/s3/server:  undefined ()
    aws-amplify/storage/server:  undefined ()
    aws-amplify/utils:  undefined ()
    axios: ^1.3.3 => 1.4.0 
    change-case: ^4.1.2 => 4.1.2 
    cypress: ^13.5.0 => 13.5.0 
    date-fns: ^2.29.3 => 2.30.0 
    date-fns-tz: ^2.0.0 => 2.0.0 
    eslint: ^8.55.0 => 8.55.0 
    eslint-config-airbnb: 19.0.4 => 19.0.4 
    eslint-config-airbnb-typescript: ^17.0.0 => 17.0.0 
    eslint-config-prettier: ^8.6.0 => 8.8.0 
    eslint-config-react-app: ^7.0.1 => 7.0.1 
    eslint-import-resolver-typescript: ^3.5.3 => 3.5.5 
    eslint-plugin-flowtype: ^8.0.3 => 8.0.3 
    eslint-plugin-import: ^2.27.5 => 2.27.5 
    eslint-plugin-jsx-a11y: ^6.7.1 => 6.7.1 
    eslint-plugin-prettier: ^4.2.1 => 4.2.1 
    eslint-plugin-react: ^7.32.2 => 7.32.2 
    eslint-plugin-react-hooks: ^4.6.0 => 4.6.0 
    framer-motion: ^9.0.4 => 9.1.7 
    history: ^5.3.0 => 5.3.0 
    i18next: ^22.4.10 => 22.5.1 
    i18next-browser-languagedetector: ^7.0.1 => 7.0.2 
    immer: ^9.0.21 => 9.0.21 (9.0.6)
    lodash-es: ^4.17.21 => 4.17.21 
    mui-one-time-password-input: ^1.1.1 => 1.1.1 
    notistack: ^2.0.8 => 2.0.8 
    nprogress: ^0.2.0 => 0.2.0 
    numeral: ^2.0.6 => 2.0.6 
    prettier: ^2.8.4 => 2.8.8 
    react: ^18.2.0 => 18.2.0 
    react-apexcharts: ^1.4.1 => 1.4.1 
    react-dom: ^18.2.0 => 18.2.0 
    react-helmet-async: ^1.3.0 => 1.3.0 
    react-hook-form: ^7.43.1 => 7.44.3 
    react-hook-form-mui: ^6.1.1 => 6.2.0 
    react-i18next: ^12.1.5 => 12.3.1 
    react-lazy-load-image-component: ^1.5.6 => 1.6.0 
    react-markdown: ^8.0.7 => 8.0.7 
    react-redux: ^8.0.5 => 8.1.0 
    react-router: ^6.8.1 => 6.13.0 
    react-router-dom: ^6.8.1 => 6.13.0 
    react-scripts: ^5.0.0 => 5.0.1 
    redux: ^4.2.1 => 4.2.1 
    redux-persist: ^6.0.0 => 6.0.0 
    redux-persist/integration/react:  undefined ()
    rehype-highlight: ^6.0.0 => 6.0.0 
    rehype-raw: ^6.1.1 => 6.1.1 
    remark-directive: ^2.0.1 => 2.0.1 
    remark-gfm: ^3.0.1 => 3.0.1 
    serve: ^14.2.1 => 14.2.1 
    simplebar-react: ^3.2.1 => 3.2.4 
    source-map-explorer: ^2.5.3 => 2.5.3 
    stylis: ^4.1.3 => 4.2.0 
    stylis-plugin-rtl: ^2.1.1 => 2.1.1 
    typescript: ^4.9.5 => 4.9.5 
    uuid: ^9.0.0 => 9.0.0 (8.3.2)
    web-vitals: ^3.1.1 => 3.3.2 
    yup: ^1.2.0 => 1.2.0 
  npmGlobalPackages:
    @aws-amplify/cli: 12.3.0
    @prosemirror-adapter/core: 0.2.6
    corepack: 0.15.3
    create-react-app: 5.0.1
    date-fns: 2.30.0
    lodash-es: 4.17.21
    nodemon: 2.0.22
    npm: 9.7.1
    parcel-bundler: 1.12.5
    pnpm: 8.3.1
    prettier: 2.8.7
    ts-node: 10.9.1



```

</details>

### Describe the bug

In latest Amplify version, both DataStore and GraphQL client not working in Service Worker environment.

* After first running `Amplify.configure(...);`
  * For DataStore, when calling `await DataStore.query(...)` it throws exception that `window is not found in its execution`
  * For GraphQL client, when calling `client.graphql(...)` it always throws error that user is not login, even though I already signed in user in main thread.

So I want to confirm current support status for running these two library in Service Worker environments.
From issue #4943 , there is still no official document answering the support status, but developers do need a clear response, thanks! 

### Expected behavior

both DataStore and GraphQL client should work in Service Worker environment.

### Reproduction steps

ditto

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
Hello, @sjdeak 👋.  Just to clarify, were they working on a v5 app that you upgraded recently to v6?  If so, just want to make sure you've updated the import paths to align with what is seen in the [v6 docs](https://docs.amplify.aws/react/build-a-backend/utilities/service-worker/) for Service Workers. Either way I'll review this with the team along with the related feature request you linked and report back!

**Comment by sjdeak** [comment]
Hi @cwomack thanks for the reply. 
* I confirmed that DataStore works for v5 and failed in v6, for GraphQL client I didn't use that in v5 so not sure the behavior.
* For "just want to make sure you've updated the import paths to align with what is seen in the [v6 docs](https://docs.amplify.aws/react/build-a-backend/utilities/service-worker/) for Service Workers."
We didn't use ServiceWorker utils to register a service worker, we use our own register logic to register our service worker. And the issue is when try using Amplify's DataStore and GraphQL client in our Service Worker scripts they didn't work as expected.

**Comment by renebrandel** [comment]
> For GraphQL client, when calling client.graphql(...) it always throws error that user is not login, even though I already signed in user in main thread.

@sjdeak - can you confirm you've passed in `authMode: 'userPool'` in the request for client.graphql()? 

Separately, we'll try to dive deeper on the DataStore issue.

**Comment by alex-breen** [comment]
I have encountered a similar issue. 

I am running a plain web worker - https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers .
The worker script runs DataStore queries. 

Worked well on aws-amplify 5.3.11. But after upgrading to aws-amplify 6.0.10 (and updating dependency imports), I receive the following error:
`index.ts:5 Uncaught (in promise) ReferenceError: window is not defined
    at getDefaultAdapter (index.ts:5:1)
    at new StorageClass (storage.ts:20:1)
    at new ExclusiveStorage (storage.ts:289:1)
    at datastore.ts:1058:1
    at BackgroundProcessManager.addFunction (BackgroundProcessManager.ts:87:1)
    at BackgroundProcessManager.add (BackgroundProcessManager.ts:51:1)
    at DataStore.start (datastore.ts:1044:1)
    at datastore.ts:1104:1
    at BackgroundProcessManager.addFunction (BackgroundProcessManager.ts:87:1)
    at BackgroundProcessManager.add (BackgroundProcessManager.ts:51:1)`

**Comment by alex-breen** [comment]
Update: Based on the very helpful recommendation by @chrisbonifacio and @cwomack from the Amplify team, I implemented a  polyfill for "window". DataStore runs without error inside a web worker using the polyfill.  Thanks!

I used "node-window-polyfill" - https://www.npmjs.com/package/node-window-polyfill  in the web worker.

**Comment by cwomack** [comment]
Glad to hear you're unblocked @alex-breen, and thanks for coming to the Discord Office Hours! 

@sjdeak, can you confirm if you've passed in authMode: 'userPool' in the request for `client.graphql()` (per @renebrandel's comment above)? And are you using a service worker to intercept fetch requests? I'm curious to know if the events are being sent to the service worker which is then trying to use Amplify _within_ it, or if this outside it.

**Comment by sjdeak** [comment]
Hi @cwomack thanks for the response, we just migrated off all Amplify code from our Service Worker, so it's hard to reproduce that, please skip the issue of GraphQL client until next issue requester and only track the fix of DataStore in this issue, thank you!
