### ISSUE TITLE
v6 `fetchAuthSession` failed to refresh access token 

### ISSUE THREAD

**Issue by gokaten-token** [aws-amplify/amplify-js#12778]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native With Expo

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
  System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1
    Memory: 79.20 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.0 - ~/.nodebrew/current/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.1.0 - ~/.nodebrew/current/bin/npm
    Watchman: 2023.10.02.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 120.0.6099.129
    Safari: 16.5
  npmPackages:
    @aws-amplify/react-native: ^1.0.6 => 1.0.6 
    @aws-amplify/rtn-web-browser: ^1.0.6 => 1.0.6 
    @aws-amplify/ui-react-native: ^2.0.4 => 2.0.4 
    @babel/core: ^7.20.0 => 7.23.5 
    @expo/webpack-config: ^19.0.0 => 19.0.0 
    @react-native-async-storage/async-storage: ^1.21.0 => 1.21.0 
    @react-native-community/netinfo: ^11.2.0 => 11.2.0 
    @types/react: ~18.2.14 => 18.2.42 
    HelloWorld:  0.0.1 
    aws-amplify: ^6.0.9 => 6.0.9 
    aws-amplify/adapter-core:  undefined ()
    aws-amplify/analytics:  undefined ()
    aws-amplify/analytics/kinesis:  undefined ()
    aws-amplify/analytics/kinesis-firehose:  undefined ()
    aws-amplify/analytics/personalize:  undefined ()
    aws-amplify/analytics/pinpoint:  undefined ()
    aws-amplify/api:  undefined ()
    aws-amplify/api/server:  undefined ()
    aws-amplify/auth:  undefined ()
    aws-amplify/auth/cognito:  undefined ()
    aws-amplify/auth/cognito/server:  undefined ()
    aws-amplify/auth/server:  undefined ()
    aws-amplify/datastore:  undefined ()
    aws-amplify/in-app-messaging:  undefined ()
    aws-amplify/in-app-messaging/pinpoint:  undefined ()
    aws-amplify/push-notifications:  undefined ()
    aws-amplify/push-notifications/pinpoint:  undefined ()
    aws-amplify/storage:  undefined ()
    aws-amplify/storage/s3:  undefined ()
    aws-amplify/storage/s3/server:  undefined ()
    aws-amplify/storage/server:  undefined ()
    aws-amplify/utils:  undefined ()
    expo: ~49.0.15 => 49.0.21 
    expo-status-bar: ~1.6.0 => 1.6.0 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    react-native: 0.72.6 => 0.72.6 
    react-native-get-random-values: ^1.10.0 => 1.10.0 
    react-native-safe-area-context: ^4.7.4 => 4.7.4 
    react-native-url-polyfill: ^2.0.0 => 2.0.0 
    react-native-vector-icons: ^10.0.2 => 10.0.2 
    react-native-web: ~0.19.6 => 0.19.9 
    typescript: ^5.1.3 => 5.3.2 
  npmGlobalPackages:
    @aws-amplify/cli: 12.8.2
    corepack: 0.20.0
    ios-deploy: 1.12.2
    npm: 10.1.0
```

</details>

### background

**frontend**
We created an sample app with expo and run with web. `npm run web`

**backend**
We followed the [document](https://docs.amplify.aws/react-native/build-a-backend/auth/set-up-auth/) and our cognito app setting has `ALLOW_REFRESH_TOKEN_AUTH` enabled.
We added Google Provider for authentication in our app.
The refresh token expiration is set to 60min, and access token expiration is set to 5min.

### Problem

We can sign in with Google Provider, and `fetchAuthSession` will get the current session if access token is not expired.

However if access token is expired, or call `fetchAuthSession({ forceRefresh: true }))`, the access token will not be refreshed, and shows following error in console:
```
Uncaught (in promise) UserUnAuthenticatedException: User needs to be authenticated to call this API.
    at assertAuthTokensWithRefreshToken (http://localhost:19006/static/js/bundle.js:92630:15)
    at refreshAuthTokens (http://localhost:19006/static/js/bundle.js:89719:81)
    at TokenOrchestrator.refreshTokens (http://localhost:19006/static/js/bundle.js:88359:61)
    at TokenOrchestrator.getTokens (http://localhost:19006/static/js/bundle.js:88343:33)
    at async AuthClass.getTokens (http://localhost:19006/static/js/bundle.js:95656:18)
    at async AuthClass.fetchAuthSession (http://localhost:19006/static/js/bundle.js:95622:18)
```

A bit dig into the `assertAuthTokensWithRefreshToken` and find it checks with
```js
if (!tokens || !tokens.accessToken || !tokens.refreshToken)
```

We suspect the refreshToken is not being maintained under the hood in our expo app, since v6 removed the `refreshToken`.

### Expected behavior

`fetchAuthSession({ forceRefresh: true }))` should refresh the access token.

### Reproduction steps

1. Create an expo app `npx create-expo-app MyApp -t expo-template-blank-typescript`
2. Fix a known issue of expo by modifying the `webpack.config.js`. https://github.com/expo/expo/issues/22989#issuecomment-1646646661
3. Pull the app settings `amplify pull --appId [appID] --envName dev`
4. Use the [sample code](https://docs.amplify.aws/react-native/build-a-backend/auth/add-social-provider/#set-up-your-frontend) to modify App.tsx

### Code Snippet

App.tsx
```typescript
import React, { useEffect, useState } from "react";
import { Button, SafeAreaView, Text } from "react-native";

import { Amplify } from "aws-amplify";

import awsExports from "./src/aws-exports";
import {
  AuthUser,
  fetchAuthSession,
  getCurrentUser,
  signInWithRedirect,
  signOut,
} from "aws-amplify/auth";
import { Hub } from "aws-amplify/utils";
Amplify.configure(awsExports);


function App() {
  const [user, setUser] = useState<AuthUser | null>(null);
  const [customState, setCustomState] = useState<string | null>(null);

  useEffect(() => {
    const unsubscribe = Hub.listen("auth", ({ payload }) => {
      switch (payload.event) {
        case "signInWithRedirect":
          getUser();
          break;
        case "signInWithRedirect_failure":
          console.error("An error has ocurred during the OAuth flow.");
          break;
        case "tokenRefresh":
          console.log("auth tokens have been refreshed.");
          break;
        case "tokenRefresh_failure":
          console.log("failure while refreshing auth tokens.");
          break;
        case "customOAuthState":
          console.log(payload.data);
          setCustomState(payload.data); // this is the customState provided on signInWithRedirect function
          break;
      }
    });

    getUser();

    return unsubscribe;
  }, []);

  const getUser = async (): Promise<void> => {
    try {
      const currentUser = await getCurrentUser();
      setUser(currentUser);
      const { accessToken } = (await fetchAuthSession()).tokens ?? {};
      console.log(accessToken);
    } catch (error) {
      console.error(error);
      console.log("Not signed in");
    }
  };

  return (
    <SafeAreaView>
      <Button
        title="Sign In"
        onPress={() => signInWithRedirect({ provider: "Google" })}
      ></Button>
      <Text>{user?.username}</Text>
      <Button title="Sign Out" onPress={() => signOut()}></Button>
      <Button
        title="Get new Token"
        onPress={async () => {
          const { accessToken } =
            (await fetchAuthSession({ forceRefresh: true })).tokens ?? {};
          console.log(accessToken);
        }}
      />
    </SafeAreaView>
  );
}

export default App;
```

### Log output

<details>

```
Uncaught (in promise) UserUnAuthenticatedException: User needs to be authenticated to call this API.
    at assertAuthTokensWithRefreshToken (http://localhost:19006/static/js/bundle.js:92630:15)
    at refreshAuthTokens (http://localhost:19006/static/js/bundle.js:89719:81)
    at TokenOrchestrator.refreshTokens (http://localhost:19006/static/js/bundle.js:88359:61)
    at TokenOrchestrator.getTokens (http://localhost:19006/static/js/bundle.js:88343:33)
    at async AuthClass.getTokens (http://localhost:19006/static/js/bundle.js:95656:18)
    at async AuthClass.fetchAuthSession (http://localhost:19006/static/js/bundle.js:95622:18)
```

</details>

### aws-exports.js

```js
const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_[user_pool_id]",
    "aws_user_pools_web_client_id": "[web_client_id]",
    "oauth": {
        "domain": "[my_app].auth.ap-northeast-1.amazoncognito.com",
        "scope": [
            "email",
            "openid",
            "phone"
        ],
        "redirectSignIn": "http://localhost:19006,https://localhost:3000",
        "redirectSignOut": "http://localhost:19006",
        "responseType": "token"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_UPPERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
```

### Additional configuration

aws cognito-idp describe-user-pool --user-pool-id [user-pool-id]
```json
{
    "UserPool": {
        "Id": "ap-northeast-1_[user-pool-id]",
        "Name": "[app_name]",
        "Policies": {
            "PasswordPolicy": {
                "MinimumLength": 8,
                "RequireUppercase": true,
                "RequireLowercase": true,
                "RequireNumbers": true,
                "RequireSymbols": true,
                "TemporaryPasswordValidityDays": 7
            }
        },
        "DeletionProtection": "ACTIVE",
        "LambdaConfig": {},
        "LastModifiedDate": "2023-12-05T20:24:23.640000+09:00",
        "CreationDate": "2023-12-05T20:24:23.640000+09:00",
        "SchemaAttributes": [
            {
                "Name": "sub",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": false,
                "Required": true,
                "StringAttributeConstraints": {
                    "MinLength": "1",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "given_name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "family_name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "middle_name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "nickname",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "preferred_username",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "profile",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "picture",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "website",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "email",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": true,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "email_verified",
                "AttributeDataType": "Boolean",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false
            },
            {
                "Name": "gender",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "birthdate",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "10",
                    "MaxLength": "10"
                }
            },
            {
                "Name": "zoneinfo",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "locale",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "phone_number",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "phone_number_verified",
                "AttributeDataType": "Boolean",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false
            },
            {
                "Name": "address",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "updated_at",
                "AttributeDataType": "Number",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "NumberAttributeConstraints": {
                    "MinValue": "0"
                }
            },
            {
                "Name": "identities",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {}
            }
        ],
        "AutoVerifiedAttributes": [
            "email"
        ],
        "UsernameAttributes": [
            "email"
        ],
        "VerificationMessageTemplate": {
            "DefaultEmailOption": "CONFIRM_WITH_CODE"
        },
        "UserAttributeUpdateSettings": {
            "AttributesRequireVerificationBeforeUpdate": [
                "email"
            ]
        },
        "MfaConfiguration": "OFF",
        "EstimatedNumberOfUsers": 3,
        "EmailConfiguration": {
            "EmailSendingAccount": "COGNITO_DEFAULT"
        },
        "UserPoolTags": {},
        "Domain": "[domain]",
        "AdminCreateUserConfig": {
            "AllowAdminCreateUserOnly": true,
            "UnusedAccountValidityDays": 7
        },
        "UsernameConfiguration": {
            "CaseSensitive": false
        },
        "Arn": "[arn endpoint]",
        "AccountRecoverySetting": {
            "RecoveryMechanisms": [
                {
                    "Priority": 1,
                    "Name": "verified_email"
                }
            ]
        }
    }
}

```

### Additional information and screenshots

**before signin**

![image](https://github.com/aws-amplify/amplify-js/assets/148519697/dc8158ab-4f56-4160-8ad6-77569aff3d4f)

**after signin**

![image](https://github.com/aws-amplify/amplify-js/assets/148519697/3e8d660f-223c-422f-8a9c-27f57df1ad01)

![image](https://github.com/aws-amplify/amplify-js/assets/148519697/066ebb2b-2623-4765-8770-ad49d4cba66c)

**after get token (force refresh)**

![image](https://github.com/aws-amplify/amplify-js/assets/148519697/b69b4293-73e6-4bb5-902a-0feb8951ae58)

![image](https://github.com/aws-amplify/amplify-js/assets/148519697/f7381204-0862-46be-8eee-97ce08264adc)

**Comment by cwomack** [comment]
@gokaten-token, thank you for opening this issue and providing so much context, screenshots, and error logs.  This is a known bug that we are tracking in issue #12749, and we will provide updates on that one going forward.  

I've already commented/linked these issues together on our side, but please follow #12749 to provide additional comments and see any progress made on fix.  Thanks!

**Comment by cwomack** [comment]
@gokaten-token, within that other issue there's a temporary workaround detailed in [this comment](https://github.com/aws-amplify/amplify-js/issues/12749#issuecomment-1872238799).  We're working on a fix, but let us know if that helps until a fix is released!
