### ISSUE TITLE
Array of strings in redirectSignIn and redirectSignOut causes redirectStr?.split is not a function

### ISSUE THREAD

**Issue by carlosLMZarego** [aws-amplify/amplify-js#12972]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

Authentication

### Amplify Version

v6

### Amplify Categories

auth

### Backend

None

### Environment information

<details>

```
# Put output below this line
 System:
    OS: macOS 12.6.8
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 3.59 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.10.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 7.13.2 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 121.0.6167.139
    Safari: 16.6
  npmPackages:
    @ampproject/toolbox-optimizer:  undefined ()
    @aws-amplify/core: ^6.0.13 => 6.0.13 
    @aws-amplify/core/internals/adapter-core:  undefined ()
    @aws-amplify/core/internals/aws-client-utils:  undefined ()
    @aws-amplify/core/internals/aws-client-utils/composers:  undefined ()
    @aws-amplify/core/internals/aws-clients/cognitoIdentity:  undefined ()
    @aws-amplify/core/internals/aws-clients/pinpoint:  undefined ()
    @aws-amplify/core/internals/providers/pinpoint:  undefined ()
    @aws-amplify/core/internals/utils:  undefined ()
    @aws-amplify/core/server:  undefined ()
    @aws-amplify/ui-react: ^6.1.2 => 6.1.2 
    @aws-amplify/ui-react-internal:  undefined ()
    @babel/core:  undefined ()
    @babel/runtime:  7.22.5 
    @edge-runtime/cookies:  4.0.2 
    @edge-runtime/ponyfill:  2.4.1 
    @edge-runtime/primitives:  4.0.2 
    @emotion/react: ^11.11.3 => 11.11.3 
    @hapi/accept:  undefined ()
    @mswjs/interceptors:  undefined ()
    @napi-rs/triples:  undefined ()
    @next/font:  undefined ()
    @next/react-dev-overlay:  undefined ()
    @opentelemetry/api:  undefined ()
    @segment/ajv-human-errors:  undefined ()
    @types/node: ^20 => 20.11.16 
    @types/react: ^18 => 18.2.55 
    @types/react-dom: ^18 => 18.2.18 
    @vercel/nft:  undefined ()
    @vercel/og:  0.5.15 
    acorn:  undefined ()
    amphtml-validator:  undefined ()
    anser:  undefined ()
    arg:  undefined ()
    assert:  undefined ()
    async-retry:  undefined ()
    async-sema:  undefined ()
    autoprefixer: ^10.0.1 => 10.4.17 
    aws-amplify: ^6.0.13 => 6.0.13 
    aws-amplify/adapter-core:  undefined ()
    aws-amplify/analytics:  undefined ()
    aws-amplify/analytics/kinesis:  undefined ()
    aws-amplify/analytics/kinesis-firehose:  undefined ()
    aws-amplify/analytics/personalize:  undefined ()
    aws-amplify/analytics/pinpoint:  undefined ()
    aws-amplify/api:  undefined ()
    aws-amplify/api/server:  undefined ()
    aws-amplify/auth:  undefined ()
    aws-amplify/auth/cognito:  undefined ()
    aws-amplify/auth/cognito/server:  undefined ()
    aws-amplify/auth/enable-oauth-listener:  undefined ()
    aws-amplify/auth/server:  undefined ()
    aws-amplify/datastore:  undefined ()
    aws-amplify/in-app-messaging:  undefined ()
    aws-amplify/in-app-messaging/pinpoint:  undefined ()
    aws-amplify/push-notifications:  undefined ()
    aws-amplify/push-notifications/pinpoint:  undefined ()
    aws-amplify/storage:  undefined ()
    aws-amplify/storage/s3:  undefined ()
    aws-amplify/storage/s3/server:  undefined ()
    aws-amplify/storage/server:  undefined ()
    aws-amplify/utils:  undefined ()
    axios: ^1.6.5 => 1.6.7 
    babel-packages:  undefined ()
    browserify-zlib:  undefined ()
    browserslist:  undefined ()
    buffer:  undefined ()
    bytes:  undefined ()
    ci-info:  undefined ()
    cli-select:  undefined ()
    client-only:  0.0.1 
    comment-json:  undefined ()
    compression:  undefined ()
    conf:  undefined ()
    constants-browserify:  undefined ()
    content-disposition:  undefined ()
    content-type:  undefined ()
    cookie:  undefined ()
    cross-spawn:  undefined ()
    crypto-browserify:  undefined ()
    css.escape:  undefined ()
    data-uri-to-buffer:  undefined ()
    debug:  undefined ()
    devalue:  undefined ()
    domain-browser:  undefined ()
    edge-runtime:  undefined ()
    eslint: ^8 => 8.56.0 
    eslint-config-next: 14.0.4 => 14.0.4 
    events:  undefined ()
    find-cache-dir:  undefined ()
    find-up:  undefined ()
    fresh:  undefined ()
    get-orientation:  undefined ()
    glob:  undefined ()
    gzip-size:  undefined ()
    http-proxy:  undefined ()
    http-proxy-agent:  undefined ()
    https-browserify:  undefined ()
    https-proxy-agent:  undefined ()
    icss-utils:  undefined ()
    ignore-loader:  undefined ()
    image-size:  undefined ()
    is-animated:  undefined ()
    is-docker:  undefined ()
    is-wsl:  undefined ()
    jest-worker:  undefined ()
    json5:  undefined ()
    jsonwebtoken:  undefined ()
    loader-runner:  undefined ()
    loader-utils:  undefined ()
    lodash.curry:  undefined ()
    lru-cache:  undefined ()
    micromatch:  undefined ()
    mini-css-extract-plugin:  undefined ()
    nanoid:  undefined ()
    native-url:  undefined ()
    neo-async:  undefined ()
    next: 14.0.4 => 14.0.4 
    node-fetch:  undefined ()
    node-html-parser:  undefined ()
    ora:  undefined ()
    os-browserify:  undefined ()
    p-limit:  undefined ()
    path-browserify:  undefined ()
    platform:  undefined ()
    postcss: ^8 => 8.4.34 (8.4.31)
    postcss-flexbugs-fixes:  undefined ()
    postcss-modules-extract-imports:  undefined ()
    postcss-modules-local-by-default:  undefined ()
    postcss-modules-scope:  undefined ()
    postcss-modules-values:  undefined ()
    postcss-preset-env:  undefined ()
    postcss-safe-parser:  undefined ()
    postcss-scss:  undefined ()
    postcss-value-parser:  undefined ()
    process:  undefined ()
    punycode:  undefined ()
    querystring-es3:  undefined ()
    raw-body:  undefined ()
    react: ^18 => 18.2.0 
    react-builtin:  undefined ()
    react-dom: ^18 => 18.2.0 
    react-dom-builtin:  undefined ()
    react-dom-experimental-builtin:  undefined ()
    react-experimental-builtin:  undefined ()
    react-is:  18.2.0 
    react-refresh:  0.12.0 
    react-server-dom-turbopack-builtin:  undefined ()
    react-server-dom-turbopack-experimental-builtin:  undefined ()
    react-server-dom-webpack-builtin:  undefined ()
    react-server-dom-webpack-experimental-builtin:  undefined ()
    regenerator-runtime:  0.13.4 
    sass-loader:  undefined ()
    scheduler-builtin:  undefined ()
    scheduler-experimental-builtin:  undefined ()
    schema-utils:  undefined ()
    semver:  undefined ()
    send:  undefined ()
    server-only:  0.0.1 
    setimmediate:  undefined ()
    shell-quote:  undefined ()
    source-map:  undefined ()
    stacktrace-parser:  undefined ()
    stream-browserify:  undefined ()
    stream-http:  undefined ()
    string-hash:  undefined ()
    string_decoder:  undefined ()
    strip-ansi:  undefined ()
    superstruct:  undefined ()
    tailwindcss: ^3.3.0 => 3.4.1 
    tar:  undefined ()
    terser:  undefined ()
    text-table:  undefined ()
    timers-browserify:  undefined ()
    tty-browserify:  undefined ()
    typescript: ^5 => 5.3.3 
    ua-parser-js:  undefined ()
    unistore:  undefined ()
    util:  undefined ()
    vm-browserify:  undefined ()
    watchpack:  undefined ()
    web-vitals:  undefined ()
    webpack:  undefined ()
    webpack-sources:  undefined ()
    ws:  undefined ()
    zod:  undefined ()
  npmGlobalPackages:
    corepack: 0.22.0
    npm: 10.2.3
    yarn: 1.22.21

```

</details>

### Describe the bug

My Cognito user pool has configured oauth with several redirectSignIn urls, after update the aws-exports.js running amplify pull I get something like this

```js
  oauth: {
    domain: "xxx",
    scope: [
      "aws.cognito.signin.user.admin",
      "cognito-test-api/read",
      "email",
      "openid",
      "profile",
    ],
    redirectSignIn: [
      "http://localhost:3000/",
      "https://amplify-config.xxx.amplifyapp.com/",
    ],
    redirectSignOut: [
      "http://localhost:3000/",
      "https://amplify-config.xxx.amplifyapp.com/",
    ],
    responseType: "token",
  }
```

I initialize Amplify.configure like this:

```tsx
"use client";

import React, { FunctionComponent } from "react";
import { Authenticator } from "@aws-amplify/ui-react";
import { Amplify } from "aws-amplify";
import awsconfig from "@/aws-exports";

Amplify.configure(awsconfig, { ssr: true });

interface OwnProps {
  children: React.ReactNode;
}

type Props = OwnProps;

const Providers: FunctionComponent<Props> = (props) => {
  return <Authenticator.Provider>{props.children}</Authenticator.Provider>;
};

export default Providers;
```

after try adding and removing "use client", setting the ssr to true and false...all these configurations failed, I notice that if I replace the redirectSignIn in my ```aws-exports.js``` file to a single string instead of an array of urls the problem is solved...

everything fails, the dev server and the build, but with different erros ( I included them in the Log output section)

### Expected behavior

```Amplify.configure``` must work using  an ```aws-exports.js``` file with several oauth/redirectSignIn urls defined as an arry of strings

1. yarn run build and yarn run dev must work

### Reproduction steps

1- Use a Cognito pool with an Oauth Provider like Google, configured in aws console with several redirectSignIn urls
2- run amplify pull to update your aws-exports.js file in your project
3- run yarn run dev or yarn run build

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

***yarn run build** generates this error:
```
yarn run build
yarn run v1.22.21
warning ../../../../../package.json: No license field
$ next build
   ▲ Next.js 14.0.4
   - Environments: .env

(node:43505) [DEP_WEBPACK_MODULE_UPDATE_HASH] DeprecationWarning: Module.updateHash: Use new ChunkGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
 ✓ Creating an optimized production build    
 ✓ Compiled successfully
 ✓ Linting and checking validity of types    
 ✓ Collecting page data    
   Generating static pages (3/5)  [ ===] 
TypeError: e?.split is not a function
    at l (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/.next/server/chunks/139.js:56:17744)
    at u (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/.next/server/chunks/139.js:56:17868)
    at s (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/.next/server/chunks/139.js:56:17138)
    at Object.configure (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/.next/server/chunks/139.js:97:70669)
    at 86768 (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/.next/server/app/page.js:1:3204)
    at t (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/.next/server/webpack-runtime.js:1:142)
    at F (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:91937)
    at $ (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:90488)
    at rC (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:33840)
    at n$ (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:59861)

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: e?.split is not a function
    at l (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/.next/server/chunks/139.js:56:17744)
    at u (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/.next/server/chunks/139.js:56:17868)
    at s (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/.next/server/chunks/139.js:56:17138)
    at Object.configure (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/.next/server/chunks/139.js:97:70669)
    at 86768 (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/.next/server/app/page.js:1:3204)
    at t (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/.next/server/webpack-runtime.js:1:142)
    at F (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:91937)
    at $ (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:90488)
    at rC (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:33840)
    at n$ (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:59861)
TypeError: e?.split is not a function
    at l (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/.next/server/chunks/139.js:56:17744)
    at u (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/.next/server/chunks/139.js:56:17868)
    at s (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/.next/server/chunks/139.js:56:17138)
    at Object.configure (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/.next/server/chunks/139.js:97:70669)
    at 86768 (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/.next/server/app/_not-found.js:1:2953)
    at t (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/.next/server/webpack-runtime.js:1:142)
    at F (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:91937)
    at $ (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:90488)
    at rC (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:33840)
    at n$ (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:59861)

Error occurred prerendering page "/_not-found". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: e?.split is not a function
    at l (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/.next/server/chunks/139.js:56:17744)
    at u (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/.next/server/chunks/139.js:56:17868)
    at s (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/.next/server/chunks/139.js:56:17138)
    at Object.configure (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/.next/server/chunks/139.js:97:70669)
    at 86768 (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/.next/server/app/_not-found.js:1:2953)
    at t (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/.next/server/webpack-runtime.js:1:142)
    at F (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:91937)
    at $ (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:90488)
    at rC (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:33840)
 ✓ Generating static pages (5/5) 

> Export encountered errors on following paths:
        /_not-found
        /page: /
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
and yarn run dev generates this error

```
TypeError: redirectStr?.split is not a function
    at eval (./src/app/Providers.tsx:17:57)
    at (ssr)/./src/app/Providers.tsx (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/.next/server/app/page.js:238:1)
    at __webpack_require__ (/Users/testcomputer/Downloads/proj/zarego/nextcalendar/nextcalendar/.next/server/webpack-runtime.js:33:42)
 
```

</details>

### aws-exports.js

```js
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-west-2",
  aws_cognito_identity_pool_id:
    "us-west-xxx",
  aws_cognito_region: "us-west-2",
  aws_user_pools_id: "us-west-2_pxxx",
  aws_user_pools_web_client_id: "xxx",
  oauth: {
    domain: "xxx-user-pool.auth.us-west-2.amazoncognito.com",
    scope: [
      "aws.cognito.signin.user.admin",
      "cognito-test-api/read",
      "email",
      "openid",
      "profile",
    ],
    redirectSignIn: [
      "http://localhost:3000/",
      "https://amplify-config.123.amplifyapp.com/",
    ],
    redirectSignOut: [
      "http://localhost:3000/",
      "https://amplify-config.123.amplifyapp.com/",
    ],
    responseType: "token",
  },
  federationTarget: "COGNITO_USER_AND_IDENTITY_POOLS",
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: ["GOOGLE"],
  aws_cognito_signup_attributes: ["NAME", "PREFERRED_USERNAME", "EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: [],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: ["REQUIRES_LOWERCASE", "REQUIRES_NUMBERS"],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
};

export default awsmobile;
```

**Comment by jimblanc** [comment]
Thank you for your report! Which version of the Amplify CLI did you use to generate that config file? Additionally, did you modify the file manually to set the redirect URLs? 

The CLI should generate redirect fields that are comma delimitated, for example:
```
"redirectSignIn": "http://localhost:3000/,https://amplify-config.xxx.amplifyapp.com/",
"redirectSignOut": "http://localhost:3000/,https://amplify-config.xxx.amplifyapp.com/",
```

**Comment by nadetastic** [comment]
Hi @carlosLMZarego following up here - were you able to review the comment from @jimblanc above? Let me know if you still need assistance on this or if you were able to get unblocked.
