### ISSUE TITLE
awsmobile start app react failed

### ISSUE THREAD

**Issue by botflow** [aws-amplify/amplify-js#1331]
awsmobile start app react

...

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:443
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

ping mobilehub-snapshot.s3.amazonaws.com
PING mobilehub-snapshot.s3.amazonaws.com (127.0.0.1): 56 data bytes
Request timeout for icmp_seq 0

i don't why mobilehub-snapshot.s3.amazonaws.com ==> 127.0.0.1
but amazonaws.com is resolved ok to 
 ping amazonaws.com
PING amazonaws.com (207.171.166.22): 56 data bytes
64 bytes from 207.171.166.22: icmp_seq=0 ttl=227 time=281.969 ms

my dns is:
nameserver 8.8.8.8
nameserver 4.4.4.4

**Comment by botflow** [comment]
error happened :
#aws-operations/mobile-project-export-manager.js
function downloadCurrentBackendProjectSpec(downloadUrl, projectInfo, callback) {
...
    let request = https.get(downloadUrl, function(response) {
        ...
    }
}

#########

**Comment by botflow** [comment]
fixed:
dns server is the bad guy ....
