### ISSUE TITLE
API: Credentials error handling leads to second request

### ISSUE THREAD

**Issue by cornr** [aws-amplify/amplify-js#1341]
Do you want to request a feature or report a bug?
bug

What is the current behavior?
If you send out a signed request via API Framework and the backend responds with an error another unsigned request is attempted. The former error response is disguised with a "Missing Authentication Token"-Error (403). 

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.
see above

What is the expected behavior?
The 1st error should be returned from `API.get()`-Promise and no unsigned Request should be attempted.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
1.0.4

I expect the error was introduced here:
https://github.com/aws-amplify/amplify-js/commit/a7d9e577b7b247eeeea6055ed6f6181a8e9b4cf1#diff-46bb102733432be4e69c52b10b597244R127
As one can see another request is initiated in the catch block, which would be fine if it belongs only to `Credentials.get() `but the catch block is also executed for error in `._signed()`

**Comment by elorzafe** [comment]
Hi @cornr could you submit a PR to our repo?. You deserve the credit for the fix 💯 

Thanks!

**Comment by cornr** [comment]
@elorzafe thanks. I would do that but I did not figure out how to get the tests running. I would want to add a test for the bug. Is there a "howto" to get the repo working? (sorry I am quite new to web development with all its yarn and npm stuff 😀)

After a "yarn install" I ran RestClient-unit-test.ts in WebStorm and get the following error
```

  ● Test suite failed to run

    Cannot find module '@aws-amplify/core/lib/Signer' from 'RestClient-unit-test.ts'

      37 |         });
      38 |     })
    > 39 | });
      40 | 
      41 | describe('RestClient test', () => {
      42 |     describe('ajax', () => {
      
      at Resolver.resolveModule (../../node_modules/jest-runtime/node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (__tests__/RestClient-unit-test.ts:39:6)

```

**Comment by mikecann** [comment]
Looks like you just beat me to it @cornr goodluck on the PR, its a rather nasty issue that needs fixing 👍

**Comment by cornr** [comment]
Here you are.
I managed to run the tests and added a test.
I was confused with yarn and npm. but "yarn install" "yarn bootstrap" and "yarn build" fixed my problem.
