### ISSUE TITLE
Subscription does not establish from inside jest test

### ISSUE THREAD

**Issue by daveharig** [aws-amplify/amplify-js#13551]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

GraphQL API

### Amplify Version

v6

### Backend

CDK

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 14.5
    CPU: (16) x64 Apple M3 Max
    Memory: 10.95 GB / 128.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.0 - ~/.nvm/versions/node/v20.5.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 9.0.0 - ~/.nvm/versions/node/v20.5.0/bin/npm
    Watchman: 2021.12.06.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 126.0.6478.127
    Firefox: 102.0.1
    Safari: 17.5
  npmPackages:
    esbuild: ^0.15.6 => 0.15.6 
    git: ^0.1.5 => 0.1.5 
    global: ^4.4.0 => 4.4.0 
    latest-version: ^9.0.0 => 9.0.0 
    lerna: ^4.0.0 => 4.0.0 
    webpack-cli: ^4.9.2 => 4.9.2 
  npmGlobalPackages:
    aws-cdk: 2.147.2
    corepack: 0.19.0
    graphql-cli: 4.1.0
    graphql-schema-linter: 3.0.1
    npm-check-updates: 16.14.20
    npm: 9.0.0
    typescript: 5.4.5

```

</details>

### Describe the bug

Subscription does not establish from inside jest test. Queries and mutations do work from inside test. Subscriptions work from inside AWS console. Have tried with both AWS native URL and custom domain. Failing with ConnectionDisrupted.

Similar to this issue: https://github.com/aws-amplify/amplify-js/issues/9769

### Expected behavior

Subscription should go to Connected state

### Reproduction steps

Install Jest and Amplify V6.

Setup API client and login user. 

Attempt to setup subscription.

### Code Snippet

```javascript
import { TestUsers, apiTestSetup } from "../../test-helpers";

import { signOut } from "@aws-amplify/auth";
import { V6Client } from "@aws-amplify/api-graphql";
import {
  GraphQLSubscription,
  CONNECTION_STATE_CHANGE,
  ConnectionState,
} from "@aws-amplify/api";
import { Hub } from "aws-amplify/utils";

describe("test subscription connection", () => {
  let user2ApiClient: V6Client<any>;
  let user2UserId: string;
  let subscription: any;
  let connectionState: ConnectionState | null = null;

  beforeAll(async () => {
    const apiTestSetupResult = await apiTestSetup(TestUsers.User2);
    user2UserId = apiTestSetupResult.userId;
    user2ApiClient = apiTestSetupResult.apiClient;
  }, 10000);

  afterAll(async () => {
    subscription.cancel();
    await signOut();
  });

  it("should establish a subscription", async () => {
    try {
      // Setup listener for subscription state
      const connectionStatePromise = new Promise<void>((resolve) => {
        Hub.listen("api", (data: any) => {
          console.log("data is:", data);
          const { payload } = data;
          if (payload.event === CONNECTION_STATE_CHANGE) {
            connectionState = payload.data.connectionState as ConnectionState;
            console.log("connection state updated to:", connectionState);
            if (connectionState === "Connected") {
              expect(connectionState).toBe("Connected");
              resolve();
            }
          }
        });
      });

      // Start subscription
      subscription = user2ApiClient
        .graphql<GraphQLSubscription<SubscribeToSomethingResultType>>({
          query: subscribeToSomethingCustomQuery,
          variables: { userId: user2UserId },
        })
        .subscribe({
          next: (value: any) => {
            console.log("subscription value received:", value);
            // Assertions within subscription
            expect(value).toBeDefined();
          },
          error: (error: any) => {
            console.error("Subscription error:", error);
          },
        });

      console.log("subscription started:", subscription);

      // Wait for connection state to be "connected"
      await connectionStatePromise;
    } catch (error) {
      throw error;
    }
  }, 30000);
});
```

### Log output

<details>

```
// Put your logs below this line
> jest --runInBand --verbose subscription.test.ts

  console.log
    Subscription started <ref *1> SafeSubscriber {
      initialTeardown: undefined,
      closed: false,
      _parentage: null,
      _finalizers: [
        OperatorSubscriber {
          initialTeardown: undefined,
          closed: false,
          _parentage: [Circular *1],
          _finalizers: [Array],
          isStopped: false,
          destination: [Circular *1],
          onFinalize: undefined,
          shouldUnsubscribe: undefined,
          _next: [Function (anonymous)],
          _error: [Function (anonymous)],
          _complete: [Function (anonymous)]
        }
      ],
      isStopped: false,
      destination: ConsumerObserver {
        partialObserver: { next: [Function: next], error: [Function: error] }
      }
    }

      at Object.<anonymous> (tests/integration-tests/barn/awsSupport.test.ts:94:15)

  console.log
    data is: {
      channel: 'api',
      payload: {
        event: 'ConnectionStateChange',
        data: {
          provider: [AWSAppSyncRealTimeProvider],
          connectionState: 'Connecting'
        },
        message: 'Connection state is Connecting'
      },
      source: 'PubSub',
      patternInfo: []
    }

      at Object.callback (tests/integration-tests/subscription.test.ts:60:19)
          at Array.forEach (<anonymous>)

  console.log
    Connection state updated to: Connecting

      at Object.callback (tests/integration-tests/subscription.test.ts:64:21)
          at Array.forEach (<anonymous>)

  console.log
    data is: {
      channel: 'api',
      payload: {
        event: 'ConnectionStateChange',
        data: {
          provider: [AWSAppSyncRealTimeProvider],
          connectionState: 'ConnectionDisrupted'
        },
        message: 'Connection state is ConnectionDisrupted'
      },
      source: 'PubSub',
      patternInfo: []
    }

      at Object.callback (tests/integration-tests/subscription.test.ts:60:19)
          at Array.forEach (<anonymous>)

  console.log
    Connection state updated to: ConnectionDisrupted

      at Object.callback (tests/integration-tests/subscription.test.ts:64:21)
          at Array.forEach (<anonymous>)

  console.log
    data is: {
      channel: 'api',
      payload: {
        event: 'ConnectionStateChange',
        data: {
          provider: [AWSAppSyncRealTimeProvider],
          connectionState: 'Connecting'
        },
        message: 'Connection state is Connecting'
      },
      source: 'PubSub',
      patternInfo: []
    }

      at Object.callback (tests/integration-tests/subscription.test.ts:60:19)
          at Array.forEach (<anonymous>)

  console.log
    Connection state updated to: Connecting

      at Object.callback (tests/integration-tests/subscription.test.ts:64:21)
          at Array.forEach (<anonymous>)

  console.log
    data is: {
      channel: 'api',
      payload: {
        event: 'ConnectionStateChange',
        data: {
          provider: [AWSAppSyncRealTimeProvider],
          connectionState: 'ConnectionDisrupted'
        },
        message: 'Connection state is ConnectionDisrupted'
      },
      source: 'PubSub',
      patternInfo: []
    }

      at Object.callback (tests/integration-tests/subscription.test.ts:60:19)
          at Array.forEach (<anonymous>)

  console.log
    Connection state updated to: ConnectionDisrupted


```

</details>

### aws-exports.js

```
  AMPLIFY: {
    Auth: {
      Cognito: {
        userPoolId: 'us-east-1_XXXXXXXXX',
        userPoolClientId: 'XXXXXXXXXXXXXXXXXXXX',
        identityPoolId: 'us-east-XXXXXXXXXXXXXXXXX',
      },
    },
    API: {
      GraphQL: {
        endpoint: 'https://api.customdomain.com/graphql',
        defaultAuthMode: 'oidc',
        region: 'us-east-1',
      },
    },
  },
  ```

**Comment by chrisbonifacio** [comment]
Hi @daveharig , I would recommend checking out how we test subscriptions in our library:

https://github.com/aws-amplify/amplify-js/tree/main/packages/api-graphql/__tests__

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!

**Comment by heethjain21** [comment]
Hey @chrisbonifacio , little more context about this problem

This is being run on the server side (nodejs). I came across a post from Chris (not sure if it was you) on the Discord server [this](https://discord.com/channels/705853757799399426/1164929667300593714/1166097407981912084), which states that there is no proper support for subscriptions on the server side, and have replied in the same thread with additional questions

I've also created a new thread on Discord server and added a little more context about the same [here](https://discord.com/channels/705853757799399426/1261637124084469760)
