### ISSUE TITLE
Node.js | Auth.signIn() | "message": "Unknown error, the response body from fetch is: undefined"

### ISSUE THREAD

**Issue by alexchro93** [aws-amplify/amplify-js#1431]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
Calling of Auth.signIn(username, password) results in the following error: 

```
{
  "code": "UnknownError",
  "message": "Unknown error, the response body from fetch is: undefined"
}
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.** 
Node Version - v8.11.2
NPM Version - v5.6.0

package.json
```{
  "name": "cognito",
  "version": "1.0.0",
  "description": "A sample for AWS Cognito",
  "author": "Alex Chrostowski",
  "license": "MIT",
  "scripts": {
    "addUser": "node ./src/add-user.js",
    "loginUser": "node ./src/login-user.js"
  },
  "dependencies": {
    "aws-amplify": "^1.0.5",
    "node-fetch": "^2.2.0",
    "readline-sync": "^1.4.9"
  },
  "devDependencies": {}
}
```
login-user.js
```
const { Auth } = require("aws-amplify");
const readline = require("readline-sync");
global.fetch = require("node-fetch");

const aws_exports = require("./aws-exports");

// Configure
Auth.configure(aws_exports);

// Get desired username and password
const email = readline.question("Email: ");
const password = readline.question("Password: ");

(async () => {
  // Login user
  try {
    const user = await Auth.signIn(email, password);
    console.log(JSON.stringify(user, null, 2));
  } catch (err) {
    handleError(err);
  }
})();

const handleError = (err) => {
  console.log("Error...");
  console.log(JSON.stringify(err, null, 2));
  exit();
}

const exit = () => {
  process.exit(1);
}
```

After some debugging, it was found that the error is being thrown in CognitoUser.js at line 531.
It is caught in Client.js at line 92.

Error details

```
err: ReferenceError: navigator is not defined
message: "navigator is not defined"
stack: "ReferenceError: navigator is not defined
    at /Users/alex/tmp/cognito/node_modules/amazon-cognito-identity-js/lib/CognitoUser.js:531:21
    at /Users/alex/tmp/cognito/node_modules/amazon-cognito-identity-js/lib/AuthenticationHelper.js:177:7
    at BigInteger.bnModPow [as modPow] (/Users/alex/tmp/cognito/node_modules/amazon-cognito-identity-js/lib/BigInteger.js:764:3)
    at AuthenticationHelper.generateHashDevice (/Users/alex/tmp/cognito/node_modules/amazon-cognito-identity-js/lib/AuthenticationHelper.js:171:12)
    at CognitoUser.authenticateUserInternal (/Users/alex/tmp/cognito/node_modules/amazon-cognito-identity-js/lib/CognitoUser.js:513:26)
    at /Users/alex/tmp/cognito/node_modules/amazon-cognito-identity-js/lib/CognitoUser.js:379:27
    at /Users/alex/tmp/cognito/node_modules/amazon-cognito-identity-js/lib/CognitoUser.js:361:22
    at /Users/alex/tmp/cognito/node_modules/amazon-cognito-identity-js/lib/Client.js:80:31
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)"
```

**What is the expected behavior?**
Expected behavior is that Auth.signIn(username, password) completes without throwing any errors

**Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?**
Amplify version is 1.0.5
I'm running these scripts on the command line

**Comment by alexchro93** [comment]
This issue can be averted by providing a global value for userAgent:

```
global.navigator = {
  userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" 
};
```

**Comment by alexchro93** [comment]
@mlabieniec, could you please provide a reason for closing this issue?  Any info would be appreciated.
