### ISSUE TITLE
Amplify Breaks Quick Fixes in VS Code

### ISSUE THREAD

**Issue by tuhinkarmakar** [aws-amplify/amplify-js#1447]
#### Do you want to request a feature or report a bug?
Bug

#### What is the current behavior?
If Amplify (`aws-amplify`) is installed as a dependency of an Angular project (and imported in `main.ts`), quick fixes in VS Code stop working. This issue surfaced after upgrading to VS Code 1.26 (with TypeScript 3.0.1). Removing Amplify from the project fixes the issue. I have also tested with the individual packages i.e. `@aws-amplify/core` et al. Using TypeScript 2.9.2 fixes the quick fix issue but that has its own bug (noted [here](https://github.com/Microsoft/vscode/issues/53894)). Here's the error log from VS Code.
```
'getCodeFixes' request failed with error.Error processing request.
Debug Failure. Error: Debug Failure.
	at Object.assertDefined (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:1435:24)
	at getDefaultExportInfo (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105189:63)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105166:32
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105287:21
	at forEachExternalModule (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105300:21)
	at forEachExternalModuleToImportFrom (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105285:13)
	at getExportInfos (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105161:13)
	at getFixesInfoForNonUMDImport (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105147:57)
	at getFixesInfo (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105085:19)
	at Object.getCodeActions (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:104870:28)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:103896:121
	at Object.flatMap (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:498:25)
	at Object.getFixes (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:103896:23)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:111747:35
	at Object.flatMap (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:498:25)
	at Object.getCodeFixesAtPosition (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:111745:23)
	at IOSession.Session.getCodeFixes (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119339:64)
	at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:118213:61)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119496:88
	at IOSession.Session.executeWithRequestId (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119487:28)
	at IOSession.Session.executeCommand (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119496:33)
	at IOSession.Session.onMessage (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119516:35)
	at Interface. (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:120770:27)
	at emitOne (events.js:116:13)
	at Interface.emit (events.js:211:7)
	at Interface._onLine (readline.js:282:10)
	at Interface._normalWrite (readline.js:424:12)
	at Socket.ondata (readline.js:141:10)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)'getCodeFixes' request failed with error.Error processing request. Debug Failure.Error: Debug Failure.
	at Object.assertDefined (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:1435:24)
	at getDefaultExportInfo (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105189:63)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105166:32
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105287:21
	at forEachExternalModule (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105300:21)
	at forEachExternalModuleToImportFrom (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105285:13)
	at getExportInfos (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105161:13)
	at getFixesInfoForNonUMDImport (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105147:57)
	at getFixesInfo (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105085:19)
	at Object.getCodeActions (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:104870:28)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:103896:121
	at Object.flatMap (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:498:25)
	at Object.getFixes (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:103896:23)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:111747:35
	at Object.flatMap (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:498:25)
	at Object.getCodeFixesAtPosition (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:111745:23)
	at IOSession.Session.getCodeFixes (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119339:64)
	at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:118213:61)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119496:88
	at IOSession.Session.executeWithRequestId (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119487:28)
	at IOSession.Session.executeCommand (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119496:33)
	at IOSession.Session.onMessage (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119516:35)
	at Interface. (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:120770:27)
	at emitOne (events.js:116:13)
	at Interface.emit (events.js:211:7)
	at Interface._onLine (readline.js:282:10)
	at Interface._normalWrite (readline.js:424:12)
	at Socket.ondata (readline.js:141:10)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)'getCodeFixes' request failed with error.Error processing request. Debug Failure.Error: Debug Failure.
	at Object.assertDefined (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:1435:24)
	at getDefaultExportInfo (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105189:63)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105166:32
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105287:21
	at forEachExternalModule (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105300:21)
	at forEachExternalModuleToImportFrom (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105285:13)
	at getExportInfos (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105161:13)
	at getFixesInfoForNonUMDImport (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105147:57)
	at getFixesInfo (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:105085:19)
	at Object.getCodeActions (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:104870:28)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:103896:121
	at Object.flatMap (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:498:25)
	at Object.getFixes (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:103896:23)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:111747:35
	at Object.flatMap (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:498:25)
	at Object.getCodeFixesAtPosition (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:111745:23)
	at IOSession.Session.getCodeFixes (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119339:64)
	at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:118213:61)
	at c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119496:88
	at IOSession.Session.executeWithRequestId (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119487:28)
	at IOSession.Session.executeCommand (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119496:33)
	at IOSession.Session.onMessage (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:119516:35)
	at Interface. (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:120770:27)
	at emitOne (events.js:116:13)
	at Interface.emit (events.js:211:7)
	at Interface._onLine (readline.js:282:10)
	at Interface._normalWrite (readline.js:424:12)
	at Socket.ondata (readline.js:141:10)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

#### What is the expected behavior?
Quick fixes will work even with Amplify added to a project.

#### Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
I have tested with the latest versions of Amplify, TypeScript and VS Code. Yes, it worked before VS Code 1.26. But I can't say its a bug in VS Code as removing Amplify from the project fixes the issue.

**Comment by mlabieniec** [comment]
Looks like this may have been related to a vscode issue. Please feel free to re-open if you are still facing this issue.
