### ISSUE TITLE
Dont work on node because of window

### ISSUE THREAD

**Issue by aldarund** [aws-amplify/amplify-js#1790]
**Describe the bug**
Dont work on node due to use of window obj

**To Reproduce**
```
import Auth from '@aws-amplify/auth'
import Amplify from '@aws-amplify/core'
```

**Expected behavior**
No errors 
**Desktop (please complete the following information):**
Node 10
    "@aws-amplify/auth": "^1.2.5-unstable.3",
    "@aws-amplify/core": "^1.0.14-unstable.0"

**Additional context**
```
ReferenceError: window is not defined
at Object.<anonymous> (C:\Dev\PycharmProjects\dailyidea\front\node_modules\@aws-amplify\core\lib\RNComponents\index.js:24:20)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
at Module.load (internal/modules/cjs/loader.js:599:32)
at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
at Function.Module._load (internal/modules/cjs/loader.js:530:3)
at Module.require (internal/modules/cjs/loader.js:637:17)
at require (internal/modules/cjs/helpers.js:20:18)
at Object.<anonymous> (C:\Dev\PycharmProjects\dailyidea\front\node_modules\@aws-amplify\core\lib\index.js:39:10)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
at Module.load (internal/modules/cjs/loader.js:599:32)
at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
at Function.Module._load (internal/modules/cjs/loader.js:530:3)
at Module.require (internal/modules/cjs/loader.js:637:17)
at require (internal/modules/cjs/helpers.js:20:18)
```

**Comment by aldarund** [comment]
@powerful23 the pr u referenced already in 1.0.14-unstable.0 and it dont fix the issue

**Comment by aldarund** [comment]
The correct way is to ```typeof window !== 'undefined'```
And there is already helper in project for this 
https://github.com/aws-amplify/amplify-js/blob/master/packages/core/src/JS.ts#L152

**Comment by powerful23** [comment]
@aldarund sorry about that. I just approved another pr to fix that #1786

**Comment by aldarund** [comment]
@powerful23 not quite follow, the pr #1786 u referenced now is for totally different piece of code.

**Comment by aaayushsingh** [comment]
@aldarund try using a polyfill. set `global["window"] = {};`

**Comment by aldarund** [comment]
@aaayushsingh zzz. it should be fixed properly on lib level ( e.g. checking for typeof of window), not via hacks in user land code. There could be other libs used as well that check for window properly and setting it like that will  make them think its browser and fail because of it.

**Comment by mlabieniec** [comment]
Amplify is a client side library and we want to stay focused on that (client-side not server-side, browser, mobile, RN etc). Adding actual support for node/server would take **a lot** more than just a global polyfill for example, a fetch polyfill etc and more. So adding a polyfill to just fill this window global object would not give support for node.

**Comment by aldarund** [comment]
Right now im using it only for cognito auth, and it work fine if that check for window fixed properly

**Comment by powerful23** [comment]
@aldarund sorry about that. I submitted another one for this issue.
