### ISSUE TITLE
window is not defined error on next.js project

### ISSUE THREAD

**Issue by psycura** [aws-amplify/amplify-js#1811]
`package.json`

```
{
    "name": "proposalis-aws",
    "scripts": {
        "dev": "node server.js",
        "build": "next build",
        "flow": "flow",
        "start": "NODE_ENV=production node server.js",
        "types": "amplify codegen types",
        "codegen": "amplify codegen",
        "export": "next build && next export",
        "prod": "next build && next start"
    },
    "resolutions": {
        "@aws-amplify/analytics": "1.0.9"
    },
    "dependencies": {
        "@babel/core": "^7.1.2",
        "apollo-boost": "^0.1.16",
        "aws-amplify": "1.1.3",
        "aws-amplify-react": "2.0.4",
        "aws-appsync": "^1.3.5-link-effect.0",
        "aws-appsync-react": "^1.1.5-link-effect.0",
        "axios": "^0.18.0",
        "babel-plugin-inline-react-svg": "0.4.0",
        "body-parser": "^1.18.3",
        "cloudinary": "^1.11.0",
        "compression": "^1.7.3",
        "cors": "^2.8.4",
        "cross-env": "^5.2.0",
        "express": "^4.16.3",
        "express-fileupload": "^1.0.0-alpha.1",
        "form-data": "^2.3.2",
        "formik": "^1.3.0",
        "graphql": "^14.0.2",
        "graphql-tag": "^2.10.0",
        "gsap": "^2.0.2",
        "isomorphic-unfetch": "^3.0.0",
        "lodash": "^4.17.11",
        "mobx": "^5.5.0",
        "mobx-react": "^5.2.8",
        "moment": "^2.22.2",
        "next": "^7.0.1",
        "next-apollo-appsync": "^0.0.7",
        "next-with-apollo": "^3.2.0",
        "node-sass": "^4.9.2",
        "nprogress": "^0.2.0",
        "react": "^16.5.2",
        "react-apollo": "^2.2.3",
        "react-beautiful-dnd": "^9.0.2",
        "react-datepicker": "^1.6.0",
        "react-dom": "^16.5.2",
        "react-icons": "^3.1.0",
        "react-image": "^1.5.1",
        "react-no-ssr": "^1.1.0",
        "react-quill": "^1.3.1",
        "react-sortable-tree": "^2.2.0",
        "react-spinners": "^0.4.5",
        "react-table": "^6.8.6",
        "react-window-size-listener": "^1.2.1",
        "semantic-ui-react": "^0.82.5",
        "shortid": "^2.2.13",
        "styled-components": "^3.4.9",
        "yup": "^0.26.6"
    },
    "devDependencies": {
        "@babel/core": "^7.1.2",
        "@babel/plugin-proposal-class-properties": "^7.0.0",
        "@babel/plugin-proposal-decorators": "^7.1.2",
        "@babel/plugin-transform-flow-strip-types": "^7.0.0",
        "@babel/preset-flow": "^7.0.0",
        "@zeit/next-sass": "^1.0.1",
        "autoprefixer": "^9.1.5",
        "babel-plugin-styled-components": "^1.8.0",
        "babel-plugin-transform-assets-import-to-string": "^1.2.0",
        "babel-plugin-transform-decorators-legacy": "^1.3.5",
        "empty": "^0.10.1",
        "extract-text-webpack-plugin": "^4.0.0-beta.0",
        "flow-bin": "^0.82.0",
        "postcss-easy-import": "^3.0.0",
        "postcss-loader": "^3.0.0"
    }
}
```

Server start ok, but on first page load receive:
```
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/eugenealitz/projects/proposalis-aws/node_modules/@aws-amplify/core/lib/RNComponents/index.js:24:20)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/eugenealitz/projects/proposalis-aws/node_modules/@aws-amplify/core/lib/index.js:39:10)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/eugenealitz/projects/proposalis-aws/node_modules/@aws-amplify/core/lib/RNComponents/index.js:24:20)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/eugenealitz/projects/proposalis-aws/node_modules/@aws-amplify/core/lib/index.js:39:10)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/eugenealitz/projects/proposalis-aws/node_modules/@aws-amplify/core/lib/RNComponents/index.js:24:20)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/eugenealitz/projects/proposalis-aws/node_modules/@aws-amplify/core/lib/index.js:39:10)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/eugenealitz/projects/proposalis-aws/node_modules/@aws-amplify/core/lib/RNComponents/index.js:24:20)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/eugenealitz/projects/proposalis-aws/node_modules/@aws-amplify/core/lib/index.js:39:10)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/eugenealitz/projects/proposalis-aws/node_modules/@aws-amplify/core/lib/RNComponents/index.js:24:20)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/eugenealitz/projects/proposalis-aws/node_modules/@aws-amplify/core/lib/index.js:39:10)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

**Comment by haverchuck** [comment]
@psycura - The Amplify library does not officially support Node.js usage at this point (and I believe Next.js uses server side rendering, yeah?).  You are seeing this error because the library is expecting the window object that is present in the browser.  You can try using a polyfill for the window object, and you might also need to use something like [node-fetch](https://www.npmjs.com/package/node-fetch) as well.

I'm closing this issue for now, but please feel free to re-open if needed.

**Comment by haverchuck** [comment]
@psycura I'm not sure what's being invoked that's causing this, but you might want to try putting it in componentDidMount.  It's my understanding that this would cause the code to be hit in the browser when 'window' is present.

**Comment by psycura** [comment]
I cant use it in componentDidMount because this error happen before component is load, i should init the aws graphql client first, and i cant skip this step.
Strange, but until the last update everything works fine, and i tried to revert back to the previous version, but with no success.

Did you plan to add node.js support in the near feature? This is very crucial for our project

**Comment by haverchuck** [comment]
@psycura -  We are discussing Node / SSR interoperability, yes.  For the moment, can you try the unstable build of Amplify?  It appears that there is a fix that might address your specific issue in `@aws-amplify/core/lib/RNComponents/index.js`

**Comment by powerful23** [comment]
@psycura according to the error, this should have been fixed in #1802

**Comment by haverchuck** [comment]
@akaufmann  The file you cited above has been updated in the aws-amplify '@unstable' build.

**Comment by sakhmedbayev** [comment]
@psycura can you please share your setup of Next.js with amplify? Have you managed to make amplify auth to work with Next.js?
