### ISSUE TITLE
Typescript Issues with `crypto-js`

### ISSUE THREAD

**Issue by mrowles** [aws-amplify/amplify-js#1916]
**Describe the bug**
The `crypto-js` library is forcing a `typescript@2.9.*` compilation error when using `angular@6.*` AOT compilation flag. The error seems to be with the `getJSDocTags` function (see errors below).

I have tried installing `@types/crypto-js`, installing `crypto-js` locally, setting the `allowJs` flag in the `tsconfig.ts` file..no combination seems to work. 

Upgrading to `angular@7` and `typescript@3` does not fix this issue.

There is more discussion going on at the TypeScript register, but thought it should be raised here additionally: 

* https://github.com/Microsoft/TypeScript/issues/25067#issuecomment-429808819
* https://github.com/Microsoft/TypeScript/issues/24963#issuecomment-429803003

**To Reproduce**

1. Setup new angular@6, webpack@4 + typescript@2 project
2. Install aws-amplify + add some auth flow
3. Compile using webpack with AOT flag

**Expected behavior**
I expect the compilation to be successful and production ready JS files are created.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS 10.14

**Smartphone (please complete the following information):**
N/A

**Additional context**

Error logs are as follows:

```
ERROR in ./node_modules/crypto-js/core.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
Error: Debug Failure. False expression.
at getJSDocTags (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:13197:22)
at getFirstJSDocTag (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:13205:24)
at Object.getJSDocTypeTag (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:13154:19)
at checkParenthesizedExpression (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:45628:56)
at checkExpressionWorker (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:45676:28)
at checkExpression (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:45609:42)
at checkBinaryLikeExpression (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:45155:29)
at checkBinaryExpression (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:45147:20)
at checkExpressionWorker (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:45702:28)
at checkExpression (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:45609:42)
at checkExpressionCached (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:45457:38)
at getTypeOfExpression (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:45577:28)
at checkDeclarationInitializer (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:45469:24)
at getTypeForVariableLikeDeclaration (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:30738:28)
at getWidenedTypeForVariableLikeDeclaration (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:30961:24)
at getTypeOfVariableOrParameterOrProperty (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:31062:28)
at getTypeOfSymbol (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:31242:24)
at checkVariableLikeDeclaration (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:47828:41)
at checkVariableDeclaration (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:47891:20)
at checkSourceElement (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:49864:28)
at Object.forEach (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:1792:30)
at checkVariableStatement (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:47901:16)
at checkSourceElement (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:49833:28)
at Object.forEach (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:1792:30)
at checkBlock (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:47521:20)
at checkSourceElement (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:49831:28)
at checkFunctionExpressionOrObjectLiteralMethodDeferred (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:44673:21)
at checkDeferredNodes (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:49977:25)
at checkSourceFileWorker (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:50024:17)
at checkSourceFile (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:49991:13)
at Object.forEach (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:1792:30)
at getDiagnosticsWorker (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:50088:16)
at getDiagnostics (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:50056:24)
at Object.getEmitResolver (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:27241:13)
at emitWorker (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:79066:69)
at /Users/username/workspace/project/node_modules/typescript/lib/typescript.js:79029:66
@ ./node_modules/crypto-js/index.js 5:43-60
@ ./node_modules/amazon-cognito-identity-js/es/AuthenticationHelper.js
@ ./node_modules/amazon-cognito-identity-js/es/index.js
@ ./node_modules/@aws-amplify/auth/lib/index.js
@ ./node_modules/aws-amplify/lib/index.js
@ ./src/app/auth/auth.service.ts
@ ./src/app/app.module.ngfactory.js
@ ./src/main.browser.ts

ERROR in ./node_modules/crypto-js/cipher-core.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
Error: Debug Failure. False expression.
at getJSDocTags (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:13197:22)
at getFirstJSDocTag (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:13205:24)
at Object.getJSDocTypeTag (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:13154:19)
at checkParenthesizedExpression (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:45628:56)
at checkExpressionWorker (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:45676:28)
at checkExpression (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:45609:42)
at checkBinaryLikeExpression (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:45155:29)
at checkBinaryExpression (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:45147:20)
at checkExpressionWorker (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:45702:28)
at checkExpression (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:45609:42)
at checkExpressionCached (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:45457:38)
at getTypeOfExpression (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:45577:28)
at checkDeclarationInitializer (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:45469:24)
at getTypeForVariableLikeDeclaration (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:30738:28)
at getWidenedTypeForVariableLikeDeclaration (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:30961:24)
at getTypeOfVariableOrParameterOrProperty (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:31062:28)
at getTypeOfSymbol (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:31242:24)
at checkVariableLikeDeclaration (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:47828:41)
at checkVariableDeclaration (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:47891:20)
at checkSourceElement (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:49864:28)
at Object.forEach (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:1792:30)
at checkVariableStatement (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:47901:16)
at checkSourceElement (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:49833:28)
at Object.forEach (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:1792:30)
at checkBlock (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:47521:20)
at checkSourceElement (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:49831:28)
at checkFunctionExpressionOrObjectLiteralMethodDeferred (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:44673:21)
at checkDeferredNodes (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:49977:25)
at checkSourceFileWorker (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:50024:17)
at checkSourceFile (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:49991:13)
at Object.forEach (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:1792:30)
at getDiagnosticsWorker (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:50088:16)
at getDiagnostics (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:50056:24)
at Object.getEmitResolver (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:27241:13)
at emitWorker (/Users/username/workspace/project/node_modules/typescript/lib/typescript.js:79066:69)
at /Users/username/workspace/project/node_modules/typescript/lib/typescript.js:79029:66
@ ./node_modules/crypto-js/index.js 5:389-413
@ ./node_modules/amazon-cognito-identity-js/es/AuthenticationHelper.js
@ ./node_modules/amazon-cognito-identity-js/es/index.js
@ ./node_modules/@aws-amplify/auth/lib/index.js
@ ./node_modules/aws-amplify/lib/index.js
@ ./src/app/auth/auth.service.ts
@ ./src/app/app.module.ngfactory.js
@ ./src/main.browser.ts
```

**Comment by mrowles** [comment]
This issue has moved a bit, check out https://github.com/Microsoft/TypeScript/issues/24963#issuecomment-429803003

**Comment by mrowles** [comment]
Resolved with updates, see linked issue
