### ISSUE TITLE
Amplify ui migration #1517 introduce compilation errors

### ISSUE THREAD

**Issue by jason-h-michael** [aws-amplify/amplify-js#2000]
**Describe the bug**
While using ng-packagr, found that there are two references to js functions within ionic templates that do not exist.

```
BUILD ERROR
node_modules/aws-amplify-angular/dist/src/components/authenticator/forgot-password-component/forgot-password.component.ionic.d.ts.ForgotPasswordComponentIonic.html(53,85): : Property 'onResend' does not exist on type 'ForgotP
asswordComponentIonic'. Did you mean 'onSend'?
node_modules/aws-amplify-angular/dist/src/components/authenticator/require-new-password-component/require-new-password.component.ionic.d.ts.RequireNewPasswordComponentIonic.html(11,11): : Property 'username' does not exist on
 type 'RequireNewPasswordComponentIonic'.
node_modules/aws-amplify-angular/dist/src/components/authenticator/require-new-password-component/require-new-password.component.ionic.d.ts.RequireNewPasswordComponentIonic.html(10,11): : Property 'setUsername' does not exist
 on type 'RequireNewPasswordComponentIonic'.
node_modules/aws-amplify-angular/dist/src/components/authenticator/require-new-password-component/require-new-password.component.ionic.d.ts.RequireNewPasswordComponentIonic.html(21,11): : Property 'setCode' does not exist on
type 'RequireNewPasswordComponentIonic'.
node_modules/aws-amplify-angular/dist/src/components/authenticator/require-new-password-component/require-new-password.component.ionic.d.ts.RequireNewPasswordComponentIonic.html(41,7): : Property 'onSend' does not exist on ty
pe 'RequireNewPasswordComponentIonic'.

Error: node_modules/aws-amplify-angular/dist/src/components/authenticator/forgot-password-component/forgot-password.component.ionic.d.ts.ForgotPasswordComponentIonic.html(53,85): : Property 'onResend' does not exist on type '
ForgotPasswordComponentIonic'. Did you mean 'onSend'?
node_modules/aws-amplify-angular/dist/src/components/authenticator/require-new-password-component/require-new-password.component.ionic.d.ts.RequireNewPasswordComponentIonic.html(11,11): : Property 'username' does not exist on
 type 'RequireNewPasswordComponentIonic'.
node_modules/aws-amplify-angular/dist/src/components/authenticator/require-new-password-component/require-new-password.component.ionic.d.ts.RequireNewPasswordComponentIonic.html(10,11): : Property 'setUsername' does not exist
 on type 'RequireNewPasswordComponentIonic'.
node_modules/aws-amplify-angular/dist/src/components/authenticator/require-new-password-component/require-new-password.component.ionic.d.ts.RequireNewPasswordComponentIonic.html(21,11): : Property 'setCode' does not exist on
type 'RequireNewPasswordComponentIonic'.
node_modules/aws-amplify-angular/dist/src/components/authenticator/require-new-password-component/require-new-password.component.ionic.d.ts.RequireNewPasswordComponentIonic.html(41,7): : Property 'onSend' does not exist on ty
pe 'RequireNewPasswordComponentIonic'.

    at analyseEntryPoint (/Users/jmichael/git/custom-web-elements/node_modules/ng-packagr/lib/ng-v5/init/analyse-sources.transform.js:40:15)
    at MapSubscriber.exports.analyseSourcesTransform.rxjs_1.pipe.operators_1.map.graph [as project] (/Users/jmichael/git/custom-web-elements/node_modules/ng-packagr/lib/ng-v5/init/analyse-sources.transform.js:15:9)
    at MapSubscriber._next (/Users/jmichael/git/custom-web-elements/node_modules/ng-packagr/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/Users/jmichael/git/custom-web-elements/node_modules/ng-packagr/node_modules/rxjs/internal/Subscriber.js:67:18)
    at SwitchMapSubscriber.notifyNext (/Users/jmichael/git/custom-web-elements/node_modules/ng-packagr/node_modules/rxjs/internal/operators/switchMap.js:86:26)
    at InnerSubscriber._next (/Users/jmichael/git/custom-web-elements/node_modules/ng-packagr/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/Users/jmichael/git/custom-web-elements/node_modules/ng-packagr/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MapSubscriber._next (/Users/jmichael/git/custom-web-elements/node_modules/ng-packagr/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/Users/jmichael/git/custom-web-elements/node_modules/ng-packagr/node_modules/rxjs/internal/Subscriber.js:67:18)
    at /Users/jmichael/git/custom-web-elements/node_modules/ng-packagr/node_modules/rxjs/internal/util/subscribeToPromise.js:7:24
```

**To Reproduce**
1. Attempt to include aws-angular-amplify npm package in an angular app.
2. Set up ng-packagr per the instructions here:
https://medium.com/@nikolasleblanc/building-an-angular-4-component-library-with-the-angular-cli-and-ng-packagr-53b2ade0701e

**Expected behavior**
Not expecting compilation errors.

**Comment by jordanranz** [comment]
Closing as a fix has seemed to have been made. Please reopen this if you are running into any related issues.
