### ISSUE TITLE
Cannot read property 'line' of null  

### ISSUE THREAD

**Issue by nloui** [aws-amplify/amplify-js#2830]
**Describe the bug**

When building a project with aws-amplify using parcel and running "yarn build", receiving this error:

🚨  /Users/XXXX/Dev/XXXX/XXXX/node_modules/@aws-amplify/ui/dist/aws-amplify-ui.js: Cannot read property 'line' of null
    at SourceMap.originalPositionFor (/Users/XXXX/Dev/XXXX/XXXX/node_modules/parcel-bundler/src/SourceMap.js:309:30)
    at extension.eachMapping.mapping (/Users/XXXX/Dev/XXXX/XXXX/node_modules/parcel-bundler/src/SourceMap.js:153:38)
    at Array.forEach (<anonymous>)
    at SourceMap.eachMapping (/Users/XXXX/Dev/xXXX/XXXX/node_modules/parcel-bundler/src/SourceMap.js:120:19)
    at SourceMap.extendSourceMap (/Users/XXXX/Dev/XXXX/XXXX/node_modules/parcel-bundler/src/SourceMap.js:152:15)
    at module.exports (/Users/XXXX/Dev/XXXX/XXXX/node_modules/parcel-bundler/src/transforms/terser.js:54:47)
error Command failed with exit code 1.

**Expected behavior**

App should build

**Comment by powerful23** [comment]
@nloui Hi, did you run `yarn && yarn bootstrap` before `yarn build`?

**Comment by powerful23** [comment]
@nloui I am going to close this issue. Please let us know if you want to reopen it.
