### ISSUE TITLE
Amplify es5 errors with chrome 41

### ISSUE THREAD

**Issue by mohanrao** [aws-amplify/amplify-js#2940]
Hi,

I am using AWS amplify in angular application.  This application is not working in Chrome 41 (google crawler uses this version). 

Basically i am getting error in the below snippet. Not sure if any polyfills are expected

```
/**
     * transfer the first letter of the keys to lowercase
     * @param {Object} obj - the object need to be transferred
     * @param {Array} whiteListForItself - whitelist itself from being transferred
     * @param {Array} whiteListForChildren - whitelist its children keys from being transferred
     */
    JS.transferKeyToLowerCase = function (obj, whiteListForItself, whiteListForChildren) {
        if (whiteListForItself === void 0) { whiteListForItself = []; }
        if (whiteListForChildren === void 0) { whiteListForChildren = []; }
        if (typeof obj !== 'object' || Array.isArray(obj))
            return obj;
        var ret = {};
        for (var key in obj) {
            if (obj.hasOwnProperty(key)) {
                var transferedKey = whiteListForItself.includes(key) ?
                    key : key[0].toLowerCase() + key.slice(1);
                ret[transferedKey] = whiteListForChildren.includes(key) ?
                    obj[key]
                    :
                        JS.transferKeyToLowerCase(obj[key], whiteListForItself, whiteListForChildren);
            }
        }
        return ret;
    };
```

Error as below

Error: Uncaught (in promise): TypeError: undefined is not a function
TypeError: undefined is not a function
    at Function.push../node_modules/@aws-amplify/core/lib/JS.js.JS.transferKeyToLowerCase (http://localhost:4200/vendor.js:155150:56)
    at AWSPinpointProvider.<anonymous> (http://localhost:4200/vendor.js:142209:67)
    at step (http://localhost:4200/vendor.js:141830:23)
    at Object.push../node_modules/@aws-amplify/analytics/lib/Providers/AWSPinpointProvider.js.f [as next] (http://localhost:4200/vendor.js:141811:53)
    at push../node_modules/@aws-amplify/analytics/lib/Providers/AWSPinpointProvider.js.__awaiter (http://localhost:4200/vendor.js:141805:71)
    at new ZoneAwarePromise (http://localhost:4200/polyfills.js:7206:29)
    at push../node_modules/@aws-amplify/analytics/lib/Providers/AWSPinpointProvider.js.__awaiter (http://localhost:4200/vendor.js:141801:12)
    at AWSPinpointProvider.push../node_modules/@aws-amplify/analytics/lib/Providers/AWSPinpointProvider.js.AWSPinpointProvider._updateEndpoint (http://localhost:4200/vendor.js:142202:16)
    at AWSPinpointProvider.<anonymous> (http://localhost:4200/vendor.js:141938:55)
    at step (http://localhost:4200/vendor.js:141830:23)

**Comment by powerful23** [comment]
@mohanrao can you try to find out which function is treated as `undefined`? Is `Array.isArray()`?

**Comment by mohanrao** [comment]
Hi @powerful23 i am not able to figure that out from the error log or debug also

**Comment by emeryaa** [comment]
Please add hosting to your project before publishing your project
Command: amplify hosting add

Trying to add hosting without chances

amplify hosting add
Hosting is already fully enabled.

Error: Hosting is already fully enabled.

**Comment by mohanrao** [comment]
@emeryaa Sorry i am not able to understand your comment. Can you please elaborate more ?

**Comment by powerful23** [comment]
@mohanrao could you try putting breaking point into the source code, for example, putting some breaking point in `JS.transferKeyToLowerCase`, the file is in the `node_modules/@aws-amplify/core/lib/JS`. (The way of putting breaking points is to go to the `Sources` in the browser console.)

**Comment by mohanrao** [comment]
@powerful23 I found its failing for whiteListForItself.includes(key) . I got a screenshot

**Comment by mohanrao** [comment]
After further research found that i had to add the below polyfill from corejs to make the app to work

```
import 'core-js/es6/array';
import 'core-js/es7/array';
import 'core-js/es6/object';
import 'core-js/es7/object';

```
