### ISSUE TITLE
Nested GraphQL operations randomly throws 'Client network socket disconnected before secure TLS connection was established' in NodeJs

### ISSUE THREAD

**Issue by 11csive** [aws-amplify/amplify-js#2959]
** Which Category is your question related to? **
AppSync

** What AWS Services are you utilizing? **
Cognito, AppSync Api

** Provide additional details e.g. code snippets **
When nesting GraphQL operations in my NodeJs project I randomly get the following error:

```
{ data: {},
  errors:
   [ { GraphQLError: Client network socket disconnected before secure TLS connection was established
         at APIClass.<anonymous> (/home/someUser/Documents/WebstormProjects/someProject/node_modules/@aws-amplify/api/lib/API.js:535:33)
         at step (/home/someUser/Documents/WebstormProjects/someProject/node_modules/@aws-amplify/api/lib/API.js:40:23)
         at Object.throw (/home/someUser/Documents/WebstormProjects/someProject/node_modules/@aws-amplify/api/lib/API.js:21:53)
         at rejected (/home/someUser/Documents/WebstormProjects/someProject/node_modules/@aws-amplify/api/lib/API.js:13:65)
         at process._tickCallback (internal/process/next_tick.js:68:7)
       message:
        'Client network socket disconnected before secure TLS connection was established',
       locations: undefined,
       path: undefined } ] }
```

Eg. the second operation in the following code will fail about half the time:

```
API.graphql(graphqlOperation(queries.getUser, {id: user})).then(result => {
    API.graphql(graphqlOperation(queries.getSiteDoors, {id: siteId})).then(result => {
    console.log(result)
    }).catch(error => {
        console.error(error)
    })
}).catch(error => {
        console.error(error)
})
```

Whereas the following seems to work fine at all times:

```
for (const [user, userData] of users) {
        API.graphql(graphqlOperation(queries.getUser, {id: user})).then(result => {
            console.log(result)
        }).catch(error => {
            console.error(error)
        })
    }
```

I think it might be related to the following issue and answer linked here, regarding NodeJs not renegotiating the connection when the cached TLS session fails:

https://github.com/nodejs/node/issues/8368#issuecomment-244666302

Can someone help confirm whether or not this could be the reason, and propose a solution within the SDK? And if not the reason, how can I troubleshoot the issue from here on? I'm quite unsure how to proceed at the moment.

Thanks in advance

**Comment by 11csive** [comment]
Just in case anyone else faces/is gonna face this problem, I seem to have found a fix/workaround for now.

The default userAgent settings for Axios disables keep-alive. Setting keep-alive to true seems to have stopped the random errors. Whether this will cause other problems, I'm yet to find out.

If anyone can name any consequences I might face as a result of setting the keep-alive to true, I would be more than happy to know. If not, I will close this issue for now.
