### ISSUE TITLE
Package collision in react-native when using functions

### ISSUE THREAD

**Issue by vparpoil** [aws-amplify/amplify-js#2960]
**Describe the bug**
After adding functions to the amplify project in a react-native app, it creates a folder with a `package.json` file. After push, another folder is created in `amplify/#current-cloud-backend`. Then react-native start fail on error

**To Reproduce**
1. amplify add function
2. cd in function folder and run npm install
3. amplify push
4. react-native run ios
```
Duplicate module name: functionName
  Paths: /home/user/react/appName/amplify/backend/function/functionName/src/package.json collides with /home/user/react/appName/amplify/#current-cloud-backend/function/appName/src/package.json

This error is caused by `hasteImpl` returning the same name for different files.
    at setModule (/home/user/react/appName/node_modules/jest-haste-map/build/index.js:569:17)
    at workerReply (/home/user/react/appName/node_modules/jest-haste-map/build/index.js:641:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:6208) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6208) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:6208) UnhandledPromiseRejectionWarning: Error: jest-haste-map: Haste module naming collision
```

**Additional context**
React native 0.58.4
amplify CLI 1.1.7
aws-amplify 1.1.19

**Comment by vparpoil** [comment]
Seems similar to https://github.com/aws-amplify/amplify-cli/issues/1144 , sorry for duplicate in wrong repo

**Comment by powerful23** [comment]
@vparpoil It's OK. I will close this now but if you want to reopen it, pls let us know. Thanks!
