### ISSUE TITLE
[Android] Push notification not displayed when app is killed

### ISSUE THREAD

**Issue by bernhardt1** [aws-amplify/amplify-js#2975]
**Describe the bug**
Using the standard [android notification setup from the docs](https://aws-amplify.github.io/docs/js/push-notifications#working-with-the-api) a notification is **not displayed** when the app is in a killed state even though the message data is received to android studio.

Here is the android studio log.
```
V/RNPushNotification: onMessageReceived: Bundle[{pinpoint.openApp=true, pinpoint.notification.title=hello, pinpoint.notification.body=test, pinpoint.campaign.campaign_id=_DIRECT, pinpoint.notification.silentPush=0}]
I/RNPushNotificationModule: constructing RNPushNotificationModule
```
I followed  #1245 but it did not help.

**To Reproduce**
1. eject an expo app
2. [follow standard notification setup as described in the docs](https://aws-amplify.github.io/docs/js/push-notifications#working-with-the-api)

**Expected behavior**
expect a sent pinpoint notification to be displayed when the app is killed.

**Versioning (please complete the following information):**
@aws-amplify/pushnotification": "^1.0.24",
 "aws-amplify": "^1.1.23",
 "aws-amplify-react-native": "^2.1.9",

**Comment by elorzafe** [comment]
@bernhardt1 If you have your app open, can you see the notification, can you paste a code snippet from your app, to test?

**Comment by bernhardt1** [comment]
Hi @elorzafe, thanks for the quick response.

Yes, the notification is shown when I have the app open in the background. My android log in this case is the following:
```
RNPushNotificationMessagingService: Message From: 123456789012
RNPushNotificationMessagingService: sendNotification: Bundle[{pinpoint.openApp=true, userInteraction=false, pinpoint.notification.title=hello, pinpoint.notification.body=friend2, id=759258221, pinpoint.campaign.campaign_id=_DIRECT, pinpoint.notification.silentPush=0}]
RNPushNotificationHelper: sendNotification: Intent { act=com.amazonaws.amplify.pushnotification.NOTIFICATION_OPENED (has extras) }
```

here is my code:
```
import React, { Component } from 'react';
import { Provider } from 'react-redux';
import Auth from '@aws-amplify/auth';
import { Rehydrated } from 'aws-appsync-react';
import { ApolloProvider } from 'react-apollo';
import AWSAppSyncClient from 'aws-appsync';
import PushNotification from '@aws-amplify/pushnotification';
import { PushNotificationIOS, Platform } from 'react-native';

import appsyncConfig from '../../../appsync-exports';
import amplifyConfig from '../../../aws-exports';
import store from '../store';
import AppNavigator from './AppNavigator';

PushNotification.configure(amplifyConfig); // amplify push-notifications

PushNotification.onNotification((notification) => {
  console.log('in app notification', notification);
  if (Platform.OS === 'ios') {
    notification.finish(PushNotificationIOS.FetchResult.NoData);
  }
});

const client = new AWSAppSyncClient({
  url: appsyncConfig.aws_appsync_graphqlEndpoint,
  region: appsyncConfig.aws_project_region,
  auth: {
    type: appsyncConfig.aws_appsync_authenticationType,
    credentials: () => Auth.currentCredentials(),
    apiKey: appsyncConfig.aws_appsync_apiKey
  },
  complexObjectsCredentials: () => Auth.currentCredentials(),
  disableOffline: true,
  options: {
    fetchPolicy: 'network-only',
    errorPolicy: 'all'
  }
});

class AppNavigatorWrapper extends Component {
  // exposes the router static on AppNavigatorWrapper and threads through the navigation prop
  static router = AppNavigator.router;

  async componentDidMount() {
    if (Platform.OS === 'ios') {
      PushNotificationIOS.requestPermissions();
    }

    // get the registration token
    PushNotification.onRegister(token => {
      console.log('in app registration', token);
    });

    // get the notification data when notification is opened
    PushNotification.onNotificationOpened(notification => {
      console.log('the notification is opened', notification);
    });
  }

  render() {
    return (
      <ApolloProvider client={client}>
        <Rehydrated>
          <Provider store={store}>
            <AppNavigator />
          </Provider>
        </Rehydrated>
      </ApolloProvider>
    );
  }
}

export default AppNavigatorWrapper;
```

**Comment by elorzafe** [comment]
@powerful23 what do you think?

**Comment by bernhardt1** [comment]
@powerful23 is there any more information I could provide?

**Comment by powerful23** [comment]
@bernhardt1 we couldn't reproduce that issue. Can you provide more info like the details of your Android device?

**Comment by bernhardt1** [comment]
I'm testing on a samsung S9+. I haven't tried using another device.

I am able to receive a notification when I send it from firebase test messaging center.

The part I find odd is the android studio log. It is definitely catching the notification when the app is closed.
```
RNPushNotificationMessagingService: Message From: 747515889146
```

@powerful23 Are you aware of some device specific issues with other android phones?

**Comment by powerful23** [comment]
@bernhardt1 No. But some other customers are also experiencing the issue of notification not showing up. Did you see any error in the Android log? Also what's the version of `react-native`?

**Comment by bernhardt1** [comment]
`"react-native": "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz",`
Expo SDK v31.0.0 is based on React Native 0.57.

I tried uninstalling my app from the device. The fresh install does show some errors in the android log the first time I start it. These errors don't show up when I run the app after it is installed:

```
I/RNPushNotificationMessagingService: Message From: 747515889146
D/BadgeProviderManager: 2. updateBadgeCounts: com.androidPush/host.exp.exponent.MainActivity = 0
D/BadgeCache: 1. pkgName : com.androidPush = 0
D/BadgeCache: 2. componentName: com.androidPush/host.exp.exponent.MainActivity = 0
I/RNPushNotificationModule: constructing RNPushNotificationModule
W/ActivityManager: **Background start not allowed**: service Intent { act=com.google.firebase.INSTANCE_ID_EVENT pkg=com.facebook.orca cmp=com.facebook.orca/com.facebook.push.fcm.FcmInstanceIDListenerService (has extras) } to com.facebook.orca/com.facebook.push.fcm.FcmInstanceIDListenerService from pid=18651 uid=10214 pkg=com.facebook.orca startFg?=false
E/FirebaseInstanceId: **Failed to start service while in background**: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.firebase.INSTANCE_ID_EVENT pkg=com.facebook.orca cmp=com.facebook.orca/com.facebook.push.fcm.FcmInstanceIDListenerService (has extras) }: app is in background uid UidRecord{3b7e9b1 u0a214 CEM  idle change:idle|cached procs:1 proclist:18651, seq(0,0,0)}
V/AlarmManagerEXT: <AppSync3 Whitelist>
    (AppSync) com.google.android.gms : 14400(35940)
    (AppSync) com.google.android.gms : 14400(28740)
    (AppSync) com.google.android.gms : 10800(13980)
    (AppSync) com.google.android.gms : 7200(33360)
    (AppSync) com.sec.spp.push : 1200(1200)
    (AppSync) ### 5 added ###
I/BCL@Settings: (PushManager) init() +
I/BCL@Settings: (PushManager) init() -
I/BCL@Settings: (PushManager) provision is needed
I/GservicesProvider: Gservices pushing to system: true; secure/global: true
D/HxPushNotificationsManager: Hx FCM Token is-empty false is-different false . If empty or different, job to update will be kicked
```

**Comment by powerful23** [comment]
@bernhardt1 seems like this error is related to https://stackoverflow.com/questions/46117554/firebasemessagingservice-crashes-on-android-o-due-to-background-execution-limits/48166636

I did some change to stop using that deprecated service and published a version for testing: `@aws-amplify/pushnotification@next`. If you are interested you can download that package and try it with your app. Please note that because that package is using new version of firebase, please update your `android/app/build.gradle` accordingly:
```
 compile "com.google.firebase:firebase-core:16.0.6"
  compile "com.google.firebase:firebase-messaging:17.3.4"
```

```

**Comment by bernhardt1** [comment]
@powerful23 thank you for the rapid solution. I will test it in the coming hours.

**Comment by bernhardt1** [comment]
@powerful23 

I downloaded that package into my app but have run into the same issues. 

I ran into a few build errors but solved them by falling back to the following. Are these firebase versions recent enough? :
```
  implementation ('com.google.firebase:firebase-core:16.0.4')
  implementation ('com.google.firebase:firebase-messaging:17.3.3')
```

My updated package.json to verify proper versioning
```
"dependencies": {
    "@aws-amplify/pushnotification": "^1.0.26-next.0",
```

Here's an example of my logcat on a fresh install of the app. There seems to be a problem instantiating the service around line 8. Also the similar **Background execution not allowed: receiving Intent** happening:
```
/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.levity flg=0x4000010 (has extras) } to com.samsung.android.spay/.common.push.spp.SppReceiver
/? D/BadgeProviderManager: 2. updateBadgeCounts: com.androidPush/host.exp.exponent.MainActivity = 0
/? D/BadgeCache: 1. pkgName : com.androidPush = 0
/? D/BadgeCache: 2. componentName: com.androidPush/host.exp.exponent.MainActivity = 0
/com.levity V/RNPushNotificationMessagingService: On new token received: 1234565StR3g:APA91bGs-5DOBznsYlG59wMJcu7wk3TtB5rSm8feOWt65cylb4TRferAaugjaLNSWUNUqe_VPPfxNdCqLQaEWORLTpgHqv3pUYLW3-dYROQIP4RuUIgfTYbgSkvaglj123412512341234
/com.levity E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.levity, PID: 11245
    java.lang.RuntimeException: Unable to instantiate service com.amazonaws.amplify.pushnotification.RNPushNotificationDeviceIDService: java.lang.ClassNotFoundException: Didn't find class "com.amazonaws.amplify.pushnotification.RNPushNotificationDeviceIDService" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.levity-_wvox6EqzKGaxiJ_8lc_Ug==/base.apk"],nativeLibraryDirectories=[/data/app/com.levity-_wvox6EqzKGaxiJ_8lc_Ug==/lib/arm, /data/app/com.levity-_wvox6EqzKGaxiJ_8lc_Ug==/base.apk!/lib/armeabi-v7a, /system/lib]]
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3715)
        at android.app.ActivityThread.access$1400(ActivityThread.java:235)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1784)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.amazonaws.amplify.pushnotification.RNPushNotificationDeviceIDService" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.levity-_wvox6EqzKGaxiJ_8lc_Ug==/base.apk"],nativeLibraryDirectories=[/data/app/com.levity-_wvox6EqzKGaxiJ_8lc_Ug==/lib/arm, /data/app/com.levity-_wvox6EqzKGaxiJ_8lc_Ug==/base.apk!/lib/armeabi-v7a, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:103)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3710)
        at android.app.ActivityThread.access$1400(ActivityThread.java:235) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1784) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:6981) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445) 
/? V/SamsungAlarmManager: Sending to uid : 10055 action=com.sec.spp.push.ACTION_SEND_PING_MESSAGE alarm=Alarm{195f952 type 2 when 4301667092 com.sec.spp.push}
/? D/SamsungAlarmManager: Cancel Alarm calling from uid:10055 pid :10888 / op:PendingIntent{d317b4c: PendingIntentRecord{a6ad795 com.sec.spp.push broadcastIntent}}
/? I/chatty: uid=10055 com.sec.spp.push:RemoteDlcProcess identical 18 lines
/? D/SamsungAlarmManager: Cancel Alarm calling from uid:10055 pid :10522 / op:PendingIntent{65a6f77: PendingIntentRecord{62fa6d9 com.sec.spp.push broadcastIntent}}
/? D/SamsungAlarmManager: Cancel Alarm calling from uid:10055 pid :10522 / op:PendingIntent{7679e50: PendingIntentRecord{cb182b2 com.sec.spp.push broadcastIntent}}
/? D/FA: Setting user property (FE): recommend_push, on
/? D/FA-SVC: Setting user property: recommend_push, on
/? D/FA-SVC: User property set: recommend_push, on
/? D/SyncManager: startSync!!! begin PUSH data
/? D/SyncManager: push begin... [1]
/? D/SyncManager: startSync!!! end PUSH data RESULT:true DURATION:17
/? D/BadgeCache: 1. pkgName : com.androidPush = 0
/? D/BadgeCache: 2. componentName: com.androidPush/host.exp.exponent.MainActivity = 0
/? D/BadgeProviderManager: 2. updateBadgeCounts: com.androidPush/host.exp.exponent.MainActivity = 0
/? D/PackageManager: getComponentMetadataForIconTray : com.sec.spp.push.PushClientApplication does not exist in mActivities
/? D/PackageManager: getComponentMetadataForIconTray : com.sec.spp.push.PushClientApplication does not exist in mServices
/? D/PackageManager: getComponentMetadataForIconTray : com.sec.spp.push.PushClientApplication does not exist in mProviders
/? D/PackageManager: getComponentMetadataForIconTray : com.sec.spp.push.PushClientApplication does not exist in mReceivers
/? I/AppIconSolution: load=com.sec.spp.push, bg=144-144, dr=105-105, forDefault=true, density=0
/? I/AppIconSolution: load=com.sec.spp.push-contain, bg=130-130, dr=105-105
/com.levity I/RNPushNotificationModule: constructing RNPushNotificationModule
/com.levity I/RNPushNotificationModule: initializing RNPushNotificationModule
/com.levity I/RNPushNotificationModule: registering receiver
/? D/HxPushNotificationsManager: Hx FCM Token is-empty false is-different false . If empty or different, job to update will be kicked
/? V/AlarmManagerEXT: (AppSync) com.sec.spp.push : 1200(1200)
/? I/SamsungNotes$SC/PushManager: isPushRegNeeded : false
/? I/SamsungNotes$SC/SyncLogic: initSyncLogic() : ignore registering push!
/? D/SamsungNotes$SC/SyncLogic: Finish push operation - elapsed time : 43
/? I/SamsungNotes$SC/PushManager: isPushRegNeeded : false
/? I/SamsungNotes$SC/PushManager: isPushRegNeeded : false
/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:com.levity flg=0x4000010 (has extras) } to com.samsung.android.mateagent/.push.spp.SppDataClearReceiver
/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:com.levity flg=0x4000010 (has extras) } to com.samsung.android.spay/.common.push.spp.SppReceiver
/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.levity flg=0x4000010 (has extras) } to com.samsung.android.spay/.common.push.spp.SppReceiver
/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REPLACED dat=package:com.levity flg=0x4000010 (has extras) } to com.samsung.android.spay/.common.push.spp.SppReceiver
/? D/BadgeCache: 1. pkgName : com.androidPush = 0
/? D/BadgeCache: 2. componentName: com.androidPush/host.exp.exponent.MainActivity = 0
/? D/BadgeProviderManager: 2. updateBadgeCounts: com.androidPush/host.exp.exponent.MainActivity = 0
/? I/BCL@Settings: (PushManager) init() +
/? I/BCL@Settings: (PushManager) init() -
/? I/BCL@Settings: (PushManager) provision is needed
/com.levity I/RNPushNotificationModule: constructing RNPushNotificationModule
/com.levity I/RNPushNotificationModule: initializing RNPushNotificationModule
/com.levity I/RNPushNotificationModule: registering receiver
```

**Comment by bernhardt1** [comment]
@powerful23 

I downloaded that package into my app but have run into the same issues. 

I ran into a few build errors but solved them by falling back to the following. Are these firebase versions recent enough? 
```
  implementation ('com.google.firebase:firebase-core:16.0.4')
  implementation ('com.google.firebase:firebase-messaging:17.3.3')
```
