### ISSUE TITLE
Updating @aws-amplify/storage from 1.0.26 to 1.0.27 or 1.0.28 gives an "AccessDenied: Access Denied" error on `.put`

### ISSUE THREAD

**Issue by philiiiiiipp** [aws-amplify/amplify-js#3051]
When updating `@aws-amplify/storage` from 1.0.26 to any of the following versions  

Before:
```
$ npm list @aws-amplify/core @aws-amplify/auth @aws-amplify/storage 
@dh/sfa-api@0.0.99 /Users/philipp/node/dev/dh/sfa-api
├─┬ @aws-amplify/auth@1.2.21 
│ ├─┬ @aws-amplify/cache@1.0.25
│ │ └── @aws-amplify/core@1.0.25  deduped
│ └── @aws-amplify/core@1.0.25  deduped
├── @aws-amplify/core@1.0.25 
└─┬ @aws-amplify/storage@1.0.26 
  └── @aws-amplify/core@1.0.25  deduped
```

After:
```
$ npm list @aws-amplify/core @aws-amplify/auth @aws-amplify/storage 
@dh/sfa-api@0.0.99 /Users/philipp/node/dev/dh/sfa-api
├─┬ @aws-amplify/auth@1.2.21 
│ ├─┬ @aws-amplify/cache@1.0.25
│ │ └── @aws-amplify/core@1.0.25  deduped
│ └── @aws-amplify/core@1.0.25  deduped
├── @aws-amplify/core@1.0.25 
└─┬ @aws-amplify/storage@1.0.27 
  └── @aws-amplify/core@1.0.25  deduped
```

I am unable to upload to my protected bucket.
```
[WARN] 57:55.361 AWSS3Provider - error uploading { AccessDenied: Access Denied
        at Request.extractError (/Users/philipp/node/dev/dh/sfa-api/node_modules/aws-sdk/lib/services/s3.js:585:35)
        at Request.callListeners (/Users/philipp/node/dev/dh/sfa-api/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
        at Request.emit (/Users/philipp/node/dev/dh/sfa-api/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
        at Request.emit (/Users/philipp/node/dev/dh/sfa-api/node_modules/aws-sdk/lib/request.js:683:14)
        at Request.transition (/Users/philipp/node/dev/dh/sfa-api/node_modules/aws-sdk/lib/request.js:22:10)
        at AcceptorStateMachine.runTo (/Users/philipp/node/dev/dh/sfa-api/node_modules/aws-sdk/lib/state_machine.js:14:12)
        at /Users/philipp/node/dev/dh/sfa-api/node_modules/aws-sdk/lib/state_machine.js:26:10
        at Request.<anonymous> (/Users/philipp/node/dev/dh/sfa-api/node_modules/aws-sdk/lib/request.js:38:9)
        at Request.<anonymous> (/Users/philipp/node/dev/dh/sfa-api/node_modules/aws-sdk/lib/request.js:685:12)
        at Request.callListeners (/Users/philipp/node/dev/dh/sfa-api/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
        at Request.emit (/Users/philipp/node/dev/dh/sfa-api/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
        at Request.emit (/Users/philipp/node/dev/dh/sfa-api/node_modules/aws-sdk/lib/request.js:683:14)
        at Request.transition (/Users/philipp/node/dev/dh/sfa-api/node_modules/aws-sdk/lib/request.js:22:10)
        at AcceptorStateMachine.runTo (/Users/philipp/node/dev/dh/sfa-api/node_modules/aws-sdk/lib/state_machine.js:14:12)
        at /Users/philipp/node/dev/dh/sfa-api/node_modules/aws-sdk/lib/state_machine.js:26:10
        at Request.<anonymous> (/Users/philipp/node/dev/dh/sfa-api/node_modules/aws-sdk/lib/request.js:38:9)
        at Request.<anonymous> (/Users/philipp/node/dev/dh/sfa-api/node_modules/aws-sdk/lib/request.js:685:12)
        at Request.callListeners (/Users/philipp/node/dev/dh/sfa-api/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
        at callNextListener (/Users/philipp/node/dev/dh/sfa-api/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
        at IncomingMessage.onEnd (/Users/philipp/node/dev/dh/sfa-api/node_modules/aws-sdk/lib/event_listeners.js:299:13)
        at emitNone (events.js:111:20)
        at IncomingMessage.emit (events.js:208:7)
        at endReadableNT (_stream_readable.js:1064:12)
        at _combinedTickCallback (internal/process/next_tick.js:139:11)
        at process._tickDomainCallback (internal/process/next_tick.js:219:9)
      message: 'Access Denied',
      code: 'AccessDenied',
      region: null,
      time: 2019-04-09T13:57:55.359Z,
      requestId: '5D9502697E646668',
      extendedRequestId: 'cglAgYDsgI0zvAcvTNi1rxVbi6hqqNSZCyZVYFiJQz+fNEurtyN3caawCZO7SzPXvMQf+9Rg45E=',
      cfId: undefined,
      statusCode: 403,
      retryable: false,
      retryDelay: 84.91206672555862 }
```

Was there a change in how this is handled, or the path to where this is uploaded? 

***EDIT*** 

I first thought that it was something nodejs specific, but its actually also failing on our frontend.

**Comment by powerful23** [comment]
Related to #3034

**Comment by philiiiiiipp** [comment]
I digged a little and it seems as if the custom prefixes are getting ignored.

If I set
```
Storage: {
    identityPoolId: COGNITO_CF_VALUES.CognitoIdentityPoolId,
    bucket: S3_CF_VALUES.ImageBucketName,
    region: AWS_REGION,
    customPrefix: {
      private: 'customPlace/',
      protected: 'customPlace/',
      public: 'customPlace/',
    },
```

It tries to upload to `https://BUCKET_NAME.s3.eu-west-1.amazonaws.com/protected/IDENTITY_ID/profile.png` instead of `https://BUCKET_NAME.s3.eu-west-1.amazonaws.com/customPlace/IDENTITY_ID/profile.png`
