### ISSUE TITLE
Amplify Console - Build Failing

### ISSUE THREAD

**Issue by nelsynelz** [aws-amplify/amplify-js#3249]
**Describe the bug**
Build is failing when using the Amplify Console. The error message does not provide very much info, but you can see it below. 

>                                   # Starting phase: build
> 2019-05-09T15:40:41.107Z [INFO]: # Executing command: amplifyPush --simple
> 2019-05-09T15:40:41.112Z [INFO]: # Getting Amplify CLI Cloud-Formation stack info from environment cache
> 2019-05-09T15:40:41.123Z [INFO]: # Start initializing Amplify environment: Prod
>                                  # Initializing new Amplify environment: Prod (amplify init)
> 2019-05-09T15:40:48.453Z [INFO]: Note: It is recommended to run this command from the root of your app directory
> 2019-05-09T15:40:48.457Z [INFO]: Environment name should be between 2 and 10 characters (only lowercase alphabets).
> 2019-05-09T15:40:48.461Z [ERROR]: !!! Build failed
> 2019-05-09T15:40:48.549Z [ERROR]: !!! Non-Zero Exit Code detected
> 2019-05-09T15:40:48.550Z [INFO]: # Starting environment caching...
> 2019-05-09T15:40:48.550Z [INFO]: # Environment caching completed
> Terminating logging...

**To Reproduce**
1. Attempting to deploy either on initial deploy or when I click "Redeploy this version" will fail with the same error on the build page. 

**Expected behavior**
I expected the console to finish the deployment and not fail on the build stage.

**Screenshots**
![image](https://user-images.githubusercontent.com/41842184/57467233-2712bb80-7250-11e9-8e12-3885915dda14.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome

**Additional context**
My build deployed fine in an Dev state using Amplify Publish via the Amplify CLI. 

This project is also using Amplify-Vue. 

**Sample code**
https://github.com/nelsynelz/DansBlog

**Comment by powerful23** [comment]
Related to #3246

**Comment by nimacks** [comment]
Hi @nelsynelz, it looks like the name of your new environment you created begins with a capital P, as in `Prod`. The environment name should be only lowercase characters. To resolve this, go to your environment variables and rename it to use lowercase. 

After you've done that you should be able to import the backend environment deployed by the Amplify Console to your repo (the amplify/team-provider.json file contains information on all backend environments in your AWS account). The GIF below shows how you to copy the amplify env import command from the Amplify Console.

https://github.com/aws-samples/create-react-app-auth-amplify/raw/master/src/images/import-backend.gif

**Comment by swaminator** [comment]
@powerful23 seems like you weren't successful. What error message are you seeing now?

**Comment by nelsynelz** [comment]
> @powerful23 seems like you weren't successful. What error message are you seeing now?

The environment variable fixed the error in the backend build stage, which is unfortunate because I tried changing that before I submitted the issue and I guess it never saved because it was still capital when I just checked back. 

However now I'm hitting another error on the frontend part of the build. I can make this a new issue as this isn't related to the original issue. 

```
                                 # Starting phase: preBuild
                                 # Executing command: npm install
2019-05-09T21:37:16.988Z [WARNING]: npm WARN
2019-05-09T21:37:16.989Z [WARNING]: deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
2019-05-09T21:37:17.801Z [WARNING]: npm WARN deprecated bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!
2019-05-09T21:37:19.646Z [WARNING]: npm WARN
2019-05-09T21:37:19.648Z [WARNING]: deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
2019-05-09T21:37:35.111Z [INFO]: > uglifyjs-webpack-plugin@0.4.6 postinstall /codebuild/output/src484485155/src/DansBlog/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
                                 > node lib/post_install.js
2019-05-09T21:37:36.410Z [WARNING]: npm notice created a lockfile as package-lock.json. You should commit this file.
2019-05-09T21:37:36.412Z [WARNING]: npm WARN ajv-keywords@3.4.0 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
                                    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
                                    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2019-05-09T21:37:36.418Z [INFO]: added 1096 packages from 643 contributors and audited 11502 packages in 21.12s
                                 found 12 vulnerabilities (7 moderate, 5 high)
                                 run `npm audit fix` to fix them, or `npm audit` for details
2019-05-09T21:37:36.443Z [INFO]: # Completed phase: preBuild
                                 # Starting phase: build
2019-05-09T21:37:36.444Z [INFO]: # Executing command: npm run build
2019-05-09T21:37:36.627Z [INFO]: > dansblog_v0.1@1.0.0 build /codebuild/output/src484485155/src/DansBlog
                                 > node build/build.js
2019-05-09T21:37:45.000Z [INFO]: Hash: [1mc237b2145665d6d2d2ad[39m[22m
                                 Version: webpack [1m3.12.0[39m[22m
                                 Time: [1m6475[39m[22mms
                                 [1mAsset[39m[22m       [1mSize[39m[22m  [1mChunks[39m[22m  [1m[39m[22m           [1m[39m[22m[1mChunk Names[39m[22m
                                 [1m[32mstatic/img/dan@dev-logo-B-LogoOnly.cedc67f.png[39m[22m    14.6 kB        [1m[39m[22m  [1m[32m[emitted][39m[22m
                                 [1m[32mstatic/js/vendor.ff645668d886489cf122.js[39m[22m     145 kB       [1m0[39m[22m  [1m[32m[emitted][39m[22m  vendor
                                 [1m[32mstatic/js/app.ab611037dedf2f3a7efc.js[39m[22m  462 bytes       [1m1[39m[22m  [1m[32m[emitted][39m[22m  app
                                 [1m[32mstatic/js/manifest.2ae2e69a05c33dfc65f8.js[39m[22m  857 bytes       [1m2[39m[22m  [1m[32m[emitted][39m[22m  manifest
                                 [1m[32mstatic/css/app.71e30f7b0e35c26fc5d80317d4d22105.css[39m[22m    2.06 kB       [1m1[39m[22m  [1m[32m[emitted][39m[22m  app
                                 [1m[32mstatic/css/app.71e30f7b0e35c26fc5d80317d4d22105.css.map[39m[22m    3.92 kB        [1m[39m[22m  [1m[32m[emitted][39m[22m
                                 [1m[32mstatic/js/vendor.ff645668d886489cf122.js.map[39m[22m     727 kB       [1m0[39m[22m  [1m[32m[emitted][39m[22m  vendor
                                 [1m[32mstatic/js/app.ab611037dedf2f3a7efc.js.map[39m[22m  489 bytes       [1m1[39m[22m  [1m[32m[emitted][39m[22m  app
                                 [1m[32mstatic/js/manifest.2ae2e69a05c33dfc65f8.js.map[39m[22m    4.97 kB       [1m2[39m[22m  [1m[32m[emitted][39m[22m  manifest
                                 [1m[32mindex.html[39m[22m  676 bytes        [1m[39m[22m  [1m[32m[emitted][39m[22m
                                 [1m[31mERROR in ./src/main.js
                                 Module not found: Error: Can't resolve 'aws-amplify' in '/codebuild/output/src484485155/src/DansBlog/src'
                                 @ ./src/main.js 8:0-55[39m[22m
                                 [1m[31mERROR in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
                                 Module not found: Error: Can't resolve 'aws-amplify' in '/codebuild/output/src484485155/src/DansBlog/src'
                                 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue 37:0-35
                                 @ ./src/App.vue
                                 @ ./src/main.js[39m[22m
                                 [1m[31mERROR in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/WriteBlog.vue
                                 Module not found: Error: Can't resolve 'aws-amplify' in '/codebuild/output/src484485155/src/DansBlog/src/components'
                                 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/WriteBlog.vue 26:0-35
                                 @ ./src/components/WriteBlog.vue
                                 @ ./src/router/index.js
                                 @ ./src/main.js[39m[22m
                                 [1m[31mERROR in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/Login.vue
                                 Module not found: Error: Can't resolve 'aws-amplify' in '/codebuild/output/src484485155/src/DansBlog/src/components'
                                 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/Login.vue 15:0-35
                                 @ ./src/components/Login.vue
                                 @ ./src/router/index.js
                                 @ ./src/main.js[39m[22m
                                 [1m[31mERROR in ./src/main.js
                                 Module not found: Error: Can't resolve 'aws-amplify-vue' in '/codebuild/output/src484485155/src/DansBlog/src'
                                 @ ./src/main.js 9:0-48[39m[22m
                                 [1m[31mERROR in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/Login.vue
                                 Module not found: Error: Can't resolve 'aws-amplify-vue' in '/codebuild/output/src484485155/src/DansBlog/src/components'
                                 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/Login.vue 16:0-50
                                 @ ./src/components/Login.vue
                                 @ ./src/router/index.js
                                 @ ./src/main.js[39m[22m
                                 [1m[31mERROR in ./src/main.js
                                 Module not found: Error: Can't resolve 'bootstrap' in '/codebuild/output/src484485155/src/DansBlog/src'
                                 @ ./src/main.js 6:0-19[39m[22m
                                 [1m[31mERROR in ./src/main.js
                                 Module not found: Error: Can't resolve 'bootstrap/dist/css/bootstrap_lux.min.css' in '/codebuild/output/src484485155/src/DansBlog/src'
                                 @ ./src/main.js 7:0-50[39m[22m
                                 [1m[31mERROR in ./src/components/Home.vue
                                 Module not found: Error: Can't resolve 'sass-loader' in '/codebuild/output/src484485155/src/DansBlog/src/components'
                                 @ ./src/components/Home.vue 2:2-400
                                 @ ./src/router/index.js
                                 @ ./src/main.js[39m[22m
2019-05-09T21:37:45.002Z [INFO]: Build failed with errors.
2019-05-09T21:37:45.016Z [WARNING]: npm
2019-05-09T21:37:45.017Z [WARNING]: ERR! code ELIFECYCLE
                                    npm ERR! errno 1
                                    npm ERR! dansblog_v0.1@1.0.0 build: `node build/build.js`
                                    npm ERR! Exit status 1
                                    npm
2019-05-09T21:37:45.018Z [WARNING]: ERR!
                                    npm ERR! Failed at the dansblog_v0.1@1.0.0 build script.
                                    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-05-09T21:37:45.045Z [WARNING]: 
2019-05-09T21:37:45.046Z [WARNING]: npm ERR! A complete log of this run can be found in:
                                    npm ERR!     /root/.npm/_logs/2019-05-09T21_37_45_018Z-debug.log
```

**Comment by nelsynelz** [comment]
I checked my package.json and it's missing the dependency for amplify along with the other packages it named here. I'll see if I can get them manually added as dependencies and try again.

**Comment by nelsynelz** [comment]
Worked through all of the above and now having an issue with my webpack version. 

```
2019-05-09T22:32:39.838Z [WARNING]: /codebuild/output/src598208421/src/DansBlog/node_modules/webpack/lib/webpack.js:185
                                    throw new RemovedPluginError(errorMessage);
                                    ^
                                    Error: webpack.optimize.CommonsChunkPlugin has been removed, please use config.optimization.splitChunks instead.
                                    at Object.get [as CommonsChunkPlugin] (/codebuild/output/src598208421/src/DansBlog/node_modules/webpack/lib/webpack.js:185:10)
                                    at Object.<anonymous> (/codebuild/output/src598208421/src/DansBlog/build/webpack.prod.conf.js:82:26)
                                    at Module._compile (module.js:653:30)
                                    at Object.Module._extensions..js (module.js:664:10)
                                    at Module.load (module.js:566:32)
                                    at tryModuleLoad (module.js:506:12)
                                    at Function.Module._load (module.js:498:3)
                                    at Module.require (module.js:597:17)
                                    at require (internal/module.js:11:18)
                                    at Object.<anonymous> (/codebuild/output/src598208421/src/DansBlog/build/build.js:12:23)
                                    at Module._compile (module.js:653:30)
                                    at Object.Module._extensions..js (module.js:664:10)
                                    at Module.load (module.js:566:32)
                                    at tryModuleLoad (module.js:506:12)
                                    at Function.Module._load (module.js:498:3)
                                    at Function.Module.runMain (module.js:694:10)
2019-05-09T22:32:39.845Z [WARNING]: npm
2019-05-09T22:32:39.846Z [WARNING]: ERR! code ELIFECYCLE
                                    npm ERR! errno 1
                                    npm ERR! dansblog_v0.1@1.0.0 build: `node build/build.js`
                                    npm ERR! Exit status 1
                                    npm ERR!
                                    npm ERR! Failed at the dansblog_v0.1@1.0.0 build script.
                                    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-05-09T22:32:39.853Z [WARNING]: 
2019-05-09T22:32:39.854Z [WARNING]: npm ERR! A complete log of this run can be found in:
```

**Comment by swaminator** [comment]
Does `npm run build` work for you from your local machine?

**Comment by nelsynelz** [comment]
> Does `npm run build` work for you from your local machine?

Nope same error. Somehow my Vue CLI was outdated which is probably the root of all of these issues. I just updated it and am in the process of creating a new project and migrating everything over to it.

**Comment by nelsynelz** [comment]
Everything is working now after upgrading Vue CLI. Somehow NPM installed an old version last week. 

I just successfully deployed via the Amplify Console. Thanks again for all the help!

**Comment by powerful23** [comment]
Closing the issue. Please let us know if you still have this issue. @swaminator thanks for the help!
