### ISSUE TITLE
Angular Testing - Karma

### ISSUE THREAD

**Issue by malcomm** [aws-amplify/amplify-js#3318]
** Which Category is your question related to? **

aws-amplify-angular 

** What AWS Services are you utilizing? **

Amplify graphql

** Provide additional details e.g. code snippets **

I'm trying to figure out the best way to use the API services from Amplify in my testing. I'm running an issue where the API is not configured. I'm hoping to get some guidance on this and best practices for how to do this. I'm running the default **ng test**. I've done a fair amount of searching and I don't see this documented anywhere.

I'm configuring the API using the standard method of **main.ts**:

```
Amplify.configure(amplify);
API.configure(amplify);
```

Getting errors like this:

```
Uncaught Error: Uncaught (in promise): API not configured thrown
Failed: Uncaught (in promise): API not configured

```

```
Error: Uncaught (in promise): API not configured
    at resolvePromise (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:831:1)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:741:1
    at rejected (http://localhost:9876/_karma_webpack_/webpack:/node_modules/tslib/tslib.es6.js:69:88)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:391:1)
    at AsyncTestZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.AsyncTestZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-testing.js:714:1)
    at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-testing.js:286:1)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:390:1)
    at Object.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/core.js:17299:1)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:390:1)
    at Zone../node_modules/zone.js/dist/zone.js.Zone.run (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:150:1)
    at ____________________Elapsed_0_ms__At__Mon_May_20_2019_15_06_02_GMT_0700__Pacific_Daylight_Time_ (http://localhost)
    at Object.onScheduleTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-testing.js:108:1)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:404:1)
    at Object.onScheduleTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:301:1)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:404:1)
    at Zone../node_modules/zone.js/dist/zone.js.Zone.scheduleTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:238:1)
    at Zone../node_modules/zone.js/dist/zone.js.Zone.scheduleMicroTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:258:1)
    at scheduleResolveOrReject (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:879:1)
    at resolvePromise (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:825:1)
    at ____________________Elapsed_1_ms__At__Mon_May_20_2019_15_06_02_GMT_0700__Pacific_Daylight_Time_ (http://localhost)
    at Object.onScheduleTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-testing.js:108:1)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:404:1)
    at Object.onScheduleTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:301:1)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:404:1)
    at Zone../node_modules/zone.js/dist/zone.js.Zone.scheduleTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:238:1)
    at Zone../node_modules/zone.js/dist/zone.js.Zone.scheduleMicroTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:258:1)
    at scheduleResolveOrReject (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:879:1)
    at ZoneAwarePromise.then (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:1012:1)
    at ____________________Elapsed_90_ms__At__Mon_May_20_2019_15_06_02_GMT_0700__Pacific_Daylight_Time_ (http://localhost)
    at Object.onScheduleTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-testing.js:108:1)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:404:1)
    at Object.onScheduleTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:301:1)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:404:1)
    at Zone../node_modules/zone.js/dist/zone.js.Zone.scheduleTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:238:1)
    at Zone../node_modules/zone.js/dist/zone.js.Zone.scheduleEventTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:264:1)
    at HTMLButtonElement.addEventListener (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:2054:1)
    at DomEventsPlugin.push../node_modules/@angular/platform-browser/fesm5/platform-browser.js.DomEventsPlugin.addEventListener (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/platform-browser/fesm5/platform-browser.js:1363:1)
StudyAdminComponent should create
Uncaught Error: Uncaught (in promise): API not configured thrown

```

Thanks in advance for any help.

**Comment by gerrytsui** [comment]
Both our **ng test** & **ng e2e** are working fine.

in **main.tst** we have:

> Amplify.configure({
>   ...amplify_exports,
>   ...amplify_config_local
> });
> // Note we merge / override with our amplify_config_local

and  amplify_config_local is in this format:

> let amplify_config_local = {
>   "aws_project_region": "us-east-1",
>   API: {
>     endpoints: [ 
>       {
>         name: "api_1_NameHere",
>         "endpoint": "https://52dXXXXX.execute-api.us-east-1.amazonaws.com/prod",
>         "region": "us-east-1"          
>       },
>       {
>         name: "api_2_NameHere",
>         "endpoint": "https://NAME.api.CUSTOMDOMAIN.com/PRODv0.4", 
>         "region": "us-east-1"
>       }
>     ]
>   },
>  // ...
> }

**Comment by haverchuck** [comment]
@malcomm  - Can you check your node_modules and ensure that you don't have multiple versions of @aws-amplfiy/api?  Also, try to call Amplify.configure just once as @gerrytsui suggests and see if this helps.

**Comment by malcomm** [comment]
OK I changed my main.ts to have just this:

```
Amplify.configure(amplify);
// API.configure(amplify);
```
Removed the API.configure call.

I also deleted my node_modules directory and did an `npm install` to make sure I had a clean copy of everything. After doing that, the only version I see from `node_modules/@aws-amplify/api/package.json` is:

```
"version": "1.0.35"
```

The application is working fine, but `ng test` is still throwing similar errors.

Thank you for taking a look.

**Comment by gerrytsui** [comment]
Another area to check. I vaguely remember I had issue with ng test, due to not up-to-date settings in angular.json :  projects-> "name" -> architect  -> test not updated to be same as "serve" and "build"

**Comment by malcomm** [comment]
@gerrytsui - I think that is getting us to the problem. So my projects-> "name" -> architect -> test, looks like this:

```
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [
              "src/styles.scss"
            ],
            "scripts": [],
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ]
          }
        },
```
Notice the `"main": "src/test.ts"`. I added the following to my `src/test.ts`:

```
import Amplify from '@aws-amplify/core';
import amplify from './aws-exports';

Amplify.configure(amplify);
....

And I am no longer getting the `Error: Uncaught (in promise): API not configured`. But what I am getting now is:

```
Uncaught Error: Uncaught (in promise): No current user thrown
Failed: Uncaught (in promise): No current user

Error: Uncaught (in promise): No current user
    at resolvePromise (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:831:1)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:741:1
    at rejected (http://localhost:9876/_karma_webpack_/webpack:/node_modules/tslib/tslib.es6.js:69:88)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:391:1)
```

Which makes sense, since I do not have a user logged in and my graphql has `@auth`. 

So the 2 options would be to authenticate or to try and mock (inject a different service) out the API service. Authentication is not great, because I'd have to put a user and password in the code and that's prone to problems.

Any ideas on this?

**Comment by gerrytsui** [comment]
cool. problem solved as related to amplify-angular.
 
In our use case, it is ok for us to enter the password in test code  (for a dummy account) and have your code set the test accordingly in Test-Only environment.
 
We use ng e2e, with jasmine & protractor:    page.pswdElement.sendkeys('thePasswordHere');
I guess you can load the password a database / api / file,  just so the password is else where.

**Comment by haverchuck** [comment]
Related to #3085

**Comment by haverchuck** [comment]
@gerrytsui Thanks for your response.  @malcomm I'm closing this issue due to inactivity, but If you are still stuck feel free to open an issue specifically about the storage of variables such as password for e2e testing. Thanks all.
