### ISSUE TITLE
AWS_IAM mode 403 when using custom domain instead of AppSync endpoint

### ISSUE THREAD

**Issue by komushi** [aws-amplify/amplify-js#3452]
**Describe the bug**
AWS_IAM mode 403 when using custom domain instead of AppSync endpoint

**Sample code**
Include additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)
```
Amplify.configure(aws_exports);

const rtn = await Amplify.API.graphql({
	query: createNotification,
	variables: {input: params},
	authMode: 'AWS_IAM'
}).catch(e => {
	return e;
});
```

```
{ data: {},
errors:
[ { GraphQLError: Request failed with status code 403
at APIClass.<anonymous> (/var/task/node_modules/@aws-amplify/api/lib/API.js:547:33)
at step (/var/task/node_modules/@aws-amplify/api/lib/API.js:40:23)
at Object.throw (/var/task/node_modules/@aws-amplify/api/lib/API.js:21:53)
at rejected (/var/task/node_modules/@aws-amplify/api/lib/API.js:13:65)
at process._tickCallback (internal/process/next_tick.js:68:7)
message: 'Request failed with status code 403',
locations: undefined,
path: undefined } ] }
```
My configuration option:
```
const awsmobile = {
    ...
    "aws_appsync_graphqlEndpoint": "https://<domain.managed.by.route53.which.points.to.cloudfront>/graphql",
    "aws_appsync_region": "<myregion>",
    "aws_appsync_authenticationType": "AWS_IAM"
};
```

**Comment by haverchuck** [comment]
@komushi Can you post a little more about what your custom domain is?

**Comment by komushi** [comment]
@haverchuck 

Thanks. Added the configuration option.

**Comment by undefobj** [comment]
@komushi Are you using a custom CloudFront domain in front of AppSync? If so this isn't currently supported by AppSync when using IAM as the [Signature Version 4](https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html) calculation will fail.

**Comment by komushi** [comment]
Understood and thanks
