### ISSUE TITLE
Window is not defined for amplify @ 1.1.29

### ISSUE THREAD

**Issue by andriachmad93** [aws-amplify/amplify-js#3477]
I have problem for use aws-amplify. Why the amplify message show 

/home/backend/Documents/node_modules/youtube-iframe/index.js:50
}(window));
  ^

ReferenceError: window is not defined
    at Object.<anonymous> (/home/backend/node_modules/youtube-iframe/index.js:50:3)
    at Module._compile (module.js:577:32)
    at Module._extensions..js (module.js:586:10)
    at Object.require.extensions.(anonymous function) [as .js] 

(/home/backend/Documents/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/backend/node_modules/@aws-amplify/analytics/src/Providers/AmazonPersonalizeHelper/MediaAutoTrack.ts:13:1)
    at Module._compile (module.js:577:32)
    at Module._extensions..js (module.js:586:10)
    at Object.require.extensions.(anonymous function) [as .js]

 (/home/backend/Documents/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)

When I put command NPM START. Why aws-amplify installed youtube-iframe?

**Comment by pedlop** [comment]
I'm having the same issue.

**Comment by SvetlozarKalchev** [comment]
I am also having this issue, but only on a build machine. I am trying to narrow it down to a version of either @aws-amplify or aws-sdk, but no luck so far. 

I'll report back if I succeed.

**Comment by jhoffmcd** [comment]
I found that I also get this error from `@aws-amplify/ui`. If you are using `yarn` you can resolve the sub dependencies to earlier versions by adding `resolutions` to the `package.json`:

```js
  "resolutions": {
    "@aws-amplify/analytics": "1.2.16",
    "@aws-amplify/ui": "1.0.19"
  },
```

**Comment by aldegoeij** [comment]
referencing tickets #3486, #3506, #3615, #3015, #876, #3477 and webpack/webpack#6522
