### ISSUE TITLE
amplify can't find my appsync after deployment

### ISSUE THREAD

**Issue by damianrr** [aws-amplify/amplify-js#3482]
**Describe the bug**
I have a website in production with 2 envs, I made a css change on dev branch, commit and push, and since I've the amplify console configured, it deployed correctly my website as usual. However, when I merge to master and push, I've a deployment error it saids:

```
2019-06-18T19:11:26.680Z [WARNING]: Error updating cloudformation stack
2019-06-18T19:11:26.738Z [INFO]: Following resources failed
2019-06-18T19:11:26.741Z [INFO]: Resource Name: gzqlhcne2vevvegmn7sd47fldaGraphQLSchema (AWS::AppSync::GraphQLSchema)
                                 Event Type: update
                                 Reason: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 2914FFFA231EC77B; S3 Extended Request ID: tTewGguUd4O4+7SUuU8oMQo3pAkKuNdy06i6HQUe2D6KwD/bE1t5zmtLSPU3T+dewUCakw9Z+W4=)
                                 URL: https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/arn%3Aaws%3Acloudformation%3Aus-east-1%3A155161765563%3Astack%2Fportal-20190528145021-apiportal-1J6HJ2ZE3SERG%2Ffffd3bd0-817a-11e9-b938-0aad5d963972/events
                                 init failed
2019-06-18T19:11:26.742Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
                                    ✖ There was an error initializing your environment.
2019-06-18T19:11:26.744Z [INFO]: { ResourceNotReady: Resource is not in the state stackUpdateComplete
                                 at constructor.setError (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/resource_waiter.js:182:47)
                                 at Request.CHECK_ACCEPTORS (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/resource_waiter.js:44:12)
                                 at Request.callListeners (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                 at Request.emit (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
                                 at Request.transition (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 at Request.<anonymous> (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
                                 at Request.<anonymous> (/root/.nvm/versions/node/v8.12.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
                                 message: 'Resource is not in the state stackUpdateComplete',
                                 code: 'ResourceNotReady',
                                 retryable: false,
                                 time: 2019-06-18T19:11:26.679Z,
                                 statusCode: 200,
                                 retryDelay: 30000 }
2019-06-18T19:11:26.759Z [ERROR]: !!! Build failed
2019-06-18T19:11:26.861Z [ERROR]: !!! Non-Zero Exit Code detected
2019-06-18T19:11:26.861Z [INFO]: # Starting environment caching...
2019-06-18T19:11:26.862Z [INFO]: # Uploading environment cache artifact...
2019-06-18T19:11:26.947Z [INFO]: # Environment caching completed
```
This is happening on my production site, help with this will be be most appreciated!

**Comment by damianrr** [comment]
Sorry, this is fixed. I forgot to push my function's cloudformation template: 
```

                               "Timeout": "25",
                                "Code": {
                                        "S3Bucket": "portal-20190528145021-deployment",
-                                       "S3Key": "amplify-builds/getPredictionData-1560520081-latest-build.zip"
+                                       "S3Key": "amplify-builds/getPredictionData-1560884402-latest-build.zip"
                                }
                        }
                },

```

Follow up question though, why does this changes in every `amplify push`? Is really annoying and doesn't work well with having different git branches.
