### ISSUE TITLE
Imported User (RESET_REQUIRED) throws InvalidParameterException on Auth.signIn

### ISSUE THREAD

**Issue by marcpaskell** [aws-amplify/amplify-js#4516]
** Which Category is your question related to? **
Authentication Flow using `import { Auth } from 'aws-amplify';`

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **
Importing a User into the pool leaves the user in the RESET_REQUIRED status... 

When trying to log that user in with:

`const user = await Auth.signIn(email, password)`

The response is

`{"__type":"InvalidParameterException","message":"Invalid input given"}`

Rather than a challenge or a type that pertains to the actual problem.

I have tested the code and flow with a user created by hand and all works OK.

Thanks

**Comment by ericclemmons** [comment]
@marcpaskell Can you clarify, or provide a screenshot, how you're getting the user into that state?

The user I've been testing with is getting a different error.

Thanks!

**Comment by marcpaskell** [comment]
@ericclemmons - the user is simply imported via the Cognito console, gets the `RESET_REQUIRED` state and as soon as you attempt a login with that user, the lib returns the irrelevant error.

For now, we're just handling it and forcing a password refresh, but it'd be good to have a proper challenge.

**Comment by ericclemmons** [comment]
@marcpaskell I was able to look into this and you're right: the library isn't handling the `RESET_REQUIRED` state and it makes it appear like an input validation error.

Marking this as a bug so we can address it.

@haverchuck Should we fold this in with your Auth v2 work?

**Comment by santhedan** [comment]
I am able to reproduce this in Android SDK of AWSMobileClient as well. The call to signIn just results in the following exception getting logged in logcat.

com.amazonaws.services.cognitoidentityprovider.model.InvalidParameterException: Invalid input given (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: InvalidParameterException; Request ID: XXXXXXX)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:730)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.invoke(AmazonCognitoIdentityProviderClient.java:6292)
        at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.initiateAuth(AmazonCognitoIdentityProviderClient.java:4277)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$24.run(CognitoUser.java:2465)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.continuations.AuthenticationContinuation.continueTask(AuthenticationContinuation.java:124)
        at com.amazonaws.mobile.client.AWSMobileClient$6$1.getAuthenticationDetails(AWSMobileClient.java:1177)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:778)
        at com.amazonaws.mobile.client.AWSMobileClient$6.run(AWSMobileClient.java:1137)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:919)

**Comment by sammartinez** [comment]
@marcpaskell Are you still experiencing this issue? Please let us know
