### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by jeanverster** [aws-amplify/amplify-js#4730]
**Describe the bug**
I recently updated my aws-amplify version to the latest (2.2.2) and now all my tests are failing with the error `ReferenceError: document is not defined`. The issue seems to be with the `@aws-amplify/analytics` package. A workaround for the time being is to add a resolution in my package.json to resolve the analytics package to an older version (pre version 2.x.x) seems to work.

**To Reproduce**

1) run `yarn add aws-amplify` in your React Native app
2) run `yarn test`
3) Get error about document not being defined.

**Expected behavior**
Expect the analytics package to be able to correctly determine that the tests aren't being run in a browser and handle accordingly.

**Screenshots**

<details>
  <summary><strong>Environment</strong></summary>

```
  System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 1.30 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.0 - ~/Repos/babor-app/node_modules/.bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 80.0.3987.53
    Safari: 13.0.4
  npmPackages:
    @apollo/react-components: ^3.1.3 => 3.1.3 
    @apollo/react-hoc: ^3.1.3 => 3.1.3 
    @apollo/react-hooks: ^3.1.3 => 3.1.3 
    @apollo/react-testing: ^3.1.3 => 3.1.3 
    @bankify/react-native-animate-number: ^0.2.1 => 0.2.1 
    @bugsnag/expo: ^6.4.1 => 6.4.1 
    @graphql-codegen/cli: ^1.8.3 => 1.8.3 
    @graphql-codegen/typescript: ^1.8.3 => 1.8.3 
    @graphql-codegen/typescript-operations: ^1.8.3 => 1.8.3 
    @graphql-codegen/typescript-react-apollo: ^1.8.3 => 1.8.3 
    @react-native-community/datetimepicker: ^2.1.0 => 2.1.0 
    @testing-library/react-native: ^4.2.0 => 4.2.0 
    @types/jest: ^24.0.21 => 24.0.22 
    @types/react: ^16.8.23 => 16.9.11 
    @types/react-native: ^0.57.65 => 0.57.65 
    @types/react-native-svg-charts: ^5.0.3 => 5.0.3 
    @types/react-native-tab-view: ^1.0.6 => 1.0.6 
    @types/react-native-vector-icons: ^6.4.4 => 6.4.4 
    @types/react-navigation: ^3.0.8 => 3.0.8 
    @types/styled-components: ^4.1.20 => 4.4.0 
    @types/styled-system: ^5.1.3 => 5.1.3 
    @typescript-eslint/eslint-plugin: ^2.6.1 => 2.6.1 
    @typescript-eslint/parser: ^2.6.1 => 2.6.1 
    apollo-boost: ^0.4.4 => 0.4.4 
    apollo-cache-inmemory: ^1.6.3 => 1.6.3 
    apollo-client: ^2.6.4 => 2.6.4 
    apollo-link: ^1.2.13 => 1.2.13 
    apollo-link-http: ^1.5.16 => 1.5.16 
    aws-amplify: ^2.2.2 => 2.2.2 
    aws-amplify-react-native: ^3.2.0 => 3.2.0 
    aws-appsync: ^2.0.2 => 2.0.2 
    aws-appsync-auth-link: ^1.0.1 => 1.0.1 
    aws-appsync-subscription-link: ^1.0.1 => 1.0.1 
    babel-preset-expo: ^7.1.0 => 7.1.0 
    eslint: ^6.8.0 => 6.8.0 
    eslint-config-prettier: ^6.5.0 => 6.5.0 
    eslint-plugin-prettier: ^3.1.1 => 3.1.1 
    eslint-plugin-react: ^7.16.0 => 7.16.0 
    eslint-plugin-react-native: ^3.8.1 => 3.8.1 
    expo: ^35.0.0 => 35.0.1 
    expo-blur: ~7.0.0 => 7.0.0 
    expo-constants: ~7.0.0 => 7.0.1 
    expo-contacts: ~7.0.0 => 7.0.0 
    expo-file-system: ~7.0.0 => 7.0.0 
    expo-font: ~7.0.0 => 7.0.0 
    expo-image-picker: ~7.0.0 => 7.0.0 
    expo-linear-gradient: ~7.0.0 => 7.0.1 
    expo-permissions: ~7.0.0 => 7.0.0 
    expo-sharing: ~7.0.0 => 7.0.0 
    formik: ^2.0.3 => 2.0.3 
    graphql: ^14.5.8 => 14.5.8 
    husky: ^3.0.9 => 3.0.9 
    jest: ^24.9.0 => 24.9.0 
    jest-expo: ^35.0.0 => 35.0.0 
    jsdom: ^16.0.0 => 16.0.0 
    jwt-decode: ^2.2.0 => 2.2.0 
    moment: ^2.24.0 => 2.24.0 
    prettier: ^1.18.2 => 1.19.1 
    react: 16.8.3 => 16.8.3 
    react-dom: 16.8.3 => 16.8.3 
    react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
    react-native-animatable: ^1.3.3 => 1.3.3 
    react-native-circular-progress: ^1.3.4 => 1.3.4 
    react-native-collapsible: ^1.5.1 => 1.5.1 
    react-native-expo-image-cache: ^4.0.8 => 4.0.8 
    react-native-gesture-handler: ~1.3.0 => 1.3.0 
    react-native-modal-datetime-picker: ^8.1.0 => 8.1.0 
    react-native-reanimated: ~1.2.0 => 1.2.0 
    react-native-redash: ^8.6.0 => 8.6.0 
    react-native-snap-carousel: ^3.8.4 => 3.8.4 
    react-native-styled-toast: ^1.0.15 => 1.0.15 
    react-native-svg: 9.9.5 => 9.9.5 
    react-native-svg-charts: ^5.3.0 => 5.3.0 
    react-native-tab-view: ^2.10.0 => 2.10.0 
    react-native-vector-icons: ^6.6.0 => 6.6.0 
    react-native-web: ^0.11.7 => 0.11.7 
    react-navigation: ^4.0.10 => 4.0.10 
    react-navigation-animated-switch: ^0.3.2 => 0.3.2 
    react-navigation-stack: ^1.10.3 => 1.10.3 
    react-navigation-tabs: ^2.5.6 => 2.5.6 
    semantic-release: ^15.13.30 => 15.13.30 
    semantic-release-expo: ^2.2.3 => 2.2.3 
    semantic-release-git-branches: ^1.2.1 => 1.2.1 
    styled-components: ^4.4.1 => 4.4.1 
    styled-system: ^5.1.2 => 5.1.2 
    svg-path-properties: ^0.5.2 => 0.5.2 
    typescript: ^3.6.3 => 3.7.2 
    yup: ^0.27.0 => 0.27.0 
  npmGlobalPackages:
    @create-labs-app/cli: 1.0.10
    amplify-cli: 1.0.0
    cla-expo: 1.1.0
    depcheck: 0.8.3
    expo-cli: 3.11.5
    fsevents: 2.0.7
    graphql-cli: 3.0.12
    gulp: 4.0.2
    npm: 6.13.1
    react-native-cli: 2.0.1
    react-native-styled-toast: 1.0.15
    semantic-release-cli: 5.2.2
    tsc: 1.20150623.0
    typescript: 3.6.4
```

</details>

**Comment by amhinson** [comment]
Hey @jeanverster, are you still seeing this error? So far, I have been unsuccessful in reproducing the issue with version 2.2.2. 

Would you be able to try with the latest major version of `aws-amplify` (currently `3.0.5`) and let me know if the error persists?

Also, if you could provide some additional details to the steps to reproduce or a basic example repo, that would be great. 😄

**Comment by tncbbthositg** [comment]
I'm currently having this issue on a react-native project.  :(

```
  ● Test suite failed to run

    ReferenceError: document is not defined

      at Object.<anonymous> (node_modules/@aws-amplify/analytics/src/vendor/dom-utils/parse-url.ts:11:42)
      at Object.<anonymous> (node_modules/@aws-amplify/analytics/src/vendor/dom-utils/index.ts:7:1)
```

I'll keep digging . . .

**Comment by amhinson** [comment]
@tncbbthositg Could you post the output of this so we can try to reproduce the issue?

`npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages`

Also, if you have a code snippet of how you're using Amplify in your project, that would be helpful as well.

**Comment by tncbbthositg** [comment]
@amhinson, here's the environment:

```
  System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 2.63 GB / 16.00 GB
    Shell: 5.0.11 - /usr/local/bin/bash
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 80.0.3987.163
    Firefox: 69.0
    Safari: 13.0.4
  npmPackages:
    @babel/plugin-proposal-decorators: ^7.7.4 => 7.7.4 
    @babel/plugin-proposal-export-namespace-from: ^7.7.4 => 7.7.4 
    @expo/vector-icons: ^10.0.0 => 10.0.6 
    @react-native-community/eslint-config: 0.0.6 => 0.0.6 
    @types/enzyme: ^3.10.4 => 3.10.4 
    @types/jest: ^24.0.25 => 24.0.25 
    @types/moment-timezone: ^0.5.12 => 0.5.12 
    @types/react: ^16.8.23 => 16.9.5 
    @types/react-native: ^0.57.65 => 0.57.65 
    @types/react-navigation: ^3.0.5 => 3.0.5 
    @types/validator: ^10.11.3 => 10.11.3 
    @typescript-eslint/eslint-plugin: ^2.3.3 => 2.3.3 
    @typescript-eslint/parser: ^2.3.3 => 2.3.3 
    aws-amplify: ^2.2.2 => 2.2.2 
    aws-amplify-react-native: ^2.3.3 => 2.3.3 
    aws-appsync: ^1.0.17 => 1.0.17 
    aws-appsync-react: ^1.0.10 => 1.0.10 
    aws-sdk: ^2.6.16 => 2.598.0 
    awsmobile-cli: ^1.1.7 => 1.1.7 
    babel-eslint: ^10.0.3 => 10.0.3 
    babel-preset-expo: ^7.0.0 => 7.0.0 
    describe-react-element: ^0.1.0 => 0.1.0 
    enzyme: ^3.11.0 => 3.11.0 
    enzyme-adapter-react-16: ^1.15.2 => 1.15.2 
    eslint: ^6.1.0 => 6.1.0 
    eslint-config-airbnb: ^18.0.1 => 18.0.1 
    eslint-plugin-import: ^2.18.2 => 2.18.2 
    eslint-plugin-jsx-a11y: ^6.2.3 => 6.2.3 
    eslint-plugin-react: ^7.16.0 => 7.16.0 
    eslint-plugin-react-hooks: ^1.7.0 => 1.7.0 
    expo: ^35.0.0 => 35.0.0 
    expo-ads-facebook: ~7.0.0 => 7.0.0 
    expo-constants: ~7.0.0 => 7.0.0 
    expo-font: ~7.0.0 => 7.0.0 
    expo-image-manipulator: ~7.0.0 => 7.0.0 
    expo-image-picker: ~7.0.0 => 7.0.0 
    expo-permissions: ~7.0.0 => 7.0.0 
    expo-vector-icons: ^10.0.1 => 10.0.1 
    expokit: ^35.0.3 => 35.0.4 
    graphql-tag: ^2.9.1 => 2.9.1 
    hoist-non-react-statics: ^2.5.0 => 2.5.0 
    immutability-helper: ^2.7.1 => 2.7.1 
    jest: ^24.9.0 => 24.9.0 
    jest-enzyme: ^7.1.2 => 7.1.2 
    jest-expo: ^35.0.0 => 35.0.0 
    jetifier: ^1.6.4 => 1.6.4 
    jsonfile-updater: ^3.1.0 => 3.1.0 
    lodash: ^4.17.10 => 4.17.10 
    metro-react-native-babel-preset: ^0.57.0 => 0.57.0 
    mobx: ^5.9.0 => 5.9.0 
    mobx-react: ^5.4.3 => 5.4.3 
    moment-duration-format: ^2.2.2 => 2.2.2 
    moment-timezone: ^0.5.17 => 0.5.17 
    native-base: ^2.13.8 => 2.13.8 
    prop-types: ^15.7.2 => 15.7.2 
    react: 16.8.6 => 16.8.6 
    react-apollo: ^2.1.11 => 2.1.11 
    react-devtools: ^3.2.1 => 3.2.1 
    react-dom: ^16.12.0 => 16.12.0 
    react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
    react-native-expo-image-cache: ^3.1.1 => 3.1.1 
    react-native-gesture-handler: ~1.3.0 => 1.3.0 
    react-native-iap: ^4.2.0 => 4.2.0 
    react-native-indicators: ^0.13.0 => 0.13.0 
    react-native-iphone-x-helper: ^1.2.0 => 1.2.0 
    react-native-linear-gradient: ^2.5.6 => 2.5.6 
    react-native-mask-loader: 0.0.3 => 0.0.3 
    react-native-mime-types: ^2.2.1 => 2.2.1 
    react-native-modal: ^6.5.0 => 6.5.0 
    react-native-modal-datetime-picker: ^7.4.2 => 7.4.2 
    react-native-purchases: ^3.0.6 => 3.0.6 
    react-native-reanimated: ~1.2.0 => 1.2.0 
    react-native-scripts: ^1.14.0 => 1.14.0 
    react-native-status-bar-height: ^2.4.0 => 2.4.0 
    react-native-typescript-transformer: ^1.2.12 => 1.2.12 
    react-native-unimodules: ^0.6.0 => 0.6.0 
    react-navigation: ^3.11.1 => 3.13.0 
    react-navigation-header-buttons: 0.0.7 => 0.0.7 
    react-test-renderer: 16.3.1 => 16.3.1 
    rn-viewpager: https://github.com/tncbbthositg/React-Native-ViewPager.git => 1.2.9 
    typescript: ^3.4.5 => 3.6.4 
    uuid: ^3.3.2 => 3.3.2 
    validator: ^10.8.0 => 10.8.0 
  npmGlobalPackages:
    @aws-amplify/cli: 4.16.1
    expo-cli: 3.15.4
    gulp-cli: 2.2.0
    npm: 6.13.4
```

I'm not explicitly using amplify analytics.  I'm explicitly using `I18n`, `Auth`, `Storage`, and `Logger` from Amplify.

I tend to use `index.js` files for groups of components.  I changed one of my tests to import the component specifically and the test runs and passes.

I then added this and the error came back: 
```
import { I18n } from 'aws-amplify';
// ...

I18n.get('oh noes');
```

This makes sense to me because importing anything from `aws-amplify` requires `@aws-amplify/analytics`.  `@aws-amplify/analytics` requires `trackers` which requires `EventTracker` which requires `dom-utils` which requires `parse-url` which throws the error during testing.

I haven't debugged this when running the application yet because I haven't seen this error in the react native application.  But, `@aws-amplify/core`'s `JS.browserOrNode()` is returning this:
```
{ isBrowser: true, isNode: true }
```

It seems like, in Jest, global is window . . . I haven't dug in to see why that's the case with the`"testEnivronment": "node"` configuration.

https://github.com/facebook/jest/issues/3692#issuecomment-408132529

If I replace the 2.2.2 implementation with the 3.0.6 implementation, it correctly identifies that it's not a browser test.  I don't know if that's the end of my woes because another error comes up, but I'm not sure if it's amplify related.

```
    JS.browserOrNode = function () {
      const isBrowser =
        typeof window !== 'undefined' && typeof window.document !== 'undefined';

      const isNode =
        typeof process !== 'undefined' &&
        process.versions != null &&
        process.versions.node != null;

      return {
        isBrowser,
        isNode,
      };
    };

    // JS.browserOrNode = function () {
    //     // function to check if the global scope is "window"
    //     var isBrowser = new Function('try {return this===window;}catch(e){ return false;}');
    //     // function to test if global scope is binded to "global"
    //     var isNode = new Function('try {return this===global;}catch(e){return false;}');
    //     return {
    //         isBrowser: isBrowser(),
    //         isNode: isNode(),
    //     };
    // };
```

**Comment by amhinson** [comment]
Thanks for the info! What error are you seeing with 3.0.6?

**Comment by tncbbthositg** [comment]
It's `Invariant Violation: Native module cannot be null.` when importing `react-native-purchases`.  I don't think it's amplify related because I can mock that library out and most of the tests pass without error.

Just to make sure I was clear, I didn't update amplify yet (because we're prepping for a release and updating amplify can be effortful sometimes).  I just patched the JS.js file in `node_modules` just to debug the issue.

**Comment by amhinson** [comment]
Ah ok. Well when you get some time, I'd recommend updating to the latest version of aws-amplify  because there are quite a bit of improvements in the v3 release 🙂

**Comment by tncbbthositg** [comment]
@amhinson, will do!  Thanks a lot for all the hard work.  Amplify has helped us out quite a bit.

Also, I put this in my test setup as a very hacky temporary fix to the current issue (don't judge me):

```
// TODO: remove this as soon as we can update amplify
(global as any).window = { ...global };
```
