### ISSUE TITLE
AuthError - Challenge response cannot be empty

### ISSUE THREAD

**Issue by GaurangBhatt** [aws-amplify/amplify-js#4776]
**Describe the bug**
I am stuck with the below error when using aws-amplify in my react app. Auth.signIn is returning the confirmed user from cognito pool. I also receive the verification code via SMS. However, when I try to call Auth.sendCustomChallengeAnswer I am getting below error. Note that Auth.signIn and Auth.sendCustomChallengeAnswer are in two different methods. Please advise.

**Expected behavior**
Step 1: User enters phone number, first name and last name and clicks "Sign In"  **(Working)**
Step 2: Auth.signIn is called that returns verification code via SMS **(Working)** 
Step3: User enters the 6 digit verification code and clicks "Verify" **(Working)** 
Step 4: Auth.sendCustomChallengeAnswer should verify that the verification code entered by the user matches what was sent in Step 2. ** NOT WORKING **

 **SignIn and Verify code** 
```
  handleSignIn = (a) => (param) => (e) => {
    if (this.validator.fieldValid('First Name')
          && this.validator.fieldValid('Last Name')
          && this.validator.fieldValid('Phone Number')) {

      let username = "+01" + this.state.phoneNumber.replace(/[^\d]/g, '');
      Auth.signIn({
          username, // Required, the username
      }).then(user => {
        console.log(user);
        this.setState({
          ['formActivePanel' + a]: param,
          ['formActivePanel' + a + 'Changed']: true,
          cognitoUser: user,
        });
      }).catch(err => {
        console.log(err);
        //TODO Handle ERROR
      });
    } else {
      this.validator.showMessageFor('First Name');
      this.validator.showMessageFor('Last Name');
      this.validator.showMessageFor('Phone Number');
    }
  }

  handleVerify = () => {
    if (this.validator.fieldValid('Verification code')) {
      let opt = { code: "123456" };//this.state.otpCode;
      let user = this.state.cognitoUser;
      console.log(opt);
      console.log(this.state.cognitoUser);

      Auth.sendCustomChallengeAnswer({
        user,
        opt,
      }).then(user => {
        console.log(user);
      }).catch(err => {
        console.log(err);
        //TODO Handle ERROR
      });

    } else {
      this.validator.showMessageFor('Verification code');
    }
  }
```

**ERROR**
```
[ERROR] 46:49.568 AuthError - Challenge response cannot be empty
AuthError: Challenge response cannot be empty
    at new AuthError (http://localhost:3000/static/js/0.chunk.js:9585:20)
    at AuthClass.rejectAuthError (http://localhost:3000/static/js/0.chunk.js:9506:27)
    at AuthClass.sendCustomChallengeAnswer (http://localhost:3000/static/js/0.chunk.js:8376:19)
    at Header.handleVerify (http://localhost:3000/static/js/main.chunk.js:979:58)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/0.chunk.js:205204:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/0.chunk.js:205253:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/0.chunk.js:205306:35)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/static/js/0.chunk.js:205321:29)
    at executeDispatch (http://localhost:3000/static/js/0.chunk.js:205452:7)
    at executeDispatchesInOrder (http://localhost:3000/static/js/0.chunk.js:205477:9)
```

**Device (please complete the following information):**
- macOS Catalina version 10.15.2
- Chrome
- "aws-amplify": "^2.2.2"

**Comment by GaurangBhatt** [comment]
This issue fixed.

I changed how I was sending values to Auth. sendCustomChallengeAnswer

**Error**
```
Auth.sendCustomChallengeAnswer({
        user,
        opt,
      }).then(user => {
        console.log(user);
      }).catch(err => {
        console.log(err);
        //TODO Handle ERROR
      });
```

**Working**
```
handleVerify = () => {
    if (this.validator.fieldValid('Verification code')) {
      let opt = String(this.state.otpCode);
      let user = this.state.cognitoUser;
      Auth.sendCustomChallengeAnswer(user, opt)
      .then(user => {
        console.log(user);
      }).catch(err => {
        console.log(err);
        //TODO Handle ERROR
      });
    } else {
      this.validator.showMessageFor('Verification code');
    }
  }
```
