### ISSUE TITLE
jest-haste-map: Haste module naming collision:   -> namefunction <-

### ISSUE THREAD

**Issue by esuarezz** [aws-amplify/amplify-js#4792]
**To Reproduce**
1) amplify add function
2) function is created locally correctly
3) amplify push and pushed correctly
4)  when I run expo I get:

```
INFO
22:55
Starting Metro Bundler on port 19001.
ERROR
22:55
jest-haste-map: Haste module naming collision: funcionlambdaparadietas
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/amplify/#current-cloud-backend/function/funcionlambdaparadietas/src/package.json
    * <rootDir>/amplify/backend/function/funcionlambdaparadietas/src/package.json

ERROR
22:55
Failed to construct transformer:  { Error: Duplicated files or mocks. Please check the console for more info
    at setModule (/Users/elio/WebstormProjects/Hapsto-app/node_modules/jest-haste-map/build/index.js:620:17)
    at workerReply (/Users/elio/WebstormProjects/Hapsto-app/node_modules/jest-haste-map/build/index.js:691:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  mockPath1:
   'amplify/#current-cloud-backend/function/funcionlambdaparadietas/src/package.json',
  mockPath2:
   'amplify/backend/function/funcionlambdaparadietas/src/package.json' }
ERROR
22:55
(node:61503) UnhandledPromiseRejectionWarning: Error: Duplicated files or mocks. Please check the console for more info
    at setModule (/Users/elio/WebstormProjects/Hapsto-app/node_modules/jest-haste-map/build/index.js:620:17)
    at workerReply (/Users/elio/WebstormProjects/Hapsto-app/node_modules/jest-haste-map/build/index.js:691:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:61503) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:61503) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
INFO
22:55
Tunnel ready.
```

###

**Comment by dantasfiles** [comment]
https://github.com/aws/awsmobile-cli/issues/172#issuecomment-502989258
