### ISSUE TITLE
Jest/Nrwl tests using amplify fail

### ISSUE THREAD

**Issue by mattmbrightside** [aws-amplify/amplify-js#4812]
**Describe the bug**
Jest + Nrwl tests using amplify fail

**To Reproduce**
Create an Angular application using Nx
Inject AmplifyService into an Angular component
Write a Jest test for that component
Run the test

**Expected behavior**
Tests can execute using nx test or jest cli commands

Same issue as reported in closed issue #3531 

```
● Test suite failed to run

Jest encountered an unexpected token
/node_modules/aws-amplify-angular/index.ts:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export { AmplifyAngularModule } from './src/aws-amplify-angular.module';
                                                                                         ^^^^^^

SyntaxError: Unexpected token export

  2 | import { Auth } from 'aws-amplify';
  3 | import { Router } from '@angular/router';
> 4 | import { AmplifyService } from 'aws-amplify-angular';
    | ^
at ScriptTransformer._transformAndBuildScript (../../node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
at ScriptTransformer.transform (../../node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
at Object. (src/app/app.component.ts:4:1)
```

In package.json I have config
```
  "jest": {
    "preset": "jest-preset-angular",
    "setupFilesAfterEnv": [
      "<rootDir>/apps/desktop/src/test-setup.ts"
    ],
    "testPathIgnorePatterns": [
      "<rootDir>/node_modules/",
      "<rootDir>/dist/",
    ],
    "moduleNameMapper": {
      "@mycompany/(.*)": "<rootDir>/libs/mycompany-ui/src/index.ts"
    },
    "globals": {
      "ts-jest": {
        "diagnostics": false,
        "tsConfig": "<rootDir>/apps/desktop/tsconfig.spec.json",
        "stringifyContentPathRegex": "\\.html$",
        "astTransformers": [
          "<rootDir>/node_modules/jest-preset-angular/InlineHtmlStripStylesTransformer"
        ]
      }
    }
  }
```

**Comment by ajonp** [comment]
Has anyone had any luck with this? I keep bouncing between that error then adding 

jest.config.js
```
  transformIgnorePatterns: ['node_modules/(?!aws-amplify-angular)']
```

Results in various
TypeError: Unable to require `.d.ts` file. errors

**Comment by ericclemmons** [comment]
We've moved our UI efforts into `@aws-amplify/ui-angular`:
> https://docs.amplify.aws/ui/q/framework/angular

Can you give that a shot & let us know if you're still experiencing issues?

**Comment by bmcilw1** [comment]
I'm still seeing this error

**Comment by gruckionvit** [comment]
Me too it's really unclear how this is supposed to work. I've followed @brookemitchell from this post https://github.com/aws-amplify/amplify-js/issues/2686#issuecomment-480044712

With no success though. I've listed the npm packages that need to be transpiled. But my unit tests continue to fail for the same reason.

## More detail:

6 tests are failing with the following.

```
➜  my-project git:(feature/update-async-storage) ✗ npm run test

> my-project@0.0.1 test /Users/first.last/workdir/my-project
> jest

 PASS   iOS  app/services/api/api-problem.test.ts (6.106s)
 PASS   Android  app/services/api/api-problem.test.ts (6.136s)
 PASS   iOS  test/i18n.test.ts (6.169s)
 PASS   iOS  app/models/extensions/with-status.test.ts (6.199s)
 PASS   Android  app/utils/storage/storage.test.ts (6.213s)
 PASS   Android  app/models/extensions/with-status.test.ts (6.28s)
 PASS   iOS  app/utils/storage/storage.test.ts (6.355s)
 PASS   Android  test/i18n.test.ts (6.405s)
 PASS   iOS  app/models/feature-store/feature-store.test.ts (7.411s)
 PASS   Android  app/models/feature-store/feature-store.test.ts (7.408s)
 FAIL   Android  app/models/features/features.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/first.last/workdir/my-project/node_modules/graphql/error/GraphQLError.mjs:9
    import { printError } from './printError';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime._execModule (node_modules/jest-runtime/build/index.js:1157:58)
      at Object.<anonymous> (node_modules/@aws-amplify/api-graphql/src/GraphQLAPI.ts:13:1)

 FAIL   iOS  app/models/features/features.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/first.last/workdir/my-project/node_modules/graphql/error/GraphQLError.mjs:9
    import { printError } from './printError';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime._execModule (node_modules/jest-runtime/build/index.js:1157:58)
      at Object.<anonymous> (node_modules/@aws-amplify/api-graphql/src/GraphQLAPI.ts:13:1)

 FAIL   iOS  app/models/current-user/current-user.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/first.last/workdir/my-project/node_modules/graphql/error/GraphQLError.mjs:9
    import { printError } from './printError';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
        at compileFunction (<anonymous>)

      at Runtime._execModule (node_modules/jest-runtime/build/index.js:1157:58)
      at Object.<anonymous> (node_modules/@aws-amplify/api-graphql/src/GraphQLAPI.ts:13:1)

 FAIL   Android  app/models/current-user/current-user.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/first.last/workdir/my-project/node_modules/graphql/error/GraphQLError.mjs:9
    import { printError } from './printError';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
        at compileFunction (<anonymous>)

      at Runtime._execModule (node_modules/jest-runtime/build/index.js:1157:58)
      at Object.<anonymous> (node_modules/@aws-amplify/api-graphql/src/GraphQLAPI.ts:13:1)

 FAIL   iOS  test/storyshots.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/first.last/workdir/my-project/node_modules/node-fetch/lib/index.mjs:1
    import Stream from 'stream';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
        at compileFunction (<anonymous>)

      at Runtime._execModule (node_modules/jest-runtime/build/index.js:1157:58)
      at Object.<anonymous> (node_modules/@storybook/core/dist/server/build-dev.js:31:41)

 FAIL   Android  test/storyshots.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/first.last/workdir/my-project/node_modules/node-fetch/lib/index.mjs:1
    import Stream from 'stream';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
        at compileFunction (<anonymous>)

      at Runtime._execModule (node_modules/jest-runtime/build/index.js:1157:58)
      at Object.<anonymous> (node_modules/@storybook/core/dist/server/build-dev.js:31:41)

Test Suites: 6 failed, 10 passed, 16 total
Tests:       46 passed, 46 total
Snapshots:   0 total
Time:        28.163s
Ran all test suites in 2 projects.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project@0.0.1 test: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-project@0.0.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/first.last/.npm/_logs/2021-02-09T16_54_36_584Z-debug.log
```

Conclusion `@aws-amplify` is using `graphql` 4 failed tests due to this. Another 2 for `@storybook/core` because it is using `node-fetch`.

Here is my jest.config.json

```
{
  "setupFilesAfterEnv": [
    "./jest.setup.js"
  ],
  "transformIgnorePatterns": [
    "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|native-base|@storybook|@aws-amplify|graphql|node-fetch)"
  ],
  "projects": [
    {
      "preset": "jest-expo/ios"
    },
    {
      "preset": "jest-expo/android"
    }
  ]
}

```

As you can see I have `@storybook|@aws-amplify|graphql|node-fetch` all of these listed. It still doesn't work. Here is both my `babel.config.js` and `tsconfig.json`.

```js
module.exports = {
  presets: ["module:metro-react-native-babel-preset"],
  env: {
    production: {},
  },
  plugins: [
    [
      "@babel/plugin-proposal-decorators",
      {
        legacy: true,
      },
    ],
    ["@babel/plugin-proposal-optional-catch-binding"],
  ],
}
```

```ts
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "jsx": "react-native",
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "noImplicitAny": false,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "sourceMap": true,
    "lib": ["esnext"],
    "skipLibCheck": true,                     /* Skip type checking of declaration files. */
    "forceConsistentCasingInFileNames": true,  /* Disallow inconsistently-cased references to the same file. */
    "esModuleInterop": true,                  /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
    "strict": true,                           /* Enable all strict type-checking options. */
    "resolveJsonModule": true,
    "isolatedModules": true,
    "baseUrl": "app",
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
  },
  "exclude": ["node_modules"],
  "include": ["App.js", "app", "test", "storybook", "jest.setup.js"]
}
```

Here's my jest.setup.js for good measure too;

```js
// Provides access to matchers https://github.com/testing-library/jest-native
import '@testing-library/jest-native/extend-expect'

jest.setTimeout(10000) // in milliseconds
```

If any one knows why this feature doesn't appear to work would appreciate some advice.

## Conclusion

I am not importing `node-fetch` or `graphql` directly mind you. These are both being used via `@aws-amplify` and `@storybook` respectively`. So I am wondering if it is a limitation when dependencies of dependencies when using `transformIgnorePatterns`?
