### ISSUE TITLE
Cannot find module 'amplify-frontend-javascript'

### ISSUE THREAD

**Issue by ericclemmons** [aws-amplify/amplify-js#4833]
**Describe the bug**

Following along to https://aws-amplify.github.io/docs/js/datastore#using-npx in a `/tmp` folder results in:

```console
❯ npx amplify-app@latest
npx: installed 94 in 6.599s
✅ Found Amplify CLI version 4.13.1
🎸 Creating base Amplify project
{ Error: Cannot find module 'amplify-frontend-javascript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at validFrontends.forEach.key (/Users/ecclemm/.npm/_npx/96925/lib/node_modules/amplify-app/src/index.js:185:31)
    at Array.forEach (<anonymous>)
    at guessPlatform (/Users/ecclemm/.npm/_npx/96925/lib/node_modules/amplify-app/src/index.js:184:20)
    at getProjectConfig (/Users/ecclemm/.npm/_npx/96925/lib/node_modules/amplify-app/src/index.js:151:51)
    at ChildProcess.createSkeletonAmplifyProject.on.code (/Users/ecclemm/.npm/_npx/96925/lib/node_modules/amplify-app/src/index.js:115:18)
    at ChildProcess.emit (events.js:198:13) code: 'MODULE_NOT_FOUND' }
```

**To Reproduce**

1. `cd /tmp`
1. `npx create-react-app amplify-datastore --use-npm`
1. `cd amplify-datastore`
1. `npx amplify-app@latest`

**Expected behavior**

Expected `npx amplify-app@latest` to work.

**Screenshots**

<details>
  <summary><strong>Environment</strong></summary>

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 441.55 MB / 16.00 GB
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 10.18.1 - ~/.config/nvm/10.18.1/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.config/nvm/10.18.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 68.4.2
    Safari: 13.0.5
  npmPackages:
    @testing-library/jest-dom: ^4.2.4 => 4.2.4
    @testing-library/react: ^9.4.0 => 9.4.0
    @testing-library/user-event: ^7.2.1 => 7.2.1
    react: ^16.12.0 => 16.12.0
    react-dom: ^16.12.0 => 16.12.0
    react-scripts: 3.3.1 => 3.3.1
  npmGlobalPackages:
    @aws-amplify/cli: 4.13.1
    npm: 6.13.4
```

</details>

**Comment by ericclemmons** [comment]
Where is `amplify-app` located?  There's no repository URL associated with it:
> https://www.npmjs.com/package/amplify-app

**Comment by ericclemmons** [comment]
Was working on reproducing https://github.com/aws-amplify/amplify-js/issues/4827 when I ran into this problem

**Comment by ashika01** [comment]
@ericclemmons I think this should be with the CLI.
