### ISSUE TITLE
Unexpected identifier

### ISSUE THREAD

**Issue by jcardus** [aws-amplify/amplify-js#5091]
**Describe the bug**
Just initializing amplify from scratch

**To Reproduce**
sudo npm install -g @aws-amplify/cli
amplify init
 amplify add auth

**Expected behavior**
Should work

**Current behaviour**
$ amplify add auth
Unexpected identifier
SyntaxError: Unexpected identifier
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/commands/auth/enable.js:22:8)
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/index.js:284:23)
    at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:131:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

** OS **
Mac

**Comment by jcardus** [comment]
For the record, I solved this by deleting the @aws-amplify folder in /usr/local/lib/node_modules.

**Comment by krikork** [comment]
I was getting this problem when adding storage. What fixed it for me is upgrading Node to the latest version.
