### ISSUE TITLE
import { Logger } from '@aws-amplify/core - amplify build fails, vs local build works

### ISSUE THREAD

**Issue by dakoller** [aws-amplify/amplify-js#5158]
Hi,

my build on amplify angular get broken, when including amplifyService.

The most immediate error I spot is a failure to 

"import { Logger } from '@aws-amplify/core". 

Interestingly the build works on my local windows10 local dev environment, but builds on aws fail.

My build output:
`2020-03-20T07:54:47.317Z [INFO]: Git SSH Key acquired
2020-03-20T07:54:47.400Z [INFO]: # Cloning repository: git@gitlab.com:dakoller/planningpilot.git
2020-03-20T07:54:47.531Z [INFO]: Agent pid 125
2020-03-20T07:54:47.558Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2020-03-20T07:54:47.739Z [INFO]: Cloning into 'planningpilot'...
2020-03-20T07:54:48.366Z [INFO]: Warning: Permanently added the ECDSA host key for IP address '35.231.145.151' to the list of known hosts.
2020-03-20T07:54:49.699Z [INFO]: # Switching to commit: 19049a08349a64112f24e876746d949af39ecb3d
2020-03-20T07:54:49.802Z [INFO]: Note: checking out '19049a08349a64112f24e876746d949af39ecb3d'.
                                 You are in 'detached HEAD' state. You can look around, make experimental
                                 changes and commit them, and you can discard any commits you make in this
                                 state without impacting any branches by performing another checkout.
                                 If you want to create a new branch to retain commits you create, you may
                                 do so (now or later) by using -b with the checkout command again. Example:
                                 git checkout -b <new-branch-name>
                                 HEAD is now at 19049a0 AmplifyService reactivated
2020-03-20T07:54:49.802Z [INFO]: # Checking for Git submodules at: /codebuild/output/src947856100/src/planningpilot/.gitmodules
2020-03-20T07:54:49.832Z [INFO]: # Retrieving cache...
2020-03-20T07:54:53.203Z [INFO]: # Extracting cache...
2020-03-20T07:54:59.333Z [INFO]: # Extraction completed
2020-03-20T07:54:59.461Z [INFO]: # Retrieving environment cache...
2020-03-20T07:54:59.548Z [INFO]: # Retrieved environment cache
2020-03-20T07:54:59.550Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: 'latest'
2020-03-20T07:55:06.770Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 1.12.0 to 4.16.1...
2020-03-20T07:55:58.729Z [INFO]: # Done patching NPM package '@aws-amplify/cli'
2020-03-20T07:56:07.647Z [INFO]: ## Starting Backend Build
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2020-03-20T07:56:12.329Z [INFO]: 
2020-03-20T07:56:12.331Z [INFO]: For more information on AWS Profiles, see:
                                 https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html
2020-03-20T07:56:12.693Z [INFO]: Amplify AppID found: d1857l5ljomn40. Amplify App name is: planningpilot
2020-03-20T07:56:12.808Z [INFO]: Backend environment prod found in Amplify Console app: planningpilot
2020-03-20T07:56:13.057Z [INFO]: 
2020-03-20T07:56:13.867Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2020-03-20T07:56:18.408Z [WARNING]: - Initializing your environment: prod
2020-03-20T07:56:18.636Z [WARNING]: ✔ Initialized provider successfully.
2020-03-20T07:56:18.647Z [WARNING]: - Updating resources in the cloud. This may take a few minutes...
2020-03-20T07:56:18.794Z [WARNING]: ✔ All resources are updated in the cloud
2020-03-20T07:56:18.794Z [INFO]: 
2020-03-20T07:56:18.795Z [INFO]: 
2020-03-20T07:56:18.996Z [INFO]: Initialized your environment successfully.
2020-03-20T07:56:18.997Z [INFO]: Your project has been successfully initialized and connected to the cloud!
                                 Some next steps:
                                 "amplify status" will show you what you've added already and if it's locally configured or deployed
                                 "amplify add <category>" will allow you to add features like user login or a backend API
                                 "amplify push" will build all your local backend resources and provision it in the cloud
                                 “amplify console” to open the Amplify Console and view your project status
                                 "amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud
                                 Pro tip:
                                 Try "amplify add api" to create a backend API and then "amplify publish" to deploy everything
2020-03-20T07:56:19.014Z [INFO]: # Completed phase: build
                                 ## Completed Backend Build
2020-03-20T07:56:19.014Z [INFO]: ## Starting Frontend Build
                                 # Starting phase: preBuild
                                 # Executing command: npm ci
2020-03-20T07:56:19.481Z [WARNING]: npm
2020-03-20T07:56:19.483Z [WARNING]: WARN prepare removing existing node_modules/ before installation
2020-03-20T07:56:32.714Z [INFO]: > fsevents@1.2.11 install /codebuild/output/src947856100/src/planningpilot/node_modules/webpack-dev-server/node_modules/fsevents
                                 > node-gyp rebuild
2020-03-20T07:56:32.842Z [WARNING]: gyp
2020-03-20T07:56:32.842Z [WARNING]: 
2020-03-20T07:56:32.843Z [WARNING]: info it worked if it ends with ok
2020-03-20T07:56:32.844Z [WARNING]: gyp
2020-03-20T07:56:32.845Z [WARNING]: info using node-gyp@3.8.0
                                    gyp info using node@10.16.0 | linux | x64
2020-03-20T07:56:33.802Z [WARNING]: gyp
2020-03-20T07:56:33.803Z [WARNING]: info spawn /usr/bin/python2
                                    gyp info spawn args [ '/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
                                    gyp info spawn args   'binding.gyp',
                                    gyp info spawn args   '-f',
                                    gyp info spawn args   'make',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/codebuild/output/src947856100/src/planningpilot/node_modules/webpack-dev-server/node_modules/fsevents/build/config.gypi',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/root/.node-gyp/10.16.0/include/node/common.gypi',
                                    gyp info spawn args   '-Dlibrary=shared_library',
                                    gyp info spawn args   '-Dvisibility=default',
                                    gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/10.16.0',
                                    gyp info spawn args   '-Dnode_gyp_dir=/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp',
                                    gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/10.16.0/<(target_arch)/node.lib',
                                    gyp info spawn args   '-Dmodule_root_dir=/codebuild/output/src947856100/src/planningpilot/node_modules/webpack-dev-server/node_modules/fsevents',
                                    gyp info spawn args   '-Dnode_engine=v8',
                                    gyp info spawn args   '--depth=.',
                                    gyp info spawn args   '--no-parallel',
                                    gyp info spawn args   '--generator-output',
                                    gyp info spawn args   'build',
                                    gyp info spawn args   '-Goutput_dir=.' ]
2020-03-20T07:56:34.148Z [WARNING]: gyp info spawn make
2020-03-20T07:56:34.149Z [WARNING]: gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
2020-03-20T07:56:34.150Z [INFO]: make: Entering directory `/codebuild/output/src947856100/src/planningpilot/node_modules/webpack-dev-server/node_modules/fsevents/build'
2020-03-20T07:56:34.172Z [INFO]: SOLINK_MODULE(target) Release/obj.target/.node
2020-03-20T07:56:34.637Z [INFO]: COPY Release/.node
2020-03-20T07:56:34.644Z [INFO]: make: Leaving directory `/codebuild/output/src947856100/src/planningpilot/node_modules/webpack-dev-server/node_modules/fsevents/build'
2020-03-20T07:56:34.644Z [WARNING]: gyp
2020-03-20T07:56:34.644Z [WARNING]: info ok
2020-03-20T07:56:34.704Z [INFO]: > fsevents@1.2.11 install /codebuild/output/src947856100/src/planningpilot/node_modules/watchpack/node_modules/fsevents
                                 > node-gyp rebuild
2020-03-20T07:56:34.805Z [WARNING]: gyp
2020-03-20T07:56:34.806Z [WARNING]: 
2020-03-20T07:56:34.806Z [WARNING]: info it worked if it ends with ok
2020-03-20T07:56:34.808Z [WARNING]: gyp
2020-03-20T07:56:34.808Z [WARNING]: info using node-gyp@3.8.0
                                    gyp info using node@10.16.0 | linux | x64
2020-03-20T07:56:34.963Z [WARNING]: gyp
2020-03-20T07:56:34.965Z [WARNING]: info spawn /usr/bin/python2
                                    gyp info spawn args [ '/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
                                    gyp info spawn args   'binding.gyp',
                                    gyp info spawn args   '-f',
                                    gyp info spawn args   'make',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/codebuild/output/src947856100/src/planningpilot/node_modules/watchpack/node_modules/fsevents/build/config.gypi',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/root/.node-gyp/10.16.0/include/node/common.gypi',
                                    gyp info spawn args   '-Dlibrary=shared_library',
                                    gyp info spawn args   '-Dvisibility=default',
                                    gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/10.16.0',
                                    gyp info spawn args   '-Dnode_gyp_dir=/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp',
                                    gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/10.16.0/<(target_arch)/node.lib',
                                    gyp info spawn args   '-Dmodule_root_dir=/codebuild/output/src947856100/src/planningpilot/node_modules/watchpack/node_modules/fsevents',
                                    gyp info spawn args   '-Dnode_engine=v8',
                                    gyp info spawn args   '--depth=.',
                                    gyp info spawn args   '--no-parallel',
                                    gyp info spawn args   '--generator-output',
                                    gyp info spawn args   'build',
                                    gyp info spawn args   '-Goutput_dir=.' ]
2020-03-20T07:56:35.016Z [WARNING]: gyp
2020-03-20T07:56:35.017Z [WARNING]: info spawn make
                                    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
2020-03-20T07:56:35.018Z [INFO]: make: Entering directory `/codebuild/output/src947856100/src/planningpilot/node_modules/watchpack/node_modules/fsevents/build'
                                 SOLINK_MODULE(target) Release/obj.target/.node
2020-03-20T07:56:35.067Z [INFO]: COPY Release/.node
2020-03-20T07:56:35.073Z [INFO]: make: Leaving directory `/codebuild/output/src947856100/src/planningpilot/node_modules/watchpack/node_modules/fsevents/build'
2020-03-20T07:56:35.074Z [WARNING]: gyp
2020-03-20T07:56:35.074Z [WARNING]: info ok
2020-03-20T07:56:35.201Z [INFO]: > core-js@3.6.4 postinstall /codebuild/output/src947856100/src/planningpilot/node_modules/core-js
                                 > node -e "try{require('./postinstall')}catch(e){}"
2020-03-20T07:56:35.429Z [INFO]: > fsevents@1.2.11 install /codebuild/output/src947856100/src/planningpilot/node_modules/@angular/compiler-cli/node_modules/fsevents
                                 > node-gyp rebuild
2020-03-20T07:56:35.531Z [WARNING]: gyp
2020-03-20T07:56:35.532Z [WARNING]: 
2020-03-20T07:56:35.532Z [WARNING]: info it worked if it ends with ok
2020-03-20T07:56:35.534Z [WARNING]: gyp
2020-03-20T07:56:35.534Z [WARNING]: info using node-gyp@3.8.0
                                    gyp info using node@10.16.0 | linux | x64
2020-03-20T07:56:35.685Z [WARNING]: gyp
2020-03-20T07:56:35.686Z [WARNING]: info spawn /usr/bin/python2
                                    gyp info spawn args [ '/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
                                    gyp info spawn args   'binding.gyp',
                                    gyp info spawn args   '-f',
                                    gyp info spawn args   'make',
                                    gyp info spawn args   '-I',
                                    gyp
2020-03-20T07:56:35.686Z [WARNING]: info spawn args   '/codebuild/output/src947856100/src/planningpilot/node_modules/@angular/compiler-cli/node_modules/fsevents/build/config.gypi',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/root/.node-gyp/10.16.0/include/node/common.gypi',
2020-03-20T07:56:35.687Z [WARNING]: gyp info spawn args   '-Dlibrary=shared_library',
                                    gyp info spawn args   '-Dvisibility=default',
                                    gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/10.16.0',
                                    gyp info spawn args   '-Dnode_gyp_dir=/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp',
                                    gyp info spawn args
2020-03-20T07:56:35.687Z [WARNING]: '-Dnode_lib_file=/root/.node-gyp/10.16.0/<(target_arch)/node.lib',
                                    gyp info spawn args   '-Dmodule_root_dir=/codebuild/output/src947856100/src/planningpilot/node_modules/@angular/compiler-cli/node_modules/fsevents',
                                    gyp info spawn args   '-Dnode_engine=v8',
                                    gyp info spawn args   '--depth=.',
                                    gyp info spawn args   '--no-parallel',
                                    gyp
2020-03-20T07:56:35.687Z [WARNING]: info spawn args   '--generator-output',
                                    gyp info spawn args   'build',
                                    gyp info spawn args   '-Goutput_dir=.' ]
2020-03-20T07:56:35.734Z [WARNING]: gyp
2020-03-20T07:56:35.734Z [WARNING]: info spawn make
                                    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
2020-03-20T07:56:35.735Z [INFO]: make: Entering directory `/codebuild/output/src947856100/src/planningpilot/node_modules/@angular/compiler-cli/node_modules/fsevents/build'
2020-03-20T07:56:35.736Z [INFO]: SOLINK_MODULE(target) Release/obj.target/.node
2020-03-20T07:56:35.780Z [INFO]: COPY Release/.node
2020-03-20T07:56:35.786Z [INFO]: make: Leaving directory `/codebuild/output/src947856100/src/planningpilot/node_modules/@angular/compiler-cli/node_modules/fsevents/build'
2020-03-20T07:56:35.786Z [WARNING]: gyp
2020-03-20T07:56:35.787Z [WARNING]: info ok
2020-03-20T07:56:35.832Z [INFO]: > @angular/cli@8.2.2 postinstall /codebuild/output/src947856100/src/planningpilot/node_modules/@angular/cli
                                 > node ./bin/postinstall/script.js
2020-03-20T07:56:36.212Z [INFO]: added 1194 packages in 16.751s
2020-03-20T07:56:36.226Z [INFO]: # Completed phase: preBuild
                                 # Starting phase: build
2020-03-20T07:56:36.227Z [INFO]: # Executing command: npm run build
2020-03-20T07:56:36.447Z [INFO]: > planningpilot@0.0.0 build /codebuild/output/src947856100/src/planningpilot
                                 > ng build
2020-03-20T07:56:43.923Z [WARNING]: ERROR in [96mnode_modules/aws-amplify-angular/dist/src/providers/amplify.service.d.ts[0m:[93m3[0m:[93m24[0m - [91merror[0m[90m TS2307: [0mCannot find module '@aws-amplify/core'.
                                    [7m3[0m import { Logger } from '@aws-amplify/core';
                                    [7m [0m [91m                       ~~~~~~~~~~~~~~~~~~~[0m
                                    [96msrc/main.ts[0m:[93m14[0m:[93m21[0m - [91merror[0m[90m TS2307: [0mCannot find module 'aws-amplify'.
                                    [7m14[0m import Amplify from 'aws-amplify';
                                    [7m  [0m [91m                    ~~~~~~~~~~~~~[0m
2020-03-20T07:56:43.925Z [WARNING]: 
2020-03-20T07:56:43.951Z [WARNING]: npm
2020-03-20T07:56:43.952Z [WARNING]: ERR! code ELIFECYCLE
                                    npm ERR! errno 1
                                    npm ERR! planningpilot@0.0.0 build: `ng build`
                                    npm ERR! Exit status 1
2020-03-20T07:56:43.954Z [WARNING]: npm ERR!
2020-03-20T07:56:43.955Z [WARNING]: npm ERR! Failed at the planningpilot@0.0.0 build script.
                                    npm
2020-03-20T07:56:43.957Z [WARNING]: ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-03-20T07:56:43.962Z [WARNING]: npm ERR! A complete log of this run can be found in:
                                    npm ERR!     /root/.npm/_logs/2020-03-20T07_56_43_956Z-debug.log
2020-03-20T07:56:43.962Z [HELP]: Outputting the npm debug log
                                 0 info it worked if it ends with ok
                                 1 verbose cli [ '/root/.nvm/versions/node/v10.16.0/bin/node',
                                 1 verbose cli   '/root/.nvm/versions/node/v10.16.0/bin/npm',
                                 1 verbose cli   'run',
                                 1 verbose cli   'build' ]
                                 2 info using npm@6.9.0
                                 3 info using node@v10.16.0
                                 4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
                                 5 info lifecycle planningpilot@0.0.0~prebuild: planningpilot@0.0.0
                                 6 info lifecycle planningpilot@0.0.0~build: planningpilot@0.0.0
                                 7 verbose lifecycle planningpilot@0.0.0~build: unsafe-perm in lifecycle true
                                 8 verbose lifecycle planningpilot@0.0.0~build: PATH: /root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/codebuild/output/src947856100/src/planningpilot/node_modules/.bin:/usr/local/rvm/gems/ruby-2.4.6/bin:/usr/local/rvm/gems/ruby-2.4.6@global/bin:/usr/local/rvm/rubies/ruby-2.4.6/bin:/usr/local/rvm/bin:/root/.yarn/bin:/root/.config/yarn/global/node_modules/.bin:/root/.nvm/versions/node/v10.16.0/bin:/root/.local/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
                                 9 verbose lifecycle planningpilot@0.0.0~build: CWD: /codebuild/output/src947856100/src/planningpilot
                                 10 silly lifecycle planningpilot@0.0.0~build: Args: [ '-c', 'ng build' ]
                                 11 silly lifecycle planningpilot@0.0.0~build: Returned: code: 1  signal: null
                                 12 info lifecycle planningpilot@0.0.0~build: Failed to exec build script
                                 13 verbose stack Error: planningpilot@0.0.0 build: `ng build`
                                 13 verbose stack Exit status 1
                                 13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
                                 13 verbose stack     at EventEmitter.emit (events.js:198:13)
                                 13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
                                 13 verbose stack     at ChildProcess.emit (events.js:198:13)
                                 13 verbose stack     at maybeClose (internal/child_process.js:982:16)
                                 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
                                 14 verbose pkgid planningpilot@0.0.0
                                 15 verbose cwd /codebuild/output/src947856100/src/planningpilot
                                 16 verbose Linux 4.14.165-103.209.amzn1.x86_64
                                 17 verbose argv "/root/.nvm/versions/node/v10.16.0/bin/node" "/root/.nvm/versions/node/v10.16.0/bin/npm" "run" "build"
                                 18 verbose node v10.16.0
                                 19 verbose npm  v6.9.0
                                 20 error code ELIFECYCLE
                                 21 error errno 1
                                 22 error planningpilot@0.0.0 build: `ng build`
                                 22 error Exit status 1
                                 23 error Failed at the planningpilot@0.0.0 build script.
                                 23 error This is probably not a problem with npm. There is likely additional logging output above.
                                 24 verbose exit [ 1, true ]
2020-03-20T07:56:43.966Z [ERROR]: !!! Build failed
2020-03-20T07:56:44.069Z [ERROR]: !!! Non-Zero Exit Code detected
2020-03-20T07:56:44.069Z [INFO]: # Starting environment caching...
2020-03-20T07:56:44.069Z [INFO]: # Uploading environment cache artifact...
2020-03-20T07:56:44.203Z [INFO]: # Environment caching completed
Terminating logging...
`
My package.json: 
`{
  "name": "planningpilot",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@ui5/webcomponents": "^1.0.0-rc.5",
    "@ui5/webcomponents-fiori": "^1.0.0-rc.5",
    "aws-amplify-angular": "^4.1.7",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.803.24",
    "@angular/cli": "~8.2.2",
    "@angular/compiler-cli": "~8.2.0",
    "@angular/language-service": "~8.2.0",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.4.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
}
`
Any ideas?

**Comment by jordanranz** [comment]
Hi @dakoller, thanks for submitting this issue.

Can you elaborate on "builds on aws fail"? 

Also, I noticed `aws-amplify` is not listed in your `package.json`. `aws-amplify` is required to use the `aws-amplify-angular` library.

If you are only using the `amplify-authenticator` you can also try upgrading to use our latest Angular UI package: https://docs.amplify.aws/ui/auth/authenticator?framework=angular (`@aws-amplify/ui-angular`)
