### ISSUE TITLE
Error in `amplify api add-graphql-datasource`

### ISSUE THREAD

**Issue by gaegaelab** [aws-amplify/amplify-js#5297]
**Describe the bug**
Executing `amplify api add-graphql-datasource` resulted in an error.
I tried to change the API connection to Aurora Serverless.

**To Reproduce**
https://aws-amplify.github.io/docs/cli-toolchain/graphql?sdk=js#relational-databases
I set up while watching the Relational Databases connection tutorial above.

1. Execute `amplify add api`.
2. Finish setting by default.
3. Execute `amplify api add-graphql-datasource`.
4. Set the connection destination of Aurora Serverless.

**Expected behavior**
No error.
All I need to do is run `amplify push` and the API connects to Aurora Serverless from DynamoDB.

**Screenshots**
This is the log that executed the procedure.
```
D:\project_man>amplify add api
? Please select from one of the below mentioned services: GraphQL
? Provide API name: projectapi
? Choose the default authorization type for the API Amazon Cognito User Pool     
Use a Cognito user pool configured as a part of this project.
? Do you want to configure advanced settings for the GraphQL API No, I am done.
? Do you have an annotated GraphQL schema? No
? Do you want a guided schema creation? Yes
? What best describes your project: Single object with fields (e.g., “Todo” with ID, name, description)
? Do you want to edit the schema now? Yes
Please edit the file in your editor: D:\project_man\amplify\backend/api/projectapi/schema.graphql
? Press enter to continue Selected  editor vscode was not found in your machine. Please manually edit the file created at D:\project_man\amplify\backend/api/projectapi/schema.graphql
? Press enter to continue 


The following types do not have '@auth' enabled. Consider using @auth with @model
         - Todo
Learn more about @auth here: https://aws-amplify.github.io/docs/cli-toolchain/graphql#auth    


GraphQL schema compiled successfully.

Edit your schema at D:\project_man\amplify\backend\api\projectapi\schema.graphql or place .graphql files in a directory at D:\project_man\amplify\backend\api\projectapi\schema
Successfully added resource projectapi locally

Some next steps:
"amplify push" will build all your local backend resources and provision it in the cloud      
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud


D:\project_man>amplify api add-graphql-datasource
Using datasource: Aurora Serverless, provided by: awscloudformation
? Provide the region in which your cluster is located: us-east-2
? Select the Aurora Serverless cluster that will be used as the data source for your API: project-db
√ Fetched Aurora Serverless cluster.
? Select the database to use as the datasource: projectdb
Successfully added the Aurora Serverless datasource locally

Some next steps:
"amplify push" will build all your local backend resources and provision it in the cloud      
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud


The following types do not have '@auth' enabled. Consider using @auth with @model
         - Todo
Learn more about @auth here: https://aws-amplify.github.io/docs/cli-toolchain/graphql#auth    

(node:18672) UnhandledPromiseRejectionWarning: Error: Type Query must define one or more fields.

Type Mutation must define one or more fields.

Type Subscription must define one or more fields.
    at assertValidSchema (C:\Users\MYNAME\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\graphql\type\validate.js:71:11)
    at Object.validate (C:\Users\MYNAME\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\graphql\validation\validate.js:54:35)
    at Object.exports.validateModelSchema (C:\Users\MYNAME\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\graphql-transformer-core\src\validation.ts:142:10)
    at GraphQLTransform.transform (C:\Users\MYNAME\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\graphql-transformer-core\src\GraphQLTransform.ts:240:20)
    at _buildProject (C:\Users\MYNAME\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\graphql-transformer-core\src\util\amplifyUtils.ts:54:35)
    at ensureMissingStackMappings (C:\Users\MYNAME\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\graphql-transformer-core\src\util\amplifyUtils.ts:128:23)
    at Object.buildProject [as buildAPIProject] (C:\Users\MYNAME\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\graphql-transformer-core\src\util\amplifyUtils.ts:27:3)      
    at transformGraphQLSchema (C:\Users\MYNAME\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\lib\transform-graphql-schema.js:457:29)     
(node:18672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18672) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The contents of `schema.graphql` are as follows.
```
type Todo @model {
  id: ID!
  name: String!
  description: String
}

type Mutation

type Query

type Subscription

schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}

```

Cannot amplify push.
```
D:\project_man>amplify push
√ Successfully pulled backend environment dev from the cloud.

Current Environment: dev

| Category | Resource name     | Operation | Provider plugin   |
| -------- | ----------------- | --------- | ----------------- |
| Api      | projectapi          | Update    | awscloudformation |
| Auth     | projectman97ab60eb  | No Change | awscloudformation |
| Function | S3Trigger143ea3c5 | No Change | awscloudformation |
| Storage  | projects3           | No Change | awscloudformation |
? Are you sure you want to continue? Yes

The following types do not have '@auth' enabled. Consider using @auth with @model
         - Todo
Learn more about @auth here: https://aws-amplify.github.io/docs/cli-toolchain/graphql#auth    

× An error occurred when pushing the resources to the cloud

Type Query must define one or more fields.

Type Mutation must define one or more fields.

Type Subscription must define one or more fields.
An error occured during the push operation: Type Query must define one or more fields.        

Type Mutation must define one or more fields.

Type Subscription must define one or more fields.
```

<details>
  <summary><strong>Environment</strong></summary>

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

```
D:\project_man>npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
npx: 1個のパッケージを4.71秒でインストールしました。

  System:
    OS: Windows 10 10.0.19041
    CPU: (6) x64 AMD Ryzen 5 3500 6-Core Processor
    Memory: 6.60 GB / 15.92 GB
  Binaries:
    Node: 12.14.1 - D:\software\nodejs\node.EXE
    Yarn: 1.22.1 - D:\software\Yarn\bin\yarn.CMD
    npm: 6.13.4 - D:\software\nodejs\npm.CMD
  Browsers:
    Edge: 44.19041.1.0
    Internet Explorer: 11.0.19041.1
  npmPackages:
    react-scripts: ^3.4.1 => 3.4.1
```

</details>

**Smartphone (please complete the following information):**

I do not use a smartphone.

**Additional context**

**Sample code**

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by gaegaelab** [comment]
I didn't know the CLI was a different repository. 💦
Moved below.

https://github.com/aws-amplify/amplify-cli/issues/3872
