### ISSUE TITLE
Just updating aws-amplify from 3.0.4 to 3.0.8 get app crashed in react-native 

### ISSUE THREAD

**Issue by AhmedMesawer** [aws-amplify/amplify-js#5496]
```
error: bundling failed: Error: Unable to resolve module `./providers` from `node_modules\@aws-amplify\storage\lib-esm\index.js`:

None of these files exist:
  * node_modules\@aws-amplify\storage\lib-esm\providers(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules\@aws-amplify\storage\lib-esm\providers\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (E:\react\funbits-app\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (E:\react\funbits-app\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (E:\react\funbits-app\node_modules\metro\src\node-haste\DependencyGraph.js:282:16)
    at Object.resolve (E:\react\funbits-app\node_modules\metro\src\lib\transformHelpers.js:267:42)
    at dependencies.map.result (E:\react\funbits-app\node_modules\metro\src\DeltaBundler\traverseDependencies.js:426:31)
    at Array.map (<anonymous>)
    at resolveDependencies (E:\react\funbits-app\node_modules\metro\src\DeltaBundler\traverseDependencies.js:423:18)
    at E:\react\funbits-app\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (E:\react\funbits-app\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)
```

**Comment by paulsjohnson91** [comment]
I'm also getting this error after updating to 3.0.8

**Comment by amhinson** [comment]
@AhmedMesawer Can you post your `package.json`?

**Comment by AhmedMesawer** [comment]
@amhinson 
```
{
  "name": "myproject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "clean": "cd android && gradlew clean",
    "clean-cache": "npm cache clean --force",
    "install-packages": "npm i",
    "preios": "cd ios && pod install",
    "ios": "react-native run-ios --simulator \"iPhone X\"",
    "start": "react-native start",
    "test": "jest --detectOpenHandles"
  },
  "dependencies": {
    "aws-amplify": "^3.0.8",
    "@react-native-community/async-storage": "^1.9.0",
    "@react-native-community/google-signin": "^4.0.0",
    "@react-native-community/masked-view": "^0.1.9",
    "@react-native-community/netinfo": "^5.7.1",
    "@react-native-community/push-notification-ios": "^1.1.1",
    "@react-native-firebase/app": "^6.4.0",
    "@react-native-firebase/dynamic-links": "^6.4.0",
    "amazon-cognito-identity-js": "^4.2.1",
    "aws-api-gateway-client": "^0.3.3",
    "body-parser": "^1.19.0",
    "events": "^3.1.0",
    "moment": "^2.24.0",
    "react": "16.8.1",
    "react-native": "0.61.1",
    "react-native-calendars": "^1.265.0",
    "react-native-confirmation-code-input": "^1.0.4",
    "react-native-dialog": "^5.6.0",
    "react-native-elements": "^1.2.7",
    "react-native-fbsdk": "^1.1.2",
    "react-native-geolocation-service": "^4.0.0",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-i18n": "^2.0.15",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-maps": "^0.27.1",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-material-menu": "^1.1.3",
    "react-native-raw-bottom-sheet": "^2.1.0",
    "react-native-reanimated": "^1.8.0",
    "react-native-restart": "^0.0.14",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.5.0",
    "react-native-simple-dialogs": "^1.2.1",
    "react-native-trustkit-wrapper": "^0.0.8",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^4.3.7",
    "react-navigation-stack": "^2.3.12",
    "react-navigation-tabs": "^2.8.11",
    "react-router": "^5.1.2",
    "reactn": "^2.2.7",
    "tipsi-stripe": "^7.5.3",
    "update": "^0.7.4"
  },
  "devDependencies": {
    "@babel/core": "^7.5.0",
    "@babel/runtime": "^7.5.0",
    "@react-native-community/eslint-config": "^0.0.3",
    "babel-jest": "^24.1.0",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.2",
    "jest": "^24.1.0",
    "metro-react-native-babel-preset": "^0.51.1",
    "react-test-renderer": "16.8.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

**Comment by amhinson** [comment]
Ok thanks! I'll take a look. Are you seeing this error at build time?

**Comment by AhmedMesawer** [comment]
No, app is built successfully

**Comment by amhinson** [comment]
Can you describe when/where this error is occurring? I've got a sample Amplify app running with the same `react-native` and `aws-amplify` versions as what you posted but I'm not seeing any errors.

A sample app repo or code snippet could be helpful as well, if possible.

**Comment by Amplifiyer** [comment]
@AhmedMesawer and @paulsjohnson91 can you try after deleting your node_modules directory and let us know if that that helped?

**Comment by AhmedMesawer** [comment]
@Amplifiyer Thank you, the files mentioned in error stack has been downloaded when I delete @aws-amplify/storage folder and install it again
