### ISSUE TITLE
Cyclic Dependency issue when using new Authenticator

### ISSUE THREAD

**Issue by michaelcuneo** [aws-amplify/amplify-js#5827]
**Describe the bug**
Old aws-amplify-react 4.1.10 no longer has styling for Authenticator Component. So I have transitioned to @aws-amplify/react-ui, but this gives me a cyclic dependency error.

**To Reproduce**

Installed aws-amplify and aws-amplify-react.
Realised that aws-amplify-react no longer has any styling or supports styling at all.
Removed aws-amplify-react.
Installed @aws-amplify/react-ui
Cyclic Dependency Errors on amplify serve.

```
webpack building...
/mnt/store/share/fastlab-new/node_modules/toposort/index.js:35
      throw new Error('Cyclic dependency' + nodeRep)
      ^

Error: Cyclic dependency
    at visit (/mnt/store/share/fastlab-new/node_modules/toposort/index.js:35:13)
    at visit (/mnt/store/share/fastlab-new/node_modules/toposort/index.js:53:9)
    at visit (/mnt/store/share/fastlab-new/node_modules/toposort/index.js:53:9)
    at Function.toposort [as array] (/mnt/store/share/fastlab-new/node_modules/toposort/index.js:22:22)
    at Object.module.exports.dependency (/mnt/store/share/fastlab-new/node_modules/html-webpack-plugin/lib/chunksorter.js:50:35)
    at HtmlWebpackPlugin.sortChunks (/mnt/store/share/fastlab-new/node_modules/html-webpack-plugin/index.js:364:35)
    at /mnt/store/share/fastlab-new/node_modules/html-webpack-plugin/index.js:113:21
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/mnt/store/share/fastlab-new/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Compiler.emitAssets (/mnt/store/share/fastlab-new/node_modules/webpack/lib/Compiler.js:441:19)
    at onCompiled (/mnt/store/share/fastlab-new/node_modules/webpack/lib/Watching.js:50:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fastlab-enigma@0.1.0 start: `cross-env NODE_ENV=development node server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fastlab-enigma@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/michael/.npm/_logs/2020-05-19T02_49_15_489Z-debug.log
frontend start command exited with code 1

```

**Expected behavior**
Normal running service.

**Comment by jordanranz** [comment]
Can you provide a repo for us to reproduce this? Not able to reproduce this with any of our test applications.

This error looks similar: https://github.com/marcelklehr/toposort/issues/20

**Comment by jordanranz** [comment]
Seems related to how RB4 uses HtmlWebpackPlugin.

You should be either able to add chunksSortMode like this: https://github.com/keystonejs/keystone/pull/1909

or update `html-webpack-plugin` to version 4+ per the CHANGELOG bug fix:
https://github.com/jantimon/html-webpack-plugin/blob/master/CHANGELOG.md#400-2020-03-23

**Comment by michaelcuneo** [comment]
@jordanranz thanks. Looks like chunksSortMode: none solved it for now. Works fine after that.
