### ISSUE TITLE
Amplify authentication cannot be configured with just identity pool

### ISSUE THREAD

**Issue by typerandom** [aws-amplify/amplify-js#6350]
**Describe the bug**

From documentation, it seems that Amplify should support authentication using only an identity pool without having to specify a user pool. However, this does not seem to be the case as just specifying `region` and `identityPoolId` as `Auth` parameters generates a client-side `Amplify has not been configured correctly` error:

```
ConsoleLogger.js:99 [ERROR] 08:34.301 AuthError - 
            Error: Amplify has not been configured correctly. 
            The configuration object is missing required auth properties. 
            Did you run `amplify push` after adding auth via `amplify add auth`?
            See https://aws-amplify.github.io/docs/js/authentication#amplify-project-setup for more information  
```

The configuration used is:

```
Amplify.configure({
    Auth: {
        region: "us-west-2",
        identityPoolId: "us-west-2:<omitted...>",
    },
});
```

Specifying a `userPoolId` and `userPoolWebClientId` makes the error go away (and "everything work"), but unfortunately makes Amplify just use one user pool, e.g:

```
Amplify.configure({
    Auth: {
        region: "us-west-2",
        identityPoolId: "us-west-2:<omitted...>",
        userPoolId: "us-west-2_<omitted...>",
        userPoolWebClientId: "<omitted...>",
    }
});
```

The [authentication configuration section of Amplify](https://docs.amplify.aws/lib/auth/start/q/platform/js#re-use-existing-authentication-resource) states:

```
Auth: {
    // REQUIRED - Amazon Cognito Identity Pool ID
    identityPoolId: 'XX-XXXX-X:XXXXXXXX-XXXX-1234-abcd-1234567890ab',
    // REQUIRED - Amazon Cognito Region
    region: 'XX-XXXX-X', 
    // OPTIONAL - Amazon Cognito User Pool ID
    userPoolId: 'XX-XXXX-X_abcd1234', 
    // OPTIONAL - Amazon Cognito Web Client ID (26-char alphanumeric string)
    userPoolWebClientId: 'a1b2c3d4e5f6g7h8i9j0k1l2m3',
},
```

Indicating that it should be possible to set just `region` and `identityPoolId`, however, the configuration error thrown during setup indicates that this is not supported. The same configuration is also backed up as being valid here:

https://docs.amplify.aws/lib/analytics/getting-started/q/platform/js#set-up-existing-analytics-backend

I might also add that there are no API requests being made, so the configuration error thrown is isolated to local configuration and nothing external.

**To Reproduce**

1. Configure Amplify to use just `region` and `identityPoolId` auth parameters as shown below:

```
Amplify.configure({
    Auth: {
        region: "us-west-2",
        identityPoolId: "us-west-2:<omitted...>",
    },
});
```

2. Open the developer console and observe that there are no external requests and that a configuration error is shown:

```
ConsoleLogger.js:99 [ERROR] 08:34.301 AuthError - 
            Error: Amplify has not been configured correctly. 
            The configuration object is missing required auth properties. 
            Did you run `amplify push` after adding auth via `amplify add auth`?
            See https://aws-amplify.github.io/docs/js/authentication#amplify-project-setup for more information
        
```

**Expected behavior**

Correct me if I'm wrong here. But my idea is that Amplify would support authentication through an identity pool. I.e. making it possible to login as a user from one of multiple user pools defined in an identity pool.

**Code Snippet**

N/A. See section *To Reproduce*.

**Screenshots**

![image](https://user-images.githubusercontent.com/1331778/87785933-5bf9a580-c839-11ea-860e-1357f467d478.png)

**What is Configured?**

Amplify:

```
Amplify.configure({
    Auth: {
        region: "us-west-2",
        identityPoolId: "us-west-2:<omitted...>",
    },
});
```

npm package.json:

```
"dependencies": {
  "@aws-amplify/auth": "^3.3.1",
  "@aws-amplify/core": "^3.4.2",
  "@aws-amplify/storage": "^3.2.9",
  "@aws-amplify/ui-components": "^0.5.4",
  "@aws-amplify/ui-react": "^0.2.11",
  "@aws-amplify/xr": "^2.1.19",
  ...
```

npx envinfo:

```
$ npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
npx: installed 1 in 3.704s

  System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 675.51 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.21.0 - ~/.nvm/versions/node/v10.21.0/bin/node
    npm: 6.14.4 - ~/.nvm/versions/node/v10.21.0/bin/npm
  Browsers:
    Chrome: 84.0.4147.89
    Safari: 13.1.1
  npmGlobalPackages:
    @aws-amplify/cli: 4.24.1
    depcheck: 0.9.2
    gulp: 4.0.2
    npm-check: 5.9.2
    npm: 6.14.4
```

**Smartphone (please complete the following information):**

N/A

**Additional context**

Error with `window.LOG_LEVEL = 'DEBUG';` set:

```
...
[DEBUG] 29:25.124 AuthClass - getting current authenticated user
ConsoleLogger.js:99 [DEBUG] 29:25.125 AuthClass - cannot load federated user from auth storage
ConsoleLogger.js:99 [DEBUG] 29:25.125 AuthClass - get current authenticated userpool user
ConsoleLogger.js:99 [ERROR] 29:25.125 AuthError - 
            Error: Amplify has not been configured correctly. 
            The configuration object is missing required auth properties. 
            Did you run `amplify push` after adding auth via `amplify add auth`?
            See https://aws-amplify.github.io/docs/js/authentication#amplify-project-setup for more information
ConsoleLogger.js:109 [DEBUG] 29:25.125 AuthClass - The user is not authenticated by the error NoUserPoolError: Authentication Error
    at NoUserPoolError.AuthError [as constructor] (http://localhost:8000/static/dist/admin.bundle.js:7240:24)
    at new NoUserPoolError (http://localhost:8000/static/dist/admin.bundle.js:7256:28)
    at AuthClass.../../node_modules/@aws-amplify/auth/lib/Auth.js.AuthClass.rejectNoUserPool (http://localhost:8000/static/dist/admin.bundle.js:7187:31)
    at AuthClass.../../node_modules/@aws-amplify/auth/lib/Auth.js.AuthClass.currentUserPoolUser (http://localhost:8000/static/dist/admin.bundle.js:6344:25)
    at AuthClass.<anonymous> (http://localhost:8000/static/dist/admin.bundle.js:6489:51)
    at step (http://localhost:8000/static/dist/admin.bundle.js:5370:23)
    at Object.next (http://localhost:8000/static/dist/admin.bundle.js:5351:53)
    at fulfilled (http://localhost:8000/static/dist/admin.bundle.js:5342:58)
ConsoleLogger.js:109 [DEBUG] 29:25.126 Hub - Dispatching to UI Auth with  {event: "AuthStateChange", message: "signin", data: undefined}data: undefinedevent: "AuthStateChange"message: "signin"__proto__: Object
ConsoleLogger.js:109 [INFO] 29:25.126 Authenticator - Inside onAuthStateChange Method current authState: loading
ConsoleLogger.js:99 [INFO] 29:25.126 Authenticator - authState has been updated to signin
ConsoleLogger.js:109 [DEBUG] 29:25.126 Hub - Dispatching to UI Auth with  {event: "AuthStateChange", message: "signin", data: undefined}
ConsoleLogger.js:99 [DEBUG] 29:25.139 AuthClass - configure Auth
ConsoleLogger.js:109 [DEBUG] 29:25.139 Parser - parse config (3) [{…}, "to amplifyconfig", {…}]
ConsoleLogger.js:109 [DEBUG] 29:25.140 Hub - Dispatching to auth with  {event: "configured", data: null, message: "The Auth category has been configured successfully"}
ConsoleLogger.js:109 [DEBUG] 29:25.140 Hub - Dispatching to auth with  {event: "configured", data: null, message: "The Auth category has been configured successfully"}
ConsoleLogger.js:109 [DEBUG] 29:25.140 AnalyticsClass - on hub capsule auth {event: "configured", data: null, message: "The Auth category has been configured successfully"}
ConsoleLogger.js:109 [DEBUG] 29:25.140 Hub - Dispatching to auth with  {event: "configured", data: null, message: "The Auth category has been configured successfully"}
```

**Comment by manueliglesias** [comment]
Hi @typerandom 

When using Identity Pools without User pools, you'll have a way to get AWS credentials but without having "users", calling Amplify Auth's APIs like `currentAuthenticatedUser` will give you the error you are seeing. If you need a user directory, then you need Cognito User Pools.

You can get more details in the [Concepts](https://docs.amplify.aws/lib/auth/overview/q/platform/js) section of our docs.
