### ISSUE TITLE
Amplify pull - The specified key does not exist.

### ISSUE THREAD

**Issue by what-name** [aws-amplify/amplify-js#6356]
**Describe the bug**
I want to pull a currently deployed Amplify App into an empty folder with the command provided by the Amplify console `amplify pull --appId myAppId --envName dev`. Previously I was having credential problems in my `.aws/credentials & config` files so I cleaned it completely and did `aws configure` with the access & secret key that has access to the Amplify App as the deafult aws cli profile. This is the error I was getting **before** cleaning out the credentials:

```
Amplify AppID: myAppId not found. Please ensure your local profile matches the AWS account or region in which the Amplify app exists.
Failed to pull the backend.
Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
```

After cleaning out (currently):

```
? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use default
? Which app are you working on? <myAppId>
Backend environment 'dev' found. Initializing...
Failed to pull the backend.
The specified key does not exist.
NoSuchKey: The specified key does not exist.
    at Request.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/services/s3.js:831:35)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
```

I have tried reinstalling the amplify cli with `npm uninstall -g @aws-amplify/cli` & `npm install -g @aws-amplify/cli`. The reinstall was successful. Still getting the error. I have also tried running the `amplify pull --appId myAppId --envName dev` command from the app's locally cloned repository with the same results. The only difference there is it prompts me to choose which app I want to pull (as seen above).

**To Reproduce**
- Deploy an Amplify App through the console
- Go to "Backend Environments" -> edit -> copy the `amplify pull...` command
- Execute the `amplify pull...` command in an empty directory
- Exdecute the `amplify pull...` command in the app's git cloned directory

**Expected behavior**
When I execute the pull command, it pulls the complete deployed app to local and I can continue working on it.

**Code Snippet**
```
mkdir myAmplifyApp
cd myAmplifyApp
amplify pull --appId myAppId --envName dev
```

**Screenshots**
<img width="916" alt="Screen Shot 2020-07-18 at 03 21 10" src="https://user-images.githubusercontent.com/20590073/87841499-03142680-c8a6-11ea-9f94-44d6e7641852.png">

**What is Configured?**
`aws sts get-caller-identity` returns the correct user that has full access to the Amplify app.
 
**Environment**
```
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
    Memory: 86.59 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 83.1.10.97
    Chrome: 83.0.4103.116
    Firefox: 78.0.2
    Safari: 13.1.1
  npmGlobalPackages:
    @aws-amplify/cli: 4.24.2
    favicon-emoji: 2.3.0
    npm: 6.14.4
    twilio-cli: 1.12.0
```

**Comment by what-name** [comment]
I posted in the wrong repo, I'm sorry... [here is the correct issue](https://github.com/aws-amplify/amplify-cli/issues/4867)
