### ISSUE TITLE
Using federated singin with developer identities lost when refresh

### ISSUE THREAD

**Issue by enrique-gil-vessi** [aws-amplify/amplify-js#6749]
**Describe the bug**
When using singin with developer identities, get not authenticated on refresh.

**To Reproduce**

With a lambda returning a openId token with GetOpenIdTokenForDeveloperIdentity
1. In the front-end generate AWS credentials with the idenityId and token from the lambda with GetCredentialsForIdentity.

```javascript
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
	IdentityPoolId,
	IdentityId,
	Logins: {
		'cognito-identity.amazonaws.com':  token
	}
});
```

2. Sign up with 
```javascript
Auth.federatedSignIn(
	'developer',
	{
		token,
		identity_id, // Optional
		expires_at: new Date().getTime()+(60*60*1000) // the expiration timestamp
	},
	{
		username
	}
);
```

It should sign in the user.

3. Refresh the page.
4. Get the current user with Auth.currentAuthenticatedUser().
5. It displays "not authenticated" and deletes the localStorage credentials.

**Expected behavior**
Keep the current signed session active.

**Code Snippet**

```javascript
function signIn(){
	try{

		let resp = await <SIGN_IN_LAMBDA>(username, pass);

		identityId = resp.IdentityId;
		token = resp.Token;
	}catch(err){
		throw err;
	}

	let token_backend = !token? false: token || false;

	if(!!token_backend){

		try{

			let c = new AWS.CognitoIdentityCredentials({
				username: username,
				IdentityPoolId,
				IdentityId,
				Logins: {
					'cognito-identity.amazonaws.com': token_backend
				}
			});

			AWS.config.credentials = c;

			let authresp = await Auth.federatedSignIn(
				'developer',
				{
					token:token_backend,
					identity_id: identityId, // Optional
					expires_at: new Date().getTime() + (6*60*60*1000) // the expiration timestamp
				},
				{
					username,
					siiToken: sii_token
				}
			);

			return await Auth.currentAuthenticatedUser();
		}catch(err){
			return err;
		}
	}
}
```

**Screenshots**
Sign in lambda result
![image](https://user-images.githubusercontent.com/53239348/92527829-0e2c6880-f1fe-11ea-9276-c4e9216f13f8.png)

federatedInfo in localStorage BEFORE refresh the page
![image](https://user-images.githubusercontent.com/53239348/92527909-34ea9f00-f1fe-11ea-9932-e7a214c1c305.png)

console log (in debug level) when try to ask for Auth.currentAuthenticatedUser()
![image](https://user-images.githubusercontent.com/53239348/92528421-19cc5f00-f1ff-11ea-9d3c-357e633f515d.png)

**What is Configured?**

```javascript
Amplify.configure({
	Auth: {
		identityPoolId, // an existing identity pool
		region: 'us-east-1',
		identityPoolRegion: 'us-east-1',
	}
});
```

**Additional context**

DEBUG log

<details>
  <summary>Click to expand!</summary>

 ```
18:12:17.258 VM12638 ConsoleLogger.js:99 [DEBUG] 12:17.257 AuthClass - getting current credentials
18:12:17.646 VM12638 ConsoleLogger.js:99 [DEBUG] 12:17.646 Credentials - getting credentials
18:12:17.647 VM12638 ConsoleLogger.js:99 [DEBUG] 12:17.647 Credentials - picking up credentials
18:12:17.648 VM12638 ConsoleLogger.js:99 [DEBUG] 12:17.647 Credentials - getting new cred promise
18:12:17.648 VM12638 ConsoleLogger.js:99 [DEBUG] 12:17.648 Credentials - checking if credentials exists and not expired
18:12:17.649 VM12638 ConsoleLogger.js:99 [DEBUG] 12:17.649 Credentials - need to get a new credential or refresh the existing one
18:12:17.650 VM12638 ConsoleLogger.js:99 [DEBUG] 12:17.650 AuthClass - Getting current user credentials
18:12:17.680 VM12638 ConsoleLogger.js:99 [DEBUG] 12:17.680 AuthClass - Getting current session
18:12:17.681 VM12638 ConsoleLogger.js:99 [DEBUG] 12:17.681 AuthClass - no current Cognito user
18:12:17.682 VM12638 ConsoleLogger.js:109 [DEBUG] 12:17.682 Hub - Dispatching to auth with  {event: "signOut", data: null, message: "A user has been signed out"}
18:12:17.683 VM12638 ConsoleLogger.js:109 [DEBUG] 12:17.682 Hub - Dispatching to auth with  {event: "signOut", data: null, message: "A user has been signed out"}
18:12:17.683 VM12638 ConsoleLogger.js:109 [DEBUG] 12:17.683 AnalyticsClass - on hub capsule auth {event: "signOut", data: null, message: "A user has been signed out"}
18:12:17.684 VM12638 ConsoleLogger.js:99 [DEBUG] 12:17.684 AuthClass - Failed to get user from user pool
18:12:17.685 VM12638 ConsoleLogger.js:109 [DEBUG] 12:17.685 AuthClass - Failed to get the current user No current user
18:12:17.685 VM12638 ConsoleLogger.js:109 [DEBUG] 12:17.685 AuthClass - getting session failed No current user
18:12:17.686 VM12638 ConsoleLogger.js:99 [DEBUG] 12:17.686 Credentials - setting credentials for guest
18:12:17.762 VM12564 vue.runtime.esm.js:8428 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
18:12:19.114 VM12698 fetch-http-handler.js:46 POST https://cognito-identity.us-east-1.amazonaws.com/ 400
FetchHttpHandler.handle @ VM12698 fetch-http-handler.js:46
eval @ VM12774 GetIdCommand.js:33
eval @ VM12766 deserializerMiddleware.js:6
eval @ VM12651 tslib.es6.js:98
__awaiter @ VM12651 tslib.es6.js:94
eval @ VM12766 deserializerMiddleware.js:5
eval @ VM12724 defaultStrategy.js:33
step @ VM12651 tslib.es6.js:124
eval @ VM12651 tslib.es6.js:105
step @ VM12651 tslib.es6.js:109
eval @ VM12651 tslib.es6.js:105
eval @ VM12651 tslib.es6.js:98
__awaiter @ VM12651 tslib.es6.js:94
ExponentialBackOffStrategy.retry @ VM12724 defaultStrategy.js:20
eval @ VM12723 retryMiddleware.js:8
step @ VM12651 tslib.es6.js:124
eval @ VM12651 tslib.es6.js:105
eval @ VM12651 tslib.es6.js:98
__awaiter @ VM12651 tslib.es6.js:94
eval @ VM12723 retryMiddleware.js:6
eval @ VM12721 index.js:26
step @ VM12651 tslib.es6.js:124
eval @ VM12651 tslib.es6.js:105
eval @ VM12651 tslib.es6.js:98
__awaiter @ VM12651 tslib.es6.js:94
eval @ VM12721 index.js:9
eval @ VM12720 index.js:25
step @ VM12651 tslib.es6.js:124
eval @ VM12651 tslib.es6.js:105
eval @ VM12651 tslib.es6.js:98
__awaiter @ VM12651 tslib.es6.js:94
eval @ VM12720 index.js:8
eval @ VM12749 middleware.js:21
eval @ VM12767 serializerMiddleware.js:7
fulfilled @ VM12651 tslib.es6.js:95
Promise.then (async)
step @ VM12651 tslib.es6.js:97
eval @ VM12651 tslib.es6.js:98
__awaiter @ VM12651 tslib.es6.js:94
eval @ VM12767 serializerMiddleware.js:5
Client.send @ VM12751 client.js:24
eval @ VM12673 Credentials.js:270
step @ VM12673 Credentials.js:55
eval @ VM12673 Credentials.js:36
eval @ VM12673 Credentials.js:30
__awaiter @ VM12673 Credentials.js:26
credentialsProvider @ VM12673 Credentials.js:266
eval @ VM12673 Credentials.js:285
step @ VM12673 Credentials.js:55
eval @ VM12673 Credentials.js:36
fulfilled @ VM12673 Credentials.js:27
Promise.then (async)
step @ VM12673 Credentials.js:29
eval @ VM12673 Credentials.js:30
__awaiter @ VM12673 Credentials.js:26
CredentialsClass._setCredentialsForGuest @ VM12673 Credentials.js:219
CredentialsClass.set @ VM12673 Credentials.js:478
eval @ VM12798 Auth.js:1293
Promise.catch (async)
eval @ VM12798 Auth.js:1291
step @ VM12798 Auth.js:56
eval @ VM12798 Auth.js:37
fulfilled @ VM12798 Auth.js:28
Promise.then (async)
step @ VM12798 Auth.js:30
eval @ VM12798 Auth.js:31
__awaiter @ VM12798 Auth.js:27
AuthClass.currentUserCredentials @ VM12798 Auth.js:1255
CredentialsClass._keepAlive @ VM12673 Credentials.js:127
CredentialsClass._pickupCredentials @ VM12673 Credentials.js:110
CredentialsClass.get @ VM12673 Credentials.js:104
AuthClass.currentCredentials @ VM12798 Auth.js:1303
_callee$ @ VM12605 guard.js:33
tryCatch @ VM14245 pdf_viewer.js:1294
invoke @ VM14245 pdf_viewer.js:1470
prototype.<computed> @ VM14245 pdf_viewer.js:1337
asyncGeneratorStep @ VM12632 asyncToGenerator.js:9
_next @ VM12632 asyncToGenerator.js:31
eval @ VM12632 asyncToGenerator.js:38
eval @ VM12632 asyncToGenerator.js:27
eval @ VM12605 guard.js:86
iterator @ VM12604 vue-router.esm.js:2226
step @ VM12604 vue-router.esm.js:1897
runQueue @ VM12604 vue-router.esm.js:1905
confirmTransition @ VM12604 vue-router.esm.js:2256
transitionTo @ VM12604 vue-router.esm.js:2126
init @ VM12604 vue-router.esm.js:2878
beforeCreate @ VM12604 vue-router.esm.js:1239
invokeWithErrorHandling @ VM12564 vue.runtime.esm.js:1853
callHook @ VM12564 vue.runtime.esm.js:4213
Vue._init @ VM12564 vue.runtime.esm.js:4994
Vue @ VM12564 vue.runtime.esm.js:5075
eval @ VM12474 main.js:53
./src/main.js @ VM12439 app.js:2212
__webpack_require__ @ VM12439 app.js:849
fn @ VM12439 app.js:151
1 @ VM12439 app.js:2969
__webpack_require__ @ VM12439 app.js:849
checkDeferredModules @ VM12439 app.js:46
(anonymous) @ VM12439 app.js:925
(anonymous) @ VM12439 app.js:928
Show 42 more frames
18:12:19.118 VM12638 ConsoleLogger.js:109 [DEBUG] 12:19.118 Credentials - Failed to load credentials Promise {<rejected>: NotAuthorizedException: Unauthenticated access is not supported for this identity pool.
  at eval…}
18:12:19.119 VM12638 ConsoleLogger.js:109 [DEBUG] 12:19.119 Credentials - Error loading credentials NotAuthorizedException: Unauthenticated access is not supported for this identity pool.
  at eval (webpack-internal:///./node_modules/@aws-sdk/client-cognito-identity/dist/es/protocols/Aws_json1_1.js:939:68)
  at step (webpack-internal:///./node_modules/tslib/tslib.es6.js:124:23)
  at Object.eval [as next] (webpack-internal:///./node_modules/tslib/tslib.es6.js:105:53)
  at fulfilled (webpack-internal:///./node_modules/tslib/tslib.es6.js:95:58)
18:12:19.120 VM12605 guard.js:37 currentCredentials NotAuthorizedException: Unauthenticated access is not supported for this identity pool.
  at eval (webpack-internal:///./node_modules/@aws-sdk/client-cognito-identity/dist/es/protocols/Aws_json1_1.js:939:68)
  at step (webpack-internal:///./node_modules/tslib/tslib.es6.js:124:23)
  at Object.eval [as next] (webpack-internal:///./node_modules/tslib/tslib.es6.js:105:53)
  at fulfilled (webpack-internal:///./node_modules/tslib/tslib.es6.js:95:58)
18:12:19.120 VM12638 ConsoleLogger.js:99 [DEBUG] 12:19.120 AuthClass - getting current authenticated user
18:12:19.121 VM12638 ConsoleLogger.js:99 [DEBUG] 12:19.121 AuthClass - cannot load federated user from auth storage
18:12:19.121 VM12638 ConsoleLogger.js:99 [DEBUG] 12:19.121 AuthClass - get current authenticated userpool user
18:12:19.122 VM12638 ConsoleLogger.js:99 [DEBUG] 12:19.122 AuthClass - Failed to get user from user pool
18:12:19.122 VM12638 ConsoleLogger.js:109 [DEBUG] 12:19.122 AuthClass - The user is not authenticated by the error No current user
18:12:19.123 VM12605 guard.js:67 err not authenticated
```

</details>

**Comment by mllrmat** [comment]
I have the same problem. Looking at the code, they are never passed to/from the refresh function. 
See: https://github.com/aws-amplify/amplify-js/blob/abb5e3605e21685c98959af67115fa6a37bf22f2/packages/core/src/Credentials.ts#L148

**Comment by mauerbac** [comment]
hey @enrique-gil-vessi - coming back to this issue. Sorry for the delay. We have [documentation on Lambda Triggers](https://docs.amplify.aws/cli/usage/lambda-triggers#cognito-lambda-triggers) with Cognito -- this should help with your use case. Please open a new issue if you run into problems. Thanks
