### ISSUE TITLE
Error in Lambda function when creating object with relationship

### ISSUE THREAD

**Issue by duncangroenewald** [aws-amplify/amplify-js#6966]
I am trying to get a list of video objects with some properties of related objects.

Schema as shown below:

```
    type SessionType 
    @model
    {
        id: ID!
        name: String!
        activityTypes: [ActivityType] @connection(keyName: "bySessionType", fields: ["id"])
        videos: [Video] @connection(name: "SessionTypeVideo")
    }

    type Video 
    @model 
    {
        id: ID!
        bucket: String!
        key: String!
        sessionDate: String
        isReviewed: String!
        reviewedBy: ID
        reviewDate: String
        title: String
        comments: String
        sessionTypeID: ID!
        sessionType: SessionType @connection(name: "SessionTypeVideo")
        activityTypeID: ID!
        modeID: ID!
        genderID: ID!
        ageGroupID: ID!
        weightCategoryID: ID!
    }
    
    
    # create the input object for the lambda function so 
    # we can pass in the owner - is this actually required ??

    input CreateVideoInput {
    	id: ID
      owner: String
    	sessionDate: String!
      genderID: ID!
      ageGroupID: ID!
      weightCategoryID: ID!
      sessionTypeID: ID!
      videoSessionTypeId: ID!
      activityTypeID: ID!
      modeID: ID!
      isReviewed: String!
    	bucket: String!
    	key: String!
    	title: String
    }
```

AppSync annotations appear to have created the `videoSessionTypeId` property in the actual graphql schema definition when viewed in AppSync console.  Although these don't show up in the generated queries and mutations which are shown below.

 ```
   export const createVideo = /* GraphQL */ `
      mutation CreateVideo(
        $input: CreateVideoInput!
        $condition: ModelVideoConditionInput
      ) {
        createVideo(input: $input, condition: $condition) {
          id
          bucket
          key
          sessionDate
          isReviewed
          reviewedBy
          reviewDate
          title
          comments
          sessionTypeID
          sessionType {
            id
            name
            activityTypes {
              nextToken
            }
            modes {
              nextToken
            }
            createdAt
            updatedAt
            videos {
              nextToken
            }
          }
          activityTypeID
          modeID
          genderID
          ageGroupID
          weightCategoryID
          athletes {
            items {
              id
              createdAt
              updatedAt
            }
            nextToken
          }
          createdAt
          updatedAt
          owner
        }
      }
    `;
    
    export const listVideos = /* GraphQL */ `
      query ListVideos(
        $filter: ModelVideoFilterInput
        $limit: Int
        $nextToken: String
      ) {
        listVideos(filter: $filter, limit: $limit, nextToken: $nextToken) {
          items {
            id
            bucket
            key
            sessionDate
            isReviewed
            reviewedBy
            reviewDate
            title
            comments
            sessionTypeID
            sessionType {
              id
              name
              createdAt
              updatedAt
            }
            activityTypeID
            modeID
            genderID
            ageGroupID
            weightCategoryID
            athletes {
              nextToken
            }
            createdAt
            updatedAt
            owner
          }
          nextToken
        }
      }
    `;
```

Currently the sessionType {id, name} property returned by the listVideos function is always null so I guess the create method I am using is not setting the correct properties on the Video object.  If I manually create the entry using AppSync console and setting the videoSessionTypeId property it works.

The input properties are passed as metadata when uploading the file and subsequently extracted from the S3.headObject().
The input object used in the Lambda function is as follows:

 ```
   const item = {
    		id: id, 
        owner: metadata.owner,
        sessionDate: metadata.sessiondate,
        genderID: metadata.genderid,
        ageGroupID: metadata.agegroupid,
        weightCategoryID: metadata.weightcategoryid,
        sessionTypeID: metadata.sessiontypeid,
        videoSessionTypeId: metadata.sessiontypeid,               <==== 
        activityTypeID: metadata.activitytypeid,
        modeID: metadata.modeid,
        isReviewed: 'false',
        bucket: bucketName,
        key: key,
        title: metadata.videotitle
      } 
```

The lambda function that calls the mutate function is shown below:

  ```
  async function storeVideoInfo(item) {
      console.log('storeVideoItem', JSON.stringify(item))
      const createVideo = gql`
        mutation CreateVideo(
          $input: CreateVideoInput!
          $condition: ModelVideoConditionInput
        ) {
          createVideo(input: $input, condition: $condition) {
            id
            sessionDate
            genderID
            ageGroupID
            weightCategoryID
            sessionTypeID
            videoSessionTypeId
            activityTypeID
            modeID
            isReviewed
            title
            owner
            bucket
            key
          }
        }
      `;
    
      console.log('trying to createvideo with input', JSON.stringify(item))
      const result = await client.mutate({
        mutation: createVideo,
        variables: { input: item },
        fetchPolicy: 'no-cache'
      })
    
      console.log('result', JSON.stringify(result))
      return result
    }
```

However when calling the AppSync API to create the video record is fails when running validation on the input property 'videoSessionTypeId'.

Can anyone provide an explanation for how relations work and how you create a new object and the relationships such that subsequent queries return the object and properties of related objects.

BTW this is the error from the Lambda function:

```
    2020-10-13T22:28:35.438Z	d42efde3-100b-434f-b967-ce080bd43e6e	ERROR	Unhandled Promise Rejection	
    {
        "errorType": "Runtime.UnhandledPromiseRejection",
        "errorMessage": "Error: GraphQL error: Validation error of type FieldUndefined: Field 'videoSessionTypeId' in type 'Video' is undefined @ 'createVideo/videoSessionTypeId'",
        "reason": {
            "errorType": "Error",
            "errorMessage": "GraphQL error: Validation error of type FieldUndefined: Field 'videoSessionTypeId' in type 'Video' is undefined @ 'createVideo/videoSessionTypeId'",
            "graphQLErrors": [
                {
                    "path": null,
                    "locations": [
                        {
                            "line": 9,
                            "column": 5,
                            "sourceName": null
                        }
                    ],
                    "message": "Validation error of type FieldUndefined: Field 'videoSessionTypeId' in type 'Video' is undefined @ 'createVideo/videoSessionTypeId'"
                }
            ],
            "networkError": null,
            "message": "GraphQL error: Validation error of type FieldUndefined: Field 'videoSessionTypeId' in type 'Video' is undefined @ 'createVideo/videoSessionTypeId'",
            "stack": [
                "Error: GraphQL error: Validation error of type FieldUndefined: Field 'videoSessionTypeId' in type 'Video' is undefined @ 'createVideo/videoSessionTypeId'",
                "    at new ApolloError (/var/task/node_modules/apollo-client/bundle.umd.js:85:32)",
                "    at Object.next (/var/task/node_modules/apollo-client/bundle.umd.js:890:37)",
                "    at notifySubscription (/var/task/node_modules/zen-observable/lib/Observable.js:135:18)",
                "    at onNotify (/var/task/node_modules/zen-observable/lib/Observable.js:179:3)",
                "    at SubscriptionObserver.next (/var/task/node_modules/zen-observable/lib/Observable.js:235:7)",
                "    at notifySubscription (/var/task/node_modules/zen-observable/lib/Observable.js:135:18)",
                "    at onNotify (/var/task/node_modules/zen-observable/lib/Observable.js:179:3)",
                "    at SubscriptionObserver.next (/var/task/node_modules/zen-observable/lib/Observable.js:235:7)",
                "    at notifySubscription (/var/task/node_modules/zen-observable/lib/Observable.js:135:18)",
                "    at onNotify (/var/task/node_modules/zen-observable/lib/Observable.js:179:3)"
            ]
        },
        "promise": {},
        "stack": [
            "Runtime.UnhandledPromiseRejection: Error: GraphQL error: Validation error of type FieldUndefined: Field 'videoSessionTypeId' in type 'Video' is undefined @ 'createVideo/videoSessionTypeId'",
            "    at process.on (/var/runtime/index.js:37:15)",
            "    at process.emit (events.js:198:13)",
            "    at process.EventEmitter.emit (domain.js:448:20)",
            "    at emitPromiseRejectionWarnings (internal/process/promises.js:140:18)",
            "    at process._tickCallback (internal/process/next_tick.js:69:34)"
        ]
    }
```

**Comment by duncangroenewald** [comment]
For whatever reason I had to delete the $condition parameter to get it to work.  Not sure if that is a bug since this is an optional parameter!!

**Comment by sammartinez** [comment]
@duncangroenewald Was there a reason for the use of the `$condition`? Since it is an optional parameter, I believe you solved your own issue here :). Please let us know if you were needing to use the `$condition` flag for whatever reason and we can look to investigate this further. Thanks!
