### ISSUE TITLE
Lerna Error When Building

### ISSUE THREAD

**Issue by reggie3** [aws-amplify/amplify-js#7142]
**Describe the bug**
After following the steps in `CONTRIBUTING.md` for building the repo:

```
$ git clone git@github.com:[username]/amplify-js.git
$ cd amplify-js

$ yarn
$ yarn bootstrap
$ yarn build
``` 

I receive the following error when I try to run the `yarn build` command:
![image](https://user-images.githubusercontent.com/7347192/98453709-45e65c80-212a-11eb-8a78-d8eb129dd001.png)

**To Reproduce**

Follow the build steps listed in `CONTRIBUTING.md`

```
$ git clone git@github.com:[username]/amplify-js.git
$ cd amplify-js

$ yarn
$ yarn bootstrap
$ yarn build
``` 

The error occurs during `yarn build`

**Expected behavior**
I expect to be able to complete `yarn build` successfully.

**What is Configured?**
Versions:
aws-amplify - 0.1.30
npm - 6.14.8
yarn - 1.22.5
node - 14.15.0
Windows - 10.0.19041 Build 19041
Using Windows Subsystem for Linux 2 with Ubuntu 20.04 LTS

The fork that I am working with is in my WSL directory and is mounted in the WSL filesystem.

**Additional context**
Here are the contents of the `lerna-debug.log` file after the error occurs:

```
0 silly input [ 'yarn', 'build' ]
1 silly flags {
1 silly flags   _: [ 'exec' ],
1 silly flags   'reject-cycles': false,
1 silly flags   rejectCycles: false,
1 silly flags   command: 'yarn',
1 silly flags   args: [ 'build' ]
1 silly flags }
2 verbose rootPath /home/reggie3/repos/amplify-js
3 info version 2.11.0
4 silly existsSync /home/reggie3/repos/amplify-js/VERSION
5 info versioning independent
6 silly initialize attempt
7 silly initialize success
8 silly execute attempt
9 error exec Errored while executing 'yarn build' in 'aws-amplify-angular'
10 error execute callback with error
11 error Error: Command failed: yarn build
11 error     at /home/reggie3/repos/amplify-js/node_modules/lerna/node_modules/execa/index.js:236:11
```

**Comment by reggie3** [comment]
Additionally, Lerna experiences a different error when I attempt to build it directly in Windows without using WSL.

```
0 silly input [ 'yarn', 'build' ]
1 silly flags {
1 silly flags   _: [ 'exec' ],
1 silly flags   'reject-cycles': false,
1 silly flags   rejectCycles: false,
1 silly flags   command: 'yarn',
1 silly flags   args: [ 'build' ]
1 silly flags }
2 verbose rootPath C:\Users\rej_i\Dropbox\My PC (Reggie-Desktop)\Documents\development\amplify-js
3 info version 2.11.0
4 silly existsSync C:\Users\rej_i\Dropbox\My PC (Reggie-Desktop)\Documents\development\amplify-js\VERSION
5 info versioning independent
6 silly initialize attempt
7 silly initialize success
8 silly execute attempt
9 error exec Errored while executing 'yarn build' in 'aws-amplify-angular'
10 error execute callback with error
11 error Error: spawn yarn ENOENT
11 error     at notFoundError (C:\Users\rej_i\Dropbox\My PC (Reggie-Desktop)\Documents\development\amplify-js\node_modules\cross-spawn\lib\enoent.js:11:11)
11 error     at verifyENOENT (C:\Users\rej_i\Dropbox\My PC (Reggie-Desktop)\Documents\development\amplify-js\node_modules\cross-spawn\lib\enoent.js:46:16)
11 error     at ChildProcess.cp.emit (C:\Users\rej_i\Dropbox\My PC (Reggie-Desktop)\Documents\development\amplify-js\node_modules\cross-spawn\lib\enoent.js:33:19)
```

**Comment by harrysolovay** [comment]
Hi @reggie3, this does seem odd. Can you please run the following and let me know what is output in your CLI?:

```
yarn lerna run build --stream --concurrency=1 --include-dependencies
```

Also, I'm removing the `Core` label, as I don't believe this issue is related to `@aws-amplify/core`.

**Comment by reggie3** [comment]
@harrysolovay  Here are the results of running that command

```
C:\Users\rej_i\Documents\development\amplify-js> yarn lerna run build --stream --concurrency=1 --include-dependencies
yarn run v1.22.4
$ C:\Users\rej_i\Documents\development\amplify-js\node_modules\.bin\lerna run build --stream --concurrency=1 --include-dependencies
lerna info version 2.11.0
lerna info versioning independent
amazon-cognito-identity-js: $ npm run clean && npm run build:commonjs && npm run build:es && npm run build:umd && npm run build:umd:min
amazon-cognito-identity-js: > amazon-cognito-identity-js@2.0.14 clean C:\Users\rej_i\Documents\development\amplify-js\packages\amazon-cognito-identity-js
amazon-cognito-identity-js: > rimraf lib es
amazon-cognito-identity-js: > amazon-cognito-identity-js@2.0.14 build:commonjs C:\Users\rej_i\Documents\development\amplify-js\packages\amazon-cognito-identity-js
amazon-cognito-identity-js: > cross-env BABEL_ENV=commonjs babel src --out-dir lib
amazon-cognito-identity-js: src\AuthenticationDetails.js -> lib\AuthenticationDetails.js
amazon-cognito-identity-js: src\AuthenticationHelper.js -> lib\AuthenticationHelper.js
amazon-cognito-identity-js: src\BigInteger.js -> lib\BigInteger.js
amazon-cognito-identity-js: src\Client.js -> lib\Client.js
amazon-cognito-identity-js: src\CognitoAccessToken.js -> lib\CognitoAccessToken.js
amazon-cognito-identity-js: src\CognitoIdToken.js -> lib\CognitoIdToken.js
amazon-cognito-identity-js: src\CognitoJwtToken.js -> lib\CognitoJwtToken.js
amazon-cognito-identity-js: src\CognitoRefreshToken.js -> lib\CognitoRefreshToken.js
amazon-cognito-identity-js: src\CognitoUser.js -> lib\CognitoUser.js
amazon-cognito-identity-js: src\CognitoUserAttribute.js -> lib\CognitoUserAttribute.js
amazon-cognito-identity-js: src\CognitoUserPool.js -> lib\CognitoUserPool.js
amazon-cognito-identity-js: src\CognitoUserSession.js -> lib\CognitoUserSession.js
amazon-cognito-identity-js: src\CookieStorage.js -> lib\CookieStorage.js
amazon-cognito-identity-js: src\DateHelper.js -> lib\DateHelper.js
amazon-cognito-identity-js: src\index.js -> lib\index.js
amazon-cognito-identity-js: src\StorageHelper-rn.js -> lib\StorageHelper-rn.js
amazon-cognito-identity-js: src\StorageHelper.js -> lib\StorageHelper.js
amazon-cognito-identity-js: src\UserAgent.js -> lib\UserAgent.js
amazon-cognito-identity-js: > amazon-cognito-identity-js@2.0.14 build:es C:\Users\rej_i\Documents\development\amplify-js\packages\amazon-cognito-identity-js
amazon-cognito-identity-js: > cross-env BABEL_ENV=es babel src --out-dir es
amazon-cognito-identity-js: src\AuthenticationDetails.js -> es\AuthenticationDetails.js
amazon-cognito-identity-js: src\AuthenticationHelper.js -> es\AuthenticationHelper.js
amazon-cognito-identity-js: src\BigInteger.js -> es\BigInteger.js
amazon-cognito-identity-js: src\Client.js -> es\Client.js
amazon-cognito-identity-js: src\CognitoAccessToken.js -> es\CognitoAccessToken.js
amazon-cognito-identity-js: src\CognitoIdToken.js -> es\CognitoIdToken.js
amazon-cognito-identity-js: src\CognitoJwtToken.js -> es\CognitoJwtToken.js        
amazon-cognito-identity-js: src\CognitoRefreshToken.js -> es\CognitoRefreshToken.js
amazon-cognito-identity-js: src\CognitoUser.js -> es\CognitoUser.js
amazon-cognito-identity-js: src\CognitoUserAttribute.js -> es\CognitoUserAttribute.js
amazon-cognito-identity-js: src\CognitoUserPool.js -> es\CognitoUserPool.js
amazon-cognito-identity-js: src\CognitoUserSession.js -> es\CognitoUserSession.js
amazon-cognito-identity-js: src\CookieStorage.js -> es\CookieStorage.js
amazon-cognito-identity-js: src\DateHelper.js -> es\DateHelper.js
amazon-cognito-identity-js: src\index.js -> es\index.js
amazon-cognito-identity-js: src\StorageHelper-rn.js -> es\StorageHelper-rn.js
amazon-cognito-identity-js: src\StorageHelper.js -> es\StorageHelper.js
amazon-cognito-identity-js: src\UserAgent.js -> es\UserAgent.js
amazon-cognito-identity-js: > amazon-cognito-identity-js@2.0.14 build:umd C:\Users\rej_i\Documents\development\amplify-js\packages\amazon-cognito-identity-js
amazon-cognito-identity-js: > cross-env BABEL_ENV=commonjs NODE_ENV=development webpack -p dist/amazon-cognito-identity.js
amazon-cognito-identity-js: (node:21356) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
amazon-cognito-identity-js: parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
amazon-cognito-identity-js: (Use `node --trace-deprecation ...` to show where the warning was created)
amazon-cognito-identity-js: Hash: 3b4fb01c2b62a6598b74
amazon-cognito-identity-js: Version: webpack 3.12.0
amazon-cognito-identity-js: Time: 2209ms
amazon-cognito-identity-js:                      Asset     Size  Chunks             Chunk Names
amazon-cognito-identity-js: amazon-cognito-identity.js  86.4 kB       0  [emitted]  main
amazon-cognito-identity-js:    [2] ./src/AuthenticationHelper.js 14 kB {0} [built]
amazon-cognito-identity-js:    [4] ./src/BigInteger.js 19.3 kB {0} [built]
amazon-cognito-identity-js:    [5] ./src/CognitoAccessToken.js 9.8 kB {0} [built]
amazon-cognito-identity-js:    [6] ./src/CognitoJwtToken.js 4.34 kB {0} [built]
amazon-cognito-identity-js:    [7] ./src/CognitoIdToken.js 9.75 kB {0} [built]
amazon-cognito-identity-js:    [8] ./src/CognitoRefreshToken.js 1.45 kB {0} [built]
amazon-cognito-identity-js:    [9] ./src/CognitoUser.js 66.8 kB {0} [built]
amazon-cognito-identity-js:   [10] ./src/CognitoUserSession.js 3.41 kB {0} [built]
amazon-cognito-identity-js:   [11] ./src/DateHelper.js 1.94 kB {0} [built]
amazon-cognito-identity-js:   [12] ./src/CognitoUserAttribute.js 2.58 kB {0} [built]
amazon-cognito-identity-js:   [13] ./src/StorageHelper.js 2.76 kB {0} [built]
amazon-cognito-identity-js:   [14] ./src/index.js 2.61 kB {0} [built]
amazon-cognito-identity-js:   [15] ./src/AuthenticationDetails.js 2.47 kB {0} [built]
amazon-cognito-identity-js:   [24] ./src/CognitoUserPool.js 8.63 kB {0} [built]
amazon-cognito-identity-js:   [27] ./src/CookieStorage.js 2.92 kB {0} [built]
amazon-cognito-identity-js:     + 14 hidden modules
amazon-cognito-identity-js: > amazon-cognito-identity-js@2.0.14 build:umd:min C:\Users\rej_i\Documents\development\amplify-js\packages\amazon-cognito-identity-js
amazon-cognito-identity-js: > cross-env BABEL_ENV=commonjs NODE_ENV=production webpack -p dist/amazon-cognito-identity.min.js
amazon-cognito-identity-js: (node:24760) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
amazon-cognito-identity-js: parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
amazon-cognito-identity-js: (Use `node --trace-deprecation ...` to show where the warning was created)
amazon-cognito-identity-js: Hash: 3579487efd20b35583ca
amazon-cognito-identity-js: Version: webpack 3.12.0
amazon-cognito-identity-js: Time: 2979ms
amazon-cognito-identity-js:                              Asset     Size  Chunks             Chunk Names
amazon-cognito-identity-js:     amazon-cognito-identity.min.js  86.4 kB       0  [emitted]  main
amazon-cognito-identity-js: amazon-cognito-identity.min.js.map   562 kB       0  [emitted]  main
amazon-cognito-identity-js:    [2] ./src/AuthenticationHelper.js 14 kB {0} [built]
amazon-cognito-identity-js:    [4] ./src/BigInteger.js 19.3 kB {0} [built]
amazon-cognito-identity-js:    [5] ./src/CognitoAccessToken.js 9.8 kB {0} [built]
amazon-cognito-identity-js:    [6] ./src/CognitoJwtToken.js 4.34 kB {0} [built]
amazon-cognito-identity-js:    [7] ./src/CognitoIdToken.js 9.75 kB {0} [built]
amazon-cognito-identity-js:    [8] ./src/CognitoRefreshToken.js 1.45 kB {0} [built]
amazon-cognito-identity-js:    [9] ./src/CognitoUser.js 66.8 kB {0} [built]
amazon-cognito-identity-js:   [10] ./src/CognitoUserSession.js 3.41 kB {0} [built]
amazon-cognito-identity-js:   [11] ./src/DateHelper.js 1.94 kB {0} [built]
amazon-cognito-identity-js:   [12] ./src/CognitoUserAttribute.js 2.58 kB {0} [built]
amazon-cognito-identity-js:   [13] ./src/StorageHelper.js 2.76 kB {0} [built]
amazon-cognito-identity-js:   [14] ./src/index.js 2.61 kB {0} [built]
amazon-cognito-identity-js:   [15] ./src/AuthenticationDetails.js 2.47 kB {0} [built]
amazon-cognito-identity-js:   [24] ./src/CognitoUserPool.js 8.63 kB {0} [built]
amazon-cognito-identity-js:   [27] ./src/CookieStorage.js 2.92 kB {0} [built]
amazon-cognito-identity-js:     + 14 hidden modules
aws-amplify-angular: $ gulp inline-templates && npm run ngcompile && npm run cleantemp
aws-amplify-angular: fs.js:39
aws-amplify-angular: } = primordials;\n    ^
aws-amplify-angular: ReferenceError: primordials is not defined\n    at fs.js:39:5\n    at req_ (C:\Users\rej_i\Documents\development\amplify-js\node_modules\natives\index.js:137:5)\n    at Object.req [as require] (C:\Users\rej_i\Documents\development\amplify-js\node_modules\natives\index.js:54:10)\n    at Object.<anonymous> (C:\Users\rej_i\Documents\development\amplify-js\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)\n    at Module._compile (internal/modules/cjs/loader.js:1200:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)\n    at Module.load (internal/modules/cjs/loader.js:1049:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:937:14)\n    at Module.require (internal/modules/cjs/loader.js:1089:19)\n    at require (internal/modules/cjs/helpers.js:73:18)
aws-amplify-angular: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
aws-amplify-angular: error Command failed with exit code 1.
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn run build
lerna ERR! fs.js:39
lerna ERR! } = primordials;
lerna ERR!     ^
lerna ERR!
lerna ERR! ReferenceError: primordials is not defined
lerna ERR!     at fs.js:39:5
lerna ERR!     at req_ (C:\Users\rej_i\Documents\development\amplify-js\node_modules\natives\index.js:137:5)
lerna ERR!     at Object.req [as require] (C:\Users\rej_i\Documents\development\amplify-js\node_modules\natives\index.js:54:10)
lerna ERR!     at Object.<anonymous> (C:\Users\rej_i\Documents\development\amplify-js\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
lerna ERR!     at Module._compile (internal/modules/cjs/loader.js:1200:30)
lerna ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
lerna ERR!     at Module.load (internal/modules/cjs/loader.js:1049:32)
lerna ERR!     at Function.Module._load (internal/modules/cjs/loader.js:937:14)
lerna ERR!     at Module.require (internal/modules/cjs/loader.js:1089:19)
lerna ERR!     at require (internal/modules/cjs/helpers.js:73:18)
lerna ERR! error Command failed with exit code 1.
lerna ERR!
lerna ERR! $ gulp inline-templates && npm run ngcompile && npm run cleantemp
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR!
lerna ERR!     at C:\Users\rej_i\Documents\development\amplify-js\node_modules\lerna\node_modules\execa\index.js:236:11
Error: Command failed: yarn run build
fs.js:39
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:39:5
    at req_ (C:\Users\rej_i\Documents\development\amplify-js\node_modules\natives\index.js:137:5)
    at Object.req [as require] (C:\Users\rej_i\Documents\development\amplify-js\node_modules\natives\index.js:54:10)
    at Object.<anonymous> (C:\Users\rej_i\Documents\development\amplify-js\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
error Command failed with exit code 1.

$ gulp inline-templates && npm run ngcompile && npm run cleantemp
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at C:\Users\rej_i\Documents\development\amplify-js\node_modules\lerna\node_modules\execa\index.js:236:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 1,
  killed: false,
  stdout: '$ gulp inline-templates && npm run ngcompile && npm run cleantemp\n' +
    'info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n',
  stderr: 'fs.js:39\r\n' +
    '} = primordials;\r\n' +
    '    ^\r\n' +
    '\r\n' +
    'ReferenceError: primordials is not defined\r\n' +
    '    at fs.js:39:5\r\n' +
    '    at req_ (C:\\Users\\rej_i\\Documents\\development\\amplify-js\\node_modules\\natives\\index.js:137:5)\r\n' +
    '    at Object.req [as require] (C:\\Users\\rej_i\\Documents\\development\\amplify-js\\node_modules\\natives\\index.js:54:10)\r\n' +
    '    at Object.<anonymous> (C:\\Users\\rej_i\\Documents\\development\\amplify-js\\node_modules\\vinyl-fs\\node_modules\\graceful-fs\\fs.js:1:37)\r\n' +
    '    at Module._compile (internal/modules/cjs/loader.js:1200:30)\r\n' +
    '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)\r\n' +
    '    at Module.load (internal/modules/cjs/loader.js:1049:32)\r\n' +
    '    at Function.Module._load (internal/modules/cjs/loader.js:937:14)\r\n' +
    '    at Module.require (internal/modules/cjs/loader.js:1089:19)\r\n' +
    '    at require (internal/modules/cjs/helpers.js:73:18)\r\n' +
    'error Command failed with exit code 1.\n',
  failed: true,
  signal: null,
  cmd: 'yarn run build',
  timedOut: false,
  exitCode: 1
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by sammartinez** [comment]
@reggie3 I cannot reproduce this, I also see that you are on older versions of `aws-amplify` can you try this on the latest version? I am going to resolve this as we can't reproduce this. Please let us know if you are still experiencing this on the latest versions and we can reopen. Thanks!
