### ISSUE TITLE
Amplify Auth | Admin query not working if form data is posted.

### ISSUE THREAD

**Issue by AzherAleem** [aws-amplify/amplify-js#7537]
I am trying to utilise the admin actions from the following doc links: https://docs.amplify.aws/cli/auth/admin#example

However, when i try to call a post method i.e. disableUser i get the error: 

```
 ReferenceError: FormData is not defined

      at RestClient.<anonymous> (node_modules/@aws-amplify/api-rest/src/RestClient.ts:136:30)
      at step (node_modules/@aws-amplify/api-rest/lib/RestClient.js:56:23)
      at Object.next (node_modules/@aws-amplify/api-rest/lib/RestClient.js:37:53)
      at node_modules/@aws-amplify/api-rest/lib/RestClient.js:31:71
      at Object.<anonymous>.__awaiter (node_modules/@aws-amplify/api-rest/lib/RestClient.js:27:12)
      at RestClient.Object.<anonymous>.RestClient.ajax (node_modules/@aws-amplify/api-rest/lib/RestClient.js:139:16)
      at RestClient.Object.<anonymous>.RestClient.post (node_modules/@aws-amplify/api-rest/lib/RestClient.js:288:21)
      at RestAPIClass.Object.<anonymous>.RestAPIClass.post (node_modules/@aws-amplify/api-rest/src/RestAPI.ts:152:38)
      at APIClass.Object.<anonymous>.APIClass.post (node_modules/@aws-amplify/api/src/API.ts:102:24)
```

In the RestClient.js file in the amplify package has this piece of code that runs when body is passed along to the post method(s).

 ```
if (initParams.body) {
  if (initParams.body instanceof FormData) {
      libraryHeaders['Content-Type'] = 'multipart/form-data';
      params.data = initParams.body;
  }
  else {
      libraryHeaders['Content-Type'] = 'application/json; charset=UTF-8';
      params.data = JSON.stringify(initParams.body);
  } 
} 
```

Is amplify having issues referencing the FormData? Or is there anything that i am missing?

Steps to reproduce:

1. Install amplify and its cli.
2. Add api with admin api queries.
3. Add auth.
4. Create user in the user pool with the admin rights.
5. Write script to call any of the admin actions which are POST methods e.g. Enable, Disable user.

**Comment by nadetastic** [comment]
Hi @AzherAleem 👋,

I'm following up on this issue - I was working to reproduce this however, I haven't been able to do so, at least with v5.0.4?

Were you able to get unblocked on this issue?
