### ISSUE TITLE
awsmobile InternalFailureException: java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Base64.encodeBase64String([B)Ljava/lang/String;

### ISSUE THREAD

**Issue by takumiecofit** [aws-amplify/amplify-js#7643]
**Describe the bug**
We are using awsmobile to deploy our app. It deployed without errors as it should yesterday and today it is failing to deploy. It has been deploying fine for the last 2-3 years.

We understand that awsmobile will be deprecated in Oct 2021 and will promptly migrate when the time is right for us. 

If the developers of aws-amplify recommend us to migrate sooner rather than later to avoid situations like this. We take it into consideration.

**To Reproduce**

1. awsmobile init 6077****-*****-****-*****-***********
2. awsmobile publish

**Expected behavior**
Deploys to the Mobilehub properly and able to access the deployed app.

**Code Snippet**
```
➜  asset-portal-2 git:(develop) ✗ awsmobile publish
checking the backend contents
   generating backend project content
   done
backend build artifacts are saved at:
/Users/******/Documents/repos/portal/awsmobilejs/.awsmobile/backend-build
preparing for backend project update: portal
done
updating backend project: portal
Failed to update project portal
InternalFailureException: java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Base64.encodeBase64String([B)Ljava/lang/String;
    at Object.extractError (/usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/request.js:685:12) {
  code: 'InternalFailureException',
  time: 2021-01-28T16:38:14.376Z,
  requestId: '2a49b195-4739-4f44-a645-ccdb418bdf54',
  statusCode: 500,
  retryable: true
```

<details>
  <summary><strong>Environment</strong></summary>

```
 System:
    OS: macOS 11.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 780.93 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
  Browsers:
    Chrome Canary: 90.0.4402.0
    Safari: 14.0.2
    Safari Technology Preview: 14.1
  npmPackages:
    @agm/core: ^3.0.0-beta.0 => 3.0.0-beta.0 
    @angular-devkit/build-angular: ~0.1100.6 => 0.1100.7 
    @angular/animations: ^11.0.7 => 11.1.1 
    @angular/cdk: ^11.0.3 => 11.1.1 
    @angular/cli: ^11.0.6 => 11.1.1 
    @angular/common: ^11.0.7 => 11.1.1 
    @angular/compiler: ^11.0.7 => 11.1.1 
    @angular/compiler-cli: ^11.0.7 => 11.1.1 
    @angular/core: ^11.0.7 => 11.1.1 
    @angular/forms: ^11.0.7 => 11.1.1 
    @angular/google-maps: ^9.2.4 => 9.2.4 
    @angular/language-service: ^11.0.7 => 11.1.1 
    @angular/localize: ^11.0.7 => 11.1.1 
    @angular/material: ^11.0.3 => 11.1.1 
    @angular/material-moment-adapter: ^11.0.3 => 11.1.1 
    @angular/platform-browser: ^11.0.7 => 11.1.1 
    @angular/platform-browser-dynamic: ^11.0.7 => 11.1.1 
    @angular/platform-server: ^11.0.7 => 11.1.1 
    @angular/router: ^11.0.7 => 11.1.1 
    @angularclass/hmr: ^2.1.3 => 2.1.3 
    @ng-bootstrap/ng-bootstrap: ^8.0.1 => 8.0.4 
    @ngx-loading-bar/core: ^2.2.0 => 2.2.0 
    @ngx-translate/core: ^10.0.2 => 10.0.2 
    @stripe/stripe-js: ^1.9.0 => 1.11.0 
    @types/chart.js: 2.9.14 => 2.9.14 
    @types/google.analytics: 0.0.40 => 0.0.40 
    @types/googlemaps: ^3.40.5 => 3.43.2 
    @types/jasmine: ~3.6.0 => 3.6.3 
    @types/jasminewd2: ^2.0.3 => 2.0.8 
    @types/lodash: ^4.14.158 => 4.14.168 
    @types/moment-duration-format: ^2.2.2 => 2.2.2 
    @types/moment-timezone: 0.5.12 => 0.5.12 
    @types/node: ^12.11.1 => 12.19.15 
    acorn: ^6.4.1 => 6.4.2 
    angular-in-memory-web-api: ^0.10.0 => 0.10.0 
    apexcharts: ^3.19.3 => 3.23.1 
    aws-amplify: ^1.3.3 => 1.3.3 
    aws-amplify-angular: ^5.0.43 => 5.0.43 
    babel-polyfill: ^6.26.0 => 6.26.0 
    bootstrap: ^4.4.1 => 4.6.0 
    chart.js: ^2.7.2 => 2.9.4 
    chartjs-plugin-datalabels: ^0.7.0 => 0.7.0 
    classlist.js: ^1.1.20150312 => 1.1.20150312 
    codelyzer: ^6.0.0 => 6.0.1 
    cookieconsent: ^3.1.1 => 3.1.1 
    core-js: ^2.6.11 => 2.6.12 
    crypto-js: 3.1.9-1 => 3.1.9-1 
    fuse.js: ^6.4.1 => 6.4.6 
    html2canvas: ^1.0.0-rc.5 => 1.0.0-rc.7 
    humanize-duration: ^3.21.0 => 3.25.1 
    jasmine: ^3.6.1 => 3.6.4 
    jasmine-core: ~3.6.0 => 3.6.0 
    jasmine-spec-reporter: ~5.0.0 => 5.0.2 
    jquery: ^3.4.1 => 3.5.1 
    karma: ~5.0.0 => 5.0.9 
    karma-chrome-launcher: ~3.1.0 => 3.1.0 
    karma-coverage-istanbul-reporter: ~3.0.2 => 3.0.3 
    karma-jasmine: ~4.0.0 => 4.0.1 
    karma-jasmine-html-reporter: ^1.5.0 => 1.5.4 
    lodash: ^4.17.19 => 4.17.20 
    material-design-icons: ^3.0.1 => 3.0.1 
    moment: ^2.22.2 => 2.29.1 
    moment-duration-format: ^2.3.2 => 2.3.2 
    moment-timezone: 0.5.27 => 0.5.27 
    morris.js: ^0.5.0 => 0.5.0 
    ng-apexcharts: ^1.5.0 => 1.5.6 
    ng2-charts: ^2.4.2 => 2.4.2 
    ngx-auth: 5.3.0 => 5.3.0 
    ngx-cookieconsent: ^2.2.3 => 2.2.3 
    ngx-daterangepicker-material: ^3.0.4 => 3.0.4 
    ngx-highlightjs: ^2.1.4 => 2.1.4 
    ngx-mat-select-search: ^3.0.1 => 3.2.0 
    ngx-material-timepicker: ^5.5.3 => 5.5.3 
    ngx-mqtt: ^6.14.0 => 6.14.0 
    ngx-perfect-scrollbar: ^6.3.1 => 6.3.1 
    ngx-permissions: ^7.0.3 => 7.0.3 
    ngx-stripe: ^9.2.0 => 9.2.0 
    ngx-webcam: ^0.3.0 => 0.3.2 
    object-path: ^0.11.4 => 0.11.5 
    pdfmake: ^0.1.66 => 0.1.70 
    popper.js: ^1.16.1 => 1.16.1 
    protractor: ~7.0.0 => 7.0.0 
    raphael: ^2.3.0 => 2.3.0 
    rxjs: 6.6.3 => 6.6.3 
    rxjs-compat: ^6.6.0 => 6.6.3 
    rxjs-tslint: ^0.1.8 => 0.1.8 
    sass: ^1.32.4 => 1.32.5 
    ts-node: ^6.2.0 => 6.2.0 
    tslib: ^2.0.0 => 2.1.0 
    tslint: ~6.1.0 => 6.1.3 
    typescript: 4.0.5 => 4.0.5 
    web-animations-js: ^2.3.2 => 2.3.2 
    whatwg-fetch: ^3.2.0 => 3.5.0 
    zone.js: ~0.10.2 => 0.10.3 
  npmGlobalPackages:
    @angular/cli: 11.0.6
    @aws-amplify/cli: 4.41.2
    @ionic/cli: 6.12.3
    aws-amplify: 3.3.14
    npm: 6.14.8
    serverless: 2.18.0
    source-map-explorer: 2.5.2
```

</details>

**Comment by elorzafe** [comment]
@takumiecofit 

Thanks for your feedback, I will transfer this to @amplify/cli repo. They will give you more information about this.
