### ISSUE TITLE
Cannot destructure property 'timeout' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by aterreno** [aws-amplify/amplify-js#7798]
Hi there, 
I am following step by step this tutorial https://aws.amazon.com/blogs/mobile/amplify-framework-local-mocking/ and when I try to add a lambda I get an error invoking the lambda with `amplify mock api` 

```
Lambda Data source failed with the following error
TypeError: Cannot destructure property 'timeout' of 'undefined' as it is undefined.
    at getCancellableTimer (/Users/toni/.nvm/versions/node/v14.15.5/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/func/index.ts:73:32)
    at Object.timeConstrainedInvoker (/Users/toni/.nvm/versions/node/v14.15.5/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/func/index.ts:65:29)
    at Object.invoke (/Users/toni/.nvm/versions/node/v14.15.5/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/api/api.ts:203:22)
    at LambdaDataLoader.<anonymous> (/Users/toni/.nvm/versions/node/v14.15.5/lib/node_modules/@aws-amplify/cli/node_modules/amplify-appsync-simulator/src/data-loader/lambda/index.ts:25:37)
    at step (/Users/toni/.nvm/versions/node/v14.15.5/lib/node_modules/@aws-amplify/cli/node_modules/amplify-appsync-simulator/lib/data-loader/lambda/index.js:33:23)
    at Object.next (/Users/toni/.nvm/versions/node/v14.15.5/lib/node_modules/@aws-amplify/cli/node_modules/amplify-appsync-simulator/lib/data-loader/lambda/index.js:14:53)
    at /Users/toni/.nvm/versions/node/v14.15.5/lib/node_modules/@aws-amplify/cli/node_modules/amplify-appsync-simulator/lib/data-loader/lambda/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/toni/.nvm/versions/node/v14.15.5/lib/node_modules/@aws-amplify/cli/node_modules/amplify-appsync-simulator/lib/data-loader/lambda/index.js:4:12)
    at LambdaDataLoader.load (/Users/toni/.nvm/versions/node/v14.15.5/lib/node_modules/@aws-amplify/cli/node_modules/amplify-appsync-simulator/lib/data-loader/lambda/index.js:56:16)
```

If I look at the source code in `amplify-util-mock` the timeout is nullable 

```typescript
export declare const timeConstrainedInvoker: <T>(promise: Promise<T>, options: InvokerOptions) => Promise<T>;
interface InvokerOptions {
timeout?: string;
}
```

however is then expected to be present with destrucuring in here:

```javascript
const getCancellableTimer = ({ timeout }) => {
    const inputTimeout = Number.parseInt("10", 10);
```

I am not sure (and I'd love to know) how I can set the timeout, so that my lambda would be mocked locally 

Thanks

**Comment by aterreno** [comment]
Pardon me, wrong project, it has already been raised here https://github.com/aws-amplify/amplify-cli/issues/6653
