### ISSUE TITLE
cognitoHostedUI_failure happens because of ValidationException when redirected after login attempt from CognitoHostedUIIdentityProvider.Google

### ISSUE THREAD

**Issue by katryo** [aws-amplify/amplify-js#7845]
**Describe the bug**

"cognitoHostedUI_failure" happened when I tried to login with `CognitoHostedUIIdentityProvider.Google` .

The error message was *ValidationException: 1 validation error detected: Value '{cognito-idp.us-east-1.amazonaws.com/us-east-1_5AO0qbaSS=}' at 'logins' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 50000, Member must have length greater than or equal to 1]*

There are only a few clues to fix. I'm not sure how can I fix it.

**To Reproduce**

0. Implement an Amplify app with Google OAuth2 login following the tutorial https://docs.amplify.aws/lib/auth/social/q/platform/js
1. Open login page of Google with `CognitoHostedUIIdentityProvider.Google`
2. Click your Google account and login with Google. It looks successful.
3. Callback redirect happens. The URL of signin redirect is `http://localhost:3000/auth/signin/`
4. Redirected to `http://localhost:3000/auth/signin/` . However, I failed to login because of the following error.

```
ValidationException: 1 validation error detected: Value '{cognito-idp.us-east-1.amazonaws.com/us-east-1_5AO0qbaSS=}' at 'logins' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 50000, Member must have length greater than or equal to 1]
    at eval (webpack-internal:///./node_modules/@aws-sdk/client-cognito-identity/dist/es/protocols/Aws_json1_1.js:931:68)
    at step (webpack-internal:///./node_modules/tslib/tslib.es6.js:127:23)
    at Object.eval [as next] (webpack-internal:///./node_modules/tslib/tslib.es6.js:108:53)
    at fulfilled (webpack-internal:///./node_modules/tslib/tslib.es6.js:98:58)
```

**Expected behavior**

Customers should be able to log in without errors.

**Code Snippet**

This issue happened in a Next.js app (in TypeScript).

👇   `pages/_app.tsx` configures Amplify.

```pages/_app.tsx
import "../styles/globals.css";
import * as React from "react";
import type { AppProps } from "next/app";
import { Provider } from "next-auth/client";
import { ChakraProvider } from "@chakra-ui/react";
import Amplify from "aws-amplify";
import awsConfig from "../src/aws-exports";

const isLocalhost = process.browser
  ? Boolean(
      window.location.hostname === "localhost" ||
        // [::1] is the IPv6 localhost address.
        window.location.hostname === "[::1]" ||
        // 127.0.0.1/8 is considered localhost for IPv4.
        window.location.hostname.match(
          /^127(?:\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}$/
        )
    )
  : false;

const [
  localRedirectSignIn,
  productionRedirectSignIn,
] = awsConfig.oauth.redirectSignIn.split(",");

const [
  localRedirectSignOut,
  productionRedirectSignOut,
] = awsConfig.oauth.redirectSignOut.split(",");

const updatedAwsConfig = {
  ...awsConfig,
  oauth: {
    ...awsConfig.oauth,
    redirectSignIn: isLocalhost
      ? localRedirectSignIn
      : productionRedirectSignIn,
    redirectSignOut: isLocalhost
      ? localRedirectSignOut
      : productionRedirectSignOut,
  },
};

Amplify.configure(updatedAwsConfig);

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Provider session={pageProps.session}>
      <ChakraProvider>
        <Component {...pageProps} />
      </ChakraProvider>
    </Provider>
  );
}

export default MyApp;
```

👇  `pages/index.tsx` has a button that executes `Auth.federatedSignIn` with Google.

```pages/index.tsx
           <button
              onClick={() =>
                Auth.federatedSignIn({
                  provider: CognitoHostedUIIdentityProvider.Google,
                })
              }
            >
              Federated Sign In
            </button>
```

`pages/auth/signin.tsx` handles the website of the destination of the login redirect.

`console.log("Sign in failure", data);` under `case "cognitoHostedUI_failure":` shows the error message.

```pages/auth/signin.tsx
import { Auth, Hub } from "aws-amplify";
import { useState, useEffect } from "react";

const SignIn = () => {
  const [user, setUser] = useState();

  useEffect(() => {
    Hub.listen("auth", ({ payload: { event, data } }) => {
      switch (event) {
        case "signIn":
        case "cognitoHostedUI":
          getUser().then((userData) => setUser(userData));
          break;
        case "signOut":
          setUser(undefined);
          break;
        case "signIn_failure":
        case "cognitoHostedUI_failure":
          console.log("Sign in failure", data);
          break;
      }
    });

    getUser().then((userData) => setUser(userData));
  }, []);

  function getUser() {
    return Auth.currentAuthenticatedUser()
      .then((userData) => {
        console.log({ userData });
        return userData;
      })
      .catch(() => console.log("Not signed in"));
  }
  return (
    <div>
      <button onClick={getUser}>buttttton</button>Sign in
    </div>
  );
};

export default SignIn;

```

👇  Here is the request payload of the POST request to `https://cognito-identity.us-east-1.amazonaws.com/` that got 400 error.

```
{"IdentityPoolId":"us-east-1:aa84337a-99de-4b84-8168-b30a9813cb82","Logins":{"cognito-idp.us-east-1.amazonaws.com/us-east-1_5AO0qbaSS":""}}
```

I guess `"Logins":{"cognito-idp.us-east-1.amazonaws.com/us-east-1_5AO0qbaSS":""` is the culprit. I think Amplify assumes that the value of `"cognito-idp.us-east-1.amazonaws.com/us-east-1_5AO0qbaSS"` is not an empty string.

![localhost_3000_auth_signin_code_d7a76d43-5331-4b9f-b659-ad8689b65b0f_state_7AREETiMbQYNqWQNiJ2dA9om0hJ5QxEX__and_Profiles](https://user-images.githubusercontent.com/1451339/109602926-649eb200-7b64-11eb-99f3-d6ea0b7460bc.png)

![localhost_3000_auth_signin_code_d7a76d43-5331-4b9f-b659-ad8689b65b0f_state_7AREETiMbQYNqWQNiJ2dA9om0hJ5QxEX__and_Profiles-2](https://user-images.githubusercontent.com/1451339/109602939-68323900-7b64-11eb-9b82-ab7fbd73ef04.png)

**Screenshots**

![localhost_3000_auth_signin_code_d7a76d43-5331-4b9f-b659-ad8689b65b0f_state_7AREETiMbQYNqWQNiJ2dA9om0hJ5QxEX_](https://user-images.githubusercontent.com/1451339/109601319-fa850d80-7b61-11eb-92ad-347fc9c6431b.png)

**What is Configured?**

 
```src/aws-exports.js
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:xxxx-xxx-xxxx-xxxx",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xxxxxx",
    "aws_user_pools_web_client_id": "xxxxxxxx",
    "oauth": {
        "domain": "xxxxxxxxx-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/auth/signin/,https://my.domain.com/auth/signin/",
        "redirectSignOut": "http://localhost:3000/auth/signout/,https://my.domain.com/auth/signout/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
```

* If applicable, provide more configuration data, for example for Amazon Cognito, run `aws cognito-idp describe-user-pool --user-pool-id us-west-2_xxxxxx` (Be sure to remove any sensitive data)

```
aws cognito-idp describe-user-pool --user-pool-id us-east-1xxxxxxxxx >> pool.json
```
 
```pool.json
{
    "UserPool": {
        "Id": "us-east-1_xxxxxxxx",
        "Name": "xxxxxxxxxx-dev",
        "Policies": {
            "PasswordPolicy": {
                "MinimumLength": 8,
                "RequireUppercase": false,
                "RequireLowercase": false,
                "RequireNumbers": false,
                "RequireSymbols": false,
                "TemporaryPasswordValidityDays": 7
            }
        },
        "LambdaConfig": {},
        "LastModifiedDate": "2021-03-01T20:41:46.300000-08:00",
        "CreationDate": "2021-03-01T20:41:46.300000-08:00",
        "SchemaAttributes": [
            {
                "Name": "sub",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": false,
                "Required": true,
                "StringAttributeConstraints": {
                    "MinLength": "1",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "given_name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "family_name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "middle_name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "nickname",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "preferred_username",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "profile",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "picture",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "website",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "email",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": true,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "email_verified",
                "AttributeDataType": "Boolean",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false
            },
            {
                "Name": "gender",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "birthdate",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "10",
                    "MaxLength": "10"
                }
            },
            {
                "Name": "zoneinfo",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "locale",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "phone_number",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "phone_number_verified",
                "AttributeDataType": "Boolean",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false
            },
            {
                "Name": "address",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "updated_at",
                "AttributeDataType": "Number",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "NumberAttributeConstraints": {
                    "MinValue": "0"
                }
            },
            {
                "Name": "identities",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {}
            }
        ],
        "AutoVerifiedAttributes": [
            "email"
        ],
        "UsernameAttributes": [
            "email"
        ],
        "SmsVerificationMessage": "Your verification code is {####}",
        "EmailVerificationMessage": "Your verification code is {####}",
        "EmailVerificationSubject": "Your verification code",
        "VerificationMessageTemplate": {
            "SmsMessage": "Your verification code is {####}",
            "EmailMessage": "Your verification code is {####}",
            "EmailSubject": "Your verification code",
            "DefaultEmailOption": "CONFIRM_WITH_CODE"
        },
        "MfaConfiguration": "OFF",
        "EstimatedNumberOfUsers": 1,
        "EmailConfiguration": {
            "EmailSendingAccount": "COGNITO_DEFAULT"
        },
        "SmsConfiguration": {
            "SnsCallerArn": "arn:aws:iam::xxxxxx:role/xxxxx-dev",
            "ExternalId": "xxxxxx_role_external_id"
        },
        "UserPoolTags": {},
        "Domain": "xxxxxx",
        "AdminCreateUserConfig": {
            "AllowAdminCreateUserOnly": false,
            "UnusedAccountValidityDays": 7
        },
        "UsernameConfiguration": {
            "CaseSensitive": false
        },
        "Arn": "arn:aws:cognito-idp:us-east-1:xxxxxxxxx:userpool/us-east-1_xxxxx"
    }
}

```

**Device (please complete the following information):**

- Device: MacBook Pro (15-inch, 2017)
- OS: macOS Catalina Version 10.15.7
- Browser Chrome
- Version 88.0.4324.150 (Official Build) (x86_64)

**Additional context**
I ran into this issue when I was developing my web app in my localhost.

**Is this a production issue?**
No.

Are you experiencing this issue with a production application where end users are affected?

- [ ] (check box if yes)

**Comment by katryo** [comment]
The same issue happened in Facebook login too. Same error message.

**Comment by katryo** [comment]
Looks like the same issue. https://github.com/aws-amplify/amplify-js/issues/7477

**Comment by katryo** [comment]
```next.config.js
module.exports = {
  trailingSlash: true,
};
```

One possible solution is setting `trailingSlash: true` in `next.config.js` . By this, we can avoid 308 Permanent Redirect done by Next.js.

```
308 Permanent Redirect - example.com/dashboard/?code=xxxxxxxx&state=xxxxxx
200 OK - example.com/dashboard?code=xxxxxxxx&state=xxxxxx
```

However, as mentioned here https://github.com/aws-amplify/amplify-js/issues/7477#issuecomment-766273818 , it is better to allow removing a trailing slash. A lot of customers want to set `trailingSlash: false` .

**Comment by tlmader** [comment]
I ran into the below error last night, and my redirect did not contain a trailing slash.
```
validation error detected: Value '{cognito-idp.us-east-1.amazonaws.com/us-east-xxx=}' at 'logins' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 50000, Member must have length greater than or equal to 1]"}
```
My issue was that I needed to add `responseType: 'code'` to the Amplify `oauth` configuration object.

My Amplify configuration:
```
const awsconfig = {
  Auth: {
    userPoolId: 'us-east-1_x',xxx
    userPoolWebClientId: 'xxx',
    identityPoolId: 'us-east-1:xxx',
    region: 'us-east-1',
    oauth: {
      domain: 'xxx.auth.us-east-1.amazoncognito.com',
      redirectSignIn: redirectUri,
      redirectSignOut: redirectUri,
      responseType: 'code',
      urlOpener,
    },
  },
};
```
What helped me to figure out the exact problem was adding `window.LOG_LEVEL = 'DEBUG';` and I was able to get the following message:
```
[DEBUG] 57:07.955 OAuth - Starting undefined flow with exp://127.0.0.1:19000?code=xxx
```
Hope this helps someone!

**Comment by tlmader** [comment]
I ran into the below error last night, and my redirect did not contain a trailing slash.
```
validation error detected: Value '{cognito-idp.us-east-1.amazonaws.com/us-east-xxx=}' at 'logins' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 50000, Member must have length greater than or equal to 1]"}
```
My issue was that I needed to add `responseType: 'code'` to the Amplify `oauth` configuration object.

My Amplify configuration:
```
const awsconfig = {
  Auth: {
    userPoolId: 'us-east-1_x',xxx
    userPoolWebClientId: 'xxx',
    identityPoolId: 'us-east-1:xxx',
    region: 'us-east-1',
    oauth: {
      domain: 'xxx.auth.us-east-1.amazoncognito.com',
      redirectSignIn: redirectUri,
      redirectSignOut: redirectUri,
      responseType: 'code',
      urlOpener,
    },
  },
};
```
What helped me figure out the exact problem was adding `window.LOG_LEVEL = 'DEBUG';` and I was able to get the following message:
```
[DEBUG] 57:07.955 OAuth - Starting undefined flow with exp://127.0.0.1:19000?code=xxx
```
Hope this helps someone!
