### ISSUE TITLE
Get/Update GraphQL request from Lambda not working

### ISSUE THREAD

**Issue by Neuroforge** [aws-amplify/amplify-js#7883]
**Describe the bug**

I am using https://docs.amplify.aws/guides/functions/graphql-from-lambda/q/platform/ios as a guide on how to call GraphQL from a lambda. And it seems to work great for List Queries and Create Mutations. It does not seem to work from GetQuery and UpdateMutations

However, when i tried to use UpdateDirectory and GetDirectory I get the following error. It appears to be the same error for both the operations. I am using the graphQL queries generated by Amplify from client side model declarations.

`2021-03-05T02:39:27.646Z	6b25d092-994a-49eb-a600-bb019b9602ea	ERROR	Uncaught Exception 	{"errorType":"SyntaxError","errorMessage":"Unexpected end of JSON input","stack":["SyntaxError: Unexpected end of JSON input","    at JSON.parse (<anonymous>)","    at IncomingMessage.<anonymous> (/var/task/index.js:31:30)","    at IncomingMessage.emit (events.js:314:20)","    at IncomingMessage.EventEmitter.emit (domain.js:483:12)","    at IncomingMessage.Readable.read (_stream_readable.js:507:10)","    at flow (_stream_readable.js:1007:34)","    at resume_ (_stream_readable.js:988:3)","    at processTicksAndRejections (internal/process/task_queues.js:84:21)"]}
END RequestId: 6b25d092-994a-49eb-a600-bb019b9602ea`

**To Reproduce**

1) Follow the tutorial linked above.
2) Use an Update mutation
4) See error in lambda console.log
5) Use a GetQuery using id of existing item
6) See error in lambda console.log

**Expected behavior**
The item should be updated by the update mutation and fetched by the get mutation.

**Code Snippet**

```
const executeAppSyncQuery = async (operationName, query, item) => {
    const req = new AWS.HttpRequest(appsyncUrl, region);

    req.method = 'POST';
    req.path = '/graphql';
    req.headers.host = endpoint;
    req.headers['Content-Type'] = 'application/json';

    req.body = JSON.stringify({
        query: query,
        operationName: operationName,
        variables: item,
    });

    const signer = new AWS.Signers.V4(req, 'appsync', true);
    signer.addAuthorization(AWS.config.credentials, AWS.util.date.getDate());

    const data = await new Promise((resolve, reject) => {
        const httpRequest = https.request({ ...req, host: endpoint }, (result) => {
            result.on('data', (data) => {
                resolve(JSON.parse(data.toString()));
            });
        });
        httpRequest.write(req.body);
        httpRequest.end();
    });
    return data;
};

```
CreateMutation (WORKS!!)

Using input....
`
            const item = {
                input: {
                    id: directoryId,
                    directoryName: "DirectoryName"
                }
            };
`

And mutation....

 `mutation CreateDirectory(
        $input: CreateDirectoryInput!
        $condition: ModelDirectoryConditionInput
      ) 
{
        createDirectory(input: $input, condition: $condition) {
          id
          directoryName
          _version
          _deleted
          _lastChangedAt
          createdAt
          updatedAt
        }
      }
    `

GetQuery (DOES NOT WORK)

Using input...

`
            const item = {
                id: directoryId,
            };
`

Using Query
`query GetDirectory($id: ID!) {
      getDirectory(id: $id) {
        id
        directoryName
        _version
        _deleted
        _lastChangedAt
        createdAt
        updatedAt
      }
    }`

Update Mutation (DOES NOT WORK)

Using input....
`
            const item = {
                input: {
                    id: directoryId,
                    directoryName: "New Directory Name"
                }
            };
`

Using mutation....

 `mutation UpdateDirectory(
        $input: UpdateDirectoryInput!
        $condition: ModelDirectoryConditionInput
      )
 {
        updateDirectory(input: $input, condition: $condition) {
          id
          directoryName
          _version
          _deleted
          _lastChangedAt
          createdAt
          updatedAt
        }
      }
    `
Update Mutation
**Screenshots**

<img width="1290" alt="Screenshot 2021-03-05 at 1 54 51 pm" src="https://user-images.githubusercontent.com/1474186/110060676-6497ef80-7dba-11eb-9102-bdb854e6a417.png">

**What is Configured?**

Amplify configuration is not applicable as occurring in the lambda
.

Function created by amplify has Create, Read, Update, Delete access configured when creating function using Amplify CLI.

Checking Role/Policy shown below, but appears correct as other mutations work
`
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "appsync:Create*",
                "appsync:StartSchemaCreation",
                "appsync:GraphQL",
                "appsync:Get*",
                "appsync:List*",
                "appsync:Update*",
                "appsync:Delete*"
            ],
            "Resource": [
                "arn:aws:appsync:<REGION>:<ACCOUNT_ID>:apis/<API_ID>/*"
            ],
            "Effect": "Allow"
        }
    ]
}`

**Additional context**
The CreateMutation seems to work fine and i think it is something wrong with the query. 

Other people seem to have issues like this, but the solutions do not seem to work well.

https://stackoverflow.com/questions/55400909/graphql-axios-variables-injection
https://stackoverflow.com/questions/53168160/graphql-apollo-client-issue-network-error-syntaxerror-unexpected-end-of-js

**Comment by Neuroforge** [comment]
This does not appear to be an AppSync issue. The response was too long. Maybe Axios issue.

**Comment by Neuroforge** [comment]
Ok. Appears response is coming back in chunks.

Solution... 

`
    const data = await new Promise((resolve, reject) => {
        const httpRequest = https.request({ ...req, host: endpoint }, (response) => {
            let data = '';
            response.on('data', (chunk) => {
                data += chunk;
            });
            response.on('end', () => {
                const body = JSON.parse(data);
                console.log(body);
            });
        });
        httpRequest.write(req.body);
        httpRequest.end();
    });
`
