### ISSUE TITLE
Angular Universal auth error every time

### ISSUE THREAD

**Issue by oliverandersencox** [aws-amplify/amplify-js#7955]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.16.0

### Amplify CLI Version

4.44.0

### What operating system are you using?

Mac

### Amplify Categories

auth, api

### Amplify Commands

Not applicable

### Describe the bug

We have created an angular amplify project which works fine in all cases apart from when hosting the angular project as an SSR Universal application. In this case, the project still works to the users, however it consistently gives this error for the first few calls:

GraphQLAPI - ensure credentials error No Cognito Identity pool provided for unauthenticated access

The app still serves the content correctly, however because of this the universal server side rendering doesnt work as well as it should and therefore google's crawler doesnt pick up the pages correctly.

```ts
// Main.ts
import awsconfig from "./aws-exports";
Auth.configure(awsconfig);
API.configure(awsconfig);
```

and I have all the cognito and amplify settings set up correctly to allow user pools and unauthenticated users using IAM - as they all work fine for our web app and Ionic app. 

I can't understand why then, the angular universal project gets this error.

### Expected behavior

It should not give an auth error.

### Reproduction steps

1. Create angular universal project
2. Make any unauthenticated call for some data from the api:

```ts
  public runQuery<T>(query: any, variables: any, mapField: string, iamMode?: boolean, hideToast?: boolean): Observable<T | ErrorType> {
    return from(API.graphql({
      query,
      variables,
      authMode: !iamMode ? GRAPHQL_AUTH_MODE.AMAZON_COGNITO_USER_POOLS : GRAPHQL_AUTH_MODE.AWS_IAM
    }))
      .pipe(
        map((res: GraphQLResult<T>) => res?.data[mapField]),
        catchError(err => {
          console.log('API Service calling the query: ' + mapField);
          console.error(err);
          return of(ErrorType.ERROR);
        }),
        first(),
      )
  }
```

### Log output

```
# Put your logs below this line
Node Express server listening on http://localhost:4000
[WARN] 19:45.186 GraphQLAPI - ensure credentials error No Cognito Identity pool provided for unauthenticated access
Error: No credentials
    at GraphQLAPIClass.<anonymous> (/Users/ollie/Documents/Development/Ping-web-version/dist/server/main.js:1:12792569)
    at step (/Users/ollie/Documents/Development/Ping-web-version/dist/server/main.js:1:12789146)
    at Object.next (/Users/ollie/Documents/Development/Ping-web-version/dist/server/main.js:1:12789262)
    at fulfilled (/Users/ollie/Documents/Development/Ping-web-version/dist/server/main.js:1:12787741)
    at ZoneDelegate.invoke (/Users/ollie/Documents/Development/Ping-web-version/dist/server/main.js:1:11013148)
    at Object.onInvoke (/Users/ollie/Documents/Development/Ping-web-version/dist/server/main.js:1:2500846)
    at ZoneDelegate.invoke (/Users/ollie/Documents/Development/Ping-web-version/dist/server/main.js:1:11013044)
    at Zone.run (/Users/ollie/Documents/Development/Ping-web-version/dist/server/main.js:1:11005562)
    at /Users/ollie/Documents/Development/Ping-web-version/dist/server/main.js:1:11024659
    at ZoneDelegate.invokeTask (/Users/ollie/Documents/Development/Ping-web-version/dist/server/main.js:1:11014080)

```

**Comment by amhinson** [comment]
@oliverandersencox Could you share your `package.json` as well?

Also, we recommend only configuring Amplify with `Amplify.configure(awsconfig)` instead of configuring both `Auth` & `API`. Does changing that affect the behavior you're seeing?

**Comment by oliverandersencox** [comment]
hello, yes I initially had that, however no difference. I moved this function into a service constructor rather than the main.ts and now the auth error is not being logged on the server so I presume it worked.

Is there any reason why it is usually one in the main.ts?

**Comment by sky4git** [comment]
I have the same issue too. my **package.json** is shared in [https://github.com/aws-amplify/amplify-js/issues/7934](url).
Seems like Auth package issue to me, affecting both Analytics and API categories.

**Comment by oliverandersencox** [comment]
@sky4git I initialise my amplify packages like this:

API.configure(config);
PubSub.configure(config);
Storage.configure(config);
Auth.configure(config);

but i now do it in my api service and it doesnt have any issues now

**Comment by sky4git** [comment]
Thing is that, it only happnening recently and i always just had
 Amplify.configure(awsconfig)

So i think its related to Auth module.

**Comment by Nechir-89** [comment]
I do have same issue using reactjs, and tried to set Amplify.configure(awsconfig) but didn't work.

here are my dependencies

  "dependencies": {
    "@aws-amplify/ui-react": "^0.2.34",
    "@ctrl/react-adsense": "^1.3.1",
    "@material-ui/core": "^4.11.1",
    "@material-ui/icons": "^4.9.1",
    "@react-native-community/netinfo": "^5.9.9",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "amazon-cognito-identity-js": "^4.5.5",
    "aws-amplify": "^3.3.14",
    "aws-amplify-react": "^4.2.15",
    "aws-amplify-react-native": "^4.2.9",
    "aws-appsync": "^3.0.4",
    "axios": "^0.21.1",
    "bootstrap": "^4.5.3",
    "glamor": "^2.20.40",
    "graphql-tag": "^2.11.0",
    "internal": "^2.0.27",
    "main": "^1000.0.1",
    "masonry-layout": "^4.2.2",
    "query-string": "^6.13.7",
    "react": "^16.14.0",
    "react-adsense": "^0.1.0",
    "react-custom-scrollbars": "^4.2.1",
    "react-dom": "^16.14.0",
    "react-helmet": "^6.1.0",
    "react-horizontal-scrolling-menu": "^0.7.8",
    "react-player": "^2.7.0",
    "react-rating-stars-component": "^2.2.0",
    "react-router": "^5.2.0",
    "react-router-dom": "^5.0.1",
    "react-scripts": "^3.4.4",
    "react-select": "^3.1.1",
    "react-share": "^4.3.1",
    "react-simple-charts": "0.0.19",
    "redux": "^4.0.5",
    "scroll-lock": "^2.1.4"
  }

**Comment by sky4git** [comment]
Found a solution. check my last comment on #7934

**Comment by Nechir-89** [comment]
Where I can't see

**Comment by sammartinez** [comment]
@oliverandersencox Does @sky4git solution work for you? Please let us know

**Comment by sky4git** [comment]
I suggest remove "@aws-amplify" sub packages from package.json as dependencies. 
For example, "@aws-amplify/ui-react": "^0.2.34"
