### ISSUE TITLE
Angular Tutorial not working

### ISSUE THREAD

**Issue by mattmeye** [aws-amplify/amplify-js#8071]
### Before opening, please confirm:

I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

Not applicable

### Amplify Categories

Not applicable

### Environment information

<details>

```
PS F:\dev\test\amplify-app> npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
npx: installed 1 in 2.316s

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
    Memory: 17.78 GB / 31.95 GB
  Binaries:
    Node: 14.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.114
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.75)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @angular-devkit/build-angular: ~0.1102.8 => 0.1102.8
    @angular/animations: ~11.2.9 => 11.2.9
    @angular/cli: ~11.2.8 => 11.2.8
    @angular/common: ~11.2.9 => 11.2.9
    @angular/compiler: ~11.2.9 => 11.2.9
    @angular/compiler-cli: ~11.2.9 => 11.2.9
    @angular/core: ~11.2.9 => 11.2.9
    @angular/forms: ~11.2.9 => 11.2.9
    @angular/platform-browser: ~11.2.9 => 11.2.9
    @angular/platform-browser-dynamic: ~11.2.9 => 11.2.9
    @angular/router: ~11.2.9 => 11.2.9
    @types/jasmine: ~3.6.0 => 3.6.9
    @types/node: ^12.11.1 => 12.20.7
    codelyzer: ^6.0.0 => 6.0.1
    jasmine-core: ~3.6.0 => 3.6.0
    jasmine-spec-reporter: ~5.0.0 => 5.0.2
    karma: ~6.1.0 => 6.1.2
    karma-chrome-launcher: ~3.1.0 => 3.1.0
    karma-coverage: ~2.0.3 => 2.0.3
    karma-jasmine: ~4.0.0 => 4.0.1
    karma-jasmine-html-reporter: ^1.5.0 => 1.5.4
    protractor: ~7.0.0 => 7.0.0
    rxjs: ~6.6.0 => 6.6.7
    ts-node: ~8.3.0 => 8.3.0
    tslib: ^2.0.0 => 2.2.0
    tslint: ~6.1.0 => 6.1.3
    typescript: ~4.1.5 => 4.1.5
    zone.js: ~0.11.3 => 0.11.4
  npmGlobalPackages:
    @angular/cli: 11.2.7
    @aws-amplify/cli: 4.47.1
    @vue/cli-service-global: 4.5.11
    @vue/cli: 4.5.11
    aws-cdk: 1.90.1
    commitizen: 4.2.1
    lerna: 3.22.1


```

</details>

### Describe the bug

amplify init results in a TypeError: Cannot read property 'projectPath' of undefined

### Expected behavior

no error

### Reproduction steps

npx -p @angular/cli ng new amplify-app
cd amplify-app
# polyfill changed for ng 6+
amplify init # enter first question

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
PS F:\dev\test\amplify-app> amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project amplifyapp
The following configuration will be applied:

Project information
| Name: amplifyapp
| Environment: dev
| Default editor: Visual Studio Code
| App type: javascript
TypeError: Cannot read property 'projectPath' of undefined
    at getAngularConfig (C:\Users\me\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-frontend-javascript\lib\framework-config-mapping.js:57:52)
    at getProjectConfiguration (C:\Users\me\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-frontend-javascript\lib\framework-config-mapping.js:85:14)
    at Object.displayFrontendDefaults (C:\Users\me\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-frontend-javascript\lib\configuration-manager.js:173:32)
    at Object.displayFrontendDefaults (C:\Users\me\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-frontend-javascript\index.js:40:24)
    at displayAndSetDefaults (C:\Users\me\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\init-steps\s0-analyzeProject.js:83:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async analyzeProject (C:\Users\me\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\init-steps\s0-analyzeProject.js:99:9)
    at async Object.run (C:\Users\me\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\commands\init.js:29:13)
    at async Object.executeAmplifyCommand (C:\Users\me\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\index.js:236:9)
    at async executePluginModuleCommand (C:\Users\me\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\execution-manager.js:164:5)
    at async Object.executeCommand (C:\Users\me\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\execution-manager.js:35:9)
    at async Object.run (C:\Users\me\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\index.js:112:9)


```

</details>

**Comment by iartemiev** [comment]
Transferring to the CLI repo
