### ISSUE TITLE
Auth error [Error: Native module not found] on all Auth calls after successful signup and signup verification

### ISSUE THREAD

**Issue by coe720** [aws-amplify/amplify-js#8356]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
    Memory: 186.16 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 90.0.4430.212
    Edge: 91.0.864.37
    Safari: 14.0.3
  npmPackages:
    @babel/core: ^7.12.9 => 7.14.2 
    @babel/runtime: ^7.12.5 => 7.14.0 
    @fortawesome/fontawesome-svg-core: ^1.2.35 => 1.2.35 
    @fortawesome/free-solid-svg-icons: ^5.15.3 => 5.15.3 
    @fortawesome/react-native-fontawesome: ^0.2.6 => 0.2.6 
    @react-native-async-storage/async-storage: ^1.15.4 => 1.15.4 
    @react-native-community/eslint-config: ^2.0.0 => 2.0.0 
    @react-native-community/masked-view: ^0.1.11 => 0.1.11 
    @react-native-community/netinfo: ^6.0.0 => 6.0.0 
    @react-navigation/bottom-tabs: ^5.11.11 => 5.11.11 
    @react-navigation/native: ^5.9.4 => 5.9.4 
    @react-navigation/stack: ^5.14.5 => 5.14.5 
    @types/jest: ^26.0.20 => 26.0.23 
    @types/react-native: ^0.64.0 => 0.64.5 
    @types/react-test-renderer: ^16.9.2 => 16.9.5 
    @typescript-eslint/eslint-plugin: ^4.4.1 => 4.23.0 (3.10.1)
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: ^5.0.2 => 5.0.2 
    aws-amplify: ^4.0.3 => 4.0.3 
    aws-amplify-react-native: ^5.0.1 => 5.0.1 
    babel-jest: ^26.6.3 => 26.6.3 
    eslint: ^7.14.0 => 7.26.0 
    eslint-config-airbnb-typescript: ^12.3.1 => 12.3.1 
    eslint-plugin-import: ^2.22.0 => 2.23.2 
    eslint-plugin-jsx-a11y: ^6.3.1 => 6.4.1 
    eslint-plugin-react: ^7.20.3 => 7.23.2 
    eslint-plugin-react-hooks: ^4.0.8 => 4.2.0 
    hermes-inspector-msggen:  1.0.0 
    jest: ^26.6.3 => 26.6.3 
    metro-react-native-babel-preset: ^0.64.0 => 0.64.0 
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-gesture-handler: ^1.10.3 => 1.10.3 
    react-native-reanimated: ^2.1.0 => 2.1.0 
    react-native-safe-area-context: ^3.2.0 => 3.2.0 
    react-native-screens: ^3.2.0 => 3.2.0 
    react-native-svg: ^12.1.1 => 12.1.1 
    react-test-renderer: 17.0.1 => 17.0.1 
    typescript: ^3.8.3 => 3.9.9 
  npmGlobalPackages:
    npm: 6.14.13
    react-native: 0.64.1

```

</details>

### Describe the bug

Using the Auth class call the Auth.signIn method and successfully sign in. Call the Auth.currentCredentials() method directly after successful sign in.
Sign in successfully retrieves JWT token and produces the following output after printing the JWT:
![image](https://user-images.githubusercontent.com/11147286/120041559-744c5c00-bfd6-11eb-9389-671183521ce2.png)
![image](https://user-images.githubusercontent.com/11147286/120041610-87f7c280-bfd6-11eb-9c20-5f133de2d67b.png)
![image](https://user-images.githubusercontent.com/11147286/120041385-1fa8e100-bfd6-11eb-858d-766f91b41d95.png)
 

### Expected behavior

Sign in occurs and then I am able to see the current credentials using Auth.currentCredntials() as well as access other Amplify classes such as Storage and Analytics.

### Reproduction steps

1. Start a new React-Native project
2. Install everything according to the Amplify React-Native tutorial https://docs.amplify.aws/start/getting-started/setup/q/integration/react-native#create-a-new-react-native-app including running `npx pod-install`
3. Run `amplify add auth` and use the default setup.
4. Run `amplify add storage`
5. Run `amplify push`
6. Use the Auth module to add sign up/sign up verify and sign in a user.
7. Make a call to Auth.currentCredentials or another class requiring auth such as Storage.get()

### Code Snippet

```javascript
// Put your code below this line.
    await Auth.signIn({
        username,
        password,
    });

    const currentCredentials = await Auth.currentCredentials();
    console.log({currentCredentials});

...

    const logoFromStorage = await Storage.get('xxxx-logo.png');
```

### Log output

<details>

```
// Put your logs below this line
 LOG  About to call Cognito Auth Sign in
 LOG  [DEBUG] 50:43.107 AuthClass {"accessToken": {"jwtToken": xxxxxxxxx
...
 LOG  [DEBUG] 50:43.115 Credentials - removing aws-amplify-federatedInfo from storage
 LOG  [DEBUG] 50:43.115 Credentials - removing CognitoIdentityId-us-east-1:56d28dcd-40de-4031-8e99-523a8fb2bab4 from storage
 LOG  [DEBUG] 50:43.117 Credentials - set credentials from session
 LOG  [DEBUG] 50:43.148 Credentials - Failed to load credentials {"_U": 1, "_V": 3, "_W": {"_1": 0, "_U": 0, "_V": 2, "_W": [Error: Native module not found], "_X": null}, "_X": null}
 LOG  [DEBUG] 50:43.150 Credentials - Error loading credentials [Error: Native module not found]
 LOG  [DEBUG] 50:43.151 AuthClass - cannot get cognito credentials [Error: Native module not found]
 LOG  [DEBUG] 50:43.153 Hub - Dispatching to auth with  {"data": {"Session": null......
...
 LOG  [DEBUG] 50:43.156 AuthClass - getting current credentials
 LOG  [DEBUG] 50:43.156 Credentials - getting credentials
 LOG  [DEBUG] 50:43.156 Credentials - picking up credentials
 LOG  [DEBUG] 50:43.156 Credentials - getting new cred promise
 LOG  [DEBUG] 50:43.158 Credentials - checking if credentials exists and not expired
 LOG  [DEBUG] 50:43.158 Credentials - need to get a new credential or refresh the existing one
 LOG  [DEBUG] 50:43.158 Credentials - no credentials for expiration check
 LOG  [DEBUG] 50:43.158 AuthClass - Getting current user credentials
 LOG  [DEBUG] 50:43.159 AuthClass - failed to get or parse item aws-amplify-federatedInfo [SyntaxError: JSON Parse error: Unexpected identifier "undefined"]
 LOG  [DEBUG] 50:43.159 AuthClass - Getting current session
 LOG  [DEBUG] 50:43.160 AuthClass - Getting the session from this user: {
....
 LOG  [DEBUG] 50:43.168 Credentials - set credentials from session
 LOG  [DEBUG] 50:43.170 Credentials - Failed to load credentials {"_U": 1, "_V": 3, "_W": {"_1": 1, "_U": 0, "_V": 2, "_W": [Error: Native module not found], "_X": null}, "_X": null}
 LOG  [DEBUG] 50:43.170 Credentials - Error loading credentials [Error: Native module not found]
 LOG  [DEBUG] 50:43.170 AuthClass - getting session failed [Error: Native module not found]
 LOG  [DEBUG] 50:43.171 Credentials - setting credentials for guest
 LOG  [DEBUG] 50:43.175 Credentials - Failed to load credentials {"_U": 1, "_V": 3, "_W": {"_1": 2, "_U": 0, "_V": 2, "_W": [Error: Native module not found], "_X": null}, "_X": null}
 LOG  [DEBUG] 50:43.175 Credentials - Error loading credentials [Error: Native module not found]
 LOG  {"currentCredentials": [Error: Native module not found]}
```

</details>

### aws-exports.js

```javascript
const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:XXX",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_XXX",
    "aws_user_pools_web_client_id": "XXX",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "XXX",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "XXX",
    "aws_user_files_s3_bucket": "XXX",
    "aws_user_files_s3_bucket_region": "us-east-1"
};
```

### Mobile Device

iPhone 12 Simulator

### Mobile Operating System

iOS 14.5

**Comment by njariwala2019** [comment]
Did you try calling the signIn method without the curly braces?

`await Auth.signIn( username, password );`

**Comment by coe720** [comment]
No the opening param takes in an object of type SignUpParams so that wouldn't work. I also tried just starting up a new React-Native project and it works totally fine there. Setup was exactly the same.

**Comment by coe720** [comment]
Still having this issue so it is not stale. I've tried multiple projects and this still happens

**Comment by chrisbonifacio** [comment]
Hi @coe720 👋 I have not been able to reproduce this issue. I see that you mentioned having created a new RN project and it seemed to be working there but that it was still happening in others. Let me know if you're still in need of assistance.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!

**Comment by gtraghav** [comment]
We have the same issue. We followed https://docs.amplify.aws/lib/auth/getting-started/q/platform/js/#option-2-call-authentication-apis-manually for react native.

**Comment by akihisa-sumi** [comment]
@chrisbonifacio @coe720 
We have the same issue. 
When starting the React Native app normally, this problem occurs, but it is not reproducible in debug mode.
Any help would be great.

**package.json**
```
"dependencies": {
    "@hookform/resolvers": "^2.9.11",
    "@react-native-async-storage/async-storage": "^1.17.11",
    "@react-native-community/netinfo": "^9.3.7",
    "@react-navigation/native": "^6.1.4",
    "@react-navigation/native-stack": "^6.9.10",
    "@types/uuid": "^9.0.1",
    "amazon-cognito-identity-js": "^6.1.2",
    "aws-amplify": "^5.0.15",
    "constate": "^3.3.2",
    "native-base": "^3.4.25",
    "react": "18.2.0",
    "react-hook-form": "^7.43.1",
    "react-native": "0.71.3",
    "react-native-inappbrowser-reborn": "^3.7.0",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "^3.20.0",
    "react-native-svg": "12.1.1",
    "react-query": "^3.39.3",
    "uuid": "^9.0.0",
    "zod": "^3.20.6"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native-community/eslint-config": "^3.2.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^29.4.0",
    "@types/react": "^18.0.28",
    "@types/react-native": "^0.71.3",
    "@types/react-test-renderer": "^18.0.0",
    "@typescript-eslint/eslint-plugin": "^5.57.1",
    "@typescript-eslint/parser": "^5.57.1",
    "babel-jest": "^29.2.1",
    "eslint": "^8.38.0",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-jest": "^27.2.1",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react": "^7.32.2",
    "eslint-plugin-react-native": "^4.0.0",
    "eslint-plugin-unused-imports": "^2.0.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.73.7",
    "prettier": "^2.8.7",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
```

**code snippet**
```
Amplify.configure({
  Auth: {
    identityPoolId: awsExports.aws_cognito_identity_pool_id,
    region: awsExports.aws_cognito_region,
    userPoolId: awsExports.aws_user_pools_id,
    userPoolWebClientId: awsExports.aws_user_pools_web_client_id,
  },
  oauth: {
    ...awsExports.oauth,
    urlOpener,
  },
  Storage: {
    AWSS3: {
      bucket: awsExports.aws_user_files_s3_bucket,
      region: awsExports.aws_user_files_s3_bucket_region,
    },
  },
  API: {
    aws_appsync_graphqlEndpoint: awsExports.aws_appsync_graphqlEndpoint,
    aws_appsync_region: awsExports.aws_appsync_region,
    aws_appsync_authenticationType: awsExports.aws_appsync_authenticationType,
  },
  Analytics: {
    disabled: true,
  },
});

await Auth.signIn({
  username,
  password,
});

const currentCredentials = await Auth.currentCredentials();
console.log({currentCredentials});
const result = await Storage.get(fileName, {
  level: 'private',
});
console.log(result);
```

**console output**
```
LOG  Running "flik" with {"rootTag":11}
LOG  {"currentCredentials": [Error: Native module not found]}
WARN  [WARN] 26:22.503 AWSS3Provider - get signed url error [TypeError: Cannot read property 'byteLength' of undefined]
 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'byteLength' of undefined
TypeError: Cannot read property 'byteLength' of undefined
    at isEmptyData (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.flik&modulesOnly=false&runModule=true:105523:16)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.flik&modulesOnly=false&runModule=true:105214:78)
    at hmac (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.flik&modulesOnly=false&runModule=true:346790:16)
    at ?anon_0_ (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.flik&modulesOnly=false&runModule=true:346761:33)
    at next (native)
    at asyncGeneratorStep (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.flik&modulesOnly=false&runModule=true:1195:26)
    at _next (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.flik&modulesOnly=false&runModule=true:1214:29)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.flik&modulesOnly=false&runModule=true:1219:14)
    at tryCallTwo (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/4b1t586k/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/4b1t586k/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/4b1t586k/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.flik&modulesOnly=false&runModule=true:1211:25)
    at apply (native)
    at getSigningKey (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.flik&modulesOnly=false&runModule=true:346777:24)
    at getSigningKey (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.flik&modulesOnly=false&runModule=true:347069:86)
    at ?anon_0_ (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.flik&modulesOnly=false&runModule=true:346902:155)
    at next (native)
    at asyncGeneratorStep (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.flik&modulesOnly=false&runModule=true:1195:26)
    at _next (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.flik&modulesOnly=false&runModule=true:1214:29)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/4b1t586k/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/4b1t586k/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.flik&modulesOnly=false&runModule=true:26322:26)
    at _callTimer (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.flik&modulesOnly=false&runModule=true:26241:17)
    at _callReactNativeMicrotasksPass (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.flik&modulesOnly=false&runModule=true:26271:17)
    at callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.flik&modulesOnly=false&runModule=true:26434:44)
    at __callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.flik&modulesOnly=false&runModule=true:2591:46)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.flik&modulesOnly=false&runModule=true:2403:45)
    at __guard (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.flik&modulesOnly=false&runModule=true:2575:15)
    at flushedQueue (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.flik&modulesOnly=false&runModule=true:2402:21)
    at callFunctionReturnFlushedQueue (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.flik&modulesOnly=false&runModule=true:2387:33)
```

**Comment by tannerabread** [comment]
Hi @akihisa-sumi can you open up a new issue with these details so we can investigate further

**Comment by akihisa-sumi** [comment]
@tannerabread 

Thank you.
I have opened a new Issue.
https://github.com/aws-amplify/amplify-js/issues/11251
