### ISSUE TITLE
npm install aws-amplify I get this error: chromedriver: No matching version found for chromedriver@91

### ISSUE THREAD

**Issue by felixdlealc** [aws-amplify/amplify-js#8378]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

GraphQL API

### Amplify Categories

api

### Environment information

<details>

```
  System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 234.51 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.15.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 91.0.4472.77
    Firefox: 88.0.1
    Safari: 14.1.1
  npmPackages:
    @types/chai: ^4.2.11 => 4.2.18 
    @types/mocha: ^5.2.4 => 5.2.7 
    @typescript-eslint/eslint-plugin: ^4.18.0 => 4.26.0 
    @typescript-eslint/parser: ^4.18.0 => 4.26.0 
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.13 
    @vue/cli-plugin-e2e-nightwatch: ~4.5.0 => 4.5.13 
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.13 
    @vue/cli-plugin-pwa: ~4.5.0 => 4.5.13 
    @vue/cli-plugin-router: ~4.5.0 => 4.5.13 
    @vue/cli-plugin-typescript: ~4.5.0 => 4.5.13 
    @vue/cli-plugin-unit-mocha: ~4.5.0 => 4.5.13 
    @vue/cli-plugin-vuex: ~4.5.0 => 4.5.13 
    @vue/cli-service: ~4.5.0 => 4.5.13 
    @vue/compiler-sfc: ^3.0.0 => 3.0.11 
    @vue/eslint-config-typescript: ^7.0.0 => 7.0.0 
    @vue/test-utils: ^2.0.0-0 => 2.0.0-rc.6 
    chai: ^4.1.2 => 4.3.4 
    chromedriver: 91 => 90.0.1 
    core-js: ^3.6.5 => 3.13.1 (2.6.12)
    eslint: ^6.7.2 => 6.8.0 
    eslint-plugin-vue: ^7.0.0 => 7.10.0 
    geckodriver: ^1.20.0 => 1.22.3 
    register-service-worker: ^1.7.1 => 1.7.2 
    sass: ^1.26.5 => 1.34.0 
    sass-loader: ^8.0.2 => 8.0.2 
    typescript: ~4.1.5 => 4.1.5 
    vue: ^3.0.0 => 3.0.11 
    vue-class-component: ^8.0.0-0 => 8.0.0-rc.1 
    vue-router: ^4.0.0-0 => 4.0.8 
    vuex: ^4.0.0-0 => 4.0.1 
  npmGlobalPackages:
    @aws-amplify/cli: 4.52.0
    @vue/cli: 4.5.13
    npm: 7.15.1
    yarn: 1.22.10
```

</details>

### Describe the bug

When I try to install 'aws-amplify' in a new vue project, I get this error:
```
Name-MacBook-Pro:new-project name$ npm install aws-amplify
npm ERR! code ETARGET
npm ERR! notarget No matching version found for chromedriver@91.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/name/.npm/_logs/2021-06-02T18_18_00_078Z-debug.log
```
I just created the project using: 'vue create new-project'

### Expected behavior

I hope 'aws-amplify' can be installed correctly.

### Reproduction steps

1.- npm install aws-amplify

### Code Snippet

```
Name-MacBook-Pro:new-project name$ npm install aws-amplify
npm ERR! code ETARGET
npm ERR! notarget No matching version found for chromedriver@91.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/name/.npm/_logs/2021-06-02T18_18_00_078Z-debug.log
```

### Log output

<details>

```
0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install',
0 verbose cli   'aws-amplify'
0 verbose cli ]
1 info using npm@7.15.1
2 info using node@v14.17.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
... ...
1580 timing idealTree:node_modules/stacktrace-parser/node_modules/type-fest Completed in 0ms
1581 timing idealTree:node_modules/temp/node_modules/rimraf Completed in 0ms
1582 timing idealTree:node_modules/uglify-es/node_modules/commander Completed in 0ms
1583 timing idealTree:node_modules/zen-push/node_modules/zen-observable Completed in 0ms
1584 timing idealTree:node_modules/@aws-sdk/client-cognito-identity/node_modules/@aws-crypto/sha256-js/node_modules/tslib Completed in 0ms
1585 timing idealTree:node_modules/@aws-sdk/client-comprehend/node_modules/@aws-crypto/sha256-js/node_modules/tslib Completed in 0ms
1586 timing idealTree:node_modules/@aws-sdk/client-firehose/node_modules/@aws-crypto/sha256-js/node_modules/tslib Completed in 1ms
1587 timing idealTree:node_modules/@aws-sdk/client-kinesis/node_modules/@aws-crypto/sha256-js/node_modules/tslib Completed in 0ms
1588 timing idealTree:node_modules/@aws-sdk/client-lex-runtime-service/node_modules/@aws-crypto/sha256-js/node_modules/tslib Completed in 0ms
1589 timing idealTree:node_modules/@aws-sdk/client-personalize-events/node_modules/@aws-crypto/sha256-js/node_modules/tslib Completed in 0ms
1590 timing idealTree:node_modules/@aws-sdk/client-pinpoint/node_modules/@aws-crypto/sha256-js/node_modules/tslib Completed in 0ms
1591 timing idealTree:node_modules/@aws-sdk/client-polly/node_modules/@aws-crypto/sha256-js/node_modules/tslib Completed in 0ms
1592 timing idealTree:node_modules/@aws-sdk/client-rekognition/node_modules/@aws-crypto/sha256-js/node_modules/tslib Completed in 0ms
1593 timing idealTree:node_modules/@aws-sdk/client-s3/node_modules/@aws-crypto/sha256-js/node_modules/tslib Completed in 0ms
1594 timing idealTree:node_modules/@aws-sdk/client-textract/node_modules/@aws-crypto/sha256-js/node_modules/tslib Completed in 0ms
1595 timing idealTree:node_modules/@aws-sdk/client-translate/node_modules/@aws-crypto/sha256-js/node_modules/tslib Completed in 0ms
1596 timing idealTree:buildDeps Completed in 19975ms
1597 timing idealTree:fixDepFlags Completed in 15ms
1598 timing idealTree Completed in 22073ms
1599 timing command:install Completed in 22083ms
1600 verbose type range
1601 verbose stack chromedriver: No matching version found for chromedriver@91.
1601 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
1601 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
1601 verbose stack     at async Arborist.[nodeFromEdge] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:934:19)
1601 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:880:11)
1601 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:218:7)
1601 verbose stack     at async Promise.all (index 1)
1601 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:136:5)
1601 verbose stack     at async Install.install (/usr/local/lib/node_modules/npm/lib/install.js:150:5)
1602 verbose cwd /Users/name/PROJECTS/new-project
1603 verbose Darwin 20.5.0
1604 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "aws-amplify"
1605 verbose node v14.17.0
1606 verbose npm  v7.15.1
1607 error code ETARGET
1608 error notarget No matching version found for chromedriver@91.
1609 error notarget In most cases you or one of your dependencies are requesting
1609 error notarget a package version that doesn't exist.
1610 verbose exit 1
```

</details>

**Comment by sammartinez** [comment]
Hey @felixdlealc, 

This issue seems to be unrelated to `aws-amplify` and moreso for `chromedriver`. In looking at their [repository](https://github.com/giggio/node-chromedriver/) I am seeing an [issue](https://github.com/giggio/node-chromedriver/issues/315) that looks to be related to what you are seeing with the matching version not being found. Please confirm with removing `chromedriver` from your dependencies in `package.json` if you still have issues with installing `aws-amplify`. Thanks ahead of time

**Comment by felixdlealc** [comment]
Hello @sammartinez,

Thanks for answering.

I had not seen "chromedriver" in my package.json. My bad!

I'm sorry about this, I'm going to keep looking for a solution, anything, I'll be back.!
Thank you.

I'm going to close.

**Comment by felixdlealc** [comment]
Yes, ChromeDriver was updated to version 91 an hour ago. [Npm Chromedriver](https://www.npmjs.com/package/chromedriver)

I updated my code and it worked.

**Comment by sammartinez** [comment]
> Hello @sammartinez,
> 
> Thanks for answering.
> 
> I had not seen "chromedriver" in my package.json. My bad!
> 
> I'm sorry about this, I'm going to keep looking for a solution, anything, I'll be back.!
> Thank you.
> 
> I'm going to close.

No worries to apologize at all! I just wanted to double check since I did notice that was the callout from your logs. Glad you got it figured out! Happy open sourcing
