### ISSUE TITLE
Can create a new env

### ISSUE THREAD

**Issue by PaulCailly** [aws-amplify/amplify-js#8495]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

Authentication, Analytics, REST API, GraphQL API, Storage

### Amplify Categories

auth, storage, function, api, analytics

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Linux 4.19 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (5) x64 Intel(R) Core(TM) i7-9700KF CPU @ 3.60GHz
    Memory: 1.84 GB / 3.84 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.18.0 - /usr/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
  npmPackages:
    @babel/core: 7.12.10 => 7.12.10 (7.14.5)
    @testing-library/dom: 7.28.1 => 7.28.1 (7.31.2)
    @testing-library/jest-dom: 5.11.6 => 5.11.6 
    @testing-library/react: 11.2.1 => 11.2.1 
    @testing-library/user-event: 12.3.0 => 12.3.0 
    @types/node: 14.14.20 => 14.14.20 (15.12.2, 14.17.3)
    @types/react: 17.0.0 => 17.0.0 (17.0.11)
    babel-jest: 26.6.3 => 26.6.3 
    babel-loader: 8.2.2 => 8.2.2 
    cz-conventional-changelog: 3.3.0 => 3.3.0 (3.2.0)
    jest: 26.6.3 => 26.6.3 
    jest-sonar-reporter: 2.0.0 => 2.0.0 
    typescript: 4.0.5 => 4.0.5 (3.9.9)
  npmGlobalPackages:
    @aws-amplify/cli: 4.50.2
    bit-bin: 14.8.8
    create-react-app: 4.0.3
    depcheck: 1.2.0
    jest: 26.6.3
    lerna: 3.22.1
    locize-cli: 7.6.6
    now: 20.1.1
    npm: 6.14.6
    prerendercloud-server: 0.5.0
    roast: 2.3.17
    serverless: 2.10.0
    source-map-explorer: 2.5.0
    vercel: 20.1.1

```

</details>

### Describe the bug

I tried to create a new env with `amplify env add`, choose "prod" as new env's name and Amplify Admin UI for authentication method. It opened Amplify Admin UI in my browser, I validated my choice but once back on my terminal I had an error telling me that I don't have the right permissions.

I retried to create a new env with the same name "prod" but this time I choose AWS profile as authentication method and this is the output: 

```
➜  students git:(master) amplify env remove prod
No environment found with the corresponding name provided
➜  students git:(master) amplify env add        
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? No
? Enter a name for the environment prod
Using default provider  awscloudformation
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use default
⠇ Initializing project in the cloud...An error occurred when creating the CloudFormation stack
✖ Root stack creation failed
AlreadyExistsException: Stack [amplify-students-prod-211214] already exists
    at Request.extractError (/home/paul/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/home/paul/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/paul/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/paul/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/home/paul/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/paul/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/paul/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/paul/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/paul/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/home/paul/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/home/paul/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/paul/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/home/paul/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/paul/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/paul/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/paul/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/paul/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/home/paul/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/home/paul/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/home/paul/.nvm/versions/node/v12.18.3/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:313:13)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'AlreadyExistsException',
  time: 2021-06-23T20:33:40.810Z,
  requestId: '346e616e-5fe0-4b5c-88d7-e3ce1ad8f5b1',
  statusCode: 400,
  retryable: false,
  retryDelay: 38.3637349356734
}
➜  students git:(master) 
```

### Expected behavior

Amplify should have clean the previous attempt

### Reproduction steps

amplify env add
=> create a new env with Amplify Admin UI authentication method

*FAILS*

amplify env add again
=> create a new env with another authentication method

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:3928d3f5-abb9-4cd7-96d5-bbf1e11e601b",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_toIr1ygEg",
    "aws_user_pools_web_client_id": "233j2993ca074vpr1cod7d0jii",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://fbtuf6bm4bcrllp2ix5sdfmyjq.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-mgsxxjw53jfyzjhhactyn3fomi",
    "aws_cloud_logic_custom": [
        {
            "name": "rest",
            "endpoint": "https://dxf5rgz8x3.execute-api.ap-southeast-1.amazonaws.com/dev",
            "region": "ap-southeast-1"
        }
    ],
    "aws_user_files_s3_bucket": "applyfuture-students-content162403-dev",
    "aws_user_files_s3_bucket_region": "ap-southeast-1",
    "aws_mobile_analytics_app_id": "1b1231e1f78d402cbc2c5b7de6fc577c",
    "aws_mobile_analytics_app_region": "us-west-2"
};

export default awsmobile;

**Comment by elorzafe** [comment]
@PaulCailly thanks for creating this issue, I will transfer this to amplify-cli repo where they can answer this better than me.
