### ISSUE TITLE
Using a related field as a query predicate in Datastore

### ISSUE THREAD

**Issue by niallotuathail** [aws-amplify/amplify-js#8511]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

DataStore

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 11.1
    CPU: (8) arm64 Apple M1
    Memory: 110.22 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.11.2 - /opt/homebrew/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Browsers:
    Safari: 14.0.2
  npmPackages:
    @babel/core: ^7.9.0 => 7.14.3 (7.9.0)
    @expo-google-fonts/nunito: ^0.1.0 => 0.1.0 
    @react-native-async-storage/async-storage: ^1.15.5 => 1.15.5 
    @react-native-community/eslint-config:  1.1.0 
    @react-native-community/eslint-plugin:  1.0.0 
    @react-native-community/masked-view: 0.1.10 => 0.1.10 
    @react-native-community/netinfo: ^6.0.0 => 6.0.0 
    @react-navigation/bottom-tabs: ^5.11.11 => 5.11.11 
    @react-navigation/drawer: ^5.12.5 => 5.12.5 
    @react-navigation/native: ^5.9.4 => 5.9.4 
    @react-navigation/stack: ^5.14.5 => 5.14.5 
    HelloWorld:  0.0.1 
    amplify-cli: ^1.0.0 => 1.0.0 
    aws-amplify: ^4.0.3 => 4.0.3 
    aws-amplify-react-native: ^5.0.1 => 5.0.1 
    babel-plugin-inline-view-configs:  0.0.5 
    color-convert: ^2.0.1 => 2.0.1 (1.9.3)
    date-fns: ^2.22.1 => 2.22.1 
    expo: ~41.0.1 => 41.0.1 
    expo-app-loading: ^1.0.3 => 1.0.3 
    expo-av: ^9.1.2 => 9.1.2 
    expo-font: ~9.1.0 => 9.1.0 
    expo-status-bar: ~1.0.4 => 1.0.4 
    hermes-inspector-msggen:  1.0.0 
    react: 16.13.1 => 16.13.1 
    react-animated:  0.1.0 
    react-dom: 16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
    react-native-chart-kit: ^6.11.0 => 6.11.0 
    react-native-codegen:  0.0.2 
    react-native-elements: ^3.4.1 => 3.4.1 
    react-native-gesture-handler: ~1.10.2 => 1.10.3 
    react-native-gifted-chat: ^0.16.3 => 0.16.3 
    react-native-reanimated: ~2.1.0 => 2.1.0 
    react-native-safe-area-context: 3.2.0 => 3.2.0 
    react-native-screens: ~3.0.0 => 3.0.0 
    react-native-svg: ^12.1.1 => 12.1.1 
    react-native-video: ^5.1.1 => 5.1.1 
    react-native-web: ~0.13.12 => 0.13.18 
  npmGlobalPackages:
    @aws-amplify/cli: 5.0.2
    expo-cli: 4.4.7
    npm: 7.11.2
    patch-package: 6.4.7
    react-native-cli: 2.0.1

```

</details>

### Describe the bug

I am trying to use a relationship as a Predicate for a DataStore query where I want to limit and sort the data returned. I am able to filter after the query using .filter() but if I try to include c=> c.relationship.id("eq", "relationship-id") as a Predicate in the query, it's not working.

If I use filter after the query I don't think it will give me the subset of data I need to limit.

### Expected behavior

I expected to be able to use the id of related object that is available in the query as a Predicate.

### Reproduction steps

I tried to use a related object id as a Predicate for a query.

![image](https://user-images.githubusercontent.com/5473801/123796653-4318c180-d8dd-11eb-9fd7-b2f8ba227b11.png)
![image](https://user-images.githubusercontent.com/5473801/123796727-5330a100-d8dd-11eb-9ba5-c338aadf97a7.png)

### Code Snippet

```javascript
// Put your code below this line.

```
    async function fetchCoachScreenData() {
        
//This code commented out works as described in docs but doesn't allow me to limit the data returned after the filter
// const MessageData = (await DataStore.query(CoachMessag, Predicates.ALL, {
        //     sort: s => s.date(SortDirection.DESCENDING),
        //     page: 0,
        //     limit: 20
        //   })).filter(c => c.Client.id === clientID);
        //   console.log('Message data', MessageData);

        //   TODO: Need to get the predicate to work with a nested object.
          const MessageData = (await DataStore.query(
                CoachMessag, 
                c => c.Coach.id("eq", clientID), 
                {
                sort: s => s.date(SortDirection.DESCENDING),
                page: 0,
                limit: 20
                }
            ));
        transformMessages(MessageData);
    }
    

### Log output

<details>

```
// Put your logs below this line

[Unhandled promise rejection: TypeError: c.Coach.id is not a function. (In 'c.Coach.id("eq", clientID)', 'c.Coach.id' is undefined)]
at http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:243493:21 in <unknown>
at node_modules/@aws-amplify/datastore/lib-esm/datastore/datastore.js:592:33 in __generator$argument_1
at http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:182691:26 in step
at node_modules/@aws-sdk/client-cognito-identity/node_modules/@aws-crypto/sha256-js/node_modules/tslib/tslib.js:122:34 in <anonymous>
at node_modules/@aws-sdk/client-cognito-identity/node_modules/@aws-crypto/sha256-js/node_modules/tslib/tslib.js:112:44 in fulfilled
at [native code]:null in flushedQueue
at [native code]:null in callFunctionReturnFlushedQueue
```

</details>

**Comment by iartemiev** [comment]
Hey @niallotuathail, this is currently the expected behavior with DataStore. You can only use a predicate on a top-level field. Marking this as a feature request and we'll explore solutions to this in the future.

**Comment by niallotuathail** [comment]
Thanks Ivan, are there better patterns/workarounds to limit the amount of data returned in the query using a relationship as a filter?

**Comment by svidgen** [comment]
Is the table your querying a M:M join table? The `filter` looks like it's right, if that's what you're doing.

But, do you have a more complete model and block of code you can share that demonstrates unexpected results?
