### ISSUE TITLE
Amplify Build failing on the framework: The previously configured Web app client cannot be found

### ISSUE THREAD

**Issue by ayotise** [aws-amplify/amplify-js#8568]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz
    Memory: 109.07 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.7.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 7.19.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 91.0.4472.114
    Safari: 14.1.1
  npmPackages:
    @material-ui/core: ^4.11.4 => 4.12.0 
    @material-ui/icons: ^4.11.2 => 4.11.2 
    @material-ui/lab: ^4.0.0-alpha.58 => 4.0.0-alpha.59 
    @testing-library/jest-dom: ^5.11.10 => 5.14.1 
    @testing-library/react: ^11.2.6 => 11.2.7 
    @testing-library/user-event: ^12.8.3 => 12.8.3 
    antd: ^4.15.1 => 4.16.6 
    apexcharts: ^3.26.1 => 3.27.1 
    autosuggest-highlight: ^3.1.1 => 3.1.1 
    aws-amplify: ^3.3.26 => 3.4.3 
    aws-amplify-react: ^4.2.30 => 4.2.35 
    axios: ^0.21.1 => 0.21.1 
    bootstrap: ^4.6.0 => 4.6.0 
    dotenv: ^8.2.0 => 8.2.0 
    history: ^5.0.0 => 5.0.0 (4.10.1)
    lodash: ^4.17.21 => 4.17.21 
    moment: ^2.29.1 => 2.29.1 
    react: ^17.0.2 => 17.0.2 (16.14.0)
    react-apexcharts: ^1.3.9 => 1.3.9 
    react-bootstrap: ^1.5.2 => 1.6.1 
    react-bootstrap/AbstractNav:  undefined ()
    react-bootstrap/AbstractNavItem:  undefined ()
    react-bootstrap/Accordion:  undefined ()
    react-bootstrap/AccordionCollapse:  undefined ()
    react-bootstrap/AccordionContext:  undefined ()
    react-bootstrap/AccordionToggle:  undefined ()
    react-bootstrap/Alert:  undefined ()
    react-bootstrap/Badge:  undefined ()
    react-bootstrap/BootstrapModalManager:  undefined ()
    react-bootstrap/Breadcrumb:  undefined ()
    react-bootstrap/BreadcrumbItem:  undefined ()
    react-bootstrap/Button:  undefined ()
    react-bootstrap/ButtonGroup:  undefined ()
    react-bootstrap/ButtonToolbar:  undefined ()
    react-bootstrap/Card:  undefined ()
    react-bootstrap/CardColumns:  undefined ()
    react-bootstrap/CardContext:  undefined ()
    react-bootstrap/CardDeck:  undefined ()
    react-bootstrap/CardGroup:  undefined ()
    react-bootstrap/CardImg:  undefined ()
    react-bootstrap/Carousel:  undefined ()
    react-bootstrap/CarouselCaption:  undefined ()
    react-bootstrap/CarouselItem:  undefined ()
    react-bootstrap/CloseButton:  undefined ()
    react-bootstrap/Col:  undefined ()
    react-bootstrap/Collapse:  undefined ()
    react-bootstrap/Container:  undefined ()
    react-bootstrap/Dropdown:  undefined ()
    react-bootstrap/DropdownButton:  undefined ()
    react-bootstrap/DropdownItem:  undefined ()
    react-bootstrap/DropdownMenu:  undefined ()
    react-bootstrap/DropdownToggle:  undefined ()
    react-bootstrap/ElementChildren:  undefined ()
    react-bootstrap/Fade:  undefined ()
    react-bootstrap/Feedback:  undefined ()
    react-bootstrap/Figure:  undefined ()
    react-bootstrap/FigureCaption:  undefined ()
    react-bootstrap/FigureImage:  undefined ()
    react-bootstrap/Form:  undefined ()
    react-bootstrap/FormCheck:  undefined ()
    react-bootstrap/FormCheckInput:  undefined ()
    react-bootstrap/FormCheckLabel:  undefined ()
    react-bootstrap/FormContext:  undefined ()
    react-bootstrap/FormControl:  undefined ()
    react-bootstrap/FormFile:  undefined ()
    react-bootstrap/FormFileInput:  undefined ()
    react-bootstrap/FormFileLabel:  undefined ()
    react-bootstrap/FormGroup:  undefined ()
    react-bootstrap/FormLabel:  undefined ()
    react-bootstrap/FormText:  undefined ()
    react-bootstrap/Image:  undefined ()
    react-bootstrap/InputGroup:  undefined ()
    react-bootstrap/Jumbotron:  undefined ()
    react-bootstrap/ListGroup:  undefined ()
    react-bootstrap/ListGroupItem:  undefined ()
    react-bootstrap/Media:  undefined ()
    react-bootstrap/Modal:  undefined ()
    react-bootstrap/ModalBody:  undefined ()
    react-bootstrap/ModalContext:  undefined ()
    react-bootstrap/ModalDialog:  undefined ()
    react-bootstrap/ModalFooter:  undefined ()
    react-bootstrap/ModalHeader:  undefined ()
    react-bootstrap/ModalTitle:  undefined ()
    react-bootstrap/Nav:  undefined ()
    react-bootstrap/NavContext:  undefined ()
    react-bootstrap/NavDropdown:  undefined ()
    react-bootstrap/NavItem:  undefined ()
    react-bootstrap/NavLink:  undefined ()
    react-bootstrap/Navbar:  undefined ()
    react-bootstrap/NavbarBrand:  undefined ()
    react-bootstrap/NavbarCollapse:  undefined ()
    react-bootstrap/NavbarContext:  undefined ()
    react-bootstrap/NavbarToggle:  undefined ()
    react-bootstrap/Overlay:  undefined ()
    react-bootstrap/OverlayTrigger:  undefined ()
    react-bootstrap/PageItem:  undefined ()
    react-bootstrap/Pagination:  undefined ()
    react-bootstrap/Popover:  undefined ()
    react-bootstrap/PopoverContent:  undefined ()
    react-bootstrap/PopoverTitle:  undefined ()
    react-bootstrap/ProgressBar:  undefined ()
    react-bootstrap/ResponsiveEmbed:  undefined ()
    react-bootstrap/Row:  undefined ()
    react-bootstrap/SafeAnchor:  undefined ()
    react-bootstrap/SelectableContext:  undefined ()
    react-bootstrap/Spinner:  undefined ()
    react-bootstrap/SplitButton:  undefined ()
    react-bootstrap/Switch:  undefined ()
    react-bootstrap/Tab:  undefined ()
    react-bootstrap/TabContainer:  undefined ()
    react-bootstrap/TabContent:  undefined ()
    react-bootstrap/TabContext:  undefined ()
    react-bootstrap/TabPane:  undefined ()
    react-bootstrap/Table:  undefined ()
    react-bootstrap/Tabs:  undefined ()
    react-bootstrap/ThemeProvider:  undefined ()
    react-bootstrap/Toast:  undefined ()
    react-bootstrap/ToastBody:  undefined ()
    react-bootstrap/ToastContext:  undefined ()
    react-bootstrap/ToastHeader:  undefined ()
    react-bootstrap/ToggleButton:  undefined ()
    react-bootstrap/ToggleButtonGroup:  undefined ()
    react-bootstrap/Tooltip:  undefined ()
    react-bootstrap/createChainedFunction:  undefined ()
    react-bootstrap/createWithBsPrefix:  undefined ()
    react-bootstrap/divWithClassName:  undefined ()
    react-bootstrap/helpers:  undefined ()
    react-bootstrap/transitionEndListener:  undefined ()
    react-bootstrap/triggerBrowserReflow:  undefined ()
    react-bootstrap/types:  undefined ()
    react-bootstrap/usePopperMarginModifiers:  undefined ()
    react-bootstrap/useWrappedRefWithWarning:  undefined ()
    react-custom-scrollbars: ^4.2.1 => 4.2.1 
    react-data-table-component: ^6.11.7 => 6.11.7 
    react-data-table-component-extensions: ^1.5.2 => 1.5.2 
    react-dom: ^17.0.2 => 17.0.2 (16.14.0)
    react-icons: ^4.2.0 => 4.2.0 
    react-number-format: ^4.5.5 => 4.6.4 
    react-redux: ^7.2.3 => 7.2.4 
    react-resize-detector: ^6.6.5 => 6.7.4 
    react-router-dom: ^5.2.0 => 5.2.0 
    react-scripts: 4.0.3 => 4.0.3 
    react-searchable-dropdown: ^2.0.3 => 2.0.3 
    react-table: ^7.7.0 => 7.7.0 
    react-test-renderer: ^17.0.2 => 17.0.2 
    redux: ^4.0.5 => 4.1.0 
    redux-thunk: ^2.3.0 => 2.3.0 
    styled-components: ^5.3.0 => 5.3.0 
    styled-components/macro:  undefined ()
    styled-components/native:  undefined ()
    styled-components/primitives:  undefined ()
    web-vitals: ^1.1.1 => 1.1.2 
  npmGlobalPackages:
    @aws-amplify/cli: 4.34.0
    amplify-cli: 1.0.0
    expo-cli: 3.23.1
    npm: 7.19.1
    react-native-cli: 2.0.1
    serve: 11.3.2
    serverless: 2.15.0
    sharp-cli: 1.14.1

```

</details>

### Describe the bug

We currently have a development environment setup with amplify (using an existing userpool and storage). Everything works fine in that environment, however, when we created another environment (ran `amplify env add stagingz`), we imported an existing auth like we did earlier (`amplify import auth`). Everything seems fine (works perfectly when running the react app locally) but it build fails on the pipeline with the following error:

```
                                # Starting phase: build
2021-07-10T18:44:53.155Z [INFO]: [0mAmplify AppID found: my-app-id. Amplify App name is: my-app-name [0m
2021-07-10T18:44:53.274Z [INFO]: [0mBackend environment stagingz found in Amplify Console app: etnowe-merchants-web[0m
2021-07-10T18:44:54.036Z [WARNING]: - Fetching updates to backend environment: stagingz from the cloud.
2021-07-10T18:44:54.224Z [WARNING]: ✔ Successfully pulled backend environment stagingz from the cloud.
2021-07-10T18:44:54.540Z [WARNING]: ✖ There was an error initializing your environment.
2021-07-10T18:44:54.544Z [INFO]: [31mFailed to pull the backend.[39m
2021-07-10T18:44:54.545Z [INFO]: [31mThe previously configured Web app client cannot be found.[39m
2021-07-10T18:44:54.555Z [INFO]: [0mError: The previously configured Web app client cannot be found.[0m
                                 [0m    at headlessImport (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:1173:11)[0m
                                 [0m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[0m
                                 [0m    at importedAuthEnvInit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:903:12)[0m
                                 [0m    at updateConfigOnEnvInit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/index.js:50:72)[0m
                                 [0m    at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/index.js:300:22[0m
2021-07-10T18:44:54.572Z [ERROR]: !!! Build failed
2021-07-10T18:44:54.572Z [ERROR]: !!! Non-Zero Exit Code detected
2021-07-10T18:44:54.572Z [INFO]: # Starting environment caching...
2021-07-10T18:44:54.573Z [INFO]: # Environment caching completed


```

### Expected behavior

Build should complete successfully like it did for the development environment

### Reproduction steps

1.) amplify env add stagingz

followed the prompts and chose the import option

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_xxxxxx",
    "aws_user_pools_web_client_id": "xxxxxxxx",
    "oauth": {
        "domain": "xxxxxx.auth.us-east-2.amazoncognito.com",
        "scope": [
            "aws.cognito.signin.user.admin",
            "email",
            "openid",
            "phone",
            "profile"
        ],
        "redirectSignIn": "xxx",
        "redirectSignOut": "xxx",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "xxxxxx",
    "aws_user_files_s3_bucket_region": "us-east-2"
};

export default awsmobile;

**Comment by chrisbonifacio** [comment]
Hey @ayotise thanks for raising this. This sounds more like a cli issue so I will transfer this to that repo.
