### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by ninsau** [aws-amplify/amplify-js#8596]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

DataStore

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

error - ReferenceError: self is not defined
    at Object.../../node_modules/isomorphic-unfetch/browser.js (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:211674:18)
    at __webpack_require__ (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:30:30)
    at Module.../amazon-cognito-identity-js/es/Client.js (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:230577:76)
    at __webpack_require__ (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:30:30)
    at Module.../amazon-cognito-identity-js/es/CognitoUserPool.js (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:233465:65)
    at __webpack_require__ (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:30:30)
    at Module.../amazon-cognito-identity-js/es/index.js (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:234183:74)
    at __webpack_require__ (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:30:30)
    at Module.../auth/lib-esm/Auth.js (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:243885:84)
    at __webpack_require__ (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:30:30)
    at Module.../auth/lib-esm/index.js (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:247621:63)
    at __webpack_require__ (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:30:30)
    at Module../lib-esm/index.js (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:291523:75)
    at __webpack_require__ (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:30:30)
    at /Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:94:18
    at /Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:97:10
ReferenceError: self is not defined
    at Object.../../node_modules/isomorphic-unfetch/browser.js (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:211674:18)
    at __webpack_require__ (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:30:30)
    at Module.../amazon-cognito-identity-js/es/Client.js (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:230577:76)
    at __webpack_require__ (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:30:30)
    at Module.../amazon-cognito-identity-js/es/CognitoUserPool.js (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:233465:65)
    at __webpack_require__ (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:30:30)
    at Module.../amazon-cognito-identity-js/es/index.js (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:234183:74)
    at __webpack_require__ (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:30:30)
    at Module.../auth/lib-esm/Auth.js (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:243885:84)
    at __webpack_require__ (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:30:30)
    at Module.../auth/lib-esm/index.js (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:247621:63)
    at __webpack_require__ (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:30:30)
    at Module../lib-esm/index.js (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:291523:75)
    at __webpack_require__ (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:30:30)
    at /Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:94:18
    at /Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:97:10

### Expected behavior

wait  - compiling...
event - compiled successfully

### Reproduction steps

npm i aws-amplify

//_app.js

import config from "../media/aws-exports";

Amplify.configure({
  ...config,
  ssr: true,
});

### Code Snippet

```javascript
// Put your code below this line.
import { Amplify, API, Auth, withSSRContext } from "aws-amplify";
import config from "../media/aws-exports";

Amplify.configure({
  ...config,
  ssr: true,
});

```

### Log output

<details>

```
// Put your logs below this line

error - ReferenceError: self is not defined
    at Object.../../node_modules/isomorphic-unfetch/browser.js (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:211674:18)
    at __webpack_require__ (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:30:30)
    at Module.../amazon-cognito-identity-js/es/Client.js (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:230577:76)
    at __webpack_require__ (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:30:30)
    at Module.../amazon-cognito-identity-js/es/CognitoUserPool.js (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:233465:65)
    at __webpack_require__ (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:30:30)
    at Module.../amazon-cognito-identity-js/es/index.js (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:234183:74)
    at __webpack_require__ (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:30:30)
    at Module.../auth/lib-esm/Auth.js (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:243885:84)
    at __webpack_require__ (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:30:30)
    at Module.../auth/lib-esm/index.js (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:247621:63)
    at __webpack_require__ (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:30:30)
    at Module../lib-esm/index.js (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:291523:75)
    at __webpack_require__ (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:30:30)
    at /Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:94:18
    at /Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:97:10
ReferenceError: self is not defined
    at Object.../../node_modules/isomorphic-unfetch/browser.js (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:211674:18)
    at __webpack_require__ (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:30:30)
    at Module.../amazon-cognito-identity-js/es/Client.js (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:230577:76)
    at __webpack_require__ (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:30:30)
    at Module.../amazon-cognito-identity-js/es/CognitoUserPool.js (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:233465:65)
    at __webpack_require__ (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:30:30)
    at Module.../amazon-cognito-identity-js/es/index.js (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:234183:74)
    at __webpack_require__ (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:30:30)
    at Module.../auth/lib-esm/Auth.js (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:243885:84)
    at __webpack_require__ (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:30:30)
    at Module.../auth/lib-esm/index.js (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:247621:63)
    at __webpack_require__ (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:30:30)
    at Module../lib-esm/index.js (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:291523:75)
    at __webpack_require__ (/Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:30:30)
    at /Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:94:18
    at /Users/mac/codespace/flowerghana/node_modules/aws-amplify/dist/aws-amplify.js:97:10
```

</details>

**Comment by chrisbonifacio** [comment]
Hey @ninsau 👋 thanks for raising this issue. Are you using a custom webpack config in your project?

**Comment by ninsau** [comment]
> Hey @ninsau 👋 thanks for raising this issue. Are you using a custom webpack config in your project?

Yes, I am. For styled-components in my project. Is that what is causing the error?

**Comment by ninsau** [comment]
SOLVED.


Rewrote my custom _document.js file

```
import Document from 'next/document';
import { ServerStyleSheet } from 'styled-components';

export default class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const sheet = new ServerStyleSheet();
    const originalRenderPage = ctx.renderPage;

    try {
      ctx.renderPage = () =>
        originalRenderPage({
          enhanceApp: (App) => (props) =>
            sheet.collectStyles(<App {...props} />),
        });

      const initialProps = await Document.getInitialProps(ctx);
      return {
        ...initialProps,
        styles: (
          <>
            {initialProps.styles}
            {sheet.getStyleElement()}
          </>
        ),
      };
    } finally {
      sheet.seal();
    }
  }
}
```
