### ISSUE TITLE
Datastore.clear() doesn't clear local data if it hasn't started already

### ISSUE THREAD

**Issue by gorbinphilip1** [aws-amplify/amplify-js#8658]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

DataStore

### Amplify Categories

auth, storage, function, api, analytics

### Environment information

<details>

```
# Put output below this line


  System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 1.86 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Browsers:
    Chrome: 92.0.4515.107
    Firefox: 79.0
    Safari: 13.1.2
  npmPackages:
    @aws-amplify/datastore: ^3.0.3 => 3.2.0 
    @aws-amplify/ui-react: ^1.2.1 => 1.2.5 
    @aws-sdk/client-cognito-identity: ^3.18.0 => 3.20.0 (3.6.1)
    @aws-sdk/client-cognito-identity-provider: ^3.18.0 => 3.20.0 
    @aws-sdk/credential-provider-cognito-identity: ^3.18.0 => 3.20.0 (3.6.1)
    @reach/router: ^1.3.4 => 1.3.4 
    @typeform/embed-react: ^1.0.7 => 1.0.7 
    @vimeo/player: ^2.15.3 => 2.15.3 
    amazon-cognito-identity-js: ^5.0.2 => 5.0.4 
    antd: ^4.16.2 => 4.16.6 
    aws-amplify: ^4.1.0 => 4.1.3 
    bundle-optimisations:  1.0.0 
    canvas: ^2.8.0 => 2.8.0 
    dayjs: ^1.10.6 => 1.10.6 
    dev-404-page:  1.0.0 
    dotenv: ^10.0.0 => 10.0.0 (8.6.0)
    eslint-config-airbnb: ^18.2.1 => 18.2.1 
    eslint-config-react-app: ^6.0.0 => 6.0.0 
    functions:  1.0.0 
    funnel-react: ^0.0.6 => 0.0.6 
    gatsby: ^3.6.2 => 3.9.0 
    gatsby-plugin-create-client-paths: ^3.8.0 => 3.9.0 
    gatsby-plugin-env-variables: ^2.1.0 => 2.1.0 
    gatsby-plugin-gatsby-cloud: ^2.6.1 => 2.9.0 
    gatsby-plugin-image: ^1.6.0 => 1.9.0 
    gatsby-plugin-manifest: ^3.6.0 => 3.9.0 
    gatsby-plugin-nprogress: ^3.9.0 => 3.9.0 
    gatsby-plugin-offline: ^4.6.0 => 4.9.0 
    gatsby-plugin-react-helmet: ^4.6.0 => 4.9.0 
    gatsby-plugin-sass: ^4.6.0 => 4.9.0 
    gatsby-plugin-sharp: ^3.6.0 => 3.9.0 
    gatsby-source-filesystem: ^3.6.0 => 3.9.0 
    gatsby-transformer-sharp: ^3.6.0 => 3.9.0 
    htmr: ^1.0.0 => 1.0.0 
    husky: ^4.2.5 => 4.3.8 
    internal-data-bridge:  1.0.0 
    jspdf: ^2.3.1 => 2.3.1 
    load-babel-config:  1.0.0 
    node-sass: ^6.0.0 => 6.0.1 
    prettier: 2.2.1 => 2.2.1 (2.3.2)
    prod-404:  1.0.0 
    prop-types: ^15.7.2 => 15.7.2 
    react: ^17.0.1 => 17.0.2 
    react-dom: ^17.0.1 => 17.0.2 
    react-helmet: ^6.1.0 => 6.1.0 
    react-pdf: ^5.3.2 => 5.3.2 
    react-svgmt: ^1.1.11 => 1.1.11 
    sass: ^1.34.1 => 1.35.2 
    sharp: ^0.28.3 => 0.28.3 
    svg2pdf.js: ^2.1.0 => 2.1.0 
    util: ^0.12.4 => 0.12.4 
    uuid: ^8.3.2 => 8.3.2 (3.4.0, 3.3.2)
    webpack-theme-component-shadowing:  1.0.0 
  npmGlobalPackages:
    @aws-amplify/cli: 5.1.2
    gatsby-cli: 2.12.102
    http-server: 0.12.3
    npm: 6.14.6
    serverless: 2.45.2

```

</details>

### Describe the bug

Doc here: https://docs.amplify.aws/lib/datastore/other-methods/q/platform/js#clear 
suggests to use `Datastore.clear()` to remove local data on sign in / sign out to avoid sharing sensitive data between sessions. However, there is no mention of that Datastore sync should have started before for this to work.

Case:
Let's say manual logout hasn't happened and Cognito token session expired and user is asked to login. No Datastore.query or Datastore.start operations has happened yet. Post login following operation isn't removing old data
```
await Datastore.clear()
await Datastore.start()
```

However following works as expected
```
await DataStore.start();
await DataStore.stop();
await DataStore.clear();
await DataStore.start();
```
- stop added in between to avoid unexpected errors from sync continuing in background

### Expected behavior

Make it clear in docs that `Datatore.clear()` works only after sync has started
or
it should be made possible to clear data before sync has initiated.

### Reproduction steps

1. Setup amplify project
2. Add an api & auth
3. Enable datastore
4. Add some data
5. Logout cognito / auth without clearing datastore - to simulate unexpected logout
6. Sign in with following code post sign in

### Code Snippet

```javascript
// Put your code below this line.
await Datastore.clear()
await Datastore.start()
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @gorbinphilip1 👋 Thanks for raising this issue. I spoke with someone on the DataStore team and while this is the intended behavior, they think it's worth discussing making it so that the local db can be cleared before DataStore has started. Until the behavior changes, we'll update the docs to be clear about when `clear` should be called.

https://github.com/aws-amplify/docs/pull/3470

**Comment by ecc7220** [comment]
The ios lib was changed accordingly, why is the team thinking, that it should be different on js?

[amplify-ios #1402](https://github.com/aws-amplify/amplify-ios/issues/1402)

I also got an exception using the following call orders, the exception is always the same:

Exception:

```
Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Proxy.<anonymous> (https://xxx.region.amazonaws.com/static/js/bundle.js:37042:22)
    at IndexedDBAdapter.<anonymous> (https://xxx.region.amazonaws.com/static/js/bundle.js:28100:23)
    at step (https://xxx.region.amazonaws.com/static/js/bundle.js:26890:17)
    at Object.next (https://xxx.region.amazonaws.com/static/js/bundle.js:26821:14)
    at fulfilled (https://xxx.region.amazonaws.com/static/js/bundle.js:26775:24)

```
Call order 1:

```
Amplify.DataStore.start().then(() => {
  Amplify.DataStore.clear().then(() => {
    Amplify.DataStore.query(...)
  });
});
```

Call order 2:

```
Amplify.DataStore.start().then(() => {
  Amplify.DataStore.clear().then(() => {
    Amplify.DataStore.start().then(() => {
      Amplify.DataStore.query(...)
    });
  });
});
```

Call order 3:

```
Amplify.DataStore.start().then(() => {
  Amplify.DataStore.clear().then(() => {
    Amplify.DataStore.stop().then(() => {
      Amplify.DataStore.start().then(() => {
        Amplify.DataStore.query(...)
      });
    });
  });
});
```

So it is for me not possible to clear the DataStore on app start, even it is recommended practice.
Does anybody know how to achieve this?
My use case involves sensitive data.
