### ISSUE TITLE
AWSPinpointProvider updateEndpoint failed 

### ISSUE THREAD

**Issue by antoniofranciscoandrade** [aws-amplify/amplify-js#8863]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication, Analytics

### Amplify Categories

auth, analytics

### Environment information

<details>

```
 System:
    OS: macOS 11.2.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 3.58 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.2.0 - ~/.nvm/versions/node/v14.2.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.2.0/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v14.2.0/bin/npm
  Browsers:
    Chrome: 93.0.4577.63
    Safari: 14.0.3
  npmPackages:
    @apollo/client: ^3.4.10 => 3.4.10 
    @apollo/client/cache:  undefined ()
    @apollo/client/core:  undefined ()
    @apollo/client/errors:  undefined ()
    @apollo/client/link/batch:  undefined ()
    @apollo/client/link/batch-http:  undefined ()
    @apollo/client/link/context:  undefined ()
    @apollo/client/link/core:  undefined ()
    @apollo/client/link/error:  undefined ()
    @apollo/client/link/http:  undefined ()
    @apollo/client/link/persisted-queries:  undefined ()
    @apollo/client/link/retry:  undefined ()
    @apollo/client/link/schema:  undefined ()
    @apollo/client/link/utils:  undefined ()
    @apollo/client/link/ws:  undefined ()
    @apollo/client/react:  undefined ()
    @apollo/client/react/components:  undefined ()
    @apollo/client/react/context:  undefined ()
    @apollo/client/react/data:  undefined ()
    @apollo/client/react/hoc:  undefined ()
    @apollo/client/react/hooks:  undefined ()
    @apollo/client/react/parser:  undefined ()
    @apollo/client/react/ssr:  undefined ()
    @apollo/client/testing:  undefined ()
    @apollo/client/utilities:  undefined ()
    @apollo/client/utilities/globals:  undefined ()
    @babel/plugin-transform-react-jsx: ^7.14.9 => 7.14.9 
    @burstware/expo-plaid-link: ^1.0.4 => 1.0.4 
    @expo/vector-icons: ^12.0.0 => 12.0.5 
    @fortawesome/fontawesome-svg-core: ^1.2.36 => 1.2.36 
    @fortawesome/free-brands-svg-icons: ^5.15.4 => 5.15.4 
    @fortawesome/free-regular-svg-icons: ^5.15.4 => 5.15.4 
    @fortawesome/free-solid-svg-icons: ^5.15.4 => 5.15.4 
    @fortawesome/react-native-fontawesome: ^0.2.7 => 0.2.7 
    @gorhom/bottom-sheet: ^3 => 3.6.6 
    @graphql-codegen/add: ^2.0.2 => 2.0.2 
    @graphql-codegen/cli: 1.21.5 => 1.21.5 
    @graphql-codegen/typescript: ^1.23.0 => 1.23.0 
    @graphql-codegen/typescript-operations: ^1.18.4 => 1.18.4 
    @graphql-codegen/typescript-react-apollo: ^2.3.1 => 2.3.1 
    @react-native-async-storage/async-storage: ^1.15.7 => 1.15.7 
    @react-native-community/blur: ^3.6.0 => 3.6.0 
    @react-native-community/eslint-config:  1.1.0 
    @react-native-community/eslint-plugin:  1.0.0 
    @react-native-community/masked-view: 0.1.10 => 0.1.10 
    @react-native-community/netinfo: ^6.0.2 => 6.0.2 
    @react-navigation/bottom-tabs: 5.11.2 => 5.11.2 
    @react-navigation/material-top-tabs: ^5.3.19 => 5.3.19 
    @react-navigation/native: ~5.8.10 => 5.8.10 
    @react-navigation/stack: ~5.12.8 => 5.12.8 
    @storybook/addon-actions: ^5.3.21 => 5.3.21 
    @storybook/addon-knobs: ^5.3.21 => 5.3.21 
    @storybook/addon-links: ^5.3.21 => 5.3.21 
    @storybook/addon-ondevice-actions: ^5.3.23 => 5.3.23 
    @storybook/addon-ondevice-knobs: ^5.3.25 => 5.3.25 
    @storybook/react-native: ^5.3.25 => 5.3.25 
    @storybook/react-native-server: ^5.3.23 => 5.3.23 
    @svgr/cli: ^5.5.0 => 5.5.0 
    @types/apollo-upload-client: ^14.1.0 => 14.1.0 
    @types/node: 10.12.18 => 10.12.18 
    @types/react: ~16.9.35 => 16.9.56 (17.0.6)
    @types/react-native: ^0.63.53 => 0.63.53 (0.64.6)
    @types/react-native-snap-carousel: ^3.8.4 => 3.8.4 
    @types/react-native-video: ^5.0.9 => 5.0.9 
    @types/styled-components-react-native: ^5.1.1 => 5.1.1 
    @types/yup: ^0.29.13 => 0.29.13 
    HelloWorld:  0.0.1 
    apollo-boost: ^0.4.9 => 0.4.9 
    apollo-link-error: ^1.1.13 => 1.1.13 
    apollo-upload-client: ^16.0.0 => 16.0.0 
    aws-amplify: ^4.2.8 => 4.2.8 
    aws-amplify-react-native: ^5.0.3 => 5.0.3 
    axios: ^0.21.4 => 0.21.4 
    babel-loader: ^8.2.2 => 8.2.2 
    babel-plugin-inline-import: ^3.0.0 => 3.0.0 
    babel-plugin-inline-view-configs:  0.0.5 
    babel-preset-expo: ^8.4.1 => 8.4.1 (8.3.0)
    example:  0.1.0 
    expo: ~41.0.1 => 41.0.1 (40.0.1)
    expo-asset: ^8.3.3 => 8.3.3 (8.2.2)
    expo-av: ~9.1.2 => 9.1.2 
    expo-blur: ~9.0.3 => 9.0.3 
    expo-constants: ~10.1.3 => 10.1.3 (9.3.5)
    expo-device: ~3.2.0 => 3.2.0 
    expo-font: ~9.1.0 => 9.1.0 (8.4.0)
    expo-image-manipulator: ~9.1.0 => 9.1.0 
    expo-image-picker: ~10.1.4 => 10.1.4 
    expo-linking: ~2.2.3 => 2.2.3 (2.0.1)
    expo-notifications: ~0.11.6 => 0.11.6 
    expo-splash-screen: ^0.10.3 => 0.10.3 
    expo-status-bar: ~1.0.4 => 1.0.4 
    expo-web-browser: ~9.1.0 => 9.1.0 
    formik: ^2.2.9 => 2.2.9 
    graphql: ^15.5.3 => 15.5.3 (14.0.0, 14.7.0)
    hermes-inspector-msggen:  1.0.0 
    jest-expo: ~41.0.0 => 41.0.0 
    react: 16.13.1 => 16.13.1 
    react-animated:  0.1.0 
    react-apollo: ^3.1.5 => 3.1.5 
    react-dom: 16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
    react-native-codegen:  0.0.2 
    react-native-custom-radio-button: ^1.0.2 => 1.0.2 
    react-native-gesture-handler: ~1.10.2 => 1.10.3 
    react-native-inappbrowser-reborn: ^3.6.3 => 3.6.3 
    react-native-mime-types: ^2.3.0 => 2.3.0 
    react-native-reanimated: ~2.1.0 => 2.1.0 
    react-native-redash: ^16.2.2 => 16.2.2 
    react-native-safe-area-context: 3.2.0 => 3.2.0 (3.1.9)
    react-native-screens: ~3.0.0 => 3.0.0 
    react-native-smooth-picker: ^1.1.5 => 1.1.5 
    react-native-snap-carousel: ^3.9.1 => 3.9.1 
    react-native-storybook-loader: ^2.0.4 => 2.0.4 
    react-native-svg: ^10.1.0 => 10.1.0 
    react-native-svg-transformer: ^0.14.3 => 0.14.3 
    react-native-svg-uri: ^1.2.3 => 1.2.3 
    react-native-switch-selector: ^2.1.4 => 2.1.4 
    react-native-tab-view: ^2.16.0 => 2.16.0 
    react-native-typescript-transformer: ^1.2.13 => 1.2.13 
    react-native-url-polyfill: ^1.3.0 => 1.3.0 
    react-native-web: ~0.13.12 => 0.13.18 
    react-native-wheel-picker: ^1.2.0 => 1.2.0 
    reanimated-bottom-sheet: ^1.0.0-alpha.22 => 1.0.0-alpha.22 
    serverless-bundle: ^4.4.0 => 4.4.0 
    styled-components: ^5.3.1 => 5.3.1 
    styled-components/macro:  undefined ()
    styled-components/native:  undefined ()
    styled-components/primitives:  undefined ()
    subscriptions-transport-ws: ^0.9.19 => 0.9.19 
    type-graphql: ^1.1.1 => 1.1.1 
    typescript: ^4.0.8 => 4.0.8 
    yup: ^0.32.9 => 0.32.9 
  npmGlobalPackages:
    @aws-amplify/cli: 4.50.2
    expo-cli: 4.4.4
    localtunnel: 2.0.1
    npm: 6.14.4
    pure-prompt: 1.16.0
    yarn: 1.22.10

```

</details>

### Describe the bug

Amplify is throwing the following error upon App launch which is preventing it from running:

AWSPinpointProvider - updateEndpoint failed, [TypeError: undefined is not an object (evaluating 'data.byteLength')]

### Expected behavior

No error is supposed to be thrown. App was running previously and no changes were made to the Amplify config

### Reproduction steps

1. configure AWS amplify
2. run expo start
3. error is thrown and app is blocked

### Code Snippet

```javascript
// Put your code below this line.
import awsConfig from './aws-exports'
import * as Linking from 'expo-linking'

const expoScheme = expoConfig.expo.scheme + '://'
let redirectUrl = Linking.makeUrl()
// simulator on localhost and devices on LAN
if (redirectUrl.startsWith('exp://')) {
  redirectUrl = redirectUrl + '/--/'
} else if (redirectUrl === expoScheme) {
  // no change required
} else {
  // for expo client
  redirectUrl = redirectUrl + '/'
}

const updatedAwsConfig = {
  ...awsConfig,
  oauth: {
    ...awsConfig.oauth,
    domain: xxxxxx,
    redirectSignIn: redirectUrl,
    redirectSignOut: redirectUrl,
    urlOpener
  }
}

Amplify.configure(updatedAwsConfig)
```

### Log output

<details>

```
// Put your logs below this line
[ERROR] 10:59.587 AWSPinpointProvider - updateEndpoint failed, [TypeError: undefined is not an object (evaluating 'data.byteLength')]
at [native code]:null in error
at node_modules/@aws-amplify/core/lib-esm/Logger/ConsoleLogger.js:139:15 in prototype._log
at node_modules/@aws-amplify/core/lib-esm/Logger/ConsoleLogger.js:210:8 in prototype.error
at node_modules/@aws-amplify/analytics/lib-esm/Providers/AWSPinpointProvider.js:445:24 in __generator$argument_1
at node_modules/@aws-sdk/client-pinpoint/node_modules/@aws-crypto/sha256-js/node_modules/tslib/tslib.js:141:21 in step
at node_modules/@aws-sdk/client-pinpoint/node_modules/@aws-crypto/sha256-js/node_modules/tslib/tslib.js:122:60 in <anonymous>
at node_modules/@aws-sdk/client-pinpoint/node_modules/@aws-crypto/sha256-js/node_modules/tslib/tslib.js:115:17 in <anonymous>
at node_modules/@aws-sdk/client-pinpoint/node_modules/@aws-crypto/sha256-js/node_modules/tslib/tslib.js:111:15 in __awaiter
at node_modules/@aws-amplify/analytics/lib-esm/Providers/AWSPinpointProvider.js:431:24 in prototype._handleEndpointUpdateFailure
at node_modules/@aws-amplify/analytics/lib-esm/Providers/AWSPinpointProvider.js:424:46 in __generator$argument_1
at node_modules/@aws-sdk/client-pinpoint/node_modules/@aws-crypto/sha256-js/node_modules/tslib/tslib.js:141:21 in step
at node_modules/@aws-sdk/client-pinpoint/node_modules/@aws-crypto/sha256-js/node_modules/tslib/tslib.js:122:60 in <anonymous>
at node_modules/@aws-sdk/client-pinpoint/node_modules/@aws-crypto/sha256-js/node_modules/tslib/tslib.js:113:50 in rejected
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue


```

</details>

### aws-exports.js

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": xxxxxxxxxx,
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": xxxxxx,
    "aws_user_pools_web_client_id": xxxxxxxx,
    "oauth": {
        "domain": xxxxxxxx,
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "exp://127.0.0.1:19000/--/,myapp://,exp://192.168.68.109:19000/--/",
        "redirectSignOut": "exp://127.0.0.1:19000/--/,myapp://,exp://192.168.68.109:19000/--/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": xxxxxxx,
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_mobile_analytics_app_id": xxxxxxxxxx,
    "aws_mobile_analytics_app_region": "us-east-1"
};

export default awsmobile;

### Mobile Device

iPhone 12 Pro Max Simulator

**Comment by hkjpotato** [comment]
Hi @antoniofranciscoandrade can you help check if you have enable unauth user (guest user) for cognito? https://github.com/aws-amplify/amplify-js/issues/7768#issuecomment-889895358 based on this reply it could be a potential reason. 

Another potential fix is to turn off the devTool https://stackoverflow.com/a/67627835/6860947

**Comment by antoniofranciscoandrade** [comment]
@hkjpotato Adding unauthenticated users on cognito solved it for me, thanks! Wonder why it only started happening recently for me though, after having used amplify/cognito for a while with no issues. 

Issue is solved, in any case 🙏🏻.

**Comment by rob1121** [comment]
Im make a nextjs project and I got the same error. Above solution is not working on me

**Comment by majirosstefan** [comment]
same here, React-Native project (Android app). 

Documentation for setting notifications should be improved as it does not mention anything about updating Cognito:
https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/js/

For me it was enough to edit backend/auth/****/parameters.json file: 

![Screen Shot 2022-08-06 at 4 30 13 PM](https://user-images.githubusercontent.com/44647381/183253226-d54eba90-b382-40ac-9e36-5f487127cc19.png)

**Comment by MensurRasic** [comment]
Same error appear out of nowhere on my project as well! I tried to solution proposed above but it still doesn't work. Has anyone found robust solution for this problem?
