### ISSUE TITLE
react native run-android error

### ISSUE THREAD

**Issue by markl-vesper** [aws-amplify/amplify-js#8869]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Analytics, Push Notifications

### Environment information

<details>

```
  System:
    OS: macOS 11.4
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 78.75 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 93.0.4577.63
    Safari: 14.1.1
  npmPackages:
    @aws-amplify/pushnotification: 4.2.8 => 4.2.8 
    @babel/core: ^7.12.9 => 7.15.5 
    @babel/plugin-proposal-decorators: 7.14.5 => 7.14.5 (7.15.4)
    @babel/runtime: ^7.12.5 => 7.15.4 
    @react-native-community/async-storage: 1.12.0 => 1.12.0 
    @react-native-community/eslint-config: ^2.0.0 => 2.0.0 
    @react-native-community/netinfo: 6.0.0 => 6.0.0 
    @react-navigation/drawer: 6.1.4 => 6.1.4 
    @react-navigation/native: 6.0.2 => 6.0.2 
    @react-navigation/native-stack: 6.1.0 => 6.1.0 
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: 5.1.0 => 5.1.0 
    aws-amplify: 4.2.8 => 4.2.8 
    aws-appsync: 4.1.1 => 4.1.1 
    aws-sdk: 2.985.0 => 2.985.0 
    babel-jest: ^26.6.3 => 26.6.3 
    babel-preset-mobx: ^2.0.0 => 2.0.0 
    cardinal-direction: 1.1.1 => 1.1.1 
    convert-radix64: ^0.2.0 => 0.2.0 
    convert-units: 2.3.4 => 2.3.4 
    eslint: 7.14.0 => 7.14.0 
    eslint-plugin-react-hooks: ^2.0.0 => 2.5.1 (4.2.0)
    geodesy: ^2.2.0 => 2.2.1 
    graphql-tag: 2.10.1 => 2.10.1 
    hermes-inspector-msggen:  1.0.0 
    jest: ^26.6.3 => 26.6.3 
    metro-react-native-babel-preset: ^0.66.0 => 0.66.2 
    mobx: 6.3.2 => 6.3.2 
    mobx-react: 7.2.0 => 7.2.0 
    moment: 2.29.1 => 2.29.1 
    numeral: ^2.0.6 => 2.0.6 
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-code-push: 7.0.1 => 7.0.1 
    react-native-codegen: ^0.0.7 => 0.0.7 
    react-native-config: 1.4.3 => 1.4.3 
    react-native-device-info: 8.3.0 => 8.3.0 
    react-native-gesture-handler: 1.10.3 => 1.10.3 
    react-native-inappbrowser-reborn: 3.6.3 => 3.6.3 
    react-native-restart: 0.0.22 => 0.0.22 
    react-native-safe-area-context: 3.3.0 => 3.3.0 
    react-native-screens: 3.6.0 => 3.6.0 
    react-native-vector-icons: 6.6.0 => 6.6.0 
    react-test-renderer: 17.0.2 => 17.0.2 
    typescript: 3.8.2 => 3.8.2 
  npmGlobalPackages:
    npm: 6.12.0
    react-native: 0.65.1


```

</details>

### Describe the bug

npx react-native run-android fails with error

```
> Task :app:checkDebugAarMetadata FAILED
27 actionable tasks: 4 executed, 23 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.firebase:firebase-jobdispatcher:0.6.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/firebase/firebase-jobdispatcher/0.6.0/firebase-jobdispatcher-0.6.0.pom
       - file:/Users/developer/.m2/repository/com/firebase/firebase-jobdispatcher/0.6.0/firebase-jobdispatcher-0.6.0.pom
       - file:/Users/developer/1.7.1/cortexMonitoring/node_modules/react-native/android/com/firebase/firebase-jobdispatcher/0.6.0/firebase-jobdispatcher-0.6.0.pom
       - file:/Users/developer/1.7.1/cortexMonitoring/node_modules/jsc-android/dist/com/firebase/firebase-jobdispatcher/0.6.0/firebase-jobdispatcher-0.6.0.pom
       - https://dl.google.com/dl/android/maven2/com/firebase/firebase-jobdispatcher/0.6.0/firebase-jobdispatcher-0.6.0.pom
       - https://www.jitpack.io/com/firebase/firebase-jobdispatcher/0.6.0/firebase-jobdispatcher-0.6.0.pom
     Required by:
         project :app > project :aws-amplify_pushnotification
```

### Expected behavior

app to build and run on android emulator

### Reproduction steps

1. npx react-native init helloWord --version 0.65.1
2. add aws amplify and push notifications as per docs
3. npx react-native run-android

### Additional configuration

adding 

com.firebase:firebase-jobdispatcher:0.6.0 to dependencies section fails to help resolve

Appears that jobdispatcher is discontinued as per https://github.com/googlearchive/firebase-jobdispatcher-android??

Why is aws referencing a discontinued package?

### Mobile Device

Pixel 3

### Mobile Operating System

Android 11

**Comment by markl-vesper** [comment]
also attempted to npx jetifier after installation. Still fails

**Comment by Mavennix** [comment]
`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.android.gms.gcm.PendingCallback found in modules jetified-firebase-jobdispatcher-0.6.0-runtime (com.firebase:firebase-jobdispatcher:0.6.0) and jetified-play-services-gcm-11.8.0-runtime (com.google.android.gms:play-services-gcm:11.8.0)
     
     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.`

**Comment by bacarybruno** [comment]
I had the same issue after upgrading my app to react-native 0.65.1
Here is what I did to fix this issue :

Add the following lines to your `android/build.gradle` :
```gradle
allprojects {
    repositories {
        // other repositories mavenCentral(), mavenLocal(), google() ...
        jcenter() {
            content {
                includeModule("com.firebase", "firebase-jobdispatcher")
            }
        }
    }
}
```

Hope this can help you.

**Comment by markl-vesper** [comment]
Tried your suggestion @bacarybruno but only ended up with further errors

After googling the errors and testing via a helloWord app I think I am beginning to formulate a picture of the issue Im facing

A react-native init helloWord app builds fine after following instructions and adding your suggestion

My app fails to build due to dependency clashes as it looks like react-native-camera pulls in some firebase 16.1.0 components according to gradew app:dependencies

Taking a punt and commenting out below lines in build.gradle allows the app to build

```
    // implementation "com.google.firebase:firebase-core:16.0.0"
    // implementation "com.google.firebase:firebase-messaging:15.0.2"
```

but app crashes

```
09-20 15:29:39.160 20581 20581 E AndroidRuntime: FATAL EXCEPTION: main
09-20 15:29:39.160 20581 20581 E AndroidRuntime: Process: com.cortexmonitoring, PID: 20581
09-20 15:29:39.160 20581 20581 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzbq;
09-20 15:29:39.160 20581 20581 E AndroidRuntime:        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:2)
09-20 15:29:39.160 20581 20581 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.java:7239)
09-20 15:29:39.160 20581 20581 E AndroidRuntime:        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6780)
09-20 15:29:39.160 20581 20581 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6697)
09-20 15:29:39.160 20581 20581 E AndroidRuntime:        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
09-20 15:29:39.160 20581 20581 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
09-20 15:29:39.160 20581 20581 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
09-20 15:29:39.160 20581 20581 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
09-20 15:29:39.160 20581 20581 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7656)
09-20 15:29:39.160 20581 20581 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-20 15:29:39.160 20581 20581 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
09-20 15:29:39.160 20581 20581 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
09-20 15:29:39.160 20581 20581 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.zzbq" on path: DexPathList[[zip file "/data/app/~~98Xfhhka7rVFfHqEdSWziQ==/com.cortexmonitoring-HTudCZU0_mxEeyB7vfo17w==/base.apk"],nativeLibraryDirectories=[/data/app/~~98Xfhhka7rVFfHqEdSWziQ==/com.cortexmonitoring-HTudCZU0_mxEeyB7vfo17w==/lib/x86, /data/app/~~98Xfhhka7rVFfHqEdSWziQ==/com.cortexmonitoring-HTudCZU0_mxEeyB7vfo17w==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
09-20 15:29:39.160 20581 20581 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
09-20 15:29:39.160 20581 20581 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
09-20 15:29:39.160 20581 20581 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
09-20 15:29:39.177 20581 20581 I Process : Sending signal. PID: 20581 SIG: 9
09-20 15:29:39.178   501   521 D EventSequenceValidator: Transition from ACTIVITY_LAUNCHED to ACTIVITY_CANCELLED
09-20 15:29:39.218   501  1868 I ActivityManager: Process com.cortexmonitoring (pid 20581) has died: fg  TOP 
09-20 15:29:39.219   501   529 I libprocessgroup: Successfully killed process cgroup uid 10175 pid 20581 in 0ms
09-20 15:29:39.219   279   279 I Zygote  : Process 20581 exited due to signal 9 (Killed)
09-20 15:29:39.221   501  1868 W ActivityManager: Scheduling restart of crashed service com.cortexmonitoring/com.firebase.jobdispatcher.GooglePlayReceiver in 1000ms for connection
09-20 15:29:39.221  6309  6715 W beci    : Empty content. Thus might mean that the settings are not synced down.
09-20 15:29:39.672   501   521 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{6ca43e5 u0 com.cortexmonitoring/.MainActivity t-1 f}}
09-20 15:29:40.232   501   528 I ActivityManager: Start proc 20625:com.cortexmonitoring/u0a175 for service {com.cortexmonitoring/com.firebase.jobdispatcher.GooglePlayReceiver}

So it looks like camera module and AWS PN dont play nice. Will head off to RN Camera git to see what I can glean there
```

Really appreciate your suggestion as it helped to get some tests moving along etc etc

**Comment by Samaritan1011001** [comment]
@markl-vesper If you do not want to downgrade the `react-native-camera` package, you can try either of these two. 
Add the following to your dependency in `/android/app/build.gradle`

1. You can exclude the colliding items from the camera package. This will prevent the clash and use the firebase dependencies specified in your `build.gradle`
```java
dependencies {
    implementation (project(':react-native-camera')) {
        exclude group: "com.google.android.gms"
        exclude group: "com.google.firebase"
    }
// ...
}
```
OR

2. You can use an upgraded `firebase-core` and `firebase-messaging` implementations
```java
    implementation ("com.google.firebase:firebase-core:19.0.1")
    implementation ("com.google.firebase:firebase-messaging:22.0.0")
```

**Comment by markl-vesper** [comment]
downgraded camera is working fine for now. 

thanks for suggestions should we need to update

appreciated @Samaritan1011001
