### ISSUE TITLE
BadRequestException: Cannot modify owner ID: 537931028676 -> <my aws id>

### ISSUE THREAD

**Issue by ranjeethpt** [aws-amplify/amplify-js#889]
Getting below exception when trying to set up local project from https://github.com/aws-samples/aws-mobile-react-native-starter using `awsmobile start my-project react-native`
```
backend awsmobile project creation error
{ BadRequestException: Cannot modify owner ID: 537931028676 -> 413030148520
    at Object.extractError (/Users/ranjeethpt/.npm-packages/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.extractError (/Users/ranjeethpt/.npm-packages/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/protocol/rest_json.js:52:8)
    at Request.callListeners (/Users/ranjeethpt/.npm-packages/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/ranjeethpt/.npm-packages/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/ranjeethpt/.npm-packages/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/ranjeethpt/.npm-packages/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/ranjeethpt/.npm-packages/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/ranjeethpt/.npm-packages/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/ranjeethpt/.npm-packages/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/ranjeethpt/.npm-packages/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/request.js:685:12)
  message: 'Cannot modify owner ID: 537931028676 -> 413030148520',
  code: 'BadRequestException',
  time: 2018-05-23T06:59:10.276Z,
  requestId: '08ec9411-0958-46da-bbd4-f0f398edde2e',
  statusCode: 400,
  retryable: false,
  retryDelay: 94.92130211214827 }
```

**Comment by UnleashedMind** [comment]
We've notified out Mobile Hub team and they are investigating the issue. 
It might be a  server side race condition that rarely happens. Please try to execute the command again  and see if it'll be successful.

**Comment by BenWal** [comment]
I saw the same issue. Retrying the command succeeded, so it does seem to be a sporadic problem.

**Comment by ranjeethpt** [comment]
Retrying did solve the problem.

**Comment by eranation** [comment]
Happened to me, retrying solved it as well

**Comment by jordanranz** [comment]
This issue seems to have been resolved. Please reopen if there are still related questions or concerns.
