### ISSUE TITLE
 Object is not an instance of a valid model

### ISSUE THREAD

**Issue by rpostulart** [aws-amplify/amplify-js#8991]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

DataStore

### Amplify Categories

api

### Environment information

<details>

```
System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.87 GB / 16.00 GB
    Shell: 5.0.11 - /usr/local/bin/bash
  Binaries:
    Node: 14.12.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 7.24.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 94.0.4606.61
    Safari: 15.0
  npmPackages:
    @aws-amplify/datastore: ^3.4.7 => 3.4.7 
    @aws-amplify/datastore-storage-adapter: ^1.1.7 => 1.1.7 
    @babel/core: ^7.9.0 => 7.15.5 (7.9.0)
    @expo/vector-icons: ^12.0.0 => 12.0.5 
    @react-native-async-storage/async-storage: ^1.15.8 => 1.15.8 
    @react-native-community/datetimepicker: 3.5.2 => 3.5.2 
    @react-native-community/eslint-config:  1.1.0 
    @react-native-community/eslint-plugin:  1.0.0 
    @react-native-community/netinfo: ^6.0.2 => 6.0.2 
    @react-navigation/bottom-tabs: ^6.0.5 => 6.0.7 
    @react-navigation/native: ^6.0.2 => 6.0.4 
    @react-navigation/native-stack: ^6.1.0 => 6.2.2 
    @stripe/stripe-react-native: 0.1.4 => 0.1.4 
    @types/react: ~16.9.35 => 16.9.56 (17.0.24)
    @types/react-native: ~0.63.2 => 0.63.53 (0.65.1)
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: ^5.2.0 => 5.2.0 
    aws-amplify: ^4.3.1 => 4.3.1 
    aws-amplify-react-native: ^5.0.3 => 5.0.3 
    babel-plugin-inline-view-configs:  0.0.5 
    expo: ~42.0.1 => 42.0.4 
    expo-asset: ~8.3.2 => 8.3.3 
    expo-constants: ~11.0.1 => 11.0.1 (11.0.2)
    expo-font: ~9.2.1 => 9.2.1 
    expo-linking: ~2.3.1 => 2.3.1 
    expo-splash-screen: ~0.11.2 => 0.11.4 
    expo-status-bar: ~1.0.4 => 1.0.4 
    expo-web-browser: ~9.2.0 => 9.2.0 
    hermes-inspector-msggen:  1.0.0 
    ini: ^1.3.5 => 1.3.8 
    inquirer: ^6.5.1 => 6.5.2 (3.3.0)
    jest-expo: ~41.0.0-beta.0 => 41.0.0 
    moment: ^2.29.1 => 2.29.1 
    react: 16.13.1 => 16.13.1 
    react-animated:  0.1.0 
    react-dom: 16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
    react-native-codegen:  0.0.2 
    react-native-config: ^1.4.4 => 1.4.4 
    react-native-datepicker: ^1.7.2 => 1.7.2 
    react-native-elements: ^3.4.2 => 3.4.2 
    react-native-gesture-handler: ~1.10.2 => 1.10.3 
    react-native-maps: 0.28.0 => 0.28.0 
    react-native-paper: ^4.9.2 => 4.9.2 
    react-native-reanimated: ~2.2.0 => 2.2.2 
    react-native-safe-area-context: 3.2.0 => 3.2.0 
    react-native-screens: ~3.4.0 => 3.4.0 
    react-native-sqlite-storage: ^6.0.1 => 6.0.1 
    react-native-web: ~0.13.12 => 0.13.18 
    typescript: ~4.0.0 => 4.0.8 
  npmGlobalPackages:
    @aws-amplify/cli: 6.1.1
    amplify-cli: 1.0.0
    expo-cli: 4.12.0
    gatsby-cli: 2.10.2
    npm: 7.24.1
    sharp-cli: 1.15.0


```

</details>

### Describe the bug

When I write to datastore I got this error:

```
[ERROR] 43:57.200 DataStore - Object is not an instance of a valid model, Object {
  "model": Event {
    "description": "Lorem ipsum dolor sit amet",
    "name": "Lorem ipsum dolor sit amet",
  },
}
```

### Expected behavior

I expect that it will write to the datastore

### Reproduction steps

I have followed these instructions https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js/

I have this schema:

```
type Event {
  id: ID!
  name: String!
  description: String
}

```

And this in my app.js
```

import { StatusBar } from "expo-status-bar";
import React, { useEffect } from "react";
import { SafeAreaProvider } from "react-native-safe-area-context";

import useCachedResources from "./hooks/useCachedResources";
import useColorScheme from "./hooks/useColorScheme";
import Navigation from "./navigation";
// import { DataStore } from "aws-amplify";
import { DataStore } from "@aws-amplify/datastore";
import { SQLiteAdapter } from "@aws-amplify/datastore-storage-adapter";
import { Event } from "./src/models/index";

import Amplify from "aws-amplify";
import awsconfig from "./src/aws-exports";

Amplify.configure(awsconfig);

DataStore.configure();
export default function App() {
  const isLoadingComplete = useCachedResources();
  const colorScheme = useColorScheme();

  useEffect(() => {
    const test = async () => {
      await DataStore.save(
        new Event({
          name: "Lorem ipsum dolor sit amet",
          description: "Lorem ipsum dolor sit amet",
        })
      );
    };

    test();
  });

  if (!isLoadingComplete) {
    return null;
  } else {
    return (
      <SafeAreaProvider>
        <Navigation colorScheme={colorScheme} />
        <StatusBar />
      </SafeAreaProvider>
    );
  }
}

```

### Log output

<details>

```
// Put your logs below this line


[ERROR] 13:02.614 DataStore - Object is not an instance of a valid model, Object {
  "model": Event {
    "description": "Lorem ipsum dolor sit amet",
    "name": "Lorem ipsum dolor sit amet",
  },
}
at node_modules/@aws-amplify/core/lib-esm/Logger/ConsoleLogger.js:138:12 in prototype._log
at http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:195593:21 in <unknown>
at node_modules/@aws-amplify/datastore/lib-esm/datastore/datastore.js:688:34 in __generator$argument_1
at http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:227538:26 in step
at node_modules/@aws-sdk/client-cognito-identity/node_modules/@aws-crypto/sha256-js/node_modules/tslib/tslib.js:122:34 in <anonymous>
at node_modules/@aws-sdk/client-cognito-identity/node_modules/@aws-crypto/sha256-js/node_modules/tslib/tslib.js:112:44 in fulfilled
```

</details>

### Mobile Device

iphone 13

### Mobile Operating System

ios 15.0

**Comment by rpostulart** [comment]
I have noticed that when I push the API then it seems to work, but you should be able to test locally, right

**Comment by DeerSpotter** [comment]
> After pushing everything I can't reproduce it anymore
> 
> 

Was it a user authentication issue?
