### ISSUE TITLE
Can't import withSSRContext from "aws-amplify"

### ISSUE THREAD

**Issue by CerberusAI** [aws-amplify/amplify-js#9004]
**Describe the bug**
Can't import withSSRContext from "aws-amplify"
Getting error "TypeError: (0 , aws_amplify__WEBPACK_IMPORTED_MODULE_0__.withSSRContext) is not a function"

**To Reproduce**
import { withSSRContext } from 'aws-amplify';

**Expected behavior**
Import withSSRContext as a function

**Screenshots**
![image](https://user-images.githubusercontent.com/59752667/136429270-eb8e6735-91b2-4a4e-a2cd-b3e07a7ea56f.png)

**Additional context**
Developing a Next.js app in VSCode and testing on my laptop with "npm run dev"

**Comment by CerberusAI** [comment]
Hi Chris,
I ran that command but same error.
For reference, I'm on Amplify 6.0.1 & NPM 7.24.0
Just trying to work through this Next.js / Amplify auth tutorial:
https://dev.to/dabit3/the-complete-guide-to-next-js-authentication-2aco

Everything works until I created the protected.js page:

[image: image.png]



Logs after starting the local server and navigating to "
http://localhost:3000/protected"...

npm run dev

> ***@***.*** dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: Enabled by default
https://nextjs.org/docs/messages/webpack5
warn  -
.***@***.***/client-firehose/dist/es/runtimeConfig.browser.js
Should not import the named export 'name' (imported as 'name') from
default-exporting module (only default export is available soon)

.***@***.***/client-firehose/dist/es/runtimeConfig.browser.js
Should not import the named export 'version' (imported as 'version') from
default-exporting module (only default export is available soon)

.***@***.***/client-kinesis/dist/es/runtimeConfig.browser.js
Should not import the named export 'name' (imported as 'name') from
default-exporting module (only default export is available soon)

.***@***.***/client-kinesis/dist/es/runtimeConfig.browser.js
Should not import the named export 'version' (imported as 'version') from
default-exporting module (only default export is available soon)

.***@***.***/client-personalize-events/dist/es/runtimeConfig.browser.js
Should not import the named export 'name' (imported as 'name') from
default-exporting module (only default export is available soon)

.***@***.***/client-personalize-events/dist/es/runtimeConfig.browser.js
Should not import the named export 'version' (imported as 'version') from
default-exporting module (only default export is available soon)

.***@***.***/client-pinpoint/dist/es/runtimeConfig.browser.js
Should not import the named export 'name' (imported as 'name') from
default-exporting module (only default export is available soon)

.***@***.***/client-pinpoint/dist/es/runtimeConfig.browser.js
Should not import the named export 'version' (imported as 'version') from
default-exporting module (only default export is available soon)
info  - ready on http://localhost:3000
event - build page: /next/dist/pages/_error
wait  - compiling...
warn  -
.***@***.***/client-firehose/dist/es/runtimeConfig.browser.js
Should not import the named export 'name' (imported as 'name') from
default-exporting module (only default export is available soon)

.***@***.***/client-firehose/dist/es/runtimeConfig.browser.js
Should not import the named export 'version' (imported as 'version') from
default-exporting module (only default export is available soon)

.***@***.***/client-kinesis/dist/es/runtimeConfig.browser.js
Should not import the named export 'name' (imported as 'name') from
default-exporting module (only default export is available soon)

.***@***.***/client-kinesis/dist/es/runtimeConfig.browser.js
Should not import the named export 'version' (imported as 'version') from
default-exporting module (only default export is available soon)

.***@***.***/client-personalize-events/dist/es/runtimeConfig.browser.js
Should not import the named export 'name' (imported as 'name') from
default-exporting module (only default export is available soon)

.***@***.***/client-personalize-events/dist/es/runtimeConfig.browser.js
Should not import the named export 'version' (imported as 'version') from
default-exporting module (only default export is available soon)

.***@***.***/client-pinpoint/dist/es/runtimeConfig.browser.js
Should not import the named export 'name' (imported as 'name') from
default-exporting module (only default export is available soon)

.***@***.***/client-pinpoint/dist/es/runtimeConfig.browser.js
Should not import the named export 'version' (imported as 'version') from
default-exporting module (only default export is available soon)
info  - ready on http://localhost:3000
event - build page: /protected
wait  - compiling...
warn  -
.***@***.***/client-firehose/dist/es/runtimeConfig.browser.js
Should not import the named export 'name' (imported as 'name') from
default-exporting module (only default export is available soon)

.***@***.***/client-firehose/dist/es/runtimeConfig.browser.js
Should not import the named export 'version' (imported as 'version') from
default-exporting module (only default export is available soon)

.***@***.***/client-kinesis/dist/es/runtimeConfig.browser.js
Should not import the named export 'name' (imported as 'name') from
default-exporting module (only default export is available soon)

.***@***.***/client-kinesis/dist/es/runtimeConfig.browser.js
Should not import the named export 'version' (imported as 'version') from
default-exporting module (only default export is available soon)

.***@***.***/client-personalize-events/dist/es/runtimeConfig.browser.js
Should not import the named export 'name' (imported as 'name') from
default-exporting module (only default export is available soon)

.***@***.***/client-personalize-events/dist/es/runtimeConfig.browser.js
Should not import the named export 'version' (imported as 'version') from
default-exporting module (only default export is available soon)

.***@***.***/client-pinpoint/dist/es/runtimeConfig.browser.js
Should not import the named export 'name' (imported as 'name') from
default-exporting module (only default export is available soon)

.***@***.***/client-pinpoint/dist/es/runtimeConfig.browser.js
Should not import the named export 'version' (imported as 'version') from
default-exporting module (only default export is available soon)
info  - ready on http://localhost:3000
error - TypeError: (0 ,
aws_amplify__WEBPACK_IMPORTED_MODULE_0__.withSSRContext) is not a function
    at getServerSideProps (webpack-internal:///./pages/protected.js:40:66)
    at Object.renderToHTML
(/Users/cerberusai/dev/next_auth/node_modules/next/dist/server/render.js:428:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async doRender
(/Users/cerberusai/dev/next_auth/node_modules/next/dist/server/next-server.js:1144:38)
    at async
/Users/cerberusai/dev/next_auth/node_modules/next/dist/server/next-server.js:1236:28
    at async
/Users/cerberusai/dev/next_auth/node_modules/next/dist/server/response-cache.js:64:36
{
  page: '/protected'
}
Failed to parse source map: Error: You must provide the URL of
lib/mappings.wasm by calling SourceMapConsumer.initialize({
'lib/mappings.wasm': ... }) before using SourceMapConsumer
    at readWasm
(/Users/cerberusai/dev/next_auth/node_modules/source-map/lib/read-wasm.js:8:13)
    at wasm
(/Users/cerberusai/dev/next_auth/node_modules/source-map/lib/wasm.js:25:16)
    at
/Users/cerberusai/dev/next_auth/node_modules/source-map/lib/source-map-consumer.js:264:14
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
