### ISSUE TITLE
UserLambdaValidationException for Cognito Passworldess Authentication with Lambda Triggers

### ISSUE THREAD

**Issue by dizhang168** [aws-amplify/amplify-js#9127]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line

System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 62.65 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: 1.22.13 - ~/.nvm/versions/node/v12.10.0/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
  Browsers:
    Chrome: 95.0.4638.54
    Safari: 13.1.3
  npmPackages:
    @types/aws-lambda: ^8.10.83 => 8.10.83 
    @types/chai: ^4.2.17 => 4.2.22 
    @types/chai-as-promised: ^7.1.3 => 7.1.4 
    @types/chai-uuid: ^1.0.2 => 1.0.2 
    @types/config: 0.0.38 => 0.0.38 
    @types/graphql: ^14.5.0 => 14.5.0 
    @types/lodash: ^4.14.168 => 4.14.175 
    @types/mocha: ^8.2.2 => 8.2.3 
    @types/object-path: ^0.11.0 => 0.11.1 
    @types/rewire: ^2.5.28 => 2.5.28 
    @types/sinon: ^10.0.0 => 10.0.4 
    @types/sinon-chai: ^3.2.5 => 3.2.5 
    @types/uuid: ^8.3.0 => 8.3.1 
    aws-amplify: ^4.3.1 => 4.3.1 
    aws-lambda: ^1.0.6 => 1.0.6 
    aws-sdk: 2.771.0 => 2.771.0 
    chai: ^4.3.4 => 4.3.4 
    chai-uuid: ^1.0.6 => 1.0.6 
    chrome-aws-lambda: ^10.1.0 => 10.1.0 
    config: ^3.3.6 => 3.3.6 
    eslint: ^7.26.0 => 7.32.0 (6.8.0)
    eslint-config-prettier: ^8.3.0 => 8.3.0 
    eslint-plugin-import: ^2.23.2 => 2.24.2 
    eslint-plugin-prettier: ^3.4.0 => 3.4.1 
    joi: ^17.4.0 => 17.4.2 
    lodash: ^4.17.21 => 4.17.21 
    mocha: ^8.3.2 => 8.4.0 
    mocha-junit-reporter: ^2.0.0 => 2.0.0 
    moment-timezone: ^0.5.33 => 0.5.33 
    nock: ^13.0.11 => 13.1.3 
    ts-node: ^9.1.1 => 9.1.1 
    typescript: ^4.2.4 => 4.4.3 
    uuid: ^8.3.2 => 8.3.2 (3.4.0, 3.3.2)
  npmGlobalPackages:
    madge: 4.0.2
    npm: 6.10.3
    yarn: 1.22.13

```

</details>

### Describe the bug

I am implementing a Passwordless authentication following this tutorial here:
https://aws.amazon.com/blogs/mobile/implementing-passwordless-email-authentication-with-amazon-cognito/

The Triggers are added to the Cognito User Pool successfully and I am able to sign in using a challenge successfully. However, this behavior is not consistent and I often have cases where the first 2 tries (login/logout) succeed, but then the third try will throw a UserLambdaValidationException error (with error status 129).

### Expected behavior

All calls to amplify's `signIn` function should be successful and not throw unexpected error. If present, triggers should run.

### Reproduction steps

1. Install `aws-amplify` in Node and setup to use a Cognito CUSTOM_AUTH authenticationFlowType
2. Setup your Cognito user pool to use a custom authentication with DefineAuthChallenge, CreateAuthChallenge, VerifyAuthChallenge
3. Try to call `signIn` repeatedly

### Code Snippet

```javascript
  try {
    await Auth.signUp({
      username: email,
      password,
    });
    console.log('Signup: Done');
  } catch (error) {
    if ((error as any).name === 'UsernameExistsException') {
      console.log('SignUp: User already exists');
    } else {
      throw error;
    }
  }

  cognitoUser = await Auth.signIn(email);
  console.log('SignIn: Done');

```

### Log output

AuthException UserLambdaValidationException: Error: Runtime exited with error: exit status 129

<details>

```
AuthException{message=Sign in failed, cause=com.amazonaws.services.cognitoidentityprovider.model.UserLambdaValidationException: DefineAuthChallenge failed with error RequestId: 3c06c00a-27e0-4b1d-a077-c3dee3138de3 Error: Runtime exited with error: exit status 129. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: UserLambdaValidationException; Request ID: ad16fc9e-5f9e-4493-9d62-0792cbe83470), recoverySuggestion=See attached exception for more details.}
    at com.amplifyframework.auth.cognito.util.CognitoAuthExceptionConverter.lookup(CognitoAuthExceptionConverter.java:106)
    at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$5.onError(AWSCognitoAuthPlugin.java:374)
    at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:77)
    at com.amazonaws.mobile.client.internal.InternalCallback.onError(InternalCallback.java:67)
    at com.amazonaws.mobile.client.AWSMobileClient$6$1.onFailure(AWSMobileClient.java:1264)
    at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$6.onFailure(CognitoUser.java:1155)
    at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$25.run(CognitoUser.java:3038)
    at com.amazonaws.mobileconnectors.cognitoidentityprovider.continuations.AuthenticationContinuation.continueTask(AuthenticationContinuation.java:147)
    at com.amazonaws.mobile.client.AWSMobileClient$6$1.getAuthenticationDetails(AWSMobileClient.java:1228)
    at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:1032)
    at com.amazonaws.mobile.client.AWSMobileClient$6.run(AWSMobileClient.java:1178)
    at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
    at java.lang.Thread.run(Thread.java:764)
Caused by: com.amazonaws.services.cognitoidentityprovider.model.UserLambdaValidationException: DefineAuthChallenge failed with error RequestId: 3c06c00a-27e0-4b1d-a077-c3dee3138de3 Error: Runtime exited with error: exit status 129. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: UserLambdaValidationException; Request ID: ad16fc9e-5f9e-4493-9d62-0792cbe83470)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
    at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.invoke(AmazonCognitoIdentityProviderClient.java:6334)
    at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.initiateAuth(AmazonCognitoIdentityProviderClient.java:4290)
    at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$25.run(CognitoUser.java:3017)
	... 6 more

```

</details>

 CognitoUserSession: CognitoUserSession is not valid because idToken is null.

<details>

```
 CognitoUserSession: CognitoUserSession is not valid because idToken is null.
 AWSMobileClient: Sending password.
 System.out: (HTTPLog)-Static: isSBSettingEnabled false
 System.out: (HTTPLog)-Static: isSBSettingEnabled false
 System.out: (HTTPLog)-Static: isSBSettingEnabled false
 System.out: (HTTPLog)-Static: isSBSettingEnabled false
 System.err: AuthException{message=Sign in failed, cause=com.amazonaws.services.cognitoidentityprovider.model.UserLambdaValidationException: DefineAuthChallenge failed with error RequestId: 9fdb5cfa-5ec1-47bf-bc07-8adc3b4bebf6 Error: Runtime exited with error: exit status 129. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: UserLambdaValidationException; Request ID: 4cd22348-1937-4cde-ac5c-d420f39a0ce7), recoverySuggestion=See attached exception for more details.}
 System.err:     at com.amplifyframework.auth.cognito.util.CognitoAuthExceptionConverter.lookup(CognitoAuthExceptionConverter.java:106)
 System.err:     at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$5.onError(AWSCognitoAuthPlugin.java:374)
 System.err:     at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:77)
 System.err:     at com.amazonaws.mobile.client.internal.InternalCallback.onError(InternalCallback.java:67)
 System.err:     at com.amazonaws.mobile.client.AWSMobileClient$6$1.onFailure(AWSMobileClient.java:1264)
 System.err:     at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$6.onFailure(CognitoUser.java:1155)
 System.err:     at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$25.run(CognitoUser.java:3038)
 System.err:     at com.amazonaws.mobileconnectors.cognitoidentityprovider.continuations.AuthenticationContinuation.continueTask(AuthenticationContinuation.java:147)
 System.err:     at com.amazonaws.mobile.client.AWSMobileClient$6$1.getAuthenticationDetails(AWSMobileClient.java:1228)
 System.err:     at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:1032)
 System.err:     at com.amazonaws.mobile.client.AWSMobileClient$6.run(AWSMobileClient.java:1178)
 System.err:     at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
 System.err:     at java.lang.Thread.run(Thread.java:764)
 System.err: Caused by: com.amazonaws.services.cognitoidentityprovider.model.UserLambdaValidationException: DefineAuthChallenge failed with error RequestId: 9fdb5cfa-5ec1-47bf-bc07-8adc3b4bebf6 Error: Runtime exited with error: exit status 129. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: UserLambdaValidationException; Request ID: 4cd22348-1937-4cde-ac5c-d420f39a0ce7)
 System.err:     at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
 System.err:     at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
 System.err:     at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
 System.err:     at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.invoke(AmazonCognitoIdentityProviderClient.java:6334)
 System.err:     at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.initiateAuth(AmazonCognitoIdentityProviderClient.java:4290)
 System.err:     at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$25.run(CognitoUser.java:3017)
 System.err: 	... 6 more

```

</details>

**Comment by yonatanganot** [comment]
@dizhang168
Because `PreventUserExistenceErrors` is set to `Enabled` by default for new user pools in Cognito, you need to change it `Legacy` to see specific authentication errors other than generic errors.
To do that, go to Cognito > App clients > Show Details > Prevent User Existence Errors- Change to `Legacy`.

**Comment by nadetastic** [comment]
Hi @dizhang168 following up here - it may be helpful to determine why exactly your Lambda function is throwing cause the `UserLambdaValidationException` exception. Were you able to root cause and identify this?

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
