### ISSUE TITLE
Unable to have Content management working on Amplify console after migration to CLI 7+

### ISSUE THREAD

**Issue by sammartinez** [aws-amplify/amplify-js#9249]
### Discussed in https://github.com/aws-amplify/amplify-js/discussions/9245

<div type='discussions-op-text'>

<sup>Originally posted by **duranmla** November 18, 2021</sup>
Hi!

I am using `amplify-cli` (@aws-amplify/cli) version `7.3.6`, and I have migrated as suggested https://docs.amplify.aws/cli/migration/override/ my resources, while everything within the app seems to be working fine that problem I have still a blocker for my use case. The "Content" section on my Amplify console is not available as it suggests:

> An additional deployment is needed to enable content management capabilities for your API. Navigate to "Data" and hit "Save and deploy.

When I try to do so, I go to the "Data modeling" and hit "Save and deploy" which then throws error like:

```
Cannot read property 'push' of undefined, at AmplifyAuthCognitoStack.generateCognitoStackResources . 
```

The error on the stack trace suggests to update my schema but I have run the codegen command like:

`amplify codegen models`, `amplify codegen`, `yarn amplify-modelgen` and none of them generate a diff that make a change on the cloud formation. 

I am a bit lost in terms of how to debug this error. Appreciate any type of help or guidance. Thanks in advance folks!

Stack Trace:
```
Command failed with exit code 1: /root/.amplify/bin/amplify pull --amplify {"envName":"migration","defaultEditor":"code","appId":"my-app-id"} --providers {"awscloudformation":{"configLevel":"project","useProfile":true,"profileName":"amplify-backend-processor"}} --frontend {"frontend":"javascript","framework":"react","config":{"SourceDir":"src","DistributionDir":"build","BuildCommand":"npm run-script build","StartCommand":"npm run-script start"}} --yes
- Fetching updates to backend environment: migration from the cloud.
- Building resource auth/userPoolGroups
- Building resource auth/solauth
- Building resource storage/media
2021-11-18T14:56:14.564Z - error: uncaughtException: Cannot read property 'push' of undefined date=Thu Nov 18 2021 14:56:14 GMT+0000 (Coordinated Universal Time), pid=489, uid=0, gid=0, cwd=/tmp/amplify-5eacc2e2-f578-4761-a266-7df59586b376, execPath=/root/.amplify/bin/amplify, version=v12.22.7, argv=[/root/.amplify/bin/amplify, /snapshot/node_modules/@aws-amplify/cli/bin/amplify, pull, --amplify, {"envName":"migration","defaultEditor":"code","appId":"my-app-id"}, --providers, {"awscloudformation":{"configLevel":"project","useProfile":true,"profileName":"amplify-backend-processor"}}, --frontend, {"frontend":"javascript","framework":"react","config":{"SourceDir":"src","DistributionDir":"build","BuildCommand":"npm run-script build","StartCommand":"npm run-script start"}}, --yes], rss=412897280, heapTotal=333860864, heapUsed=305550904, external=20525906, arrayBuffers=18958544, loadavg=[0.4, 0.32, 0.12], uptime=418, trace=[column=51, file=/snapshot/node_modules/@aws-amplify/amplify-category-auth/lib/provider-utils/awscloudformation/auth-stack-builder/auth-cognito-stack-builder.js, function=AmplifyAuthCognitoStack.generateCognitoStackResources, line=238, method=generateCognitoStackResources, native=false, column=31, file=/snapshot/node_modules/@aws-amplify/amplify-category-auth/lib/provider-utils/awscloudformation/auth-stack-builder/auth-stack-transform.js, function=AmplifyAuthTransform.generateStackResources, line=341, method=generateStackResources, native=false, column=20, file=/snapshot/node_modules/@aws-amplify/amplify-category-auth/lib/provider-utils/awscloudformation/auth-stack-builder/auth-stack-transform.js, function=AmplifyAuthTransform.transform, line=332, method=transform, native=false, column=12, file=/snapshot/node_modules/@aws-amplify/amplify-category-auth/lib/provider-utils/awscloudformation/utils/generate-auth-stack-template.js, function=generateAuthStackTemplate, line=7, method=null, native=false], stack=[TypeError: Cannot read property 'push' of undefined,     at AmplifyAuthCognitoStack.generateCognitoStackResources (/snapshot/node_modules/@aws-amplify/amplify-category-auth/lib/provider-utils/awscloudformation/auth-stack-builder/auth-cognito-stack-builder.js:238:51),     at AmplifyAuthTransform.generateStackResources (/snapshot/node_modules/@aws-amplify/amplify-category-auth/lib/provider-utils/awscloudformation/auth-stack-builder/auth-stack-transform.js:341:31),     at AmplifyAuthTransform.transform (/snapshot/node_modules/@aws-amplify/amplify-category-auth/lib/provider-utils/awscloudformation/auth-stack-builder/auth-stack-transform.js:332:20),     at generateAuthStackTemplate (/snapshot/node_modules/@aws-amplify/amplify-category-auth/lib/provider-utils/awscloudformation/utils/generate-auth-stack-template.js:7:12)]
⚠️ Amplify command hooks are disabled in the current execution environment.
⚠️ See https://docs.amplify.aws/cli/usage/command-hooks/ for more information.
[0mAmplify AppID found: my-app-id. Amplify App name is: sol[0m
[0mBackend environment migration found in Amplify Console app: sol[0m
[32mGraphQL schema compiled successfully.[39m

[32mEdit your schema at /tmp/amplify-5eacc2e2-f578-4761-a266-7df59586b376/amplify/backend/api/sol/schema.graphql or place .graphql files in a directory at /tmp/amplify-5eacc2e2-f578-4761-a266-7df59586b376/amplify/backend/api/sol/schema[39m
[0mSuccessfully generated models. Generated models can be found in /tmp/amplify-5eacc2e2-f578-4761-a266-7df59586b376/src[0m
```</div>

**Comment by minlare** [comment]
@sammartinez - did you solve your issue?
