### ISSUE TITLE
ResourceConflictException when deploying my App

### ISSUE THREAD

**Issue by DarkestMisery** [aws-amplify/amplify-js#9258]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

Authentication, GraphQL API

### Amplify Categories

auth, function, api

### Environment information

<details>

```
# Put output below this line
System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 5.02 GB / 15.52 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    npm: 8.0.0 - ~/.nvm/versions/node/v14.15.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.45
    Firefox: 94.0
  npmPackages:
    @amcharts/amcharts4: ^4.10.20 => 4.10.22 
    @amcharts/amcharts5: ^5.0.3 => 5.0.3 
    @amcharts/amcharts5-fonts: ^5.0.1 => 5.0.1 
    @amcharts/amcharts5-geodata: ^5.0.2 => 5.0.2 
    @ampproject/toolbox-optimizer:  undefined ()
    @apollo/client: ^3.3.19 => 3.3.19 
    @apollo/client/cache:  undefined ()
    @apollo/client/core:  undefined ()
    @apollo/client/errors:  undefined ()
    @apollo/client/link/batch:  undefined ()
    @apollo/client/link/batch-http:  undefined ()
    @apollo/client/link/context:  undefined ()
    @apollo/client/link/core:  undefined ()
    @apollo/client/link/error:  undefined ()
    @apollo/client/link/http:  undefined ()
    @apollo/client/link/persisted-queries:  undefined ()
    @apollo/client/link/retry:  undefined ()
    @apollo/client/link/schema:  undefined ()
    @apollo/client/link/utils:  undefined ()
    @apollo/client/link/ws:  undefined ()
    @apollo/client/react:  undefined ()
    @apollo/client/react/components:  undefined ()
    @apollo/client/react/context:  undefined ()
    @apollo/client/react/data:  undefined ()
    @apollo/client/react/hoc:  undefined ()
    @apollo/client/react/hooks:  undefined ()
    @apollo/client/react/parser:  undefined ()
    @apollo/client/react/ssr:  undefined ()
    @apollo/client/testing:  undefined ()
    @apollo/client/utilities:  undefined ()
    @babel/core:  undefined ()
    @headlessui/react: ^1.2.0 => 1.2.0 
    @heroicons/react: ^1.0.1 => 1.0.1 
    amcharts4-example-100%-stacked-column-chart:  0.1.0 
    amcharts4-example-adding-live-data:  0.1.0 
    amcharts4-example-amcharts3:  0.1.0 
    amcharts4-example-animating-along-the-line-series:  0.1.0 
    amcharts4-example-bar-chart-race:  0.1.0 
    amcharts4-example-base:  0.1.0 
    amcharts4-example-bent-gantt-chart:  0.1.0 
    amcharts4-example-bubble-chart:  0.1.0 
    amcharts4-example-candlestick-chart:  0.1.0 
    amcharts4-example-changing-series-apppearance:  0.1.0 
    amcharts4-example-changing-tree-map-data:  0.1.0 
    amcharts4-example-chord-diagram:  0.1.0 
    amcharts4-example-chord-diagram-non-ribbon:  0.1.0 
    amcharts4-example-chord-friends-kisses:  0.1.0 
    amcharts4-example-clock:  0.1.0 
    amcharts4-example-column-chart-with-axis-break:  0.1.0 
    amcharts4-example-column-chart-with-images-as-bullets:  0.1.0 
    amcharts4-example-columns-with-pies-inside:  0.1.0 
    amcharts4-example-countries-morphing-to-pie-chart:  0.1.0 
    amcharts4-example-curved-column-chart:  0.1.0 
    amcharts4-example-custom-shape-chart:  0.1.0 
    amcharts4-example-cylinder-chart:  0.1.0 
    amcharts4-example-data-grouping-50K:  0.1.0 
    amcharts4-example-date-based-radar:  0.1.0 
    amcharts4-example-day-night-map:  0.1.0 
    amcharts4-example-donut-chart:  0.1.0 
    amcharts4-example-drag-and-change-values:  0.1.0 
    amcharts4-example-dragging-pie-slices:  0.1.0 
    amcharts4-example-drill-down-map:  0.1.0 
    amcharts4-example-drill-down-tree-map:  0.1.0 
    amcharts4-example-dumbbell-plot:  0.1.0 
    amcharts4-example-dumbbell-plot-horizontal:  0.1.0 
    amcharts4-example-duration-axis:  0.1.0 
    amcharts4-example-error-chart:  0.1.0 
    amcharts4-example-fill-between-lines-chart:  0.1.0 
    amcharts4-example-fishbone-timeline:  0.1.0 
    amcharts4-example-force-directed-creating-links:  0.1.0 
    amcharts4-example-force-directed-network:  0.1.0 
    amcharts4-example-force-directed-tree:  0.1.0 
    amcharts4-example-force-directed-tree-expandable:  0.1.0 
    amcharts4-example-funnel-chart:  0.1.0 
    amcharts4-example-funnel-chart-horizontal:  0.1.0 
    amcharts4-example-gantt-chart:  0.1.0 
    amcharts4-example-gauge-with-bands:  0.1.0 
    amcharts4-example-geo-heat-map:  0.1.0 
    amcharts4-example-heat-map:  0.1.0 
    amcharts4-example-heat-map-circles:  0.1.0 
    amcharts4-example-heat-map-radar:  0.1.0 
    amcharts4-example-horizontally-stacked-axes:  0.1.0 
    amcharts4-example-infinity-chart:  0.1.0 
    amcharts4-example-lazy-loading:  0.1.0 
    amcharts4-example-line-different-ups-downs:  0.1.0 
    amcharts4-example-map-line-gauge-mix:  0.1.0 
    amcharts4-example-morphing-countries:  0.1.0 
    amcharts4-example-multiple-axes-date-based-chart:  0.1.0 
    amcharts4-example-multiple-series-map-chart:  0.1.0 
    amcharts4-example-non-chart-usage:  0.1.0 
    amcharts4-example-ohlc-chart:  0.1.0 
    amcharts4-example-packed-circles:  0.1.0 
    amcharts4-example-pictorial-bar-chart:  0.1.0 
    amcharts4-example-pictorial-chart:  0.1.0 
    amcharts4-example-pictorial-stacked-chart:  0.1.0 
    amcharts4-example-pictorial-stacked-chart-horizontal:  0.1.0 
    amcharts4-example-polar-area-chart:  0.1.0 
    amcharts4-example-population-pyramid:  0.1.0 
    amcharts4-example-pyramid-chart:  0.1.0 
    amcharts4-example-radar-chart-with-axis-break:  0.1.0 
    amcharts4-example-radar-timeline-chart:  0.1.0 
    amcharts4-example-radial-bar-chart:  0.1.0 
    amcharts4-example-real-time-data-sorting:  0.1.0 
    amcharts4-example-road-chart:  0.1.0 
    amcharts4-example-rotating-globe:  0.1.0 
    amcharts4-example-rotating-globe-with-circles:  0.1.0 
    amcharts4-example-sankey-diagram-with-animated-bullets:  0.1.0 
    amcharts4-example-semi-circle-donut-chart:  0.1.0 
    amcharts4-example-serpentine-gantt-horizontal:  0.1.0 
    amcharts4-example-serpentine-step-line:  0.1.0 
    amcharts4-example-serpentine-timeline:  0.1.0 
    amcharts4-example-simple-3D-pie-chart:  0.1.0 
    amcharts4-example-simple-bar-chart:  0.1.0 
    amcharts4-example-simple-column-chart:  0.1.0 
    amcharts4-example-simple-gauge:  0.1.0 
    amcharts4-example-simple-line-chart:  0.1.0 
    amcharts4-example-simple-map-chart:  0.1.0 
    amcharts4-example-simple-pie-chart:  0.1.0 
    amcharts4-example-simple-radar-chart:  0.1.0 
    amcharts4-example-simple-sankey-diagram:  0.1.0 
    amcharts4-example-simple-tree-map:  0.1.0 
    amcharts4-example-spiral-bar-chart:  0.1.0 
    amcharts4-example-spiral-chart:  0.1.0 
    amcharts4-example-spiral-gantt-chart:  0.1.0 
    amcharts4-example-stacked-3D-column-chart:  0.1.0 
    amcharts4-example-stacked-area-radar-chart:  0.1.0 
    amcharts4-example-stacked-column-chart:  0.1.0 
    amcharts4-example-stadium-track-chart:  0.1.0 
    amcharts4-example-step-count-chart:  0.1.0 
    amcharts4-example-step-line-chart:  0.1.0 
    amcharts4-example-step-line-no-risers-chart:  0.1.0 
    amcharts4-example-stock-chart:  0.1.0 
    amcharts4-example-stock-comparing-values:  0.1.0 
    amcharts4-example-sunburst:  0.1.0 
    amcharts4-example-syncing-cursors-and-zoom:  0.1.0 
    amcharts4-example-timeline:  0.1.0 
    amcharts4-example-triangle-column-chart:  0.1.0 
    amcharts4-example-variable-angle-radar-chart:  0.1.0 
    amcharts4-example-variable-height-3D-pie-chart:  0.1.0 
    amcharts4-example-variable-radius-pie-chart:  0.1.0 
    amcharts4-example-venn-diagram:  0.1.0 
    amcharts4-example-venn-diagram-with-patterns:  0.1.0 
    amcharts4-example-vertical-sankey-diagram:  0.1.0 
    amcharts4-example-vertically-stacked-axes:  0.1.0 
    amcharts4-example-waterfall-chart:  0.1.0 
    amcharts4-example-word-cloud:  0.1.0 
    amcharts4-example-word-cloud-changing-data:  0.1.0 
    amcharts4-example-work-hours-map:  0.1.0 
    amcharts4-example-xy-error-chart:  0.1.0 
    amcharts5-example-flow-chord:  0.1.0 
    amcharts5-example-flow-chord-directed:  0.1.0 
    amcharts5-example-flow-chord-non-ribbon:  0.1.0 
    amcharts5-example-flow-sankey:  0.1.0 
    amcharts5-example-gauge:  0.1.0 
    amcharts5-example-gauge-bands:  0.1.0 
    amcharts5-example-hierarchy-force-directed:  0.1.0 
    amcharts5-example-hierarchy-pack:  0.1.0 
    amcharts5-example-hierarchy-partition:  0.1.0 
    amcharts5-example-hierarchy-sunburst:  0.1.0 
    amcharts5-example-hierarchy-tree:  0.1.0 
    amcharts5-example-hierarchy-treemap:  0.1.0 
    amcharts5-example-map-animating-along-lines:  0.1.0 
    amcharts5-example-map-day-and-night:  0.1.0 
    amcharts5-example-map-globe-rotate-to-country:  0.1.0 
    amcharts5-example-map-globe-with-projected-circles:  0.1.0 
    amcharts5-example-map-with-bubbles:  0.1.0 
    amcharts5-example-map-zoom-to-country:  0.1.0 
    amcharts5-example-misc-40-charts:  0.1.0 
    amcharts5-example-misc-microchart-grid:  0.1.0 
    amcharts5-example-pie-chart:  0.1.0 
    amcharts5-example-pie-donut-chart:  0.1.0 
    amcharts5-example-pie-variable-radius:  0.1.0 
    amcharts5-example-radar-column-iwatch-style:  0.1.0 
    amcharts5-example-radar-heat-map:  0.1.0 
    amcharts5-example-radar-line:  0.1.0 
    amcharts5-example-radar-time-line:  0.1.0 
    amcharts5-example-sliced-funnel:  0.1.0 
    amcharts5-example-sliced-pictorial-stacked:  0.1.0 
    amcharts5-example-sliced-pyramid:  0.1.0 
    amcharts5-example-venn-diagram:  0.1.0 
    amcharts5-example-wordcloud-with-data:  0.1.0 
    amcharts5-example-wordcloud-with-text:  0.1.0 
    amcharts5-example-xy-100-percent-stacked-column:  0.1.0 
    amcharts5-example-xy-animated-bullet-at-the-end-of-the-series:  0.1.0 
    amcharts5-example-xy-bubble:  0.1.0 
    amcharts5-example-xy-candlestick:  0.1.0 
    amcharts5-example-xy-clustered-column:  0.1.0 
    amcharts5-example-xy-column:  0.1.0 
    amcharts5-example-xy-comparing-series-google-analytics-style:  0.1.0 
    amcharts5-example-xy-data-grouping:  0.1.0 
    amcharts5-example-xy-draggable-range:  0.1.0 
    amcharts5-example-xy-drawing-series-with-mouse-or-touch:  0.1.0 
    amcharts5-example-xy-dumbbell plot:  0.1.0 
    amcharts5-example-xy-evenly-spaced-date-axis:  0.1.0 
    amcharts5-example-xy-line:  0.1.0 
    amcharts5-example-xy-line-highlight-on-legend-hover:  0.1.0 
    amcharts5-example-xy-live-data:  0.1.0 
    amcharts5-example-xy-multiple-synced-value-axes:  0.1.0 
    amcharts5-example-xy-ohlc:  0.1.0 
    amcharts5-example-xy-real-time-data-sorting:  0.1.0 
    amcharts5-example-xy-smoothed-line:  0.1.0 
    amcharts5-example-xy-stacked-and-clustered-column:  0.1.0 
    amcharts5-example-xy-stacked-column:  0.1.0 
    amcharts5-example-xy-stacked-step:  0.1.0 
    amcharts5-example-xy-stock:  0.1.0 
    amcharts5-example-xy-stock-comparing:  0.1.0 
    amphtml-validator:  undefined ()
    arg:  undefined ()
    async-retry:  undefined ()
    async-sema:  undefined ()
    autoprefixer: ^10.2.5 => 10.2.5 
    aws-amplify: ^3.4.0 => 3.4.3 
    aws-appsync: ^4.0.3 => 4.0.3 
    aws-appsync-react: ^4.0.3 => 4.0.3 
    bfj:  undefined ()
    cacache:  undefined ()
    chart.js: ^2.9.4 => 2.9.4 
    ci-info:  undefined ()
    classnames: ^2.2.6 => 2.2.6 
    comment-json:  undefined ()
    compression:  undefined ()
    conf:  undefined ()
    content-type:  undefined ()
    cookie:  undefined ()
    css-loader:  undefined ()
    css.gg: ^2.0.0 => 2.0.0 
    date-fns: ^2.25.0 => 2.25.0 
    debug:  undefined ()
    devalue:  undefined ()
    escape-string-regexp:  undefined ()
    file-loader:  undefined ()
    find-cache-dir:  undefined ()
    find-up:  undefined ()
    fresh:  undefined ()
    graphql-tag: ^2.12.4 => 2.12.4 
    gzip-size:  undefined ()
    http-proxy:  undefined ()
    ignore-loader:  undefined ()
    ini: ^1.3.5 => 1.3.8 
    inquirer: ^6.5.1 => 6.5.2 
    is-animated:  undefined ()
    is-docker:  undefined ()
    is-wsl:  undefined ()
    json5:  undefined ()
    jsonwebtoken:  undefined ()
    loader-utils:  undefined ()
    lodash.curry:  undefined ()
    lru-cache:  undefined ()
    mini-css-extract-plugin:  undefined ()
    nanoid:  undefined ()
    neo-async:  undefined ()
    next: ^10.2.3 => 10.2.3 
    next-transpile-modules: ^8.0.0 => 8.0.0 
    ora:  undefined ()
    postcss: ^8.2.14 => 8.2.14 (8.2.13)
    postcss-flexbugs-fixes:  undefined ()
    postcss-loader:  undefined ()
    postcss-preset-env:  undefined ()
    postcss-scss:  undefined ()
    primeflex: 2.0.0 => 2.0.0 
    primeicons: ^4.1.0 => 4.1.0 
    primereact: ^6.3.2 => 6.3.2 
    react: 17.0.2 => 17.0.2 
    react-apollo: ^3.1.5 => 3.1.5 
    react-csv: ^2.0.3 => 2.0.3 
    react-datepicker: ^4.2.1 => 4.2.1 
    react-dom: 17.0.2 => 17.0.2 
    react-table: ^7.7.0 => 7.7.0 
    react-transition-group: ^4.4.1 => 4.4.1 (2.9.0)
    react-transition-group/CSSTransition:  undefined ()
    react-transition-group/ReplaceTransition:  undefined ()
    react-transition-group/SwitchTransition:  undefined ()
    react-transition-group/Transition:  undefined ()
    react-transition-group/TransitionGroup:  undefined ()
    react-transition-group/TransitionGroupContext:  undefined ()
    react-transition-group/config:  undefined ()
    recast:  undefined ()
    recharts: ^2.0.9 => 2.0.9 
    resolve-url-loader:  undefined ()
    sass-loader:  undefined ()
    schema-utils:  undefined ()
    semver:  undefined ()
    send:  undefined ()
    simple-line-chart:  0.0.0 
    source-map:  undefined ()
    string-hash:  undefined ()
    strip-ansi:  undefined ()
    tailwindcss: ^2.1.2 => 2.2.16 
    terser:  undefined ()
    text-table:  undefined ()
    unistore:  undefined ()
    web-vitals:  undefined ()
    webpack:  undefined ()
    webpack-sources:  undefined ()
  npmGlobalPackages:
    @aws-amplify/cli: 6.3.1
    @feathersjs/cli: 4.4.3
    npm: 8.0.0
    sequelize-cli: 6.2.0

```

</details>

### Describe the bug

When I was deploying my app, It failed. Provision was good, cloning and backend deploy as well but after compiling the front end, It just returned: 
```
ResourceConflictException: The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:us-east-1:NNNNNNN:function:XXXXXXXX
                                  at Object.extractError (/root/.//node_modules/aws-sdk/lib/protocol/json.js:52:27)
                                  at Request.extractError (/root/.//node_modules/aws-sdk/lib/protocol/rest_json.js:49:8)
                                  at Request.callListeners (/root/.//node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                  at Request.emit (/root/.//node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                  at Request.emit (/root/.//node_modules/aws-sdk/lib/request.js:686:14)
                                  at Request.transition (/root/.//node_modules/aws-sdk/lib/request.js:22:10)
                                  at AcceptorStateMachine.runTo (/root/.//node_modules/aws-sdk/lib/state_machine.js:14:12)
                                  at /root/.//node_modules/aws-sdk/lib/state_machine.js:26:10
                                  at Request.<anonymous> (/root/.//node_modules/aws-sdk/lib/request.js:38:9)
                                  at Request.<anonymous> (/root/.//node_modules/aws-sdk/lib/request.js:688:12) {
                                  code: 'ResourceConflictException',
                                  time: 2021-11-19T14:47:08.719Z,
                                  requestId: '6c1ca95f-21e5-4a96-98b5-3073942c302f',
                                  statusCode: 409,
                                  retryable: false,
                                  retryDelay: 45.87611036575101
                                  }

[G[?25h[G[J
                                  139s › ... › ResourceConflictException: The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:us-east-1:NNNNNN:function:XXXXXXXXXX
                                  [G[?25h
```

When I saw the function, It is the function that manages amplify or 'API Lambda@Edge for Next CloudFront distribution'. It never happened before.

### Expected behavior

Deploy the app.

### Reproduction steps

Just run the deploy of the app, it will throw the error minutes later.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @DarkestMisery 👋 thanks for raising this issue. However, it seems this is more related to the console than the JS library so I will transfer this issue over for better support.
