### ISSUE TITLE
Amplify lambda functions error: jest-haste-map: Haste module naming collision

### ISSUE THREAD

**Issue by zandvakiliramin** [aws-amplify/amplify-js#9269]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

GraphQL API

### Amplify Categories

function

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 11.6.1
    CPU: (4) x64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
    Memory: 131.85 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.1 - /usr/local/opt/node@14/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/opt/node@14/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Safari: 15.1
  npmPackages:
    @babel/core: ^7.12.9 => 7.16.0 
    @expo/vector-icons: ^12.0.0 => 12.0.5 
    @react-navigation/bottom-tabs: ^6.0.5 => 6.0.9 
    @react-navigation/native: ^6.0.2 => 6.0.6 
    @react-navigation/native-stack: ^6.1.0 => 6.2.5 
    @types/react: ~17.0.21 => 17.0.36 
    @types/react-native: ~0.64.12 => 0.64.19 
    HelloWorld:  0.0.1 
    expo: ~43.0.2 => 43.0.3 
    expo-asset: ~8.4.3 => 8.4.3 
    expo-constants: ~12.1.3 => 12.1.3 
    expo-font: ~10.0.3 => 10.0.3 
    expo-linking: ~2.4.2 => 2.4.2 
    expo-splash-screen: ~0.13.5 => 0.13.5 
    expo-status-bar: ~1.1.0 => 1.1.0 
    expo-web-browser: ~10.0.3 => 10.0.3 
    hermes-inspector-msggen:  1.0.0 
    jest-expo: ~43.0.0 => 43.0.1 
    react: 17.0.1 => 17.0.1 
    react-dom: 17.0.1 => 17.0.1 
    react-native: 0.64.3 => 0.64.3 
    react-native-safe-area-context: 3.3.2 => 3.3.2 
    react-native-screens: ~3.8.0 => 3.8.0 
    react-native-web: 0.17.1 => 0.17.1 
    typescript: ~4.3.5 => 4.3.5 
  npmGlobalPackages:
    @aws-amplify/cli: 7.4.2
    @expo/ngrok: 4.1.0
    expo-cli: 4.13.0
    npm: 8.1.0
```

</details>

### Describe the bug

I made an expo app, called test-functions. Then I initialized AWS-amplify on it, and then I set up a lambda function, called lambdaTestFunction, with the CLI and using the hello-world template and pushed it to the cloud. I did not do anything else, so basically this is just an expo app, with a default template (I have chosen the two-page type-script template), with an Amplify app, and one test function with default code. When I run the app now with Yarn on the ios simulator I get an error:

jest-haste-map: Haste module naming collision: lambdaTestFunction
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/amplify/#current-cloud-backend/function/lambdaTestFunction/src/package.json
    * <rootDir>/amplify/backend/function/lambdaTestFunction/src/package.json

Failed to construct transformer:  DuplicateError: Duplicated files or mocks. Please check the console for more info
    at setModule (/Users/ramin/Code/Playground/test-functions/node_modules/jest-haste-map/build/index.js:543:17)
    at workerReply (/Users/ramin/Code/Playground/test-functions/node_modules/jest-haste-map/build/index.js:614:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 27)
    at /Users/ramin/Code/Playground/test-functions/node_modules/jest-haste-map/build/index.js:426:22 {
  mockPath1: 'amplify/#current-cloud-backend/function/lambdaTestFunction/src/package.json',
  mockPath2: 'amplify/backend/function/lambdaTestFunction/src/package.json'
}

### Expected behavior

To run the default react-native expo app.

### Reproduction steps

1. expo init test-functions
2. cd test-functions
3.  yarn add -g @aws-amplify/cli
4. amplify configure
5. amplify init
6. amplify add function
7. amplify push

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line
// This is the code for the function

exports.handler = async (event) => {
    // TODO implement
    const response = {
        statusCode: 200,
    //  Uncomment below to enable CORS requests
    //  headers: {
    //      "Access-Control-Allow-Origin": "*",
    //      "Access-Control-Allow-Headers": "*"
    //  }, 
        body: JSON.stringify('Hello from Lambda!'),
    };
    return response;
};

```

</details>

### Mobile Device

iphone 13

### Mobile Operating System

ios 15

### Additional information and screenshots

I have already seen the solution in [here](https://stackoverflow.com/questions/60852276/amplify-react-native-duplicate-error-using-amplify-add-api) and the rest of the posts on Github. The solution is everywhere the same. I have tried to isolate this problem and my observation is that by adding the following code to the metro.config.js file for type-script expo app the issue is resolved, but it does not resolve the issue if the app is made with Javascript instead of typescript. 

```javascript
module.exports = {
  resolver: {
    blacklistRE: /#current-cloud-backend\/.*/,
  },
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
};
```
But I still don't feel good about it, since I am adding something extra to the code which is not on AWS Amplify's official website. Can you please tell me, what causes this problem? Is this the right way to handle this situation? If so, why it does not work with javascript? Are there any other better practices to solve it?

Thank you.

**Comment by chrisbonifacio** [comment]
Hi @zandvakiliramin 👋 this seems like it might be more related to the CLI if this behavior is being experienced on more than one framework. I'm going to transfer this over to the CLI repo for better support.
