### ISSUE TITLE
DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

### ISSUE THREAD

**Issue by laclance** [aws-amplify/amplify-js#9282]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

DataStore

### Amplify Categories

Not applicable

### Environment information

<details>

```
# Put output below this line
 System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 7.05 GB / 15.84 GB
  Binaries:
    Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.34)
  npmPackages:
    @aws-amplify/core: ^4.3.8 => 4.3.8
    @aws-amplify/datastore: ^3.7.0 => 3.7.0
    @babel/helper-call-delegate: ^7.12.1 => 7.12.13
    @capacitor-community/electron: ^4.0.3 => 4.0.3
    @capacitor/android: ^3.3.1 => 3.3.1
    @capacitor/app: ^1.0.5 => 1.0.6
    @capacitor/core: ^3.3.1 => 3.3.1
    @capacitor/device: ^1.0.5 => 1.0.6
    @material-ui/core: ^4.11.3 => 4.12.3
    @material-ui/icons: ^4.11.2 => 4.11.2
    @testing-library/jest-dom: ^5.11.9 => 5.15.0
    @testing-library/react: 12.1.2 => 12.1.2
    @testing-library/user-event: ^13.5.0 => 13.5.0
    @types/crypto-js: ^4.0.2 => 4.0.2
    @types/intl-tel-input: ^17.0.3 => 17.0.4
    @types/jest: ^27.0.2 => 27.0.2
    @types/node: 16.11.6 => 16.11.6
    @types/qrcode.react: ^1.0.1 => 1.0.2
    @types/react: ^17.0.30 => 17.0.34
    @types/react-dom: ^17.0.0 => 17.0.11
    @types/uuid: ^8.3.0 => 8.3.1
    @typescript-eslint/eslint-plugin: 5.3.0 => 5.3.0 (4.33.0)
    @typescript-eslint/parser: 5.3.0 => 5.3.0 (4.33.0)
    array-move: ^4.0.0 => 4.0.0
    clsx: ^1.1.1 => 1.1.1
    crypto-js: ^4.1.1 => 4.1.1
    eslint-plugin-prettier: ^4.0.0 => 4.0.0
    eslint-plugin-react: ^7.26.1 => 7.26.1
    eslint-plugin-react-hooks: ^4.2.0 => 4.2.0
    graphql: ^16.0.1 => 16.0.1 (14.5.0, 14.0.0)
    graphql-tag: ^2.12.6 => 2.12.6
    i18next: ^21.3.2 => 21.4.0
    intl-tel-input: ^17.0.13 => 17.0.13
    jwt-decode: ^3.1.2 => 3.1.2
    ksuid: ^3.0.0 => 3.0.0
    prettier: ^2.4.1 => 2.4.1
    qrcode.react: ^1.0.1 => 1.0.1
    react: ^17.0.1 => 17.0.2
    react-dnd: ^14.0.4 => 14.0.4
    react-dnd-html5-backend: ^14.0.2 => 14.0.2
    react-dom: ^17.0.1 => 17.0.2
    react-i18next: ^11.12.0 => 11.13.0
    react-indiana-drag-scroll: ^2.1.0 => 2.1.0
    react-loader-spinner: ^4.0.0 => 4.0.0
    react-scripts: 4.0.3 => 4.0.3
    react-simple-keyboard: ^3.3.7 => 3.3.26
    shelljs: ^0.8.4 => 0.8.4
    typescript: 4.4.4 => 4.4.4
    universal-cookie: ^4.0.4 => 4.0.4
  npmGlobalPackages:
    @aws-amplify/cli: 7.5.2
    cross-env: 7.0.3
    npm: 6.14.15
    yarn: 1.22.17

```

</details>

### Describe the bug

Trying to clear datastore after a mutation causes this error:
DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

### Expected behavior

Should be able to wait for mutations to complete before disconnecting.

### Reproduction steps

1. Make a mutation.
2. Clear datastore

### Code Snippet

```javascript
// Put your code below this line.

        //logout
        try {
          await DataStore.save(new DataTable(unsavedData));
          await DataStore.clear();
        } catch (e) {
          console.error('logout err', e);
        }
```

### Log output

<details>

```
// Put your logs below this line

[DEBUG] 46:14.36 Hub - Dispatching to datastore with  {event: 'outboxMutationEnqueued', data: {…}}
ConsoleLogger.ts:125 [DEBUG] 46:14.36 Hub - Dispatching to datastore with  {event: 'outboxMutationEnqueued', data: {…}}
ConsoleLogger.ts:125 [DEBUG] 46:14.36 Hub - Dispatching to datastore with  {event: 'outboxMutationEnqueued', data: {…}}
ConsoleLogger.ts:125 [DEBUG] 46:14.37 Hub - Dispatching to datastore with  {event: 'outboxMutationEnqueued', data: {…}}
ConsoleLogger.ts:125 [DEBUG] 46:14.37 Hub - Dispatching to datastore with  {event: 'outboxMutationEnqueued', data: {…}}
ConsoleLogger.ts:125 [DEBUG] 46:14.37 Hub - Dispatching to datastore with  {event: 'outboxStatus', data: {…}}
ConsoleLogger.ts:125 [DEBUG] 46:14.37 Hub - Dispatching to datastore with  {event: 'outboxStatus', data: {…}}
ConsoleLogger.ts:125 [DEBUG] 46:14.37 Hub - Dispatching to datastore with  {event: 'outboxStatus', data: {…}}
ConsoleLogger.ts:125 [DEBUG] 46:14.38 Hub - Dispatching to datastore with  {event: 'outboxStatus', data: {…}}
ConsoleLogger.ts:125 [DEBUG] 46:14.38 Hub - Dispatching to datastore with  {event: 'outboxStatus', data: {…}}
ConsoleLogger.ts:115 [DEBUG] 46:14.56 DataStore - Attempting mutation with authMode: API_KEY
ConsoleLogger.ts:115 [DEBUG] 46:14.56 Util -  attempt #1 with this vars: ["DataTable","Create","{\"test\":\"test\",\"id\":\"8ed1246f-6dfa-4b54-92d2-a3ae353d0d4a\"}","modelId":"8ed1246f-6dfa-4b54-92d2-a3ae353d0d4a","model":"DataTable","operation":"Create","condition":"{}","id":"01FNDT3TP0P2KJSKFTG7T43NWF"}]
ConsoleLogger.ts:125 [DEBUG] 46:14.58 RestClient - POST https://****.appsync-api.eu-west-1.amazonaws.com/graphql
ConsoleLogger.ts:125 [DEBUG] 46:14.96 Hub - Dispatching to datastore with  {event: 'outboxMutationEnqueued', data: {…}}
ConsoleLogger.ts:125 [DEBUG] 46:14.96 Hub - Dispatching to datastore with  {event: 'outboxMutationEnqueued', data: {…}}
ConsoleLogger.ts:125 [DEBUG] 46:14.96 Hub - Dispatching to datastore with  {event: 'outboxMutationEnqueued', data: {…}}
ConsoleLogger.ts:125 [DEBUG] 46:14.96 Hub - Dispatching to datastore with  {event: 'outboxMutationEnqueued', data: {…}}
ConsoleLogger.ts:125 [DEBUG] 46:14.97 Hub - Dispatching to datastore with  {event: 'outboxMutationEnqueued', data: {…}}
ConsoleLogger.ts:125 [DEBUG] 46:14.97 Hub - Dispatching to datastore with  {event: 'outboxStatus', data: {…}}
ConsoleLogger.ts:125 [DEBUG] 46:14.97 Hub - Dispatching to datastore with  {event: 'outboxStatus', data: {…}}
ConsoleLogger.ts:125 [DEBUG] 46:14.97 Hub - Dispatching to datastore with  {event: 'outboxStatus', data: {…}}
ConsoleLogger.ts:125 [DEBUG] 46:14.97 Hub - Dispatching to datastore with  {event: 'outboxStatus', data: {…}}
ConsoleLogger.ts:125 [DEBUG] 46:14.97 Hub - Dispatching to datastore with  {event: 'outboxStatus', data: {…}}
ConsoleLogger.ts:115 [DEBUG] 46:14.154 DataStore - Starting Storage

wrap-idb-value.js:150 Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Proxy.<anonymous> (http://localhost:3000/static/js/vendors~main.chunk.js:342317:22)
    at IndexedDBAdapter.<anonymous> (http://localhost:3000/static/js/vendors~main.chunk.js:38191:26)
    at step (http://localhost:3000/static/js/vendors~main.chunk.js:37730:17)
    at Object.next (http://localhost:3000/static/js/vendors~main.chunk.js:37661:14)
    at fulfilled (http://localhost:3000/static/js/vendors~main.chunk.js:37615:24)
```

</details>

### aws-exports.js

```javascript
const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-"
};
```

**Comment by chrisbonifacio** [comment]
Hi @laclance 👋 thanks for raising this issue. In our [documentation](), we recommend listening to the signout event from the Auth category to trigger a `DataStore.clear` call.

I think there might be a race condition happening between the graphql call datastore makes and the clear/signout operations but this should work.

ex.
```js
Hub.listen('auth', async (data) => {
  if (data.payload.event === 'signOut') {
    await DataStore.clear();
  }
});
```

**Comment by laclance** [comment]
ok thank you but how do I trigger the signOut event?

**Comment by chrisbonifacio** [comment]
Ohh okay. Well, in that case, maybe you could use the `API.graphql` method to create that record before DataStore gets cleared? I think the issue is mainly that you're trying to save a record to the local database, which DataStore will always do, the graphql queries happen separately apart from the DataStore operations. So, it might make more sense to make a call directly to the API so you don't have to worry about the DataStore websocket connection closing before the local record can be synced to the server.

something like this:

```js
//logout
try {
  await API.graphql({
    query: createRecord,
    variables: {
      ...unsavedData
    }
  });
  await DataStore.clear();
} catch (e) {
  console.error('logout err', e);
}
```

**Comment by laclance** [comment]
Ok yeah thank you that's probably the best idea.

**Comment by chrisbonifacio** [comment]
No problem 😄  Let me know if that works for you!

**Comment by laclance** [comment]
@chrisbonifacio is there a way to check a record has been synced to the cloud? Comparing the SubscriptionMessage when offline and online they seem to be identical?

**Comment by laclance** [comment]
The problem I'm having is similar to this one https://github.com/aws-amplify/amplify-js/issues/6488. If the internet goes down and I do a Datastore.save to the local db while still offline and then when the internet comes on again datastore does not sync right away and if a user wants to log out before the sync occurs I can't tell which items in the local db have been synced to the cloud or not.

**Comment by laclance** [comment]
> `graphql`

Also tried this and get some error.

**Comment by laclance** [comment]
Can also get the same error without trying to save right before clearing. If you do a datastore.save while offline then at any point in time clear the db and then at any point in time go online again you will get the error. So doesn't matter whether or not I try to save data before clearing will still get the error if I clear the db at any point in time while there are unsynced records.

**Comment by chrisbonifacio** [comment]
>is there a way to check a record has been synced to the cloud? Comparing the SubscriptionMessage when offline and online they seem to be identical?

As far as I know, there are two ways:

1. Using the Hub utility

```js
React.useEffect(() => {
  DataStore.start();

  const listener = async ({ payload }) => {
    const { event, data } = payload;

    switch (event) {
      case "ready":
        console.log("datastore ready");
        break;
      case "modelSynced":
        console.log("modelSynced", data.model.name);
        break;
      default:
        console.log("unknown event", event, data);
    }
  };

  Hub.listen("datastore", listener);

  return () => {
    Hub.remove("datastore", listener);
  };
}, []);
```

console logs

<img width="1438" alt="Screen Shot 2021-12-01 at 2 59 23 PM" src="https://user-images.githubusercontent.com/16952986/144304938-2eef2f78-5bed-49a8-991f-0cfea8becaf7.png">

2. Using `DataStore.observeQuery`

```js
  React.useEffect(() => {
    let sub;

    sub = DataStore.observeQuery(Profile).subscribe(({ items, isSynced }) => {
      console.log({ items, isSynced });
    });

    return () => {
      sub.unsubscribe();
    };
  }, []);
```

**Comment by chrisbonifacio** [comment]
Maybe I'm misunderstanding the use case here, but why are you clearing the local database if you are anticipating the user to perform operations offline? Do you expect multiple users to be logged into the same device? If the same user is signing in, it might be best to leave the data cached locally and only clear the database if a different user logs in.

https://docs.amplify.aws/lib/datastore/sync/q/platform/js/#clear-local-data

**Comment by laclance** [comment]
Thanks but those solutions don't tell me if data has synced to the cloud only locally because even when offline datastore says items are synced. Yes there are multiple users and their data needs to be private.

**Comment by laclance** [comment]
So whether online or offline this is what I get:
```
event: 'outboxMutationEnqueued'
event: 'outboxStatus', 
{items: Array(687), isSynced: true}
```

If offline then will get event: 'modelSynced' when I come online again which is great because I can check if 'outboxMutationEnqueued' fires then wait for 'modelSynced' to check if data has been synced but if online then 'modelSynced' events only fires when I refresh the page.

**Comment by laclance** [comment]
That I can manage though but main issue is still if app is online I want to clear datastore but save unsynced data before doing so but I get the 'Failed to execute' error.

**Comment by chrisbonifacio** [comment]
@laclance ah okay, I see what you mean. Hmm, I'm not really sure if there's a reliable way to make sure records are synced to the server before clearing.

Personally, I wouldn't clear the local database unless a different user logs into the same device to try to avoid the edge case of a user logging out while offline causing records to be lost before synced. But, I may just be missing some experience on how to properly handle this.

I'm going to reach out to the DataStore team to see if I can get some feedback for you on what might be the best way to approach this.

**Comment by laclance** [comment]
Ok cool thanks so much, the only problem with not clearing is that other users can see the data in the indexdb via browser dev tools.

**Comment by chrisbonifacio** [comment]
No problem! As a quite note, the team has pointed out that the event for when a local change has been synced to the cloud would be `outboxMutationProcessed`, rather than the enqueued changes.

Still in talks about this with the team. Thank you for bearing with me in the meantime!

**Comment by laclance** [comment]
No problem thanks, yes I did see that but it's the same problem as the 'modelSynced' event, the events don't always get fired if you do not have a stable internet connection.

**Comment by laclance** [comment]
All of a sudden getting this error and can't get rid of it. 
```index.ts:594 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'lastFullSync')```

**Comment by laclance** [comment]
@chrisbonifacio deleted amplify project and recreated from scratch but still the the same error, not sure if I should maybe open a new issue?
```
[DEBUG] 30:28.849 Util -  attempt #1 with this vars: ["query operation($limit: Int, $nextToken: String, $lastSync: AWSTimestamp, $filter: ModelPOSFilterInput){\n\t\tsyncPOS(limit: $limit, nextToken: $nextToken, lastSync: $lastSync, filter: $filter){\n\t\t\titems {\n\t\t\t\t\t\t\tid\npk\nsk\nentityType\ncurrentState\ndata\ngsi1Pk\ngsi1Sk\ncreatedAt\nupdatedAt\n_version\n_lastChangedAt\n_deleted\n\t\t\t\t\t\t}\n\t\t\t\t\t\tnextToken\n\t\t\t\t\t\tstartedAt\n\t\t}\n\t}",{"limit":1000,"nextToken":"***==","lastSync":0,"filter":null}]
ConsoleLogger.ts:125 [DEBUG] 30:28.850 RestClient - POST https://***.appsync-api.eu-west-1.amazonaws.com/graphql
ConsoleLogger.ts:115 [DEBUG] 30:31.434 DataStore - Sync successful with authMode: API_KEY
index.ts:594 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'lastFullSync')
    at SyncEngine.<anonymous> (index.ts:594)
    at step (index.ts:3)
    at Object.next (index.ts:3)
    at fulfilled (index.ts:3)
    ```

**Comment by laclance** [comment]
Re-created the project again with a different table name and created a fresh frontend app with only `Amplify.configure(aws_exports);` and `DataStore.start()` and get these 2 errors:

```
Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'namespaces')
IndexedDBAdapter.<anonymous>
C:/Users/src/storage/adapter/IndexedDBAdapter.ts:115
  112 | };
  113 | IndexedDBAdapter.prototype.getStorename = function (namespace, modelName) {
  114 |     var storeName = namespace + "_" + modelName;
> 115 |     return storeName;
      | ^  116 | };
  117 | IndexedDBAdapter.prototype.setUp = function (theSchema, namespaceResolver, modelInstanceCreator, getModelConstructorByModelName, sessionId) {
  118 |     return __awaiter(this, void 0, void 0, function () {
  ```
  
  ```
  Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'version')
DataStore.<anonymous>
C:/Users/Lance/src/datastore/datastore.ts:742
  739 | };
  740 | this.delete = function (modelOrConstructor, idOrCriteria) { return __awaiter(_this, void 0, void 0, function () {
  741 |     var condition, msg, modelConstructor, msg, msg, _a, deleted, model, modelConstructor, msg, modelDefinition, idPredicate, msg, _b, _c, deleted;
> 742 |     return __generator(this, function (_d) {
      | ^  743 |         switch (_d.label) {
  744 |             case 0: return [4 /*yield*/, this.start()];
  745 |             case 1:
  ```

**Comment by chrisbonifacio** [comment]
Hey @laclance 👋 apologies for the delay. The errors you're seeing suggest to me that your models might be missing the mentioned fields on their definitions so DataStore is unable to read them on the records. Can you check the `models/schema` file and make sure those fields are being generated after running `amplify codegen models`?

Maybe you don't have DataStore enabled for the project? You can check by running `amplify update api`

**Comment by chrisbonifacio** [comment]
looking into similar issues in the past, these errors seem to be caused by a few things.

1. Make sure DataStore is enabled for the project, of course
2. Remove any unnecessary amplify packages (I see you might have both `@aws-amplify/core` and `@aws-amplify/datastore`. You can either try only installing `aws-amplify` which you can still use the scoped packages with or removing `@aws-amplify/core` because its already listed as a dependency of the scoped datastore package.
3. Replace `DataStore.start()` with `DataStore.query()`

**Comment by laclance** [comment]
Thank you, looks like replacing dataStore.start() with DataStore.query() works, I thought the first query() called start() anyway.

**Comment by laclance** [comment]
Also have to use the aws-amplify package now, but we were using datastore fine for almost a year with @aws-amplify/core and @aws-amplify/datastore.

**Comment by laclance** [comment]
Still get the same error anytime when I start using Datastore more after the first DataStore.query().

**Comment by laclance** [comment]
Ok now it seems to only throw errors on start and clear.

`DataStore.start()` gives `Cannot read properties of undefined (reading 'lastFullSync')` but we can use `query` instead.

`DataStore.clear()` still gives `DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.` and we do want to be able to clear the db to not allow users to view other users' private information via browser dev tools.

Also using the aws-amplify package, types are not inferred which is quite annoying also can't do things like jump to the definition.

**Comment by chrisbonifacio** [comment]
Yeah, we're still working to improve TypeScript support in our library.

I was thinking about the issue you're having with clearing the database and have some thoughts I'd like to run by you because with most of the syncing process being automated and requiring an active network connection, data loss is difficult to avoid if a user were to sign out and, as a result, clear the database while offline before records have a chance to sync.

I think the documentation's recommendation of real world usage being to clear the local db if a different user logs in makes more sense than simply clearing the db on signOut.

Definitely don't want to try to save a record before the database is cleared because, as mentioned before, the time it takes between a `save` and a `clear` won't be enough to ensure the record was synced through the outbox process anyway. This will probably always result in the `Failed to execute 'transaction' on 'IDBDatabase' error.

So, I was wondering if maybe there is some room for letting the data exist in the local store at least until the network status comes back online. There is also a `networkStatus` event from the `Hub`'s datastore listener that could maybe be used to check if the user is online and only clear the database if they are logged out with an active connection?

**Comment by laclance** [comment]
Okay, thank you. Yes but as mentioned we don't want to to allow users to view other users' private information via the dev tools. The `networkStatus` still returns true if there is a network but no internet connection. So I'm using `outboxStatus` and `outboxMutationProcessed` to check if everything has synced then running clear() after a small delay. If data doesn't get synced after a certain amount of time then I encrypt it and store it locally. Using the hub events was causing a bit of a problem with an unstable internet connection but due to the other errors we haven't had a chance to fully test it yet.

**Comment by chrisbonifacio** [comment]
Okay yeah that makes sense and aligns with what the team has explained to me about what is probably the best way to handle this scenario (using the outbox status and mutationProcessed events).

Because the original issue is not a bug and intended behavior I'd close this issue but I believe this is worth a more in depth discussion so we can move it to discussions instead to keep this open for feedback.

**Comment by laclance** [comment]
Not quite the original issue but I feel like it shouldn't be the intended behavior. As I mentioned, the outboxStatus and mutationProcessed events often don't work without a stable internet connection, same goes for subscriptions. Also if a user logs out and the internet goes off for a second and datastore stops and mutations don't get processed you going to see the same error when a user logs in and `DataStore.clear()` is called. Is one purpose of datastore not suppose to be the aid in offline/online data synchronization?

**Comment by laclance** [comment]
Just got the same error now after running `DataStore.clear()` and I've had a stable internet connection and havn't done a mutation.
