### ISSUE TITLE
getting DOMException: Failed to execute 'get' on 'IDBIndex': No key or key range specified when deleting item in datastore

### ISSUE THREAD

**Issue by sergiorodriguez82** [aws-amplify/amplify-js#9285]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

DataStore

### Amplify Categories

storage

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 11.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 21.28 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 7.6.3 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Firefox: 88.0
    Safari: 15.0
  npmPackages:
    @angular-devkit/build-angular: ~0.1102.4 => 0.1102.15 
    @angular-eslint/builder: 2.0.2 => 2.0.2 
    @angular-eslint/eslint-plugin: 2.0.2 => 2.0.2 
    @angular-eslint/eslint-plugin-template: 2.0.2 => 2.0.2 
    @angular-eslint/template-parser: 2.0.2 => 2.0.2 
    @angular/cli: ~11.2.4 => 11.2.15 
    @angular/common: ~11.2.0 => 11.2.14 
    @angular/common/http:  undefined ()
    @angular/common/http/testing:  undefined ()
    @angular/common/testing:  undefined ()
    @angular/common/upgrade:  undefined ()
    @angular/compiler: ~11.2.0 => 11.2.14 
    @angular/compiler-cli: ~11.2.0 => 11.2.14 
    @angular/compiler/testing:  undefined ()
    @angular/core: ~11.2.0 => 11.2.14 
    @angular/core/testing:  undefined ()
    @angular/forms: ~11.2.0 => 11.2.14 
    @angular/language-service: ~11.2.0 => 11.2.14 
    @angular/platform-browser: ~11.2.0 => 11.2.14 
    @angular/platform-browser-dynamic: ~11.2.0 => 11.2.14 
    @angular/platform-browser-dynamic/testing:  undefined ()
    @angular/platform-browser/animations:  undefined ()
    @angular/platform-browser/testing:  undefined ()
    @angular/router: ~11.2.0 => 11.2.14 
    @angular/router/testing:  undefined ()
    @angular/router/upgrade:  undefined ()
    @angular/service-worker: ~11.2.0 => 11.2.14 
    @angular/service-worker/config:  undefined ()
    @aws-amplify/datastore: ^3.5.1 => 3.5.1 
    @aws-amplify/ui-angular: ^1.0.8 => 1.0.31 
    @capacitor-community/http: ^1.1.0 => 1.3.0 
    @capacitor/android: 3.3.1 => 3.3.1 
    @capacitor/camera: ^1.0.3 => 1.2.0 
    @capacitor/cli: ^3.2.3 => 3.3.1 
    @capacitor/core: ^3.2.3 => 3.3.1 (3.0.0)
    @capacitor/device: ^1.0.2 => 1.0.6 
    @capacitor/geolocation: ^1.0.2 => 1.1.3 
    @capacitor/network: ^1.0.2 => 1.0.6 
    @capacitor/storage: ^1.0.3 => 1.2.3 
    @ionic-native/core: ^4.20.0 => 4.20.0 
    @ionic/angular: ^5.5.2 => 5.8.5 
    @ionic/angular-toolkit: ^3.1.1 => 3.1.1 
    @ionic/prettier-config: ^2.0.0 => 2.0.0 
    @ionic/pwa-elements: ^3.0.2 => 3.0.2 
    @ngx-formly/core: ^5.0.0 => 5.10.23 
    @ngx-formly/core/json-schema:  undefined ()
    @ngx-formly/core/select:  undefined ()
    @ngx-formly/ionic: ^5.0.0 => 5.10.23 
    @ngx-formly/schematics: ^5.10.22 => 5.10.23 
    @ngx-translate/core: ^13.0.0 => 13.0.0 
    @ngx-translate/http-loader: ^6.0.0 => 6.0.0 
    @types/jasmine: ~3.6.0 => 3.6.11 
    @types/jasminewd2: ~2.0.3 => 2.0.10 
    @types/node: ^15.6.1 => 15.14.9 
    @typescript-eslint/eslint-plugin: 4.16.1 => 4.16.1 
    @typescript-eslint/parser: 4.16.1 => 4.16.1 
    aws-amplify: ^4.0.0 => 4.3.4 
    aws-amplify-angular: ^5.0.57 => 5.0.60 
    capacitor-native-biometric: ^3.0.3 => 3.0.3 
    eslint: ^7.26.0 => 7.32.0 
    eslint-config-prettier: ^8.3.0 => 8.3.0 
    eslint-plugin-import: 2.22.1 => 2.22.1 
    eslint-plugin-jsdoc: 30.7.6 => 30.7.6 
    eslint-plugin-prefer-arrow: 1.2.2 => 1.2.2 
    eslint-plugin-prettier: ^3.4.1 => 3.4.1 
    example-typescript:  1.0.0 
    graphql: ^15.5.0 => 15.7.2 (14.5.0, 14.0.0)
    ionicpwaelements-loader:  undefined ()
    jasmine-core: ~3.6.0 => 3.6.0 (2.8.0)
    jasmine-spec-reporter: ~5.0.0 => 5.0.2 
    karma: ~5.2.0 => 5.2.3 
    karma-chrome-launcher: ~3.1.0 => 3.1.0 
    karma-coverage: ~2.0.3 => 2.0.3 
    karma-coverage-coffee-example:  1.0.0 
    karma-coverage-istanbul-reporter: ~3.0.2 => 3.0.3 
    karma-jasmine: ~4.0.0 => 4.0.1 
    karma-jasmine-html-reporter: ^1.5.0 => 1.7.0 
    lib:  0.0.1 
    memo-parser:  0.2.1 
    moment: ^2.29.1 => 2.29.1 
    moment-timezone: ^0.5.33 => 0.5.33 
    node-example:  1.0.0 
    prettier: 2.4.1 => 2.4.1 
    protractor: ~7.0.0 => 7.0.0 
    protractor-example:  1.0.0 
    rxjs: ~6.6.0 => 6.6.7 (6.6.3)
    rxjs/ajax:  undefined ()
    rxjs/fetch:  undefined ()
    rxjs/internal-compatibility:  undefined ()
    rxjs/operators:  undefined ()
    rxjs/testing:  undefined ()
    rxjs/webSocket:  undefined ()
    ts-node: ~8.3.0 => 8.3.0 
    tslib: ^2.0.0 => 2.3.1 (1.14.1, 2.1.0)
    typescript: ~4.0.2 => 4.0.8 (4.1.5)
    typescript-example:  1.0.0 
    zone.js: ~0.10.2 => 0.10.3 
  npmGlobalPackages:
    @angular/cli: 12.2.11
    @apollo/client: 3.3.20
    @aws-amplify/cli: 7.4.5
    @ionic/cli: 6.18.0
    amplify: 0.0.11
    angular: 1.8.2
    apollo: 2.33.4
    graphql: 15.5.1
    husky: 6.0.0
    npm-check-updates: 8.1.0
    npm: 7.6.3
    webpack-bundle-analyzer: 4.4.0

```

</details>

### Describe the bug

We are using datastore for a Ionic/Angular app. 
We are getting DOMException: Failed to execute 'get' on 'IDBIndex': No key or key range specified error when deleting and element.

`
  deleteSymptomInstance(symptomInstance: SymptomInstance) {    
    return DataStore.delete(symptomInstance);
  }
`

![image](https://user-images.githubusercontent.com/38695777/143661264-096ed61b-f4b1-4f7d-a7a8-ef7443a57079.png)

The rare part, is that elements that are created on the same page, and have less information the datastore delets them
![image](https://user-images.githubusercontent.com/38695777/143661892-a940a09a-ebcb-41d4-8082-109e2d4aafca.png)
This item is delete ok.

### Expected behavior

Transaction should delete item in the local storage

### Reproduction steps

1. create an amplify app
2. add datastore
3. create item
4. query item
5. delete item 

### Code Snippet

```javascript
// Put your code below this line.

  deleteSymptomInstance(symptomInstance: SymptomInstance) {    
    return DataStore.delete(symptomInstance);
  }
```

### Log output

<details>

```
// Put your logs below this line

DEBUG] 44:34.787 ReportOtherSymptoms - deleting Model {id: '4be1f01f-ba13-4b78-885d-1faa7fbe1f15', subjectId: '3048f1b1-800a-4aab-bc33-f2fa9fe84265', reportInstanceId: null, dayInstanceId: null, confSymptomId: null, …}
ConsoleLogger.js:139 [ERROR] 44:34.801 ReportOtherSymptoms - deleteSymptomInstance DOMException: Failed to execute 'get' on 'IDBIndex': No key or key range specified.
    at Proxy.<anonymous> (http://localhost:8100/vendor.js:255639:26)
    at IndexedDBAdapter.<anonymous> (http://localhost:8100/vendor.js:241767:34)
    at step (http://localhost:8100/vendor.js:240869:23)
    at Object.next (http://localhost:8100/vendor.js:240850:53)
    at fulfilled (http://localhost:8100/vendor.js:240841:58)
    at ZoneDelegate.invoke (http://localhost:8100/polyfills.js:3017:30)
    at Object.onInvoke (http://localhost:8100/vendor.js:289071:33)
    at ZoneDelegate.invoke (http://localhost:8100/polyfills.js:3016:36)
    at Zone.run (http://localhost:8100/polyfills.js:2776:47)
    at http://localhost:8100/polyfills.js:3510:40
```

</details>

**Comment by iartemiev** [comment]
It looks like you've got both `aws-amplify` and `@aws-amplify/datastore` packages installed. This can cause unexpected behavior. 

Please do the following and let us know if you're still experiencing this issue:
```
npm uninstall @aws-amplify/datastore
rm -rf node_modules package-lock.json yarn.lock
npm i
```

**Comment by sergiorodriguez82** [comment]
Great that works!
