### ISSUE TITLE
Console warning messages being written when testing

### ISSUE THREAD

**Issue by sjrumsby** [aws-amplify/amplify-js#9342]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
amplify-log-warning % npx envinfo --system --binaries --browsers --npmPackages --duplicates --npmGlobalPackages
npx: installed 1 in 1.425s

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 279.29 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
    Watchman: 2021.11.15.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 96.0.4664.93
    Firefox: 94.0.2
    Safari: 15.1
  npmPackages:
    @aws-amplify/ui-react: ^2.1.4 => 2.1.4
    @aws-amplify/ui-react-internal:  undefined ()
    @aws-amplify/ui-react-legacy:  undefined ()
    @testing-library/jest-dom: ^5.11.4 => 5.16.1
    @testing-library/react: ^11.1.0 => 11.2.7
    @testing-library/user-event: ^12.1.10 => 12.8.3
    aws-amplify: ^4.3.10 => 4.3.10
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    react-scripts: 4.0.3 => 4.0.3
    web-vitals: ^1.0.1 => 1.1.2
  npmGlobalPackages:
    aws-cdk: 1.134.0
    cdk-assume-role-credential-plugin: 1.4.0
    npm: 6.14.15

```

</details>

### Describe the bug

When a test case mounts the component that is authenticated, the following messages are put into the console:

```
  console.warn
    Warning: No implementation found for action type 'clearFormValues'

      at Object.<anonymous>.exports.warn (node_modules/xstate/lib/utils.js:409:20)
      at Interpreter.exec (node_modules/xstate/lib/interpreter.js:893:17)
      at node_modules/xstate/lib/interpreter.js:571:17
          at Array.forEach (<anonymous>)
      at Interpreter.stop (node_modules/xstate/lib/interpreter.js:564:30)
      at Interpreter.stopChild (node_modules/xstate/lib/interpreter.js:922:13)
      at Interpreter.exec (node_modules/xstate/lib/interpreter.js:875:16)

  console.warn
    Warning: No implementation found for action type 'clearTouched'

      at Object.<anonymous>.exports.warn (node_modules/xstate/lib/utils.js:409:20)
      at Interpreter.exec (node_modules/xstate/lib/interpreter.js:893:17)
      at node_modules/xstate/lib/interpreter.js:571:17
          at Array.forEach (<anonymous>)
      at Interpreter.stop (node_modules/xstate/lib/interpreter.js:564:30)
      at Interpreter.stopChild (node_modules/xstate/lib/interpreter.js:922:13)
      at Interpreter.exec (node_modules/xstate/lib/interpreter.js:875:16)
```

### Expected behavior

These messages are not output to the console.

### Reproduction steps

I have created a simple git repository that shows this issue, you can reproduce it like so:

```
src % git clone git@github.com:sjrumsby/amplify-log-warning.git
src % cd amplify-log-warning
amplify-log-warning % yarn
amplify-log-warning % yarn test
```

However, you should also be able to reproduce it with

### Code Snippet

```javascript
// Put your code below this line.
// App.js
import { Amplify } from 'aws-amplify';
import { withAuthenticator } from '@aws-amplify/ui-react';
import logo from './logo.svg';
import './App.css';


Amplify.configure({
  Auth: {
    region: 'us-east-1',
    userPoolId: 'us-east-1_userPool1',
    userPoolWebClientId: 'client-id'
  }
});

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default withAuthenticator(App);

// App.test.js
import { render, screen, waitFor } from '@testing-library/react';
import App from './App';

test('renders learn react link', async () => {
  render(<App />);
  await waitFor(() => {
    const signInElement = screen.queryByText(/Create Account/i);
    expect(signInElement).toBeInTheDocument();
  })

});


```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Manual configuration

```json
Amplify.configure({
  Auth: {
    region: 'us-east-1',
    userPoolId: 'us-east-1_userPool1',
    userPoolWebClientId: 'client-id'
  }
});
```

**Comment by chrisbonifacio** [comment]
Hi @sjrumsby 👋 thanks for raising this issue! It seems to be more related to the UI components than the JS libraries, so I'm going to transfer this issue over to the Amplify UI team's repo for better support.
