### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by rupam-kundu** [aws-amplify/amplify-js#9866]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Not applicable

### Amplify Categories

hosting

### Environment information

<details>

```
# Put output below this line

System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz    
    Memory: 688.77 MB / 3.87 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.32)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @aws-amplify/ui-react: ^2.15.8 => 2.15.8 
    @aws-amplify/ui-react-internal:  undefined ()
    @aws-amplify/ui-react-legacy:  undefined ()
    @testing-library/jest-dom: ^5.16.4 => 5.16.4 
    @testing-library/react: ^13.1.1 => 13.1.1 
    @testing-library/user-event: ^13.5.0 => 13.5.0 
    aws-amplify: ^4.3.20 => 4.3.20 
    react: ^18.1.0 => 18.1.0 (17.0.2)
    react-dom: ^18.1.0 => 18.1.0 
    react-scripts: 5.0.1 => 5.0.1 
    web-vitals: ^2.1.4 => 2.1.4 
  npmGlobalPackages:
    @aws-amplify/cli: 8.1.0

```

</details>

### Describe the bug

When trying to deploy latest changes to my React app on AWS, build is failing. My app is running successfully locally. On examining the attached log file the root cause of the error appears to be the following.

`
Module not found: Error: Can't resolve 'mapbox-gl' in '/codebuild/output/src783874373/src/globalnextgentech-website/node_modules/react-map-gl/dist/esm/components'
`

### Expected behavior

The build should run successfully.

### Reproduction steps

1. Connect a Git repository to the app on AWS management console.
2. Enable continuous deployment.
3. Push code to the Git repository.
4. Build error occurs.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line

2022-05-03T15:13:12.727Z [INFO]: # Cloning repository: git@github.com:rupam-kundu/globalnextgentech-website.git
2022-05-03T15:13:13.080Z [INFO]: Cloning into 'globalnextgentech-website'...
2022-05-03T15:13:14.867Z [INFO]: # Switching to commit: 18cf5a2919a74278879a1e72dc9b6ed0ce11b7ea
2022-05-03T15:13:14.882Z [INFO]: Note: switching to '18cf5a2919a74278879a1e72dc9b6ed0ce11b7ea'.
                                 You are in 'detached HEAD' state. You can look around, make experimental
                                 changes and commit them, and you can discard any commits you make in this
                                 state without impacting any branches by switching back to a branch.
                                 If you want to create a new branch to retain commits you create, you may
                                 do so (now or later) by using -c with the switch command. Example:
                                 git switch -c <new-branch-name>
                                 Or undo this operation with:
                                 git switch -
                                 Turn off this advice by setting config variable advice.detachedHead to false
                                 HEAD is now at 18cf5a2 Pulled in components from the cloud.
2022-05-03T15:13:14.907Z [INFO]: Successfully cleaned up Git credentials
2022-05-03T15:13:14.907Z [INFO]: # Checking for Git submodules at: /codebuild/output/src783874373/src/globalnextgentech-website/.gitmodules
2022-05-03T15:13:14.936Z [INFO]: # Retrieving environment cache...
2022-05-03T15:13:15.036Z [INFO]: # Retrieved environment cache
2022-05-03T15:13:15.036Z [INFO]: ---- Setting Up SSM Secrets ----
2022-05-03T15:13:15.036Z [INFO]: SSM params {"Path":"/amplify/d10nw5r62oxier/dev/","WithDecryption":true}
2022-05-03T15:13:19.873Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 7.6.14 to 8.1.0...
2022-05-03T15:14:28.150Z [INFO]: # Done patching NPM package '@aws-amplify/cli' to version 8.1.0
2022-05-03T15:14:28.249Z [INFO]: # Retrieving cache...
2022-05-03T15:14:33.119Z [INFO]: # Extracting cache...
2022-05-03T15:14:39.939Z [INFO]: # Extraction completed
2022-05-03T15:14:43.653Z [INFO]: ## Starting Backend Build
                                 # Starting phase: build
2022-05-03T15:14:45.826Z [INFO]: [0mAmplify AppID found: d10nw5r62oxier. Amplify App name is: website[0m
2022-05-03T15:14:45.875Z [INFO]: [0mBackend environment dev found in Amplify Console app: website[0m
2022-05-03T15:14:46.394Z [WARNING]: - Fetching updates to backend environment: dev from the cloud.
2022-05-03T15:14:46.802Z [WARNING]: ✔ Successfully pulled backend environment dev from the cloud.
2022-05-03T15:14:46.804Z [INFO]: ✅
2022-05-03T15:14:48.642Z [INFO]: [33mNote: It is recommended to run this command from the root of your app directory[39m
2022-05-03T15:14:49.414Z [WARNING]: - Initializing your environment: dev
2022-05-03T15:14:49.893Z [WARNING]: ✔ Initialized provider successfully.
2022-05-03T15:14:49.929Z [WARNING]: - Updating resources in the cloud. This may take a few minutes...
2022-05-03T15:14:50.801Z [INFO]: ✅ Initialized your environment successfully.
2022-05-03T15:14:50.802Z [INFO]: [32mYour project has been successfully initialized and connected to the cloud![39m
                                 [32mSome next steps:[39m
                                 [0m"amplify status" will show you what you've added already and if it's locally configured or deployed[0m
                                 [0m"amplify add <category>" will allow you to add features like user login or a backend API[0m
                                 [0m"amplify push" will build all your local backend resources and provision it in the cloud[0m
                                 [0m"amplify console" to open the Amplify Console and view your project status[0m
                                 [0m"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud[0m
                                 [32mPro tip:[39m
                                 [0mTry "amplify add api" to create a backend API and then "amplify push" to deploy everything[0m
2022-05-03T15:14:53.199Z [INFO]: # Completed phase: build
                                 ## Completed Backend Build
2022-05-03T15:14:53.202Z [INFO]: ## Starting Frontend Build
2022-05-03T15:14:53.203Z [INFO]: # Starting phase: preBuild
                                 # Executing command: npm install
2022-05-03T15:14:55.823Z [WARNING]: npm
2022-05-03T15:14:55.823Z [WARNING]: WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
2022-05-03T15:15:04.890Z [WARNING]: npm WARN @radix-ui/react-accordion@0.1.6 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:04.900Z [WARNING]: npm
2022-05-03T15:15:04.900Z [WARNING]: WARN @radix-ui/react-collapsible@0.1.6 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:04.910Z [WARNING]: npm
2022-05-03T15:15:04.911Z [WARNING]: WARN @radix-ui/react-use-layout-effect@0.1.0 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:04.916Z [WARNING]: npm
2022-05-03T15:15:04.916Z [WARNING]: WARN @radix-ui/react-collection@0.1.4 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:04.928Z [WARNING]: npm
2022-05-03T15:15:04.928Z [WARNING]: WARN @radix-ui/react-slot@0.1.2 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:04.933Z [WARNING]: npm
2022-05-03T15:15:04.934Z [WARNING]: WARN @radix-ui/react-compose-refs@0.1.0 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:04.939Z [WARNING]: npm
2022-05-03T15:15:04.940Z [WARNING]: WARN @radix-ui/react-context@0.1.1 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:04.945Z [WARNING]: npm
2022-05-03T15:15:04.945Z [WARNING]: WARN @radix-ui/react-id@0.1.5 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:04.951Z [WARNING]: npm
2022-05-03T15:15:04.951Z [WARNING]: WARN @radix-ui/react-use-layout-effect@0.1.0 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:04.957Z [WARNING]: npm
2022-05-03T15:15:04.957Z [WARNING]: WARN @radix-ui/react-primitive@0.1.4 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:04.963Z [WARNING]: npm
2022-05-03T15:15:04.963Z [WARNING]: WARN @radix-ui/react-slot@0.1.2 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:04.969Z [WARNING]: npm
2022-05-03T15:15:04.969Z [WARNING]: WARN @radix-ui/react-use-controllable-state@0.1.0 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:04.975Z [WARNING]: npm
2022-05-03T15:15:04.975Z [WARNING]: WARN @radix-ui/react-use-callback-ref@0.1.0 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:04.981Z [WARNING]: npm
2022-05-03T15:15:04.981Z [WARNING]: WARN @radix-ui/react-dropdown-menu@0.1.6 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:04.988Z [WARNING]: npm
2022-05-03T15:15:04.988Z [WARNING]: WARN @radix-ui/react-dropdown-menu@0.1.6 requires a peer of react-dom@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:04.994Z [WARNING]: npm
2022-05-03T15:15:04.994Z [WARNING]: WARN @radix-ui/react-compose-refs@0.1.0 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:04.999Z [WARNING]: npm
2022-05-03T15:15:05.000Z [WARNING]: WARN @radix-ui/react-context@0.1.1 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.005Z [WARNING]: npm
2022-05-03T15:15:05.006Z [WARNING]: WARN @radix-ui/react-id@0.1.5 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.012Z [WARNING]: npm
2022-05-03T15:15:05.012Z [WARNING]: WARN @radix-ui/react-use-layout-effect@0.1.0 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.018Z [WARNING]: npm
2022-05-03T15:15:05.019Z [WARNING]: WARN @radix-ui/react-menu@0.1.6 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.025Z [WARNING]: npm
2022-05-03T15:15:05.025Z [WARNING]: WARN @radix-ui/react-menu@0.1.6 requires a peer of react-dom@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.031Z [WARNING]: npm
2022-05-03T15:15:05.031Z [WARNING]: WARN @radix-ui/react-collection@0.1.4 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.038Z [WARNING]: npm WARN
2022-05-03T15:15:05.038Z [WARNING]: @radix-ui/react-slot@0.1.2 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.044Z [WARNING]: npm
2022-05-03T15:15:05.044Z [WARNING]: WARN @radix-ui/react-dismissable-layer@0.1.5 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.051Z [WARNING]: npm
2022-05-03T15:15:05.051Z [WARNING]: WARN @radix-ui/react-use-body-pointer-events@0.1.1 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.057Z [WARNING]: npm
2022-05-03T15:15:05.057Z [WARNING]: WARN @radix-ui/react-use-layout-effect@0.1.0 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.063Z [WARNING]: npm
2022-05-03T15:15:05.063Z [WARNING]: WARN @radix-ui/react-use-escape-keydown@0.1.0 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.069Z [WARNING]: npm
2022-05-03T15:15:05.069Z [WARNING]: WARN @radix-ui/react-focus-guards@0.1.0 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.075Z [WARNING]: npm
2022-05-03T15:15:05.075Z [WARNING]: WARN @radix-ui/react-focus-scope@0.1.4 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.081Z [WARNING]: npm
2022-05-03T15:15:05.081Z [WARNING]: WARN @radix-ui/react-popper@0.1.4 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.087Z [WARNING]: npm
2022-05-03T15:15:05.087Z [WARNING]: WARN @radix-ui/react-arrow@0.1.4 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.094Z [WARNING]: npm WARN
2022-05-03T15:15:05.094Z [WARNING]: @radix-ui/react-use-rect@0.1.1 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.100Z [WARNING]: npm
2022-05-03T15:15:05.100Z [WARNING]: WARN @radix-ui/react-use-size@0.1.1 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.106Z [WARNING]: npm WARN
2022-05-03T15:15:05.106Z [WARNING]: @radix-ui/react-portal@0.1.4 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.113Z [WARNING]: npm WARN
2022-05-03T15:15:05.113Z [WARNING]: @radix-ui/react-portal@0.1.4 requires a peer of react-dom@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.119Z [WARNING]: npm
2022-05-03T15:15:05.119Z [WARNING]: WARN @radix-ui/react-use-layout-effect@0.1.0 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.125Z [WARNING]: npm WARN
2022-05-03T15:15:05.125Z [WARNING]: @radix-ui/react-roving-focus@0.1.5 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.131Z [WARNING]: npm
2022-05-03T15:15:05.131Z [WARNING]: WARN @radix-ui/react-use-callback-ref@0.1.0 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.137Z [WARNING]: npm
2022-05-03T15:15:05.138Z [WARNING]: WARN @radix-ui/react-use-direction@0.1.0 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.143Z [WARNING]: npm
2022-05-03T15:15:05.144Z [WARNING]: WARN @radix-ui/react-primitive@0.1.4 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.150Z [WARNING]: npm
2022-05-03T15:15:05.150Z [WARNING]: WARN @radix-ui/react-slot@0.1.2 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.156Z [WARNING]: npm
2022-05-03T15:15:05.156Z [WARNING]: WARN @radix-ui/react-use-controllable-state@0.1.0 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.162Z [WARNING]: npm
2022-05-03T15:15:05.162Z [WARNING]: WARN @radix-ui/react-use-callback-ref@0.1.0 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.168Z [WARNING]: npm
2022-05-03T15:15:05.168Z [WARNING]: WARN @radix-ui/react-slider@0.1.4 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.175Z [WARNING]: npm
2022-05-03T15:15:05.175Z [WARNING]: WARN @radix-ui/react-collection@0.1.4 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.182Z [WARNING]: npm
2022-05-03T15:15:05.182Z [WARNING]: WARN @radix-ui/react-slot@0.1.2 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.188Z [WARNING]: npm
2022-05-03T15:15:05.188Z [WARNING]: WARN @radix-ui/react-compose-refs@0.1.0 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.194Z [WARNING]: npm WARN @radix-ui/react-context@0.1.1 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.200Z [WARNING]: npm
2022-05-03T15:15:05.201Z [WARNING]: WARN @radix-ui/react-primitive@0.1.4 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.206Z [WARNING]: npm
2022-05-03T15:15:05.207Z [WARNING]: WARN @radix-ui/react-slot@0.1.2 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.213Z [WARNING]: npm
2022-05-03T15:15:05.213Z [WARNING]: WARN @radix-ui/react-use-controllable-state@0.1.0 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.219Z [WARNING]: npm
2022-05-03T15:15:05.219Z [WARNING]: WARN @radix-ui/react-use-callback-ref@0.1.0 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.225Z [WARNING]: npm
2022-05-03T15:15:05.225Z [WARNING]: WARN @radix-ui/react-use-direction@0.1.0 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.231Z [WARNING]: npm
2022-05-03T15:15:05.231Z [WARNING]: WARN @radix-ui/react-use-layout-effect@0.1.0 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.238Z [WARNING]: npm
2022-05-03T15:15:05.238Z [WARNING]: WARN @radix-ui/react-use-previous@0.1.1 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.244Z [WARNING]: npm
2022-05-03T15:15:05.244Z [WARNING]: WARN @radix-ui/react-use-size@0.1.1 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.250Z [WARNING]: npm
2022-05-03T15:15:05.250Z [WARNING]: WARN @radix-ui/react-tabs@0.1.5 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.256Z [WARNING]: npm
2022-05-03T15:15:05.256Z [WARNING]: WARN @radix-ui/react-context@0.1.1 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.262Z [WARNING]: npm
2022-05-03T15:15:05.262Z [WARNING]: WARN @radix-ui/react-id@0.1.5 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.268Z [WARNING]: npm
2022-05-03T15:15:05.268Z [WARNING]: WARN @radix-ui/react-use-layout-effect@0.1.0 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.274Z [WARNING]: npm
2022-05-03T15:15:05.275Z [WARNING]: WARN @radix-ui/react-primitive@0.1.4 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.281Z [WARNING]: npm
2022-05-03T15:15:05.281Z [WARNING]: WARN @radix-ui/react-slot@0.1.2 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.287Z [WARNING]: npm
2022-05-03T15:15:05.287Z [WARNING]: WARN @radix-ui/react-compose-refs@0.1.0 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.293Z [WARNING]: npm
2022-05-03T15:15:05.293Z [WARNING]: WARN @radix-ui/react-roving-focus@0.1.5 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.299Z [WARNING]: npm
2022-05-03T15:15:05.300Z [WARNING]: WARN @radix-ui/react-collection@0.1.4 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.305Z [WARNING]: npm
2022-05-03T15:15:05.306Z [WARNING]: WARN @radix-ui/react-slot@0.1.2 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.312Z [WARNING]: npm
2022-05-03T15:15:05.312Z [WARNING]: WARN @radix-ui/react-compose-refs@0.1.0 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.318Z [WARNING]: npm
2022-05-03T15:15:05.318Z [WARNING]: WARN @radix-ui/react-use-callback-ref@0.1.0 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.324Z [WARNING]: npm
2022-05-03T15:15:05.324Z [WARNING]: WARN @radix-ui/react-use-controllable-state@0.1.0 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.330Z [WARNING]: npm WARN
2022-05-03T15:15:05.330Z [WARNING]: @radix-ui/react-use-callback-ref@0.1.0 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.336Z [WARNING]: npm
2022-05-03T15:15:05.336Z [WARNING]: WARN @mapbox/mapbox-gl-supported@1.5.0 requires a peer of mapbox-gl@>=0.32.1 <2.0.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.342Z [WARNING]: npm
2022-05-03T15:15:05.342Z [WARNING]: WARN @radix-ui/react-compose-refs@0.1.0 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.348Z [WARNING]: npm
2022-05-03T15:15:05.348Z [WARNING]: WARN @radix-ui/react-use-layout-effect@0.1.0 requires a peer of react@^16.8 || ^17.0 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.354Z [WARNING]: npm
2022-05-03T15:15:05.354Z [WARNING]: WARN fork-ts-checker-webpack-plugin@6.5.2 requires a peer of typescript@>= 2.7 but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.361Z [WARNING]: npm WARN react-map-gl@7.0.10 requires a peer of mapbox-gl@* but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.369Z [WARNING]: npm
2022-05-03T15:15:05.369Z [WARNING]: WARN tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
2022-05-03T15:15:05.379Z [WARNING]: npm
2022-05-03T15:15:05.379Z [WARNING]: WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
                                    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2022-05-03T15:15:05.379Z [WARNING]: 
2022-05-03T15:15:05.380Z [INFO]: audited 2052 packages in 11.858s
2022-05-03T15:15:06.106Z [INFO]: 187 packages are looking for funding
                                 run `npm fund` for details
2022-05-03T15:15:06.106Z [INFO]: found 1 moderate severity vulnerability
                                 run `npm audit fix` to fix them, or `npm audit` for details
2022-05-03T15:15:06.153Z [INFO]: # Completed phase: preBuild
                                 # Starting phase: build
2022-05-03T15:15:06.153Z [INFO]: # Executing command: npm run build
2022-05-03T15:15:06.325Z [INFO]: > globalnextgentech-website@0.1.0 build /codebuild/output/src783874373/src/globalnextgentech-website
                                 > react-scripts build
2022-05-03T15:15:07.468Z [INFO]: Creating an optimized production build...
2022-05-03T15:15:30.352Z [INFO]: Failed to compile.
2022-05-03T15:15:30.354Z [INFO]: Module not found: Error: Can't resolve 'mapbox-gl' in '/codebuild/output/src783874373/src/globalnextgentech-website/node_modules/react-map-gl/dist/esm/components'
2022-05-03T15:15:30.393Z [WARNING]: npm
2022-05-03T15:15:30.393Z [WARNING]: ERR! code ELIFECYCLE
                                    npm ERR! errno 1
2022-05-03T15:15:30.395Z [WARNING]: npm
2022-05-03T15:15:30.396Z [WARNING]: ERR! globalnextgentech-website@0.1.0 build: `react-scripts build`
                                    npm ERR! Exit status 1
                                    npm ERR!
                                    npm ERR! Failed at the globalnextgentech-website@0.1.0 build script.
                                    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2022-05-03T15:15:30.401Z [WARNING]: 
2022-05-03T15:15:30.402Z [WARNING]: npm ERR! A complete log of this run can be found in:
                                    npm ERR!     /root/.npm/_logs/2022-05-03T15_15_30_396Z-debug.log
2022-05-03T15:15:30.402Z [HELP]: Outputting the npm debug log
                                 0 info it worked if it ends with ok
                                 1 verbose cli [
                                 1 verbose cli   '/root/.nvm/versions/node/v14.19.0/bin/node',
                                 1 verbose cli   '/root/.nvm/versions/node/v14.19.0/bin/npm',
                                 1 verbose cli   'run',
                                 1 verbose cli   'build'
                                 1 verbose cli ]
                                 2 info using npm@6.14.16
                                 3 info using node@v14.19.0
                                 4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
                                 5 info lifecycle globalnextgentech-website@0.1.0~prebuild: globalnextgentech-website@0.1.0
                                 6 info lifecycle globalnextgentech-website@0.1.0~build: globalnextgentech-website@0.1.0
                                 7 verbose lifecycle globalnextgentech-website@0.1.0~build: unsafe-perm in lifecycle true
                                 8 verbose lifecycle globalnextgentech-website@0.1.0~build: PATH: /root/.nvm/versions/node/v14.19.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/codebuild/output/src783874373/src/globalnextgentech-website/node_modules/.bin:/usr/local/rvm/gems/ruby-2.4.6/bin:/usr/local/rvm/gems/ruby-2.4.6@global/bin:/usr/local/rvm/rubies/ruby-2.4.6/bin:/usr/local/rvm/bin:/root/.nvm/versions/node/v14.19.0/bin:/root/.local/bin:/root/.local/bin:/root/.local/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.dotnet/tools
                                 9 verbose lifecycle globalnextgentech-website@0.1.0~build: CWD: /codebuild/output/src783874373/src/globalnextgentech-website
                                 10 silly lifecycle globalnextgentech-website@0.1.0~build: Args: [ '-c', 'react-scripts build' ]
                                 11 silly lifecycle globalnextgentech-website@0.1.0~build: Returned: code: 1  signal: null
                                 12 info lifecycle globalnextgentech-website@0.1.0~build: Failed to exec build script
                                 13 verbose stack Error: globalnextgentech-website@0.1.0 build: `react-scripts build`
                                 13 verbose stack Exit status 1
                                 13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v14.19.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
                                 13 verbose stack     at EventEmitter.emit (events.js:400:28)
                                 13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v14.19.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
                                 13 verbose stack     at ChildProcess.emit (events.js:400:28)
                                 13 verbose stack     at maybeClose (internal/child_process.js:1058:16)
                                 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
                                 14 verbose pkgid globalnextgentech-website@0.1.0
                                 15 verbose cwd /codebuild/output/src783874373/src/globalnextgentech-website
                                 16 verbose Linux 4.14.246-187.474.amzn2.x86_64
                                 17 verbose argv "/root/.nvm/versions/node/v14.19.0/bin/node" "/root/.nvm/versions/node/v14.19.0/bin/npm" "run" "build"
                                 18 verbose node v14.19.0
                                 19 verbose npm  v6.14.16
                                 20 error code ELIFECYCLE
                                 21 error errno 1
                                 22 error globalnextgentech-website@0.1.0 build: `react-scripts build`
                                 22 error Exit status 1
                                 23 error Failed at the globalnextgentech-website@0.1.0 build script.
                                 23 error This is probably not a problem with npm. There is likely additional logging output above.
                                 24 verbose exit [ 1, true ]
2022-05-03T15:15:30.404Z [ERROR]: !!! Build failed
2022-05-03T15:15:30.405Z [ERROR]: !!! Non-Zero Exit Code detected
2022-05-03T15:15:30.405Z [INFO]: # Starting environment caching...
2022-05-03T15:15:30.405Z [INFO]: # Uploading environment cache artifact...
2022-05-03T15:15:30.508Z [INFO]: # Environment caching completed
Terminating logging...


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @rupam-kundu, thanks for raising this issue. Can you try upgrading your @amplify/ui-react package to the latest version and see if that fixes the build error?

**Comment by rupam-kundu** [comment]
Hi @chrisbonifacio . Thank you for your reply. What is the command for upgrading the @amplify/ui-react package to the latest version?

**Comment by chrisbonifacio** [comment]
If you're using npm you can run `npm install @aws-amplify/ui-react@latest`

For yarn, you can run `yarn add @aws-amplify/ui-react@latest`

**Comment by rupam-kundu** [comment]
Adding the below command in the Build phase of the Build Settings file (amplify.yml) of my app and redeploying it resolved the issue for me.

`- npm install --save react-map-gl mapbox-gl`

Thank you @chrisbonifacio for trying to help me out.
