### ISSUE TITLE
Redirects for SPA not working for route params

### ISSUE THREAD

**Issue by ksmit799** [aws-amplify/amplify-js#9915]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Not applicable

### Amplify Categories

hosting

### Environment information

<details>

```
  System:                                                        
    OS: Windows 10 10.0.19044                                    
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor             
    Memory: 8.52 GB / 31.92 GB                                   
  Binaries:                                                      
    Node: 16.1.0 - C:\Program Files\nodejs\node.EXE              
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD               
    npm: 7.20.0 - C:\Program Files\nodejs\npm.CMD                
  Browsers:                                                      
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.47)    
    Internet Explorer: 11.0.19041.1566                           
  npmPackages:                                                   
    @hcaptcha/react-hcaptcha: ^1.3.0 => 1.3.0
    @headlessui/react: ^1.5.0 => 1.6.0
    @heroicons/react: ^1.0.6 => 1.0.6
    @tailwindcss/forms: ^0.5.0 => 0.5.0
    @types/react: ^17.0.41 => 17.0.44 (18.0.8)
    @types/react-dom: ^17.0.14 => 17.0.16
    @types/react-helmet: ^6.1.5 => 6.1.5
    autoprefixer: ^10.4.4 => 10.4.5
    axios: ^0.26.1 => 0.26.1
    case-sensitive-paths-webpack-plugin: ^2.4.0 => 2.4.0
    clean-webpack-plugin: ^4.0.0 => 4.0.0
    copy-webpack-plugin: ^10.2.4 => 10.2.4
    cross-env: ^7.0.3 => 7.0.3
    css-loader: ^6.7.1 => 6.7.1
    esbuild-loader: ^2.18.0 => 2.18.0
    html-webpack-plugin: ^5.5.0 => 5.5.0
    mini-css-extract-plugin: ^2.6.0 => 2.6.0
    postcss: ^8.4.12 => 8.4.12
    postcss-loader: ^6.2.1 => 6.2.1
    prettier: ^2.6.0 => 2.6.2
    process: ^0.11.10 => 0.11.10
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    react-helmet: ^6.1.0 => 6.1.0
    react-router-dom: ^6.2.2 => 6.3.0
    react-select: ^5.3.2 => 5.3.2
    tailwindcss: ^3.0.23 => 3.0.24
    typescript: ^4.6.2 => 4.6.3
    webpack: ^5.70.0 => 5.72.0
    webpack-cli: ^4.9.2 => 4.9.2
    webpack-dev-server: ^4.7.4 => 4.8.1
  npmGlobalPackages:
    @aws-amplify/cli: 6.3.0
    create-react-app: 4.0.3
    npm: 7.20.0
    yarn: 1.22.10
```

</details>

### Describe the bug

I have configured my React app with the recommended rewrites from the Amplify docs:
```
</^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|woff2|ttf|map|json|webp)$)([^.]+$)/>
/index.html
200
```

This is supposed to allow for navigating directly to a route other then `/`, and it works for routes such `/users`. However, when attempting to navigate directly to a route that contains params such as `/users/:id`, the page fails to load with the following error:

```javascript
Uncaught SyntaxError: Unexpected token '<' (at main-44460e8106777c8f3360.bundle.js:1:1)
```

This works locally using webpack  with the following config (truncated to remove irrelevant config):
```
devServer: {
    historyApiFallback: true,
},
output: {
    publicPath: "/",
},
```

### Expected behavior

Like local development, the webpage should automatically load the React application at `/index.html` and push browser history to access the route directly.

### Reproduction steps

1. Configure Rewrites and redirects for a React SPA to the recommended SPA regex in the Amplify docs.
2. Navigate to a route that contains params.

### Code Snippet

```javascript
const ViewUser: FunctionComponent = () => {
    const {id} = useParams();

    return (
        <>
            <Helmet>
                <title>User {id} | Admin</title>
            </Helmet>

            <DashboardPage>
                <div className="py-4 sm:py-6 md:py-8">
                    <h1 className="text-4xl pb-5 font-semibold text-gray-900">User - {id}</h1>
                </div>
            </DashboardPage>
        </>
    );
};
```

### Log output

<details>

```
Uncaught SyntaxError: Unexpected token '<' (at main-44460e8106777c8f3360.bundle.js:1:1)
```

</details>

**Comment by ksmit799** [comment]
Magically started working, maybe a cache issue.
