### ISSUE TITLE
Build is missing some OAuth configurations

### ISSUE THREAD

**Issue by mrichman** [aws-amplify/amplify-js#9939]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 12.3.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 201.19 MB / 16.00 GB
    Shell: 5.9 - /usr/local/bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.10.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 100.0
    Safari: 15.4
  npmPackages:
    @aws-amplify/ui-react: ^2.18.2 => 2.18.2
    @aws-amplify/ui-react-internal:  undefined ()
    @aws-amplify/ui-react-legacy:  undefined ()
    @awsui/components-react: ^3.0.491 => 3.0.502
    @awsui/global-styles: ^1.0.14 => 1.0.14
    @testing-library/jest-dom: ^5.14.1 => 5.16.4
    @testing-library/react: ^11.2.7 => 11.2.7
    @testing-library/user-event: ^12.8.3 => 12.8.3
    aws-amplify: ^4.3.22 => 4.3.22
    axios: ^0.27.2 => 0.27.2 (0.21.4)
    env-cmd: ^10.1.0 => 10.1.0
    jsonwebtoken: ^8.5.1 => 8.5.1
    moment: ^2.29.3 => 2.29.3
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    react-router-dom: ^5.3.1 => 5.3.3
    react-scripts: 4.0.3 => 4.0.3
    sass: ^1.51.0 => 1.52.1
    web-vitals: ^1.1.2 => 1.1.2
  npmGlobalPackages:
    @aws-amplify/cli: 8.2.0
    aws-cdk: 2.24.1
    corepack: 0.10.0
    eslint-plugin-import: 2.26.0
    eslint-plugin-prettier: 4.0.0
    eslint-plugin-react: 7.30.0
    eslint: 8.15.0
    npm-check-updates: 13.0.1
    npm: 8.10.0
    serve: 13.0.2
    ts-node: 10.7.0
    typescript: 4.6.4

```

</details>

### Describe the bug

When I do a build, some of the OAuth values from `aws-exports.js` are missing at runtime.

I dump this to the console at app startup. This is from localhost:

```
{
    "domain": "xxxxxxxxxx.auth.us-east-1.amazoncognito.com",
    "scope": [
        "phone",
        "email",
        "openid",
        "profile",
        "aws.cognito.signin.user.admin"
    ],
    "redirectSignIn": "http://localhost:3000/",
    "redirectSignOut": "http://localhost:3000/",
    "responseType": "code"
}
```

and this is from my staging area using a build (i.e. `npm run build`):

```
{
    "domain": "xxxxxxxxxx.auth.us-east-1.amazoncognito.com",
    "redirectSignIn": "https://xxxxxxx.people.aws.dev/",
    "redirectSignOut": "https://xxxxxxx.people.aws.dev/"
}
```

Notice the values for `responseType` and `scope` are absent.

(If you work at AWS, you can hit me up on Slack)

### Expected behavior

The `awsExports` object should remain intact in a build configuration.

### Reproduction steps

1. Have an app set up with auth.
2. Set up Federation using OAuth (I'm internal to AWS, so I'm using Federation to Midway via OIDC, but this shouldn't matter).
3. Write `awsExports` object to the console log.
4. Run locally via `npm start`.
5. Observe no issues.
6. Create a build and run that.
7. Observe the `awsExports` object is missing `responseType` and `scope`.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line

Using STAGING endpoint: https://xxxxxxx.execute-api.us-east-1.amazonaws.com/v1
main.38a54452.chunk.js:1 {NODE_ENV: 'production', PUBLIC_URL: '', WDS_SOCKET_HOST: undefined, WDS_SOCKET_PATH: undefined, WDS_SOCKET_PORT: undefined, …}
main.38a54452.chunk.js:1 awsExports:  {aws_project_region: 'us-east-1', aws_cognito_identity_pool_id: 'us-east-1:d091810c-b2e7-4a14-xxxxxxxxxf4a75a', aws_cognito_region: 'us-east-1', aws_user_pools_id: 'us-exxxxx58OpAX', aws_user_pools_web_client_id: '43tol74hn2jh7pcbrt62g0j22e', …}aws_cognito_identity_pool_id: "us-east-1:d091810c-b2e7-4a14-949e-cae977f4a75a"aws_cognito_mfa_configuration: "OFF"aws_cognito_mfa_types: ['SMS']aws_cognito_password_protection_settings: {passwordPolicyMinLength: 8, passwordPolicyCharacters: Array(0)}aws_cognito_region: "us-east-1"aws_cognito_signup_attributes: ['EMAIL']aws_cognito_social_providers: []aws_cognito_username_attributes: []aws_cognito_verification_mechanisms: ['EMAIL']aws_project_region: "us-east-1"aws_user_pools_id: "us-eastxxxxxpAX"aws_user_pools_web_client_id: "43tol74hn2jh7pcbrt62g0j22e"oauth: domain: "xxxxxxxxxxx.auth.us-east-1.amazoncognito.com"redirectSignIn: "https://mrkrchm.people.aws.dev/"redirectSignOut: "https://mrkrchm.people.aws.dev/"[[Prototype]]: Object[[Prototype]]: Object
2.9093a8d2.chunk.js:2          POST https://cognito-identity.us-east-1.amazonaws.com/ 400
e.handle @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
l @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
a @ 2.9093a8d2.chunk.js:2
Promise.then (async)
u @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
l @ 2.9093a8d2.chunk.js:2
e.retry @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
l @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
a @ 2.9093a8d2.chunk.js:2
Promise.then (async)
u @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
l @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
l @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
l @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
a @ 2.9093a8d2.chunk.js:2
Promise.then (async)
u @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
l @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
l @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
e.send @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
a @ 2.9093a8d2.chunk.js:2
Promise.then (async)
u @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
Wn @ 2.9093a8d2.chunk.js:2
e._setCredentialsFromSession @ 2.9093a8d2.chunk.js:2
e.set @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
a @ 2.9093a8d2.chunk.js:2
Promise.then (async)
u @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
Ke @ 2.9093a8d2.chunk.js:2
e._handleAuthResponse @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
e.configure @ 2.9093a8d2.chunk.js:2
(anonymous) @ 2.9093a8d2.chunk.js:2
e.configure @ 2.9093a8d2.chunk.js:2
253 @ main.38a54452.chunk.js:1
a @ ?code=28386a67-dfe1-4814-a6b3-54e5d9db3fff&state=3tiUCPUhtD8Jq2YO5r15wVAfpnOpxz2J:1
r @ ?code=28386a67-dfe1-4814-a6b3-54e5d9db3fff&state=3tiUCPUhtD8Jq2YO5r15wVAfpnOpxz2J:1
t @ ?code=28386a67-dfe1-4814-a6b3-54e5d9db3fff&state=3tiUCPUhtD8Jq2YO5r15wVAfpnOpxz2J:1
(anonymous) @ main.38a54452.chunk.js:1
main.38a54452.chunk.js:1 auth event:  signIn_failure
main.38a54452.chunk.js:1 auth data:  ValidationException: 1 validation error detected: Value '{cognito-idp.us-east-1.amazonaws.com/us-east-1_Bdm58OpAX=}' at 'logins' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 50000, Member must have length greater than or equal to 1]
    at https://mrkrchm.people.aws.dev/static/js/2.9093a8d2.chunk.js:2:544175
    at https://mrkrchm.people.aws.dev/static/js/2.9093a8d2.chunk.js:2:535029
    at Object.next (https://mrkrchm.people.aws.dev/static/js/2.9093a8d2.chunk.js:2:535134)
    at a (https://mrkrchm.people.aws.dev/static/js/2.9093a8d2.chunk.js:2:533872)
...
```

</details>

### aws-exports.js

```javascript
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d091810c-b2e7-4a14-949e-cae977f4a75a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Bdm58OpAX",
    "aws_user_pools_web_client_id": "43tol74hn2jh7pcbrt62g0j22e",
    "oauth": {
        "domain": "xxxxxxxxxx.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;

```

### Manual configuration

`index.jsx`

```javascript
import React from "react";
import ReactDOM from "react-dom";
import App from "./App";
import "@awsui/global-styles/index.css";

import { Amplify } from "aws-amplify";
import awsExports from "./aws-exports";

console.log(process.env);

if (process.env.NODE_ENV === "development") {
  Amplify.Logger.LOG_LEVEL = "DEBUG";
  awsExports.oauth.domain =
    "whatsnew-midway-auth-dev.auth.us-east-1.amazoncognito.com";
  awsExports.oauth.redirectSignIn = "http://localhost:3000/";
  awsExports.oauth.redirectSignOut = "http://localhost:3000/";
}

if (process.env.NODE_ENV === "production") {
  awsExports.oauth.domain =
    "whatsnew-midway-auth-prod.auth.us-east-1.amazoncognito.com";
  awsExports.oauth.redirectSignIn = "https://whatsnew.sa.aws.dev/";
  awsExports.oauth.redirectSignOut = "https://whatsnew.sa.aws.dev/";
}

if (process.env.REACT_APP_ENV === "staging") {
  Amplify.Logger.LOG_LEVEL = "DEBUG";
  awsExports.oauth.domain =
    "whatsnew-midway-auth-dev.auth.us-east-1.amazoncognito.com";
  awsExports.oauth.redirectSignIn = "https://mrkrchm.people.aws.dev/";
  awsExports.oauth.redirectSignOut = "https://mrkrchm.people.aws.dev/";
}

console.log("awsExports: ", awsExports);

Amplify.configure(awsExports);

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById("root")
);

```

### Additional configuration

```json
{
    "UserPool": {
        "Id": "us-east-1_Bdm58OpAX",
        "Name": "whatsnewfe8d7f1d_userpool_fe8d7f1d-dev",
        "Policies": {
            "PasswordPolicy": {
                "MinimumLength": 8,
                "RequireUppercase": false,
                "RequireLowercase": false,
                "RequireNumbers": false,
                "RequireSymbols": false,
                "TemporaryPasswordValidityDays": 7
            }
        },
        "LambdaConfig": {},
        "LastModifiedDate": "2022-05-23T17:02:34.360000-04:00",
        "CreationDate": "2022-05-20T09:44:24.575000-04:00",
        "SchemaAttributes": [
            {
                "Name": "sub",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": false,
                "Required": true,
                "StringAttributeConstraints": {
                    "MinLength": "1",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "given_name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "family_name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "middle_name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "nickname",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "preferred_username",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "profile",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "picture",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "website",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "email",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": true,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "email_verified",
                "AttributeDataType": "Boolean",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false
            },
            {
                "Name": "gender",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "birthdate",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "10",
                    "MaxLength": "10"
                }
            },
            {
                "Name": "zoneinfo",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "locale",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "phone_number",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "phone_number_verified",
                "AttributeDataType": "Boolean",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false
            },
            {
                "Name": "address",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "updated_at",
                "AttributeDataType": "Number",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "NumberAttributeConstraints": {
                    "MinValue": "0"
                }
            },
            {
                "Name": "identities",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {}
            }
        ],
        "AutoVerifiedAttributes": [
            "email"
        ],
        "EmailVerificationMessage": "Your verification code is {####}",
        "EmailVerificationSubject": "Your verification code",
        "VerificationMessageTemplate": {
            "EmailMessage": "Your verification code is {####}",
            "EmailSubject": "Your verification code",
            "DefaultEmailOption": "CONFIRM_WITH_CODE"
        },
        "UserAttributeUpdateSettings": {
            "AttributesRequireVerificationBeforeUpdate": []
        },
        "MfaConfiguration": "OFF",
        "EstimatedNumberOfUsers": 6,
        "EmailConfiguration": {
            "EmailSendingAccount": "COGNITO_DEFAULT"
        },
        "UserPoolTags": {},
        "Domain": "whatsnew-midway-auth-dev",
        "AdminCreateUserConfig": {
            "AllowAdminCreateUserOnly": true,
            "UnusedAccountValidityDays": 7
        },
        "UsernameConfiguration": {
            "CaseSensitive": false
        },
        "Arn": "arn:aws:cognito-idp:us-east-1:059963230793:userpool/us-east-1_Bdm58OpAX",
        "AccountRecoverySetting": {}
    }
}

```

**Comment by mrichman** [comment]
Solved by using the proper JavaScript splat notation when overriding aws-exports.js.

```
...
let updatedAwsExports = {};

if (process.env.NODE_ENV === "development") {
  Amplify.Logger.LOG_LEVEL = "DEBUG";
  updatedAwsExports = {
    ...awsExports,
    oauth: {
      ...awsExports.oauth,
      domain: "whatsnew-midway-auth-dev.auth.us-east-1.amazoncognito.com",
      redirectSignIn: "http://localhost:3000/",
      redirectSignOut: "http://localhost:3000/",
    },
  };
}
...
```
